### ISSUE TITLE
ThatOrThis

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#109]
### Mod name

ThatOrThis

### Other links

https://modrinth.com/mod/thatorthis
https://github.com/EZForever/ThatOrThis

### What it does

Allows defining a list of alternative mods

### Why should it be in the modpack

So people who only want to swap a mod or two can enjoy the modpack, having the management in-game is better than CF/MMC/packwiz options as it is launcher-agnostic

### Why shouldn't it be in the modpack

Not in CF, needs the jars to be bundled for now (direct downloads are planned), need to understand how it works, probably needs more time to stabilize the mod (looking at the todo and breaking changes already)

### Categories

New feature

### Additional details

Possible options:

- Iris+Sodium vs Canvas
- WI Zoom vs Ok Zoomer vs Logical Zoom
- Phosphor vs Starlight
- Custom Fog
- MCPPPP + related mods
- Enhanced Block Entities vs Better Beds + FastChest
- Experimental mods like C2ME

**Comment by Rajbir98** [comment]
Well it doesn't seem to fit for people who are smart enough to handle the mods folder but good for people who are dependent on GUI and doesn't know much about the mod folder

**Comment by MulverineX** [comment]
Another idea: MCPPPP+Chime+etc vs CIT Resewn+etc

**Comment by supsm** [comment]
Shame that this mod hasn't been updated in a while... It would be cool to have an option for canvas in the pack. Recent updates have made canvas really performant, sometimes surpassing sodium performance. It's also more compatible with other mods and has some shader features built in (e.g. bloom, wavy leaves, shadows).

**Comment by CodeF53** [comment]
Sounds like a good mod to have options for people to choose if they want unstable mods, like c2me.

**Comment by nsde** [comment]
Sounds like a useful mod for bigger modpacks like this one.

**Comment by nsde** [comment]
UPDATE: This mod hasn't been updated in about a year now. I think we can close this issue for now!

**Comment by osfanbuff63** [comment]
This seems like it might be useful, but it hasn't been updated in a long time and is still on MC 1.17.1 which we don't support anymore, so I'm going to close this for now but feel free to reopen it.

**Comment by MulverineX** [comment]
Looks like another dev might be picking this up https://github.com/SettingDust/ThatOrThis

**Comment by Madis0** [comment]
Yeah, but even if it was updated to 1.19, it also needs the aforementioned features and that seems unlikely to happen for a direct port fork. I'll reopen in case that ever does happen.

**Comment by SettingDust** [comment]
Halo. Not we don't want to update. The newer fabric rewrite the strategy for loading mods. And the newer java not allowed access the same package name classes from another jar. So that we can't use the hacking method to decide what mod we need. 
We have to wait for fabric xd

Related: https://github.com/FabricMC/fabric-loader/issues/682

**Comment by Madis0** [comment]
Fair enough. At this point I think any hack is too fragile (vs https://github.com/EZForever/ThatOrThis/issues/18, which apparently seemed impossible too?) so I think it's better just to accept that this cannot be implemented in a clean way.

**Comment by SettingDust** [comment]
Maybe the quilt can implement this. I'll looking into that instead of fabric that an issue related exists for so long time(3y?)

**Comment by SettingDust** [comment]
Finally, I rewrite it as ModSets
https://github.com/SettingDust/ModSets
