### ISSUE TITLE
Installer for Minecraft Launcher

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#110]
This is planned as soon as [Packwiz releases its installer](https://github.com/packwiz/packwiz-vanilla-installer).

(For now, vanilla is supported by the MultiMC download, [read here for instructions](https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions#minecraft-launcher-vanilla))

Edit: alternative script is being worked on in this repo: https://github.com/Fabulously-Optimized/vanilla-installer
If that one gets ready first, it will be (initially) recommended.

**Comment by nsde** [comment]
I can code a Python script that does this.

**Comment by Madis0** [comment]
> I can code a Python script that does this.

Appreciate the offer, but I would prefer contributions to the original thing (so, Java).

**Comment by nsde** [comment]
Okay. I'm not that good at Java so I'm not planning to work on their repo (at the moment)...

**Comment by osfanbuff63** [comment]
An update, https://github.com/Fabulously-Optimized/vanilla-installer isn't *ready*, but it does work. So that's progress...

**Comment by osfanbuff63** [comment]
Update again...I would say the core functionality is finished, we just have a few more things to do (if you know Python and would like to contribute, we'd appreciate it :P)

I don't really have much of a release (even alpha or beta) estimate in mind yet, right now it's get the open issues closed and get packaging stuff done (which is arguably quite hard, taking Linux into account haha).

**Comment by Madis0** [comment]
https://floss.social/@fabulouslyoptimized/113340036497357027
