### ISSUE TITLE
Draggable Resource Packs

### ISSUE THREAD

**Issue by RozeFound** [Fabulously-Optimized/fabulously-optimized#137]
### Mod name

Draggable Resource Packs

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/draggable-resource-packs

### Other links

https://github.com/MrMelon54/draggable-resource-packs-fabric

### What it does

Make servers and resource-packs draggable

### Why should it be in the modpack

Get rid of annoying arrow-buttons, improves UX a bit. Very useful if you have multiply resource-packs.

### Why shouldn't it be in the modpack

No reason.

### Categories

New feature

**Comment by Madis0** [comment]
I did test it in my personal profile at some point and removed it because it made double-clicking the servers harder (or impossible). Also it may not be directly obvious on what to do when a new user finds the modpack and tries to manage their resource packs in it.

**Comment by RozeFound** [comment]
I used it for a while on my personal profile and it makes my life so much easier because a have about 10 resource-packs which is the literal hell to sort without this mod.

> Also it may not be directly obvious on what to do when a new user finds the modpack and tries to manage their resource packs in it.

It's intuitive, they may try to drag resource-pack because it's just how it supposed to be in normal UI. And don't forget about #127

**Comment by RozeFound** [comment]
> I did test it in my personal profile at some point and removed it because it made double-clicking the servers harder (or impossible).

Maybe you can request the author to make it configurable

**Comment by Madis0** [comment]
Okay, tested again and my memory was a bit wrong about this.

>  it made double-clicking the servers harder (or impossible).

Doesn't seem to be the case, maybe I just tried to double-click too slow (but overall the double-click speed seems to be equivalent to vanilla).

> Also it may not be directly obvious on what to do

I remembered it removing the vanilla arrows, but no, they are right there. Also clicking on a server at least will indicate that it is draggable.

Now my concerns are:

- How many people actively use more than 3 resource packs (excluding built-in mod ones)?
- How many people reorder their servers (often enough)?
- Muscle memory. Getting people used to dragging their packs/servers and at some point the mod may have to be removed (e.g. not updated to current MC).

**Comment by Madis0** [comment]
Decided against this, with the main point being muscle memory and likely low usage.
<details>

With muscle memory I mean this theoretical situation:

1. (If) I decide to add this
2. People get used to this
3. Minecraft updates
4. (If) Mod does not update
5. Bad experience because people already got used to this

Other mods in the pack usually have some replacements in case an added mod does not update, this does not seem to have such.

I also expect low usage, as not many people use more than 3 resource packs (excluding the ones activated by FO) or reorder their servers often.
</details>
