### ISSUE TITLE
Lack of individual shader configuration options

### ISSUE THREAD

**Issue by Syncinus** [Fabulously-Optimized/fabulously-optimized#139]
### What config to change

I'm not certain where to find this, or if it would be a new mod that would be required.

### Why should it be changed

A lot of OptiFine shaders have settings on them (as an example Sildur's Vibrant Shaders has a ton of options on it that can allow for configuring almost all parts of the shader) which OptiFine contains a GUI to change and generates a text file in the shaderpacks folder which details the configuration of the shader. Unless I'm completely blind, I don't seem to see any sort of shader options on Fabulously Optimized even after looking for a couple of minutes. Having support for shader options would be really good and would allow for it to actually act as a stand in for OptiFine (since to enable bump mapping on Sildur's Vibrant you have to change a configuration setting which you can do in OptiFine, but not on this pack).

### Category

Other

**Comment by Madis0** [comment]
This is coming soon.
Interested users can now get test builds from Iris' Discord:  https://discord.gg/jQJnav2jPu

Note: all support for those builds will be provided there, not in this repository. [Wiki on how to add mods to FO](https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Adding-more-mods)

**Comment by Madis0** [comment]
Now released for 1.16.5, 1.17.1, 1.18.1.
