### ISSUE TITLE
Ok Zoomer

### ISSUE THREAD

**Issue by TheMadHau5** [Fabulously-Optimized/fabulously-optimized#144]
### Mod name

Ok Zoomer

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/ok-zoomer

### Other links

https://github.com/EnnuiL/OkZoomer
https://modrinth.com/mod/ok-zoomer

### What it does

It allows the user to zoom in via a keybind (and also zoom in/out further using the scroll wheel). Replaces WI Zoom.

### Why should it be in the modpack

A better, more configurable (and easier to configure) zoom mod than WI Zoom.

### Why shouldn't it be in the modpack

Slightly unclear future.

### Categories

Works like Optifine/Bedrock Edition/Forge/etc

### Additional details

> Ok Zoomer will continue to be maintained as-is, however, the original plan of having a server-side part of the mod which could restrict the client-side's capabilities will be refreshed as a separate mod which will have more options than just disabling the zoom (like making the functional parts of the zoom behave like OptiFine's). This is being done due to the addition of spyglasses.
> 
> If you are worried about losing the advantages of Ok Zoomer like its transitions, do not worry, because its logic is being split into LibZoomer, a library that can be used by other mods, such as mods that add custom spyglasses.

As the server-side disabler component is being moved into a separate mod, there should be no reason not to start using Ok Zoomer again, over WI Zoom.

**Comment by Madis0** [comment]
> As the server-side disabler component is being moved into a separate mod, there should be no reason not to start using Ok Zoomer again, over WI Zoom.

I tried to understand that paragraph as well, so I asked about it:
https://www.curseforge.com/minecraft/mc-mods/ok-zoomer?comment=121
Considering that their 5.0.0 first beta is already out, I can't be that confident that the server-side support "is not there yet".

**Comment by TheMadHau5** [comment]
Just looked at its code, could possibly make a single mixin mod that completely eliminates server-side control from Ok Zoomer.

**Comment by Madis0** [comment]
Indeed, that could be an option, though I hope the Ok Zoomer dev wouldn't react too badly about it.

**Comment by Madis0** [comment]
I'm discussing the server-side component with the developer, might eventually re-add without having to patch it 🙂

**Comment by Madis0** [comment]
Superseded by #233.
