### ISSUE TITLE
Mod Manager (Mod Menu Addon)

### ISSUE THREAD

**Issue by Rajbir98** [Fabulously-Optimized/fabulously-optimized#156]
### Mod name

Mod Manager

### Curseforge link

N/A

### Other links

Edit by Madis0: https://modrinth.com/mod/modmanager
Github: https://github.com/DeathsGun/ModManager

### What it does

Extends Mod Menu with a new tab for installing, removing, and updating mods.

### Why should it be in the mod pack

Vanilla Auto Update Maybe,
Easy Search Of Mod In-Game

Features:

Browse through Modrinth in Minecraft
Install, remove and update mods in Minecraft (needs restart to apply changes)
Notify about outdated mods
Show a list of all outdated mods

### Why shouldn't it be in the mod pack

In Alpha, No CF Till Now.

### Categories

The new feature, Addon of a mod

**Comment by Rajbir98** [comment]
ok if you think this doesn't fit mod pack its ok i am closing this issue :)

**Comment by Madis0** [comment]
Actually, I'm gonna reopen and mark it as WIP.

**Comment by Madis0** [comment]
Closing for the same reason as #225.
