### ISSUE TITLE
Ksyxis

### ISSUE THREAD

**Issue by Rajbir98** [Fabulously-Optimized/fabulously-optimized#160]
### Mod name

Ksyxis

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/ksyxis

### Other links

Modrinth: https://modrinth.com/mod/ksyxis
Github: https://github.com/VidTu/Ksyxis

### What it does

Vanilla Minecraft loads 21x21 (441) chunks every time you load a world. This mod disables this feature.

### Why should it be in the modpack

Speed up your world loading by not loading nearby chunks every time.

### Why shouldn't it be in the modpack

WARNING: This mod may be unstable and incompatible with some mods.
The effect may not be noticeable on high-end PCs. This mod is designed primarily for low-end devices
There's a video through.

### Categories

Performance optimization

### Additional details

Got To Know From: https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88#gistcomment-3929964
I didn't got have any problem with this mod and I also got nice performance improvement in loading worlds :

**Comment by RaptaG** [comment]
Well, when on a potato pc causes a ton of lag when the world is created, until the chucks load

**Comment by Madis0** [comment]
Tested in FO 3.5.0:
* without Ksyxis: the user is shown the loading screen throughout and after that the FPS seems smooth
* with Ksyxis: the user is shown the loading screen which is stuck at 0% for a while, after that the world actually loads and causes initial frame drops 

Conclusion: in its current form, the mod does not seem to improve perceived performance or overall loading UX and therefore will not be added.

**Comment by RedGreenBlue09** [comment]
This mod has been rewritten recently. Compared to FastLoad:
+ Faster with my testing.
+ Compatibility should be better.
+ FPS is smooth thanks to ThreadTweak.

**Comment by Madis0** [comment]
> This mod has been rewritten recently. Compared to FastLoad:
> 
> * Faster according to my testing.
> * Compatibility should be better.
> * Doesn't unfocus mouse input away from the window.
> * FPS is smooth thanks to ThreadTweak.

Did you test on latest stable version of FO? If not, please do so.

**Comment by RedGreenBlue09** [comment]
@Madis0

I tested with FO 5.6.3. After creating the world, I don't have to wait for it to generate to play. Furthermore, FPS is still smooth right after the loading screen even though CPU usage is 100% (my CPU is 4c, 8t).

The mod looks very simple and it's only 11 KB.

**Comment by RedGreenBlue09** [comment]
Things could change for very weak CPUs.

**Comment by notlin4** [comment]
ModernFix has the same features as Ksyxis

**Comment by Madis0** [comment]
Interesting. I guess it could be tested which implementation, if any, is better at this point then.

**Comment by RedGreenBlue09** [comment]
They have similar performance, but Ksysis seems to be a tiny bit faster. The loading screen also looks a bit different between two mods.

**Comment by Madis0** [comment]
As of 24w03a (1.20.5), spawn chunks are now a gamerule, defaulting to 2 (3x3). Hence either methods will likely be unnecessary to include in FO.

**Comment by Madis0** [comment]
Rejected per my comment above.
