### ISSUE TITLE
Chunk Mod

### ISSUE THREAD

**Issue by Rajbir98** [Fabulously-Optimized/fabulously-optimized#161]
### Mod name

Chunk Mod

### Curseforge link

N/A

### Other links

https://github.com/Mario0051/chunk-mod

### What it does

 A mod that allows the player to join during world generation, also requires a mod named (lazy stronghold mod) Moonlight Mod #162 to perform much better.

### Why should it be in the modpack

Maybe faster than ksyxis.

### Why shouldn't it be in the modpack

No CF

### Categories

Performance optimization, Replaces an existing mod

### Additional details

Got to know from: https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88#gistcomment-3940624

**Comment by Madis0** [comment]
Abandoned mod.
