### ISSUE TITLE
Moonlight

### ISSUE THREAD

**Issue by Rajbir98** [Fabulously-Optimized/fabulously-optimized#162]
### Mod name

Moonlight

### Other links

https://github.com/Gregor0410/SeedQueue

### What it does

Mod that offsets stronghold generation to a separate thread to increase the loading speed of Minecraft worlds.
It performs much better with starlight mod #21 and chunk mod #161

### Why should it be in the modpack

It makes loading much faster loading with chunk mod

### Why shouldn't it be in the modpack

No CF, Need to build no release

### Categories

Performance optimization, Fixes a bug/makes another mod work

### Additional details

https://gist.github.com/alkyaly/02830c560d15256855bc529e1e232e88#gistcomment-3940624

**Comment by Madis0** [comment]
Abandoned mod.
