### ISSUE TITLE
OKZoomer instead of WI zoom

### ISSUE THREAD

**Issue by cardcraft** [Fabulously-Optimized/fabulously-optimized#164]
### Mod name

OkZoomer

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/ok-zoomer

### Other links

https://github.com/EnnuiL/OkZoomer (source code)
https://github.com/EnnuiL/OkZoomer/releases (releases)
https://modrinth.com/mod/ok-zoomer (releases)

### What it does

Its a replacement for WI zoom that is smoother and cleaner with more config.

WI Zoom is also from a hacked client/utility mod wurst

### Why should it be in the modpack

It works smoother than WI zoom and is more configurable. also not from a hacked client. 

### Why shouldn't it be in the modpack

you can set the zoom amount to an extreme amount

### Categories

Works like Optifine/Bedrock Edition/Forge/etc, Replaces an existing mod

**Comment by Madis0** [comment]
Duplicate of #144
