### ISSUE TITLE
JPG screenshot

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#165]
### Mod name

JPG screenshot

### Other links

https://modrinth.com/mod/jpgscreenshot

### What it does

Takes screenshots as JPGs

### Why should it be in the modpack

80% size reduction

### Why shouldn't it be in the modpack

Not in CF, may have conflicts with other screenshot-affecting mods, untested

### Categories

Graphics optimization, New feature

### Additional details

* Does anyone make so many screenshots that the size matters? [Emma's example: 187 files/308 MB]
* Is potential quality loss worth the smaller size?
* Could this cause some unexpected problems for users who want to share them?

**Comment by C0Nd3Mnd** [comment]
I prefer PNG screenshots. I actually use the included Fabrishot mod a lot for taking 2x size screenshots (5120x2880) to get great screenshot quality. These screenshots are around 20 MB in size when shaders are enabled. While this may be a concern for some, I personally don't really mind. I can always compress them (convert to JPG, reduce resolution etc.) when needed, but this way I at least have the option of using the lossless screenshot.

So I personally wouldn't use this feature, but there might be some people who prefer smaller screenshots in the first place, not wanting to deal with converting/resizing or whatever.

**Comment by Madis0** [comment]
Thanks for the input. This hasn't really seen much interest in Discord either, so closing it for now.
