### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#170]
Vanilla 1.18 is released and Fabulously Optimized will get its builds out as soon as feasible.

There _may be_ some 2.x.x releases in the 3.0.0 development period and there _will be_ at least one backport update to 2.x.x when 3.1.0 launches. ~~It is also a possibility that 3.0.0 won't be released as stable at all and 3.1.0 will be released instead, as Mojang likes to do x.x.1 releases.~~ yup

[Progress can be seen here](https://github.com/Fabulously-Optimized/fabulously-optimized/projects/10)

Schedule/estimates:
- MC 1.18: Nov 30
- FO 3.0.0-alpha.1: Dec 2
- MC 1.18.1: Dec 10
- FO 3.1.0-alpha.1: Dec 11
- Multiplayer patches for all versions: Dec 11, Dec 15
- FO Starlight testing: Dec 20
- FO Phosphor testing: Jan 2
- FO Starlight/Phosphor verdict: Jan 16
- FO 3.1.0 (stable): Jan 25

Later:
- MC 1.18.2: TBD
- FO 3.2.0 (stable): ETA February (depends on Mojang and mods)

**Edit**: log4j (the multiplayer bug) happened, schedules may change.

Use this issue for generic feedback about FO 3.1.0 development.

**Comment by nchristopher** [comment]
[Sodium 0.4.0-alpha5 for Minecraft 1.18](https://github.com/CaffeineMC/sodium-fabric/releases/tag/mc1.18-0.4.0-alpha5) has been released.

**Comment by nchristopher** [comment]
[Minecraft 1.18.1](https://www.minecraft.net/en-us/article/minecraft-java-edition-1-18-1) has been released, addressing a [critical security vulnerability](https://www.minecraft.net/en-us/article/important-message--security-vulnerability-java-edition) in `log4j`. Fabulously Optimized should update to 1.18.1 ASAP - if that's not yet possible, Fabric Loader 0.12.9 contains a patch for this as well.

**Comment by ImUrX** [comment]
i advise removing littletweaks for now, Mojang wholly implemented audio functionality in Minecraft. Only thing it could do now is remove the soft limit that Minecraft puts in the maximum sounds that can be played at the same time

**Comment by Madis0** [comment]
@ImUrX Yup, that has already been removed since the first 3.0.0 alpha, I just didn't post the alpha mod list anywhere yet. That soft limit removal required additional configuration from the user (which cannot be done by FO) so those who are willing to can install by themselves.

**Comment by nsde** [comment]
As the version changed some settings with the fog (https://minecraft.fandom.com/wiki/Java_Edition_1.18.2) it probably needs updates for some performance mods.

**Comment by Madis0** [comment]
Decided to release 1.18.1 version as stable for the following reasons: 
* 1.18.2 is not out and needs time for mod updates when it is anyway
* Sodium 0.5 is coming, maybe it will release with 1.18.2 (aka no 0.4 port for it beforehand)
* Parity with 1.17.1 has been reached (incl. hydrogen archival), just extra mods to think of but that can be postponed
* Sodium and Iris got some performance patches already
