### ISSUE TITLE
Incompatibilities with Enhanced Block Entities and some resourcepacks

### ISSUE THREAD

**Issue by YumatanGames** [Fabulously-Optimized/fabulously-optimized#171]
### Describe the bug

The Enhanced Block Entities mod causes an issue with some resourcepack that changes entities, like chest and signs, rendering them invisible. I can confirm this happens with StayTrue resourcepack and chests. I've already reported the issue directly with EBE author, but I highly recommend taking it out from this modpack in the meantime.   

### Expected behavior

Chests, signs and other static entities should be rendered visible doesn't matter the resourcepack installed 

### Observed/actual behavior

Chests, signs and other static entities are being rendered invisible with some resourcepacks. I can confirm this happening with StayTrue

### Steps To Reproduce

1-Install StayTrue
2-Activate it inside options
3-Place a chest
4-It will be invisible

### Modpack version

2.3.3

### Launcher

MultiMC

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
I've thought about it for a while and decided that I will keep EBE and will not revert to FastChest/Better Beds for now, as the mod still helps 90% of the people. I've written a wiki on how to configure it in case it breaks with some resource packs though: 
https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Resource-pack-issues

**Comment by YumatanGames** [comment]
Alright! Thanks for the wiki. I recommend, thought, that you update the modpack description to inform people about those issues, so they know how to proceed, since many people use custom resourcepacks. Thanks for all the work you've done! :D
