### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by ThEnchanted** [Fabulously-Optimized/fabulously-optimized#173]
### Mod name

Clumps

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/clumps

### Other links

https://github.com/jaredlll08/Clumps

### What it does

Clumps groups XP orbs together into a single entity to reduce lag when there are many in a small area. On top of this, it also makes the player immediately collect the orbs once they touch the player, so you are not stuck with a bunch of orbs in your face.

### Why should it be in the modpack

Could be useful in mob grinders

### Why shouldn't it be in the modpack

I don't know... it's another mod

### Categories

Performance optimization, New feature

**Comment by Madis0** [comment]
Thanks for the suggestion! However, a similar mod was already rejected for the following reasons: https://github.com/Fabulously-Optimized/fabulously-optimized/issues/71#issuecomment-864748974.
