### ISSUE TITLE
Mod Eating Animation

### ISSUE THREAD

**Issue by ThEnchanted** [Fabulously-Optimized/fabulously-optimized#174]
### Mod name

Eating Animation

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/eating-animation-fabric

### Other links

https://github.com/Theoness1/EatingAnimation

### What it does

Eating Animation mod adds a simple sprite animation for vanilla items when you eat or drink! 
Works in single-player and multiplayer

### Why should it be in the modpack

Adding animation when eating any food or drink adding realistic enhancement

### Why shouldn't it be in the modpack

IDK

### Categories

Graphics optimization, New feature

**Comment by Madis0** [comment]
As far as I see, this [only works with the default resource pack](https://github.com/Theoness1/EatingAnimation/wiki/For-texture-packs!) (unless explicit support is added) and [breaks CIT resource packs](https://github.com/Theoness1/EatingAnimation/issues/9).

It is better for who want it to install manually :)

**Comment by Julienraptor01** [comment]
> As far as I see, this [only works with the default resource pack](https://github.com/Theoness1/EatingAnimation/wiki/For-texture-packs!) (unless explicit support is added) and [breaks CIT resource packs](https://github.com/Theoness1/EatingAnimation/issues/9).
> 
> It is better for people who want it to install manually :)

Well there's PR from a fork with a CIT working. (i've compiled it and use it in my own pack) 
But yes it's only compatible with the default pack for now. (even if i made a pack that is compatible with VT smaller utilities, it's not supported by default and others aren't too) 

So it's still better not to include it.
