### ISSUE TITLE
Client Tweaks

### ISSUE THREAD

**Issue by ThEnchanted** [Fabulously-Optimized/fabulously-optimized#175]
### Mod name

Client Tweaks

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/client-tweaks

### Other links

https://github.com/ModdingForBlockheads/ClientTweaks

### What it does

Adding small settings for Minecraft

### Why should it be in the modpack

Adding lot's of small but important settings, if it's will be added to the mod pack, can be modified from default settings to optimized/universal or manually made (importing files or making preset for PVP like, etc)

### Why shouldn't it be in the modpack

not everybody needs those

### Categories

New feature

**Comment by Madis0** [comment]
https://www.curseforge.com/minecraft/mc-mods/client-tweaks-fabric is the new version. 

But now, which options would you _specifically want_ to enable for everyone? If the description is up to date, I only see the potion shift as one and that already exists in the pack with a different mod.

**Comment by Madis0** [comment]
Currently I don't see any tweaks that could benefit everyone and still be beneficial to the vanilla-like experience, even the music slider is... redundant. It is better for interested users to add this mod manually.
