### ISSUE TITLE
Iron vs iron ore drop

### ISSUE THREAD

**Issue by grnassar** [Fabulously-Optimized/fabulously-optimized#177]
### Describe the bug

Iron ore mined with a pickaxe is dropping iron ore instead of raw iron (ie acting as if every Pickaxe had Silk Touch).  Does not occur with coal ore, which drops coal as it should. Not tried with other ores, as this was found in the very initial moments of each new world.

### Expected behavior

Mining Iron Ore with a pickaxe drops Raw Iron

### Observed/actual behavior

Mining Iron Ore drops the Iron Ore item

### Steps To Reproduce

1. Launch Minecraft
2. Start new game (tried with 3 different new games)
3. Create pickaxe
4. Find and mine iron ore

### Modpack version

1.10.0 for 1.16.5 (MultiMC)

### Launcher

MultiMC

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
Raw iron was added in 1.17, you are using 1.16.5. Try using FO version 2.4.1 😄
