### ISSUE TITLE
Closes randomly

### ISSUE THREAD

**Issue by Daniel1009xd** [Fabulously-Optimized/fabulously-optimized#178]
### Describe the bug

The game closes just as i start it up and i tried reinstalling and all that pls fix it

### Expected behavior

I expected the pack to.. you know.. work.

### Observed/actual behavior

Literally nothing

### Steps To Reproduce

1. Launch Minecraft with this Modpack
2. Done

### Modpack version

2.4.1

### Launcher

Minecraft Launcher (vanilla)

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
Please post your `launcher.log` to pastebin.com and share the link here.

**Comment by Madis0** [comment]
You did not share any logs, assuming it is fixed.
