### ISSUE TITLE
AdvancementInfo should be updated

### ISSUE THREAD

**Issue by gbl** [Fabulously-Optimized/fabulously-optimized#179]
### Describe the bug

Maker of AdvancementInfo here. 

Unfortunately, version 1.2.2 of the mod introduced a new bug; if you have many advancements, for example from installing the BlazeAndCave pack, and have a row of tabs at the bottom, then that row of tabs will, in fact, not be at the bottom, but somewhere in the middle of the screen.

See also https://github.com/gbl/AdvancementInfo/issues/10

This probably won't affect too many users, so is not an immediate big problem, but it's probably a good idea to update to version 1.3 here https://www.curseforge.com/minecraft/mc-mods/advancementinfo/files/3537133 where the bug is fixed.

### Expected behavior

Fabulously Optimized includes advancementinfo-1.17.1-fabric0.36.1-1.3.jar

### Observed/actual behavior

Fabulously Optimized includes advancementinfo-1.17.1-fabric0.36.1-1.2.2.jar

### Steps To Reproduce

Install F.O. with a pack that adds many advancement tabs, and get enough advancements to have a bottom tab row.
Open the advancements screen and see the bottom row in the middle of the screen instead of where it belongs.

See the screenshots at https://github.com/gbl/AdvancementInfo/issues/10

### Modpack version

2.4.1 for 1.17.1

### Launcher

MultiMC

### Install method

Fresh install/new profile

**Comment by Madis0** [comment]
Thanks for the heads up, I plan to update it early next week.

**Comment by Madis0** [comment]
Fixed on 2.5.0.
