### ISSUE TITLE
Remove Slight Gui Modifications

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#18]
**Mod name**
'Slight' Gui Modifications

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/slight-gui-modifications

**Modrinth link**
N/A

**Other link**
N/A

**What it does**
In the modpack: version title in menu, advancement animations

**Why should it be in the modpack**
Currently the only simple/sustainable way to add version text in main menu 

**Why shouldn't it be in the modpack**
Most of its features are not needed, the mod itself is big

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [x] Replaces an existing mod

**Additional details**

'Slight' GUI Modifications is 7,6 MB, by far the largest mod in FO (because it includes three dependencies)
2nd place Fabric Language Kotlin (6 MB)
3rd Iris (1,5 MB)

**Comment by Madis0** [comment]
Potential alternatives:
* https://www.curseforge.com/minecraft/mc-mods/custom-window-title
* Resource pack - change some string

**Comment by nsde** [comment]
> - Is client title a good idea, privacy-wise (Discord)?
I don't think anyone would want to hide a performance-boosting modpack.

> - Is the website link necessary? (especially MultiMC...)
Not really, I think. 

> - Are there any other features in 'Slight GUI Modifications' that could come useful?
I once used it to add GUI effects. It's nothing special, I think this mod is not quite needed, but not entirely useless.

**Comment by Madis0** [comment]
Thanks for the input. My point with the text in menu is visibility, I want people to have a consistent and noticable way to see the version.

Titlebar text:
* Is too long and therefore ugly 
* Can be forgotten about in fullscreen mode
* Needs readjusting for a lot of people as FO has been around for a while

Here's an example how it would look:

![](https://media.discordapp.net/attachments/859124104644788237/923892922473132032/unknown.png)

**Comment by nsde** [comment]
I dunno, probably use an alternative. I never had issues with both SlightGUIMods OR the title bar.

**Comment by Madis0** [comment]
Removed as of 3.7.0, now using #304
