### ISSUE TITLE
3.0.0-alpha.1 crashes on startup

### ISSUE THREAD

**Issue by PanSzelescik** [Fabulously-Optimized/fabulously-optimized#181]
### Describe the bug

3.0.0-alpha.1 crashes on startup

### Expected behavior

Not crashing

### Observed/actual behavior

The game has crashed in my language, with exit code 0.

### Steps To Reproduce

Install 3.0.0-alpha.1 via CurseForge launcher.
Run using Mojang Launcher.
Crash

### Modpack version

3.0.0-alpha.1

### Launcher

Curseforge Launcher

### Install method

Fresh install/new profile

### Additional context

There is no crash-report so I pasted latest.log:
https://pastebin.com/ezwiy6tR

**Comment by Madis0** [comment]
Try launching it again, it fixed it for me and one other person. I do not yet know the cause of the issue.

**Comment by PanSzelescik** [comment]
I launched 3 times, the same error

**Comment by Madis0** [comment]
Alright. Please try three dots -> Profile options -> Allow content management for this profile and then click the :arrow_down: next to Not Enough Crashes.

**Comment by Madis0** [comment]
Released a second alpha, maybe it helps you. Got an another user reporting a similar issue in Discord, so I'll keep this open for now though.

**Comment by PanSzelescik** [comment]
I found solution for me, it crashes because I have `-Dmixin.debug=true` argument, because I'm testing mixins in another modpacks. Without this arg the game not crashes (tested on alpha.2)

**Comment by PanSzelescik** [comment]
I didn't have `-XX:PermSize=256m` but I typed it specifically and the error is a little different: 
![image](https://user-images.githubusercontent.com/26679785/144756955-2daec4f9-6a05-4b76-ba3d-44f42fcfc9e4.png)
and after close I see this (this is in polish language - exit code 0): 
![image](https://user-images.githubusercontent.com/26679785/144757031-9b512f20-85c3-4e33-b95c-41fa0653bde9.png)
With `-Dmixin.debug=true` arg I only see error on second screen

**Comment by Madis0** [comment]
I think enough people have updated their CF Launchers so this is not an issue anymore. Any new crashes should create a new issue.
