### ISSUE TITLE
Controlling

### ISSUE THREAD

**Issue by itsmeboy0** [Fabulously-Optimized/fabulously-optimized#182]
### Mod name

Controlling

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/controlling

### Other links

https://github.com/jaredlll08/Controlling

### What it does

> Adds the ability to search for keybinds using their name in the KeyBinding menu, this allows players to easily find a key binding in the menu.
>
> Adds a button that will only show KeyBindings that conflict with each other, which makes it easier to fix them.
>
> You also have the ability to see what keys are available to be bound.

### Why should it be in the modpack

I frequently play with my keybinds and so being able to search for keybinds and look for conflicting and available keys are essential to me.

### Why shouldn't it be in the modpack

N/A

### Categories

New feature

**Comment by Madis0** [comment]
I did consider #4 but ultimately decided against just because there are very few keybinds in this modpack. Is there a reason why you think this mod would be useful for the _majority_ of the people?

**Comment by itsmeboy0** [comment]
Hmm, checked it out and it seems that what this doesn't have is:
- Doesn't add modifier keys
- Doesn't allow conflicting keys
- No auto jump and skin layer toggles

But has:
- Show conflicts 
- Show unbound
- Show available keys
- Filter and sort options

So yeah, this mod is more about easier searching and adding of keybinds and doesn't add anything else new.

> - This is still a relatively "small"/"simple" modpack, I don't think there will be that many keybinds to justify adding a mod that adds search

But like you said, not that many keybinds. I usually have some extra mods with me.
