### ISSUE TITLE
FarSight

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#184]
### Mod name

FarSight

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/farsight-fabric

### What it does

Extends render distance in servers by temporarily keeping loaded chunks

### Why should it be in the modpack

Compared to Bobby #46 it automatically clears the chunks (therefore doesn't fill up the storage or keep showing old data), seems to have less bugs and is available for 1.18

### Why shouldn't it be in the modpack

ARR, works better with Starlight than Phosphor (notably Bobby is the opposite)

### Categories

Graphics optimization, Works like Optifine/Bedrock Edition/Forge/etc

### Additional details

Tests by Probattler:
> Phophor + farsight 1.17.1
Phosphor + Bobby 1.17.1
Both of them producing missing chunks blocks, chunks not rendering sometimes
>
> While for 
Starlight + Farsight 1.17.1
No chunk and rendering issues and better performance than phosphor
>
> While 
Starlight + Bobby 1.17.1 
still less performance and still the chunk rendering issues like before

I'll postpone decision until Phosphor vs Starlight is settled.

**Comment by Julienraptor01** [comment]
curseforge link goes to forge version this is the proper link https://www.curseforge.com/minecraft/mc-mods/farsight-fabric

**Comment by Madis0** [comment]
Thanks, fixed.

**Comment by Julienraptor01** [comment]
After long time using it i didn't notice a performance drop on my high-end pc and my friends didn't noticed anything too both on their high-end and low-end pc.

**Comment by Probattler** [comment]
With my tests, I loaded a the hypixel duels lobby entirely, I was getting around 20-35fps with high settings and a low end pc, sometimes even averaging upto 40-50, overall having much better performance than #46 and #240 .
