### ISSUE TITLE
alternate-current

### ISSUE THREAD

**Issue by oblessnoob** [Fabulously-Optimized/fabulously-optimized#185]
### Mod name

alternate-current

### Other links

https://modrinth.com/mod/alternate-current
https://github.com/SpaceWalkerRS/alternate-current

### What it does

Alternate Current is an efficient and non-locational redstone dust implementation. Its main focus lies in reducing the lag caused by redstone dust, by optimizing the power calculations and reducing the number of shape and block updates emitted. As a side effect of these changes the block update order of redstone dust networks is predictable and intuitive rather than locational and chaotic.

MSPT contributions of redstone dust are up to 20 times lower with Alternate Current, all the while maintaining a high level of Vanilla parity. Its low number of code modifications make it minimally invasive, so it's an easy drop-in replacement for Vanilla redstone dust.

### Why should it be in the modpack

10 times faster than Lithium

### Why shouldn't it be in the modpack

it changes the redstone update order

### Categories

Performance optimization

**Comment by Madis0** [comment]
> it changes the redstone update order

It may be faster and more efficient, but it still changes overall redstone behavior, so unfortunately I cannot include it. See also: #44

**Comment by oblessnoob** [comment]
> > it changes the redstone update order
> 
> It may be faster and more efficient, but it still changes overall redstone behavior, so unfortunately I cannot include it. See also: #44

Basically it wont break any thing, it just make the redstone wire more predictable, or just fix some broken or locational machine which broke by the vanilla redstone wire. Vanilla redstone wire update order just worse

**Comment by Madis0** [comment]
> *While Lithium can boast 100% Vanilla parity, Alternate Current cannot.
