### ISSUE TITLE
Black World

### ISSUE THREAD

**Issue by Rajbir98** [Fabulously-Optimized/fabulously-optimized#186]
### Describe the bug

When I Enter Work Every Thing Is Rendered, Black

### Expected behavior

Everything Should Be Normal

### Observed/actual behavior

World Renders Black And White

### Steps To Reproduce

Launch Minecraft 
Create A New World
Enter The World
The World Is Dim( If Resource Pack Used World Is Black )

### Modpack version

alpha 2 3.0.0

### Launcher

TLauncher

### Install method

Fresh install/new profile

### Additional context
with resource packs
![huge_2021-12-07_22 31 16](https://user-images.githubusercontent.com/84771149/145074495-2b90137b-3961-4b95-8dfc-edf39fe70a08.png)
without resource packs
![huge_2021-12-12_16 39 10](https://user-images.githubusercontent.com/84771149/145710096-07e2273c-3b65-4d65-8201-c09d456f64e4.png)

**Edit by Madis0: fix is here:** https://github.com/Fabulously-Optimized/fabulously-optimized/issues/186#issuecomment-991899555

**Comment by Madis0** [comment]
> If Resource Pack Used World Is Black 

I cannot fix this, it most be done by the pack creator.
https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Resource-pack-issues

**Comment by Rajbir98** [comment]
but without resource pack the sam happens

**Comment by Rajbir98** [comment]
ok

**Comment by nsde** [comment]
I had a similar issue.
It was caused by Lithium I think.
Restarting the game fixed it.

Maybe you need to update your gaphical drivers.

Hope I could help!

**Comment by Rajbir98** [comment]
so i wouldn't be playing Minecraft now cause my graphics card is out of support

**Comment by Rajbir98** [comment]
or removing lithium could fix this

**Comment by Rajbir98** [comment]
launcher log
[tlauncher_12_12_2021_16_32_42.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/7698622/tlauncher_12_12_2021_16_32_42.log)

**Comment by Rajbir98** [comment]
log
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/7698623/latest.log)

**Comment by nsde** [comment]
I downloaded a fresh/untouched FO 1.18 zip, and I had the same black world issue. It's not because of any settings. I'm sure **it is caused by Lithium!!**

**Comment by Madis0** [comment]
Ah, in that case you both can use 3.1.0-alpha.1, which does not have Lithium right now.

But in the long term it would be helpful if you tested it with only Lithium enabled, tried out the development versions of it and reported the bug to them with your system details. The Discord is: https://caffeinemc.net/discord

**Comment by nsde** [comment]
I tried it without Lithium (and the issue was fixed) but we really need a good replacement! (Starlight?)

**Comment by Madis0** [comment]
Nah, Lithium is good for most users due to it's integration and testing with other CaffeineMC mods. It is rather an issue that should be reported and fixed.

**Comment by nsde** [comment]
you're right!

**Comment by nsde** [comment]
> Nah, Lithium is good for most users due to its integration and testing with other CaffeineMC mods. It is rather an issue that should be reported and fixed.

https://github.com/CaffeineMC/lithium-fabric/issues/312

**Comment by Madis0** [comment]
Yeah.. but you should still test and report crashes with _only_ Lithium and also Lithium's 1.18.1 dev version (in the discord I linked above) to make sure it is caused by _just_ that.

**Comment by nsde** [comment]
@Madis0 Maybe it's because of the version?

- 1.18 Fabulously.Optimized.MultiMC.3.0.0-alpha.2: **0.7.6-rc1**
- 1.17.1 Fabulously.Optimized.MultiMC.2.5.0 - **0.7.5**

**Comment by nsde** [comment]
> Yeah.. but you should still test and report crashes with _only_ Lithium and also Lithium's 1.18.1 dev version (in the discord I linked above) to make sure it is caused by _just_ that.

alright

**Comment by nsde** [comment]
ONLY lithium seems to work fine on FO 1.18

![image](https://user-images.githubusercontent.com/67185896/145712702-55aa91fd-22d2-4513-aa19-9e41fb613b9b.png)

**Comment by Madis0** [comment]
Okay, in that case it could be a mod conflict, so disabling mods one by one would be preferred. 

But more specifically I suggest testing 3.1.0-alpha.1 (1.18.1) with the in-development Lithium and
* disabling Colormatic
* disabling Sodium

**Comment by nsde** [comment]
Okay.

**Comment by nsde** [comment]
But Sodium doesn't make sense, it's the same dev xD

**Comment by Madis0** [comment]
Same dev team, yes, but well.. both Sodium and Lithium are clearly alpha at this point, so you never know :D

**Comment by nsde** [comment]
I just installed the newest FO 1.18.1 alpha modpack

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145713133-7ee59449-bcf2-4580-97b2-7fe02891e60e.png)

seems to work fine

**Comment by Madis0** [comment]
3.1.0-alpha.1 lacks Lithium though, hence I suggested using the dev version.

**Comment by nsde** [comment]
so, should I add Lithium in my 1.18.1 FO instance?

**Comment by Madis0** [comment]
Correct.

**Comment by nsde** [comment]
I can't manage to find it...

**Comment by nsde** [comment]
Where's the download?

**Comment by Madis0** [comment]
https://discord.com/channels/602796788608401408/886002128844374146/919214269172703283

**Comment by nsde** [comment]
Thanks!

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145713793-81ea466a-5f12-4a0c-a296-7892203a9d62.png)
Seems to work fine, I guess

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145713805-6b3ef5e1-ebe3-4490-9672-6ced1a55b79a.png)
with F3

**Comment by nsde** [comment]
![Uploading image.png…]()
Apparently, the problem only seems to occur on SOME worlds.

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145714039-a1efba56-2351-47b6-b07b-17dc6af91bee.png)

Apparently, on some worlds, it seems to work fine

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145714083-409aad80-af0a-4f3f-a53b-7b25d0f545a2.png)
Here's a (rare) example of the issue

**Comment by nsde** [comment]
On the broken worlds, the issue perists when using a

**Comment by Madis0** [comment]
Perhaps shaders are the actual issue? Or you could test with only Lithium, Sodium, Iris.

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145714173-c17299e2-f652-4aba-8fb8-f224a06cec42.png)
Even after optimizing the broken world, the issue keeps occuring

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145714247-4a72678b-c81d-411e-bb8f-c2deb4faa652.png)
I loaded the exact same broken world with vanilla, the problem still exists

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145714271-f981a546-493f-4139-adf3-bf8ddd599873.png)

some more screenshots of vanilla Minecraft with a broken shadow-world

**Comment by nsde** [comment]
By the way, my skin/hand is not broken, it's just the way my skin is built with overlays/etc.

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145714326-a721c647-d1e9-4dc6-adb4-dca01d56a0ea.png)
some more vanilla screenshots with the broken world

**Comment by nsde** [comment]
![image](https://user-images.githubusercontent.com/67185896/145714354-0d3a335c-69e8-47c7-a0dc-3c29f8bfd492.png)
It doesn't have to do with the seed. I re-created the broken world's seed on vanilla

**Comment by nsde** [comment]
***FOUND A FIX!***
![image](https://user-images.githubusercontent.com/67185896/145714434-d4f26aa6-d1da-4f90-a603-62bf3b756a43.png)

Erase cached data and optimize the world (I know that I'm doing) fixed it for me!

**Comment by Madis0** [comment]
Seems like everyone involved got it fixed, closing the issue.

**Comment by Rajbir98** [comment]
Its fixed in multiplayer but the problem still persists in singleplayer mode

**Comment by Rajbir98** [comment]
![huge_2021-12-19_23 33 32](https://user-images.githubusercontent.com/84771149/146685824-f9b79391-0e14-4814-b038-caa5f5b740bc.png)
![huge_2021-12-19_23 33 41](https://user-images.githubusercontent.com/84771149/146685825-19f5f134-1da8-44ff-bc97-db23b2e30f61.png)
![huge_2021-12-19_23 33 50](https://user-images.githubusercontent.com/84771149/146685828-ac91f40e-c9ac-4163-b7b1-ec4f4ae40627.png)

**Comment by Madis0** [comment]
Optimizing the world + deleting caches didn't work?

**Comment by Rajbir98** [comment]
i have also made a new world and checked it still continues

**Comment by Rajbir98** [comment]
but still let me try to optimize it again

**Comment by Madis0** [comment]
Did you try the local worlds _without_ the resource pack?

**Comment by Rajbir98** [comment]
yes

**Comment by Rajbir98** [comment]
> but still let me try to optimize it again

I optimized with erase cached data but still no progress

**Comment by Madis0** [comment]
Alright. 
@Rajbir98, please try a clean install of 3.1.0-alpha.3 - no extra mods, resource packs or setting changes. Then enable launcher logs, create a world and try to load some chunks. Then post your launcher log to Pastebin.

**Comment by Rajbir98** [comment]
problem solved thx for guiding me
