### ISSUE TITLE
Can you add Cull Leaves

### ISSUE THREAD

**Issue by LCBOI** [Fabulously-Optimized/fabulously-optimized#188]
### Mod name

Cull Leaves

### Other links

https://github.com/TeamMidnightDust/CullLeaves

### What it does

Adds culling to leaf blocks, providing a huge performance boost over vanilla

### Why should it be in the modpack

It just boost

### Why shouldn't it be in the modpack

the leaves looks a bit weird but it just culling

### Categories

Graphics optimization

**Comment by Madis0** [comment]
Already exists since 1.5.0 🙂
