### ISSUE TITLE
TieFix

### ISSUE THREAD

**Issue by user859347** [Fabulously-Optimized/fabulously-optimized#189]
### Mod name

TieFix

### Other links

https://modrinth.com/mod/tiefix
https://github.com/j-tai/TieFix

### What it does

A Fabric mod that fixes some annoying bugs in the Minecraft client.

### Why should it be in the modpack

It fixes some bugs in the Minecraft client. Because it is only clientside, it does not change any game mechanics.

### Why shouldn't it be in the modpack

Not on CurseForge, maybe some servers see it as cheating if you can use GUIs in a nether portal (?)

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment]
Interesting. For inclusion I would want CF and a graphical config, but I'm thinking if those specific bugs are significant enough to be fixed via a mod.
