### ISSUE TITLE
better-rsqrt

### ISSUE THREAD

**Issue by guio75t855t** [Fabulously-Optimized/fabulously-optimized#190]
### Mod name

better rsqrt

### Other links

https://modrinth.com/mod/better-rsqrt
https://github.com/leocth/better-rsqrt

### What it does

Changes Minecraft rsqrt to more accurate ones
*Used in rendering

### Why should it be in the modpack

Beter rendering

### Why shouldn't it be in the modpack

Idk

### Categories

Graphics optimization

**Comment by Madis0** [comment]
I think Sodium already does this or it wouldn't have any effect with Sodium enabled. Asked there just in case.

**Comment by Ilikemilkxd** [comment]
Ok

**Comment by Madis0** [comment]
https://discord.com/channels/602796788608401408/752637878462578778/919560727784726569 :shrug: 

If you have a better idea on how to rephrase the question, feel free :grin:

**Comment by Hdhddufhrbtbtbfh848** [comment]
This mod is ok ish for weak computers. You can close this

**Comment by Ilikemilkxd** [comment]
Ok. Sorry for the inconvenience

**Comment by Madis0** [comment]
No need to apologize for the suggestion itself (and you're not even the OP 😄), it just doesn't seem to be useful considering the current mod setup FO has.
