### ISSUE TITLE
Functional/Misc: Discord "playing" status

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/fabulously-optimized#191]
### Mod name

Simple Discord RPC

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/simple-discord-rpc

### Other links

https://github.com/hypherionmc/simple-rpc-public

### What it does

"Simple Discord RPC is a simple and easy to use mod that allows you to display what you are doing in Minecraft on your Discord Status. This is useful for modpacks that want to advertise themselves, or for people who simply want a nicer way to show that they are playing Minecraft. This mod works out of the box, but you can customize it to suit your needs."

### Why should it be in the modpack

- shows others that you're playing Minecraft
- always new updates (1.18.1 is available, updated 18h ago, ...)
- many downloads (3M) seems people enjoy it

### Why shouldn't it be in the modpack

- not open source
- a bit unnecessary, especially for people that don't use Discord 
- not performance boosting (even though it surely won't take all your performance)

### Categories

New feature

### Additional details

Alternatives:
- https://www.curseforge.com/minecraft/mc-mods/discordrpc [1.17.1 only at the moment]

**Comment by itsmeboy0** [comment]
CraftPresence is rejected in https://github.com/Fabulously-Optimized/fabulously-optimized/issues/14.

**Comment by nsde** [comment]
Okay!

**Comment by Madis0** [comment]
Yeah, I was thinking that this could breach users' privacy for advertising some (relatively unknown, still) client, which could also make it look like it provided hacks or pvp features (disallowed in some servers) while actual the intention of the modpack is to seem like vanilla.

**Comment by nsde** [comment]
You're completely right. Agreed!
