### ISSUE TITLE
Charmonium

### ISSUE THREAD

**Issue by guio75t855t** [Fabulously-Optimized/fabulously-optimized#194]
### Mod name

Charmonium

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/charmonium

### Other links

https://github.com/svenhjol/Charmonium
https://modrinth.com/mod/charmonium

### What it does

Adds more ambience and biome and time specific sounds and music

### Why should it be in the modpack

Is very cool and vannila freindly

### Why shouldn't it be in the modpack

No need if u only want performance

### Categories

New feature

**Comment by Madis0** [comment]
Seems cool, but it adds extra content which is not the goal for this pack. This pack should only add the _tools_ to make it easy for you to add any extra content easily (e.g. support more resource pack features).
