### ISSUE TITLE
Better fps render distance

### ISSUE THREAD

**Issue by Hdhddufhrbtbtbfh848** [Fabulously-Optimized/fabulously-optimized#195]
### Mod name

Better fps render distance

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance

### What it does

Improvements:

Render distance:

By default minecraft renders everything in a square radius, this is changed to a 3d circular radius which can be stretched horizontally via config or video option(video options button is not available with optifine). The higher the stretch the less caves below you will be rendered, esp distant ones. Provides about 10-35% less chunk sections to be rendered and thus gives a neat fps boost.

 

Config/Video Options:
Adds "HRdistStretch" Option which allows you to stretch the circular render distance in horizontal direction. Aka: Set it higher and less sections lower/higher than you will be rendered.

 

1.18: Minecraft implemented this partially, by making the chunks that render in 2d circle, however they will still render those chunks completely. Since this mod changed the radius to 3d it will still yield a decent benefit on 1.18 aswell since it also stops too many chunksections from rendering.

### Why should it be in the modpack

Improvements:

Render distance:

By default minecraft renders everything in a square radius, this is changed to a 3d circular radius which can be stretched horizontally via config or video option(video options button is not available with optifine). The higher the stretch the less caves below you will be rendered, esp distant ones. Provides about 10-35% less chunk sections to be rendered and thus gives a neat fps boost.

 

Config/Video Options:
Adds "HRdistStretch" Option which allows you to stretch the circular render distance in horizontal direction. Aka: Set it higher and less sections lower/higher than you will be rendered.

 

1.18: Minecraft implemented this partially, by making the chunks that render in 2d circle, however they will still render those chunks completely. Since this mod changed the radius to 3d it will still yield a decent benefit on 1.18 aswell since it also stops too many chunksections from rendering.

### Why shouldn't it be in the modpack

Closed source mod

### Categories

Performance optimization

**Comment by Madis0** [comment]
I think it is not compatible with Sodium, Phosphor/Starlight but worth a try.

**Comment by Hdhddufhrbtbtbfh848** [comment]
> I think it is not compatible with Sodium, Phosphor/Starlight but worth a try.

Ok will test the mod with starlight and phosphor

**Comment by Hdhddufhrbtbtbfh848** [comment]
Dude, this mod is probably incompatible with phosphor.
When I launched minecraft with it everything seemed fine and the fps boost kicked in. But then minecraft froze. I guess it was too much for my pc
Pc specs
i3-40310U 1.70hz
4gb ddr3
500gb hdd
Intel graphics family
(I know it's not the best pc but cmon)

**Comment by Hdhddufhrbtbtbfh848** [comment]
I didn't test it with starlight tho

**Comment by Madis0** [comment]
Others claim no freeze but no fps improvement either.

**Comment by Radk6** [comment]
> Many problems were solved and mod is open source now. You can reconsider.

The mod most likely won't be on Modrinth ([1](https://github.com/someaddons/betterfpsdistances/issues/12), [2](https://github.com/someaddons/betterfpsdistances/issues/16), [3](https://github.com/someaddons/betterfpsdistances/issues/32)), so that will create another Farsight/HoldThatChunk situation.

Also, not everyone may like what the mod does: 

This is latest 1.21 FO beta with Better FPS - Render Distance at default settings:
![2024-07-01_15 43 10](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/63958709/d8c50f9f-3311-48d4-b0d0-d13b03b20254)

This is the same world without the mod:
![2024-07-01_15 57 01](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/63958709/d4c6e75c-1552-425a-a612-a2e4370c7a51)
