### ISSUE TITLE
Custom LAN

### ISSUE THREAD

**Issue by itsmeboy0** [Fabulously-Optimized/fabulously-optimized#196]
### Mod name

Custom LAN

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/custom-lan

### Other links

https://modrinth.com/mod/custom-lan
https://github.com/DimiDimit/Custom-LAN

### What it does

Minecraft Fabric mod that gives you more control over your integrated server through the Open to LAN menu.

### Why should it be in the modpack

Mainly I was annoyed that online mode was on by default on LAN servers and you cannot change it.

Also, from the description:
> - Customize more of your integrated server (Online Mode, PvP, Port, Max Players, MOTD)
> - Change the settings mid-game (including the port) and stop the server without quitting the world
> - Change who can use cheats individually using the /op and /deop commands and cheat in singleplayer without opening to LAN (replaces the Allow Cheats button)
>
> It also allows you to start the LAN world by pressing Enter, doesn't force the gamemode (e.g. anyone who left in Creative mode will still be in Creative when they join even if the world is set to Survival), and extends the /publish command, which can now change settings mid-game as well

### Why shouldn't it be in the modpack

None to think of.

### Categories

New feature

**Comment by Madis0** [comment]
Cool idea, but I'm not so sure my target audience would actually care about any of that.

**Comment by Madis0** [comment]
- Seems niche, I don't think many people need such control on LAN (where you can literally speak to the people you're playing with)
- Online mode toggle gives a bad example, FO does not support cracked players anyway
- Changes some vanilla behaviours like cheats toggle
