### ISSUE TITLE
Starline

### ISSUE THREAD

**Issue by Donut678** [Fabulously-Optimized/fabulously-optimized#197]
### Mod name

Starline

### Other links

https://github.com/HyperCubeMC/Iris

### What it does

Adds shader option support for iris shaders.

### Why should it be in the modpack

It should be in the modpack so you have shader configurability.

### Why shouldn't it be in the modpack

It may be updated less fast because it is a fork of iris.

### Categories

Graphics optimization, New feature, Works like Optifine/Bedrock Edition/Forge/etc, Replaces an existing mod

### Additional details

It is a little complicated to install.

**Comment by itsmeboy0** [comment]
Already rejected in https://github.com/Fabulously-Optimized/fabulously-optimized/issues/147#issuecomment-932820459.
