### ISSUE TITLE
Severely glitched models with the Custom Entity Models mod

### ISSUE THREAD

**Issue by Donowa93** [Fabulously-Optimized/fabulously-optimized#199]
### Describe the bug

The mod _Custom Entity Models (CEM)_ is used in the modpack as a stand-in for Optifine's feature of the same name. However, the fabric mod is incompatible with any resource pack that uses the Optifine format of models (which is basically every resource pack that uses custom models)

### Expected behavior

The custom models and textures are loaded with the same results as optifine (at least on supported entities)
Optifine:
![Screenshot from 2021-12-17 17-26-40](https://user-images.githubusercontent.com/73498757/146616128-ef7de193-5d56-4743-8df3-c9fb0b4d193f.png)
Vanilla:
![Screenshot from 2021-12-17 17-29-02](https://user-images.githubusercontent.com/73498757/146616149-917aaca7-3fc6-475d-9edf-d1baa9e4aa9e.png)

### Observed/actual behavior

The UVs are screwed up for entities, including the ones that the mod claims to support
In addition, certain elements of the entities are rotated in bizarre ways, and the behavior doesn't match optifine or vanilla
The Mod: 
![Screenshot from 2021-12-17 17-13-08](https://user-images.githubusercontent.com/73498757/146616110-f20cbac6-e726-4fb9-a95e-e7d8cc5503b8.png)

### Steps To Reproduce

1. Launch Minecraft
2. Load a resource pack that has Optifine CEM
3. Load a world
4. (wait for the game to) spawn a mob that's replaced by the pack

### Modpack version

3.1.0-alpha.1

### Launcher

MultiMC

### Install method

Other (please write below)
I installed via MultiMC, but I installed some other mods like Terralith and BetterNether
### Additional context

The pack used in the screenshot is DefaultEx by Stridey https://www.planetminecraft.com/texture-pack/defaultex/

**Comment by Madis0** [comment]
See

https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Resource-pack-issues#custom-entity-models
and 
https://github.com/dorianpb/cem/issues/9

**Comment by Donowa93** [comment]
Even still, I enabled the entity creation fix and the UVs are still fubar
![image](https://user-images.githubusercontent.com/73498757/146644976-3dc22e45-3b4b-4c3c-8de3-f81c8b8fd7c3.png)

**Comment by Madis0** [comment]
Yeah, it seems like that resource pack (even those specific mobs) is using some features that are not supported by the mod yet.

**Comment by Donowa93** [comment]
yeah, i went into optifine, and it seems like the uvs are dependent on the random entity function

**Comment by Madis0** [comment]
Sorry, nothing I can do to fix it at this time. Feel free to contribute to the mod or disable the mod on your end.
