### ISSUE TITLE
java.util.NoSuchElementException crash on opening worlds

### ISSUE THREAD

**Issue by DrKing101101** [Fabulously-Optimized/fabulously-optimized#203]
### Describe the bug

First time writing one of these so apologies if I'm doing this wrong. Just downloaded the latest version of Fabric Launcher and FO, game launches fine. On opening worlds (local or servers), the game crashes with the error "java.util.NoSuchElementException". Crash report:
https://bytebin.lucko.me/oD34r9V04P

### Expected behavior

World opened as it should.

### Observed/actual behavior

Game crashed and world is unabled to be opened.

### Steps To Reproduce

1. Launched Minecraft using the fabric launcher profile.
2. Attempt to open a world
3. Game crashes after "saving world" shows on the loading screen.

### Modpack version

3.1.0-alpha.3 for 1.18.1 (MultiMC)

### Launcher

Minecraft Launcher (vanilla)

### Install method

Upgraded an existing profile (please write below, what version to what version)

### Additional context

Updated the modpack from 3.0.0-alpha.2 (not 100% sure on this, was either alpha 2 or 3) to the latest version (3.1.0-alpha.3).

**Comment by Madis0** [comment]
Interesting, I have not seen such crash before. Please try a clean profile and preferably another launcher (some issues may derive from installing it wrong on vanilla launcher or maybe something existing conflicts with it... not sure).

**Comment by DrKing101101** [comment]
> Interesting, I have not seen such crash before. Please try a clean profile and preferably another launcher (some issues may derive from installing it wrong on vanilla launcher or maybe something existing conflicts with it... not sure).

I've tried uninstalling and reinstalling fabric loader with no luck, might try and reinstall FO and see if that works. I've installed it the same way I installed the mod before and it worked, so I don't think it's the installation process.

**Comment by Madis0** [comment]
Is this still an issue for you? @DrKing101101

**Comment by DrKing101101** [comment]
> Is this still an issue for you? @DrKing101101

Sorry, forgot to update but yeah it got fixed when I updated the modpack to the next alpha. I still sometimes get the crash but a restart of the minecraft client seems to fix it.

**Comment by Madis0** [comment]
Hmm, okay. I'll close this for now and reopen if someone else can reproduce it.
