### ISSUE TITLE
Hat List

### ISSUE THREAD

**Issue by terabyte25** [Fabulously-Optimized/fabulously-optimized#207]
### Mod name

Hat List

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/hat-list

### Other links

https://modrinth.com/mod/hatlist

### What it does

Shows the hat layer of skins on the player list "head" preview.  See below for before and after.

![demo](https://user-images.githubusercontent.com/23338617/146983942-ca9f9e99-eddf-4e61-ac37-42419afdfe8c.gif)

### Why should it be in the modpack

Greater level of detail on the player list window - sometimes not seeing the hat layer included is a bit confusing for players. 

### Why shouldn't it be in the modpack

Very small change that most players don't even notice. Also has not been officially updated for 1.18 (last mod update was in June), but still supports it.

### Categories

New feature

**Comment by Madis0** [comment]
I will not add any _new_ mods that are not updated to the latest version, so having 1.18.1 support is needed for me to even consider this. Still, looking for feedback from people who consider this an issue.

**Comment by wu4x** [comment]
I am currently using this mod and it doesn't need to be updated for 1.18 because it is so simple. It works perfectly like this.

**Comment by Madis0** [comment]
I tested this mod and vanilla 1.18.2 and they worked the same, meaning this feature (now) already exists in vanilla.
