### ISSUE TITLE
Screenshot to Clipboard

### ISSUE THREAD

**Issue by terabyte25** [Fabulously-Optimized/fabulously-optimized#208]
### Mod name

Screenshot to Clipboard

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/screenshot-to-clipboard-fabric.

### Other links

https://modrinth.com/mod/screenshot-to-clipboard

### What it does

Automatically copies in-game screenshots to the clipboard.

### Why should it be in the modpack

Makes it much easier for users to share screenshots to applications such as Discord, instead of having to dig through the file system to find and post the image.

### Why shouldn't it be in the modpack

Some users may find it annoying that their clipboard gets cleared and replaced with the screenshot image. 

### Categories

New feature

**Comment by Madis0** [comment]
> Some users may find it annoying that their clipboard gets cleared and replaced with the screenshot image.

Yup, this defies vanilla expectations, so it should be added by the user themselves, if they need that.
