### ISSUE TITLE
AutoRun

### ISSUE THREAD

**Issue by terabyte25** [Fabulously-Optimized/fabulously-optimized#209]
### Mod name

AutoRun

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/autorun-fabric

### Other links

https://modrinth.com/mod/autorun

### What it does

Enables auto walking in Minecraft with a keybind, which can also be turned into sprinting by hitting the sprint key.

### Why should it be in the modpack

Makes it much less tedious on fingers to go long distances as you don't have to hold down on one key the whole time. 

### Why shouldn't it be in the modpack

Adds one keybind, which contributes to a bigger list of keybinds in controls that people may find irritating. Also, people accidentally hitting the keybind without knowing what it is could potentially be confused by it. 

### Categories

New feature

**Comment by Madis0** [comment]
Adds a new feature that solves a specific issue for some specific people, so those people should install it manually.

Any new mod I add should be useful for at least 70% of people while keeping the "vanilla experience".
