### ISSUE TITLE
Mod Request: Skin Layers 3D

### ISSUE THREAD

**Issue by bigfinfrank** [Fabulously-Optimized/fabulously-optimized#211]
### Mod name

Skin Layers 3D (Fabric/Forge)

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d

### Other links

GitHub: https://github.com/tr7zw/3d-skin-layers

### What it does

"Replaces the usually flat second layer of player skins with a 3d modeled version". Basically instead of having the outer layer of players' skins be 2D floating pixels, it connects them to the skin making them 3d. Skins with outer layers end up looking a bit cleaner, it's subtle but it's aesthetically really nice.

### Why should it be in the modpack

It's a subtle visual change that makes the game look a little bit better without changing much, it's an especially nice attention-to-detail style thing for screenshots.

### Why shouldn't it be in the modpack

Adding a bit more complexity to player skins will of course (minorly) impact performance\*, the mod does combat this by switching back to 2D layers when players are 12+ blocks away.

Additionally it's incompatible with a few mods (none of which are in FO):
- HD Skins
- Epic Fight Mod
- Emotecraft animations

\* I haven't noticed any difference but obviously there has to be *some* impact

### Categories

Graphics optimization

**Comment by Madis0** [comment]
Hmm, I don't know about this...
On big servers there can be a lot of players in one place and changing models could indeed hinder the performance. Also, this may make some (several?) skins look different from their intention, [e.g. these](https://www.planetminecraft.com/skins/?keywords=moving+eyes&order=order_popularity).

**Comment by Banaando** [comment]
I ran several benchmarks using a program called Fraps to test the FPS I got while standing perfectly still in the center of Bedwars lobby 1 on Hypixel, so basically worst-case scenario. I used the default settings of Fabulously Optimized and Skin Layers 3D. Here are the results:
![image](https://user-images.githubusercontent.com/67934979/147527132-cdf333f6-bbc8-4c56-84a3-9010a4aca496.png)
So there was only about an 8% decrease in FPS on my machine in the worst-case scenario so I don't think the performance impact is much of a problem. Also, I've almost never seen people with the moving eyes skins and I think the trade-off of making almost all skins look better while breaking some skins is fine.

**Comment by Madis0** [comment]
8% is quite substantial on some computers, Hypixel is a popular server as well.
I tried it out and while it didn't seem to "break" those skins exactly (the underlay was still possible to see), I just didn't like the aesthetic of this. People who like this [can add it manually](https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Adding-more-mods) :)
