### ISSUE TITLE
Feature NBT deadlock be gone

### ISSUE THREAD

**Issue by guio75t855t** [Fabulously-Optimized/fabulously-optimized#212]
### Mod name

Feature NBT deadlock be gone

### Curseforge link

No

### Other links

https://modrinth.com/mod/feature-nbt-deadlock-be-gone
https://github.com/TelepathicGrunt/FeatureNBTDeadlockBeGone

### What it does

Fixes 

### Why should it be in the modpack

No deadlocks

### Why shouldn't it be in the modpack

Not on cf

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment]
It surely sounds like a bad bug, but I have no idea how would one reproduce this in simple gameplay. Isn't this bug just affecting the creators of datapacks?

**Comment by guio75t855t** [comment]
Yah your probably right.

**Comment by Madis0** [comment]
Very specific bug that is hard to reproduce for most users (and therefore useless for most) + mod has been removed in Modrinth.

**Comment by wafflecoffee** [comment]
> Very specific bug that is hard to reproduce for most users (and therefore useless for most) + mod has been removed in Modrinth.

Not removed from Modrinth. Modrinth is having server issues right now. Please don't jump to assumptions; outright removals of mods from Modrinth are very rare.
