### ISSUE TITLE
Switch from Dynamic FPS to FPS Reducer

### ISSUE THREAD

**Issue by Banaando** [Fabulously-Optimized/fabulously-optimized#213]
### Mod name

FPS Reducer

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/fps-reducer

### Other links

[Github (outdated)](https://github.com/juliand665/Dynamic-FPS)

### What it does

It does the same thing as Dynamic FPS, reduces FPS when you're not tabbed onto the game or AFK for too long, but it also allows you to configure how loud the game is when the mod is active, so you can configure it to mute the game when you tab off of it.

### Why should it be in the modpack

It allows people to mute the game on top of their FPS being reduced so if you were AFK next to a loud farm you don't have to manually turn down the volume to AFK next to it.

### Why shouldn't it be in the modpack

"Dynamic FPS is generally more lightweight, and from what I remember of FPS Reducer, it doesn't save on background performance as much as Dynamic FPS does, does not have the ability to restore FPS on hover (and generally offers a different set of options), never completely stops rendering, and takes longer to resume rendering once the window is active again (whereas Dynamic FPS is instant here)." -juliand665 (author of Dynamic FPS)

### Categories

Performance optimization, New feature, Replaces an existing mod

### Additional details

Config screen and default options:
![image](https://user-images.githubusercontent.com/67934979/147522852-e7dad825-7863-487f-9016-b256ae3ce03e.png)

**Comment by Madis0** [comment]
So the main reason for your suggestion seems sound and per "why shouldn't it be in the modpack" there are a lot of drawbacks to that. 

Solution: suggest a sound muting option to Dynamic FPS? 😛

**Comment by Madis0** [comment]
Apparently already suggested: https://github.com/juliand665/Dynamic-FPS/issues/42

Closing this now.

**Comment by juliand665** [comment]
Wanted to point out that Dynamic FPS now has this feature :)
