### ISSUE TITLE
[Mod Request] Ears

### ISSUE THREAD

**Issue by bb010g** [Fabulously-Optimized/fabulously-optimized#214]
### Mod name

Ears

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/ears

### Other links

* Ears Skin Manipulator: https://unascribed.com/ears/
* Modrinth: https://modrinth.com/mod/ears
* Source code repository: https://git.sleeping.town/unascribed/ears
* Source code repository (mirror): https://github.com/unascribed/Ears

### What it does

From the Curseforge description (emphasis theirs):

> ![ears-banner.png](https://user-images.githubusercontent.com/340132/147611345-b35d522f-1556-48fd-b0c6-6121fce87a7c.png)
>
> **Faithful fancy fashion features for fuzzy folk.**
>
> Created due to a lack of the [Tails](https://www.curseforge.com/minecraft/mc-mods/tails/) mod for 1.16, Ears is a mod that adds ears, snouts, tails, horns, wings, and more to the player.
>
> Ears has a more vanilla-faithful appearance than Tails, with a lot of 2D regions but a few 3D ones too. There are a wide variety of possible configurations and it can all be customized.
>
> **Why use Ears instead of Tails?** Because Ears is easy to port to other versions, based on a multi-version abstraction allowing the mod to even run in web browsers. The Tails mod has wonderful 3D models and animations, but it's a burden to update it to any version due to its large rendering system and all the data syncing code, causing it to be tightly coupled with the version of the game and mod loader it was designed for. Ears stores all data as pixels in the player's skin.
>
> **However, Ears requires you to draw your own additions**, and does not come with easy recolorable prefabs like Tails. Additionally, unlike CPM or Figura, Ears has a limited number of customization options. (Note that if you have a simple idea, I may add it. Open an issue on GitHub or hop in Discord.) **Ears offers a good middle-ground that will work in any version you wish to play**, and will receive updates to snapshots for those of you who live on the edge. It also does not and never will use external servers, just Mojang's skin server, so there's no concerns about a third-party server going down (be it temporarily or for good).
>
> **Why use Ears instead of other skin fixes?** Ears provides a lot of new features to customize your skin, and is a much more lightweight patch with no usage of third-party servers and is completely open source. Additionally, Ears backports translucent secondary layer support to 1.8 and 1.7.

### Why should it be in the modpack

Ears allows for customizing skins to include ears, claws, horns, tails, snouts, and wings, all in a vanilla-like style, using only Mojang's player skin data. See the [Ears Skin Manipulator](https://unascribed.com/ears/). Not all players will want to use these features, but in those cases this mod is benign and changes nothing. For those that do want a more expressive skin, Ears is great, and including the mod means that players can appreciate the Ears-extended skins of others. Additionally, Ears requires no client-side configuration.

The Curseforge description does a pretty good job summarizing why Ears is a reliable, benign addition: only the normal Mojang player skin texture is used (no external servers), it's widely ported across Minecraft versions (and also usable on Forge), and it's kept up to date (thanks in part to its simplicity).

### Why shouldn't it be in the modpack

Ears relies on unused skin texture space to hold its data. This space is unlikely to be used soon, but if Mojang decides to use more space in the future for skin extensions that aren't compatible with Ears, both Ears and those skins will have to be updated.

Ears could also conflict with other mods that store data in unused skin texture space, but I don't know of any other mods that do so besides Ears.

Ears allows for new forms of user-provided content shown to players in multiplayer settings, but the downsides are pretty much the same as showing existing user-provided skins, just with an extended canvas.

### Categories

New feature

**Comment by nchristopher** [comment]
In my opinion, this is a very niche mod, which the majority of modpack users wouldn't use. While it's true that those users could just not use the mod, it still adds unnecessary bloat. For the (presumably) minority of users who *would* want to use the mod, they can always add it themselves.

**Comment by nsde** [comment]
This is purely cosmetic, and FO is focused on performance. It's more or less useless, in my opinion.

**Comment by Madis0** [comment]
I've been thinking about this for a while, the pros and cons of adding it... at the end I just got the result of my own subjective opinion: I don't like it, sorry.

Here's [some more discussion](https://discord.com/channels/859124104644788234/859124543712133130/925626614904152075) if anyone's interested though. [(via)](https://discord.gg/yxaXtaQqdB)
