### ISSUE TITLE
DCCH mod not compatible for minecraft 1.18.1 

### ISSUE THREAD

**Issue by KOMPuteRSH4IK** [Fabulously-Optimized/fabulously-optimized#216]
### Describe the bug

After installing the mod package, it does not start, writes a problem in the DCCH mode, after removing it, everything starts

### Expected behavior

Minecraft it doesn't starting 

### Observed/actual behavior

Minecraft it doesn't starting 

### Steps To Reproduce

1.Launched Minecraft
2Minecraft does not start because the Fabric gives an error related to this mod

### Modpack version

3.1.0-alpha 5 for 1.18.1(MultiMC)

### Launcher

Minecraft Launcher (vanilla)

### Install method

FO fresh install/new profile

### Additional context

![bug](https://user-images.githubusercontent.com/91939368/147822554-09a25f99-85a6-4c51-a0ea-6a36f71fb89f.PNG)

**Comment by Madis0** [comment]
You forgot to copy _fabric_loader_dependencies.json_ from the _config_ folder. See https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Install-instructions#minecraft-launcher-the-vanilla for install instructions.

**Comment by KOMPuteRSH4IK** [comment]
Thank you
