### ISSUE TITLE
Creative keybind

### ISSUE THREAD

**Issue by guio75t855t** [Fabulously-Optimized/fabulously-optimized#221]
### Mod name

Creative keybind

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/creative-keybind

### Other links

https://modrinth.com/mod/creative-keybind
https://github.com/AmyMialeeMods/creative-keybind

### What it does

Mod name is the feature duh.

### Why should it be in the modpack

No more typin' /gamemode creative

### Why shouldn't it be in the modpack

I don't know!!!!!!!!!!!!!

### Categories

New feature

### Additional details

P.S dosent let u switch if cheats r off

**Comment by Madis0** [comment]
Already exists in vanilla: hold down F3 and press F4. That one also works for toggling any game modes, not just survival and creative
