### ISSUE TITLE
[1.18.1] Chest texture is not correctly rendered

### ISSUE THREAD

**Issue by KhanhPham05** [Fabulously-Optimized/fabulously-optimized#223]
### Describe the bug

Chests are invisible (this issue affects both single world and servers)

### Expected behavior

Chest should normally rendered, however, it just only render the chest head WHEN OPEN

### Observed/actual behavior

look at the screenshots

### Steps To Reproduce

1. Log in a game
2. Now  the chest is invisible

### Modpack version

1.18.1 - alpha 7

### Launcher

Minecraft Launcher (vanilla)

### Install method

Using with additional mods/something else (please write below)

### Additional context

Additional Mods: 
Xaero Minimap + World Map
First Person Model
Not Enough Animations
PaperDoll
3D Skin Layer
(Those added mods aren't effect the chest rendering - tested without the pack)

IMAGES
![2022-01-09_09 41 41](https://user-images.githubusercontent.com/68932626/148675895-991f27f2-ce71-4d0e-b587-15b4840a1eef.png)
![2022-01-09_09 39 40](https://user-images.githubusercontent.com/68932626/148675896-9d6dc1e2-84c2-40c3-8843-372c1c9f5bc1.png)

**Comment by KhanhPham05** [comment]
Texture Pack used: Stay True + No Bushy Leaf Addon

**Comment by Madis0** [comment]
It is your resource pack, see this page to fix it: https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Resource-pack-issues

**Comment by guio75t855t** [comment]
No, it is an issue with enhanced block entities.

**Comment by Madis0** [comment]
> No, it is an issue with enhanced block entities.

Well, maybe, but only partly. The main problem is that the resource pack is using non-standard file paths (e.g. spaces in folders) and that can make several mods act weird.

**Comment by Hdhddufhrbtbtbfh848** [comment]
I don't think so. If you go to the eve issue page there's an issue titled "things are invisible with resource pack." It is caused by the mod itself. If you remove it, it gets fixed.
