### ISSUE TITLE
Fabrilous updater

### ISSUE THREAD

**Issue by guio75t855t** [Fabulously-Optimized/fabulously-optimized#225]
### Mod name

Fabrilous updater

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/fabrilous-updater

### Other links

https://github.com/HughBone/fabrilous-updater

### What it does

Automatically searches for mod updates by typing /fabdate update

### Why should it be in the modpack

No more hassle to update mods

### Why shouldn't it be in the modpack

As of now the autoupdate dosent work.

### Categories

New feature

### Additional details

Yezzzzzz

**Comment by Madis0** [comment]
I've thought about something like that previously, but including this now while I actively develop FO is not a great idea, people self-updating their mods can sometimes mess things up (e.g. config changes are needed, overrides are needed, some update may introduce a crash or an incompatibility etc). Maybe this will be included when I stop developing FO altogether.

**Comment by Madis0** [comment]
Closing this as I do not intend to discontinue FO in the near future and including this while I do would cause more harm than good.
