### ISSUE TITLE
Mods description in CurseForge is outdated.

### ISSUE THREAD

**Issue by Jamelos** [Fabulously-Optimized/fabulously-optimized#226]
Lot's of times mods leave and enter Fabulously Optimized, but the description containing the mods never gets updated, so update it. As for the mods differences between 1.18, 1.17 and 1.16, just separete them in section. That's all folk's.

**Comment by Madis0** [comment]
Hmm. Right now

* Latest development version modlist (currently 1.18.1) is listed in GitHub
* Latest stable version modlist (currently 1.17.1) is listed in Curseforge
* Any older versions (e.g. 1.16.5) are listed in Curseforge individual files

I would argue that 1.16.5 for example is old anyway and you should not use it... but then again, I still update it so maybe I will think of a place to list it in.
