### ISSUE TITLE
Entity Texture Features

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#231]
### Mod name

Entity Texture Features

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric

### Other links

https://github.com/Traben-0/EmissiveMod
https://modrinth.com/mod/entitytexturefeatures

### What it does

Random and emissive textures for entities

### Why should it be in the modpack

Seems directly compatible with Sodium/Indium and Optifine's format, so is way better than #75 

### Why shouldn't it be in the modpack

Untested; emissive textures are [claimed to be done worse](https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric?comment=6) than #218; emissive and random textures seem to have some limits (not sure if they match Optifine's limits)

Edit: I think the bugs and limits are fixed now

### Categories

Works like Optifine/Bedrock Edition/Forge/etc

**Comment by Julienraptor01** [comment]
Hello
As said in this discussion https://www.curseforge.com/minecraft/mc-mods/entity-texture-features-fabric?comment=21 ETF is compatible with puzzle (if puzzle's emmisives are disabled) and the mod is now as optimized as #218

**Comment by Madis0** [comment]
Added.
