### ISSUE TITLE
Invisible Chests with the Stay True resource pack

### ISSUE THREAD

**Issue by mariowhitmore** [Fabulously-Optimized/fabulously-optimized#232]
### Describe the bug

Chests are invisible when the [Stay True](https://www.curseforge.com/minecraft/texture-packs/stay-true) resource pack is used.

### Expected behavior

Chest is visible.

### Observed/actual behavior

Chest is completely transparent.
The outline of the chest is visible.
The lid of the chest is visible when the chest is opened and the opening and closing animations are being played. 

### Steps To Reproduce

Load the stay true resource pack, join or load a world and try view a chest. 

### Modpack version

3.1.0

### Launcher

GDLauncher

### Install method

FO fresh install/new profile

### Additional context

![image](https://user-images.githubusercontent.com/36354501/151140614-64bac916-c5fc-44f8-939f-c21c49949867.png)
![image](https://user-images.githubusercontent.com/36354501/151140641-ee8ed4f2-d414-4521-a765-cc9302ecffa2.png)

**Comment by Madis0** [comment]
This is known and it is a problem with that particular resource pack (not FO). Luckily it can be worked around: https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Resource-pack-issues
