### ISSUE TITLE
Blockify mod

### ISSUE THREAD

**Issue by TiboOpGithub** [Fabulously-Optimized/fabulously-optimized#238]
### Mod name

Blockify

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/blockify

### Other links

Modrinth: https://modrinth.com/mod/blockify

### What it does

The mod links the music from spotify in your game. You also have to log in with your spotify account before using it, so if you don't want that, it won't do anything.
![image](https://user-images.githubusercontent.com/95926002/153763021-87ca23de-663a-40c4-a131-86c50e1129ed.png)

### Why should it be in the modpack

Because it is useful if you use spotify and you are free whether you want to use it or not.

### Why shouldn't it be in the modpack

Because it has nothing directly to do with minecraft.

### Categories

New feature

**Comment by Madis0** [comment]
Very specific use case, especially because it requires sign in as well. Better install it manually :)
