### ISSUE TITLE
1.x.x crashes with Hydrogen on Java 12

### ISSUE THREAD

**Issue by dizicheng** [Fabulously-Optimized/fabulously-optimized#241]
### Describe the bug

Unable to start, displaying the wrong Java version, but clearly 12 is the correct Java version.

### Expected behavior

Normal boot

### Observed/actual behavior

[minecraft-exported-crash-info-2022-02-19T22-11-29.zip](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8102325/minecraft-exported-crash-info-2022-02-19T22-11-29.zip)

### Steps To Reproduce

Click Start, and an error occurs after a period of time

### Modpack version

1.12.2

### Launcher

Other (please write below)

### Install method

FO fresh install/new profile

### Additional context

[minecraft-exported-crash-info-2022-02-19T22-11-29.zip](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8102325/minecraft-exported-crash-info-2022-02-19T22-11-29.zip)

**Comment by Madis0** [comment]
I thought Hydrogen is compatible with Java <16, but it looks like it requires Java 8 (or maybe 8-11). So basically disable that if you use a newer Java.

**Comment by dizicheng** [comment]
This continued after I disabled the Hydrogen and lowered the version to Java8
[minecraft-exported-logs-2022-02-20T10-46-45.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8103362/minecraft-exported-logs-2022-02-20T10-46-45.log)
The few times I've had a successful run I can see that the Mods aren't running at all. I'm not sure what setup caused it.
This is the error screen of the initiator，
![uTools_1645325573889](https://user-images.githubusercontent.com/21209008/154826516-45b3ef89-e98c-4939-9e48-67784d81e960.png)

**Comment by dizicheng** [comment]
I think you are absolutely right, I disabled the Hydrogen and kept the version in java16 after. I can get into the game right.
