### ISSUE TITLE
Don't Clear Chat History is for 1.17

### ISSUE THREAD

**Issue by SirKrunk** [Fabulously-Optimized/fabulously-optimized#242]
### Describe the bug

![Uploading Screenshot2022_02_21_101326 AM.jpg…]()

### Expected behavior

Minecraft to be loaded

### Observed/actual behavior

![Uploading Screenshot2022_02_21_101326 AM.jpg…]()

### Steps To Reproduce

1. Launched Minecraft
2. Showed Incompatible mod set
3. Removed Don't Clear Chat History
4. Launched Minecraft
5. Minecraft has been launched properly

### Modpack version

3.2.2 for 1.18.1 (Curseforge)

### Launcher

Curseforge Launcher

### Install method

Using with additional mods/something else (please write below)

### Additional context

ftb-library-fabric-1801.3.5-build.109.jar
fabric-api-0.46.4+1.18.jar
ftb-quests-fabric-1801.3.7-build.87.jar
kubejs-fabric-1801.4.2-build.300.jar
rhino-fabric-1801.1.8-build.102.jar
ftb-teams-fabric-1801.2.4-build.46.jar
item-filters-fabric-1801.2.6-build.16.jar
architectury-3.6.17.jar

**Comment by SirKrunk** [comment]
![Uploading Screenshot2022_02_21_101326 AM.jpg…]()

**Comment by Madis0** [comment]
Sounds like #234 or #216, but you posted the topic too early so the screenshots didn't upload. Are you really using Curseforge Launcher?

**Comment by SirKrunk** [comment]
oops, I used the vanilla launcher and forgot to copy the configs
