### ISSUE TITLE
Replace Slight GUI Modifications with Fancy Menu

### ISSUE THREAD

**Issue by NotAHero04** [Fabulously-Optimized/fabulously-optimized#244]
### Mod name

Fancy Menu

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/fancymenu-fabric

### Other links

GitHub: https://github.com/Keksuccino/FancyMenu

### What it does

Customize in-game menus

### Why should it be in the modpack

- More lightweight than Slight GUI Modifications (about 1/7 in size including its hard dependencies)
- More options
- Comes with two optional companions: Drippy Loading Screen (which modifies the Mojang loading screen), and Load My Resources (has integration with Fancy Menu to load animations).
- Probably the best advancement: a GUI editor.

### Why shouldn't it be in the modpack

- Makes the screen more clutter (by including a built-in menu on the top).
- The customizations are plentiful, but it's somewhat confusing and needs time to learn.

### Categories

Replaces an existing mod

### Additional details

The replacement for Slight GUI Modifications is already discussed in #18, and so far I have found Fancy Menu the best one. These are some screenshots of what it can do, taken from my own modpack:
![Screenshot_20220226-110834](https://user-images.githubusercontent.com/84689840/155839460-ec1544f2-20d1-4555-bc2a-b257fdf3f267.png)
![Screenshot_20220225-145427~2](https://user-images.githubusercontent.com/84689840/155839461-8264a0aa-9d00-48b9-9ae1-dc4ca08e070a.png)
![screen-20220221-075411_exported_73073](https://user-images.githubusercontent.com/84689840/155839543-2a4671a6-fce4-4050-be94-0fc90f54bea5.jpg)

**Comment by Madis0** [comment]
I have considered this at some point, but it does seem a bit too much (functionality, setup) considering what FO needs - just a piece of text.

**Comment by Madis0** [comment]
Decided that no, this is still too much. Shedaniel said he might split the menu text to a separate mod, however.
