### ISSUE TITLE
Delete Worlds To Trash

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#245]
### Mod name

Delete Worlds To Trash

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/delete-worlds-to-trash-fabric

### What it does

Moves deleted worlds to trash instead of deleting instantly

### Why should it be in the modpack

UX improvement

### Why shouldn't it be in the modpack

Unexpected for users (similar to #165) as some may delete the worlds to gain storage space and this means they will not get it until they empty the trash. Also, on Linux it expects Gnome or its dependencies, which may leave out many FO users (I assume I do have a lot of Linux users due to the popularity of the MultiMC editions).

### Categories

New feature

**Comment by RaptaG** [comment]
Tested on an non-GNOME Linux DE (KDE to be exact) does NOT work, sadly :(

**Comment by Julienraptor01** [comment]
Did you test that ?
Q: Does this support all operating systems?
A: Moving an item to the recycle bin/trash varies a lot between operating systems, so this is indeed not guaranteed to work on all systems. This mod has been tested to work on Windows and Mac. Other Gnome based Unix systems should work, too (1.18+ only). If your Linux system is not supported, running apt-get install libgnome2-0 in terminal for installing the necessary components might just do the trick. If your system is not supported, worlds will be deleted using the vanilla method, meaning they're gone forever.

**Comment by Madis0** [comment]
As nice as it would be, it _is_ inconsistent across operating systems and therefore FO would give some users (probably a significant amount, according to MultiMC version downloads) high expectations and not actually deliver upon it. So, I can only consider this again when someone makes a PR to support the majority of Linux distros as well.
