### ISSUE TITLE
[Bug] Shadows/Lighting problems - 3.2.3 / 1.18.1 - AMD/Linux

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/fabulously-optimized#246]
### Describe the bug

I tried re-installing other versions. Same issue on [3.1.0-beta.2](https://github.com/Fabulously-Optimized/fabulously-optimized/releases/tag/v3.1.0-beta.2).

My Linux/OS is up-to-date.

Randomly happens on joining my server.

Log on [gist.github.com](https://gist.github.com/nsde/fe9e1a2ea81aa07d78db9e5069b733b8) or [mclo.gs](https://mclo.gs/LSoJ7xL)

### Expected behavior

Obviously normal lightning

### Observed/actual behavior

![image](https://user-images.githubusercontent.com/67185896/156052658-ee46607f-f9b2-47b4-a43e-c0c92ac18386.png)

### Steps To Reproduce

I'm unsure. I think it just happens randomly.. somehow.
I keep getting it without changing any mods.

### Modpack version

3.2.3

### Launcher

MultiMC

### Install method

FO fresh install/new profile

### Additional context

I think the same issue persists on GDLauncher.

**Comment by Madis0** [comment]
Perhaps you disabled the "light updates" setting on Sodium Extra? Otherwise maybe Phosphor works better than Starlight on your system.

**Comment by Madis0** [comment]
How did it go? Rajbir also suggested disabling Colormatic, but if that's the case, I don't think it's entirely random - perhaps a resource pack or non-standard gamma.

**Comment by nsde** [comment]
> Perhaps you disabled the "light updates" setting on Sodium Extra? Otherwise maybe Phosphor works better than Starlight on your system.
You were right. Sorry!
