### ISSUE TITLE
Forget me Chunk

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#254]
### Mod name

Forget me Chunk

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/forgetmechunk

### Other links

Modrinth: https://modrinth.com/mod/forgetmechunk

GitHub: https://github.com/mjwells2002/ForgetMeChunk

### What it does

ForgetMeChunk is a simple client side mod that removes a type of light update when unloading chunks.
This fixes the large lag spikes you sometimes get when crossing a chunk border.

### Why should it be in the modpack

Stable and smooth FPS, very few (possibly none) frame lag spikes

### Why shouldn't it be in the modpack

Some people say it does not help, but the stabilizes FPS on low-end GPUs (from personal experience)

### Categories

Performance optimization

### Additional details

CurseForge now available  :D 🎉

**Comment by Rajbir98** [comment]
Seems amazing I will test.....
After the testing, my feedback will be there.

Feedback
=============
Testing........

**Comment by Madis0** [comment]
FWIW, someone claimed that this may have already been fixed within Starlight, so if you don't notice a difference with this mod enabled, that's a good thing 😅

**Comment by RaptaG** [comment]
ForgetMeChunk#3

**Comment by mjwells2002** [comment]
> 

yes but no

starlight does fix the effective result of the problem ie the lag spike by making lighting faster in general but the spike is still there its just less noticeable

**Comment by RaptaG** [comment]
Now on CurseForge: https://www.curseforge.com/minecraft/mc-mods/forgetmechunk

🎉🎉

**Comment by Rajbir98** [comment]
In my case I have a low-end PC low end means really low end and it helps it reduce the spike to red to yellow
