### ISSUE TITLE
Inventory crash on 3.2.4/3.3.0-alpha.4

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#255]
### Describe the bug

Inventory crashes on all worlds

### Expected behavior

No crash

### Observed/actual behavior

Crash

### Steps To Reproduce

1. Open FO 3.2.4
2. Open any world
3. Open inventory
4. Crash

### Modpack version

3.2.4

### Launcher

GDLauncher

### Install method

FO fresh install/new profile

### Additional context

Currently unmarked the version as latest stable because of that

**Comment by Phelms215** [comment]
Am able to recreate this also https://crashy.net/ZOhsB5E9hD0uhbMubAa0

**Comment by RaptaG** [comment]
Not only inventory, when switching to 3rd person the game crashes, on the first report it said none mods where causing then Iris.. Also the hand on first person renders with transparent gaps.. (MultiMC, Linux)

https://crashy.net/efVQcioUDtdJmycErBLV

**Comment by Madis0** [comment]
Fixed on 3.2.5/3.3.0-alpha.5.
