### ISSUE TITLE
Rhythmic lag spikes with 3.3.0-beta.2 for 1.18.2

### ISSUE THREAD

**Issue by vonas** [Fabulously-Optimized/fabulously-optimized#260]
### Describe the bug

I wanted to bring to your attention that with version 3.3.0-beta.2 that I downloaded from Cursforge (https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3693340) I get continous lag spikes (frame drops that last for about 100ms), whereas those do not appear with version 3.3.0-beta.1 (https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3684748).

I haven't investigated this any further. Let me know if you can't reproduce it.

### Expected behavior

No noticable performance dip.

### Observed/actual behavior

Lag spikes.

### Steps To Reproduce

1. Compare vanilla installations of version 3.3.0-beta.1 and 3.3.0-beta.2.

### Modpack version

3.3.0-beta.2

### Launcher

MultiMC

### Install method

FO fresh install/new profile

### Additional context

![image](https://user-images.githubusercontent.com/24623262/158436878-5f7dd044-78dd-4421-a1e5-d95b0c76b7aa.png)

**Comment by Madis0** [comment]
Probably due to #46, thanks for the report. [By the end of this or next week](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/46#issuecomment-1067105734) there will be another mod for testing (#184), so you can see whether that performs better.

**Comment by Madis0** [comment]
Should be fixed with 3.3.0.
