### ISSUE TITLE
KennyTV's Force close loading screen mod

### ISSUE THREAD

**Issue by Ultrasonic1209** [Fabulously-Optimized/fabulously-optimized#261]
### Mod name

kennytvs-epic-force-close-loading-screen-mod-for-fabric

### Other links

Modrinth: https://modrinth.com/mod/forcecloseworldloadingscreen
Github: https://github.com/kennytv/kennytvs-epic-force-close-loading-screen-mod-for-fabric/

### What it does

Removes the 2-second block on the Loading Terrain... screen, making worlds and servers load in quicker.
The mod can also be configured to remove the screen entirely, but can result in visual bugs.

### Why should it be in the modpack

Reduced loading times are always great to have :)

### Why shouldn't it be in the modpack

The mod (as of the creation of this issue) is not available on CurseForge. Additionally, the visual bugs caused by removing the loading screen entirely (if configured that way) should be considered.

### Categories

Performance optimization

**Comment by Madis0** [comment]
Superseded by https://github.com/Fabulously-Optimized/fabulously-optimized/issues/273.
