### ISSUE TITLE
Skip transitions

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#262]
### Mod name

Skip transitions

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/skip-transitions
Distribution allowed

### Other links

https://modrinth.com/mod/skip-transitions
https://github.com/trufflezmc/skip-transitions

### What it does

Skips some transitions, increasing perceived speed and allowing to interact slightly faster 

### Why should it be in the modpack

Provides more options than No Fade, maybe it also encompasses more animations in the splash screen process

### Why shouldn't it be in the modpack

Animations may become jarring, not many animations should be disabled besides the loading screen one

### Categories

Performance optimization, Replaces an existing mod

### Additional details

To test: do the additional options provide more perceived speed benefit or is NoFade already good enough?

**Comment by Madis0** [comment]
Seems to be an improvement over No Fade, mainly because it removes both fade in _and_ out animations. 

However, there are some concerning issues reported (albeit fixed as well) in the repo, so I'm not too convinced about adding it just yet. Maybe for 1.19...

**Comment by nsde** [comment]
I think it's great for the loading screens, but the achievement popup looks ugly with the default configuration of this mod:
https://i.ibb.co/SPfxjVx/skiptransitions-toasts.webp

**Comment by Madis0** [comment]
Actually, the fade-in animation can stay and other than removing fade-out on loading screens, this mod is not needed anyway, No Fade serves the purpose better.
