### ISSUE TITLE
Always getting "Could not create Java Virtual Machine" error

### ISSUE THREAD

**Issue by Ultimation12** [Fabulously-Optimized/fabulously-optimized#265]
### Describe the bug

Any time I try to play with this modpack (and only this modpack, nothing extra), I cannot launch Minecraft and get the "Could not create the Java Virtual Machine" error. I don't get this error with any other separate modpacks or vanilla. 

### Expected behavior

Minecraft is able to launch.

### Observed/actual behavior

Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

### Steps To Reproduce

Launch profile from CurseForge.
Click "Play" in launcher.
Error message.

### Modpack version

2.7.3 & 3.2.6

### Launcher

Curseforge Launcher

### Install method

FO fresh install/new profile

### Additional context

I've checked a few different fixes for the error, nothing. Java is on its latest version, I've tried restarting my computer, etc. Nothing helped. Other modpacks, vanilla MC, and even an OptiFine install are able to launch fine, but I want this to work. The reason I have two different versions listed is because I tried the current release version (3.2.6) after failing to launch the MC 1.17.1 version (2.7.3) that I was trying to use. Same result.

**Comment by Madis0** [comment]
Have any crash or launcher logs?

**Comment by Ultimation12** [comment]
None that I can find. I also didn't see anything even appear in the output log when I had it open while trying to launch. I could be looking in the wrong places, though.

**Comment by Madis0** [comment]
Right, as I figured it is a corrupt jar. Go to `C:\Users\disco\AppData\Roaming.minecraft\Install\versions\`, delete the folder `fabric-loader-0.13.3-1.18.1` and retry.

**Comment by Ultimation12** [comment]
Still getting the same issue after deleting it.

**Comment by Madis0** [comment]
Try making a new Fabric profile (0.13.3 with MC 1.18.1) in CF Launcher and if that fails to run as well, contact their discord: https://discord.com/invite/curseforge

**Comment by Ultimation12** [comment]
Okay, yeah. That seems to be the issue. I'll go do that. Thanks for the help!

**Comment by Madis0** [comment]
I assume this is resolved.
