### ISSUE TITLE
Elytra not rendering with modded armors

### ISSUE THREAD

**Issue by Dog517** [Fabulously-Optimized/fabulously-optimized#268]
### Describe the bug

So I got the Dragon Loot mod, and the winged dragon chest piece combines a elytra and a chestplate, but the elytra is not rendering on my character. Any solutions?

### Expected behavior

The elytra rendering.

### Observed/actual behavior

The elytra not rendering.

### Steps To Reproduce

1. Launched Minecraft
2. Got the winged dragon scale chestplate
3. Elytra not rendering

### Modpack version

1.16.5 server pack

### Launcher

Curseforge Launcher

### Install method

Using with additional mods/something else (please write below)

**Comment by Madis0** [comment]
I probably won't update the 1.16.5 version anymore unless it has issues on its own, but I suggest updating the individual mods to latest [(see this tutorial and hit the down arrows on mods that have them)](https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Adding-more-mods#curseforge-launcher).

You also said that you're using Curseforge with the server pack, so I recommend to read [install instructions](https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Install-instructions#curseforge-launcher) and the [server setup wiki](https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Server-setup).
