### ISSUE TITLE
New F3 Mod

### ISSUE THREAD

**Issue by LCBOI** [Fabulously-Optimized/fabulously-optimized#271]
### Mod name

BetterF3

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/betterf3

### Other links

https://github.com/cominixo/BetterF3

### What it does

BetterF3 is a mod that replaces Minecraft's original debug HUD with a highly customizable, more human-readable HUD. You can customize colors, position, add spacings, and more

### Why should it be in the modpack

Its is much easier to read the words in the debug menu for laptop users.

### Why shouldn't it be in the modpack

The F3 menu has colours?

### Categories

New feature

**Comment by Madis0** [comment]
F3 screen is a _debug menu_, which means 80%-90% of people should not actually need it on a daily basis. If all you need is FPS or coordinates, there are options for that in Sodium Extra.
