### ISSUE TITLE
thorium

### ISSUE THREAD

**Issue by TheCoder3156** [Fabulously-Optimized/fabulously-optimized#272]
### Mod name

thorium

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/thorium

### Other links

https://modrinth.com/mod/thorium
https://github.com/PotassiumMC/thorium

### What it does

Fixes many small bugs

### Why should it be in the modpack

Will fix many small issues that shouldn't change much

### Why shouldn't it be in the modpack

May change very small vanilla things
More mods mean more chances for incompatibility
Most bugs fixed are unnoticeable

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment]
Please fix specific bugs you'd want to see fixed by this mod.

**Comment by TheCoder3156** [comment]
They should be listed under the mod itself

**Comment by Madis0** [comment]
It mentions the bugs it fixes, but I want to know which bugs do you specifically want to get fixed.

**Comment by TheCoder3156** [comment]
None myself but I thought they might be good for others

**Comment by Madis0** [comment]
Well, each mod I add to FO must be with a specific intention. Adding some minor graphical fixes that may not even be noticed by the players does not seem like a worthy addition, unfortunately.

**Comment by Madis0** [comment]
Well, each mod I add to FO must be with a specific intention. Adding some minor graphical fixes that may not even be noticed by the players does not seem like a worthy addition, unfortunately.

**Comment by TheCoder3156** [comment]
:shrug: its not really a big deal to not add it
