### ISSUE TITLE
Debugify (Mod)

### ISSUE THREAD

**Issue by TheCoder3156** [Fabulously-Optimized/fabulously-optimized#273]
### Mod name

Debugify

### Curseforge link

https://curseforge.com/minecraft/mc-mods/debugify

### Other links

https://modrinth.com/mod/debugify
https://github.com/W-OVERFLOW/Debugify

### What it does

Fixes low priority bugs on the Mojang bug tracker

### Why should it be in the modpack

Doesn't change vanilla gameplay
Fixes bugs

### Why shouldn't it be in the modpack

More mods mean more chances for incompatibility
Most bugs fixed are unnoticeable

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment]
https://discord.com/channels/859124104644788234/859124543712133130/954860198785343601

**Comment by Madis0** [comment]
Reopened as it is being discussed with the mod dev.

**Comment by Madis0** [comment]
Replaces:

- #254 
- FastOpenLinksAndFolders
- #274 
- #189 eventually?

**Comment by isXander** [comment]
### Suggested edit: 
this mod now fixes any priority of bug as it is clear that the priority listed on the mojang bug tracker
doesn't seem to dictate at what speed they are fixed by Mojang.

**Comment by isXander** [comment]
- FastOpenLinksAndFolders
- KennyTV's Force close loading screen mod
both have now been implemented in the mod (unreleased)

**Comment by Madis0** [comment]
> As requested, new bug fixes are disabled as default

Err, they don't have to be disabled for everyone though, only if I opt in to disabling them.

**Comment by isXander** [comment]
I mean they are defaulted to disable IF set by config property. Specifically:

.minecraft/config/debugify.json
```json
{
	...
    "default_disabled": true
}
```

**Comment by Madis0** [comment]
Added in 3.4.0.
