### ISSUE TITLE
McMouser

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#274]
### Mod name

McMouser

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/mcmouser

### Other links

https://github.com/MinecraftMachina/McMouser/tree/1.18.0-fabric

### What it does

- Fixes Shift + Scroll not working on macOS

- Disables Ctrl + Left Click = Right Click emulation

### Why should it be in the modpack

Better UX for macOS users

### Why shouldn't it be in the modpack

ARR I guess? Source is available but there is no license
Needs testers to claim it works and helps

### Categories

Fixes a bug/makes another mod work

**Comment by DioEgizio** [comment]
btw mcmouser works fine in my experience and it unluckly breaks between updates so it'd be fine

**Comment by Madis0** [comment]
Superseded by #273.

**Comment by ViRb3** [comment]
@Madis0 Just a heads up that while Debugify fixes the same scroll issue as McMouser, it does not disable the <kbd>Ctrl + Left Click = Right Click emulation</kbd> emulation, which you may or may not want.
