### ISSUE TITLE
MinecraftCapes

### ISSUE THREAD

**Issue by gruxor** [Fabulously-Optimized/fabulously-optimized#277]
### Mod name

MinecraftCapes

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/minecraftcapes-mod/

### What it does

Adds custom capes and ear cosmetics.

### Why should it be in the modpack

The capes mod that's currently in the pack (https://www.curseforge.com/minecraft/mc-mods/capes) hasn't been updated since December and seems abandoned by the creator.

There's an issue on the author's github regarding the animated capes not working (along with screenshots, since I'm lazy) that hasn't been replied to since November of last year: https://github.com/CaelTheColher/Capes/issues/37
(which is what prompted me to make this suggestion)

I think it'd be a better option to use the official MinecraftCapes mod since:

- it's actually actively updated
- the Fabulously Optimized section on capes already links that site 
- it'd fix the bugged animated capes 
- could potentially fix other wacky cape behavior, especially any that might arise in the future

### Why shouldn't it be in the modpack

The pack would lose support for LabyMod and OptiFine capes I believe, but that's not really a big loss (especially since the OptiFine cape is a single-variant donator cape).

I also haven't looked into the code or thoroughly tested the new suggested mod, but it's fairly popular, made by the MinecraftCapes folks, and I can't imagine the code is less optimized than the current mod we use unless the Fabric version ends up being a hacky port from Forge.

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment]
I wouldn't call it abandoned because it literally works with the latest stable version, but I am also willing to consider replacing that mod with some other one, as switching or toggling capes does not seem to be as fast as it could be. 

> but that's not really a big loss (especially since the OptiFine cape is a single-variant donator cape).

Well, I wouldn't say that people should donate to Optifine, but it undoubtedly is the biggest custom cape platform so far, so I wouldn't want to ignore it. In other words, FO should support Optifine's capes and MinecraftCapes at a minimum.

**Comment by gruxor** [comment]
> Well, I wouldn't say that people _should_ donate to Optifine, but it undoubtedly is the biggest custom cape platform so far, so I don't want to ignore it. In other words, FO should support Optifine's capes and MinecraftCapes at a minimum.

I actually didn't realize OptiFine had added a cape editor, I guess it's been a while. I remember donating for the "generic" single-variant cape a long time ago so I assumed that was still the only option.

I did find this: https://www.curseforge.com/minecraft/mc-mods/of-capes which might be an option, when combined with the original mod I linked. Might be a bad choice to have _two_ cape mods though, especially if there's conflicts. Maybe worth testing though.

MinecraftCapes seems like the far more universal platform (since it has a Forge and Fabric version) so my take is that it's worth prioritizing it over the OptiFine capes, but that's obviously debatable. Two features from the former not working with the current mod (animated capes and the deadmau5 modded ear stuff) is enough for me to want to find an alternative.

**Comment by DioEgizio** [comment]
> > Well, I wouldn't say that people _should_ donate to Optifine, but it undoubtedly is the biggest custom cape platform so far, so I don't want to ignore it. In other words, FO should support Optifine's capes and MinecraftCapes at a minimum.
> 
> I actually didn't realize OptiFine had added a cape editor, I guess it's been a while. I remember donating for the "generic" single-variant cape a long time ago so I assumed that was still the only option.
> 
> I did find this: https://www.curseforge.com/minecraft/mc-mods/of-capes which might be an option, when combined with the original mod I linked. Might be a bad choice to have _two_ cape mods though, especially if there's conflicts. Maybe worth testing though.
> 
> MinecraftCapes seems like the far more universal platform (since it has a Forge and Fabric version) so my take is that it's worth prioritizing it over the OptiFine capes, but that's obviously debatable. Two features from the former not working with the current mod (animated capes and the deadmau5 modded ear stuff) is enough for me to want to find an alternative.

https://modrinth.com/mod/kappa is probably the best option for of capes

**Comment by Zetvue** [comment]
What about Mantle and Wynntils capes?
Not like anyone cares about them, but we do need to include them if we plan to fully replace the Capes mod.

**Comment by Madis0** [comment]
Well, if nobody cares about them, then they won't care about the removal either :D
As I said, MinecraftCapes and Optifine are those I care about (plus Mojang's of course). Any others are lower priority, but can be included if the mod provides them as well.

**Comment by gruxor** [comment]
Okay, so I think there's a great solution. I did some testing and it turns out there's no conflict between the MinecraftCapes mod (https://www.curseforge.com/minecraft/mc-mods/minecraftcapes-mod/) and the above-mentioned Kappa mod (https://www.curseforge.com/minecraft/mc-mods/kappa), which appears to be the better/more future-proof implementation of the OF capes in Fabric.

If a user has both an OptiFine cape and a MinecraftCapes cape, the MinecraftCapes one takes priority and is shown. Both capes can be disabled, along with the MinecraftCapes ears. The only discrepancy is that Kappa uses the "Skin Customization" section (like OF does) for toggles and the MinecraftCapes mod uses the J key to open the cape/ears GUI. I don't see that being a problem though.

It's also neat because you can use your OF cape while also using the MinecraftCapes ears, just by disabling the MinecraftCapes cape: 
![image](https://user-images.githubusercontent.com/95389790/161181824-63c2dd0a-a878-4fa4-8082-abf450349193.png)

If those two are the only two you care about supporting (and rightfully so), I think using both of those mods is the best solution. May need further testing regarding different graphics options, but I can't imagine any other mods that'd cause conflict as I already did all this testing with FO (with the existing capes mod removed, of course).

**Comment by Zetvue** [comment]
> Okay, so... 
Wouldn't it disable other people seeing them? Or am i wrong about this?

**Comment by gruxor** [comment]
> > Okay, so...
> 
> Wouldn't it disable other people seeing them? Or am i wrong about this?

No. It'd give everyone full control over what they want to see, as well as what others see.

The in-game toggles (I believe) disable showing ALL capes/ears/whatever. However, both sites (OptiFine and MinecraftCapes) allow you to actually deactivate each feature, so you can individually choose what you want displayed. For example, if you wanted the MinecraftCapes ears alongside the OF cape, you could go into your MinecraftCapes settings and remove your cape there, which would allow the OF cape to show.

Of course, I imagine most people are only going to use one or the other, and since MinecraftCapes is superior in customization (and it's free, other than animated capes and enchanted capes) I think it's better that it takes preference over the OF capes. OF capes still work for those that have them and haven't touched MinecraftCapes at all, though, and anyone with the pack would be able to see them (as well as anyone using the individual mods in another pack, of course).
