### ISSUE TITLE
PurpurClient Mod Request

### ISSUE THREAD

**Issue by James76931** [Fabulously-Optimized/fabulously-optimized#278]
### Mod name

PurpurClient

### Other links

https://modrinth.com/mod/purpurclient
https://github.com/PurpurMC/PurpurClient

### What it does

The mod corrects client side bugs in Minecraft before Mojang releases fixes for them. It also provides subtle Quality Of Life (QOL) improvements.

### Why should it be in the modpack

The mod corrects issues with the Minecraft client thus improving game stability.

### Why shouldn't it be in the modpack

A small QOL feature displays how many bees are in a beehive in the F3 menu when players are connected to a [Purpur](https://github.com/PurpurMC/Purpur) server. This might be seen as being slightly non-vanilla. I personally see this as a non-issue given how subtle the change is (I also like the feature!).

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment]
Okay, assuming that most players don't use Purpur servers, what is the actual use for having those features?

> Customizable mob passenger offsets

Sounds like server-side and very niche (most likely unused outside Purpur servers)

> Asynchronous chat processing

And the result is... what? As far as I've seen, chat is already kind of independent from the game world in vanilla.

> Prevent client from preemptively removing item entities from the world

Sounds like "respect the 5 minute despawn time of items" which I've never heard anyone having problems with.

**Comment by James76931** [comment]
This sounds a bit odd as I’m writing this but I primarily liked the mod based on its “past features” listed on Modrinth. 😅 The idea of having client-side bugs patched before Mojang releases a new version sounds nice to me. Perhaps it would have been best to submit this issue a little after 1.18.2’s release when more issues have been found for the devs to correct… 😅 apologies - I feel a bit silly in that respect now. Nevertheless I do see value in the other features as nice additions to an improved/optimised vanilla style modpack. According to Modrinth the only Purpur-specific tweak right now is the bees in beehives counter, and even if there were one or two additional features exclusive to Purpur it’s [not like Purpur is rarely used](https://bstats.org/plugin/server-implementation/Purpur/5103) at the moment. I personally wouldn’t mind adding the mod in its state now as it doesn’t seem like a bad thing having these extra (albeit subtle) improvements in the modpack. Though, even if PurpurClient isn’t added immediately, I hope I’ve done some good in bringing it to your attention so it can perhaps be added in the future when there are additional features/optimisations available.

**Comment by Madis0** [comment]
Right. Well, I don't add mods to FO based on any future claims, the features it has now should be significant. Plus for those "fix many bugs" mods I'd want to configure each fix individually as well, to avoid unintended behavior and mod conflicts. See also: #189 #272 #273
