### ISSUE TITLE
Shut, Badlion

### ISSUE THREAD

**Issue by Zetvue** [Fabulously-Optimized/fabulously-optimized#281]
### Mod name

Shut, Badlion

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/shut-badlion

### Other links

https://modrinth.com/mod/shut-badlion
https://github.com/TropheusJ/shut-badlion

### What it does

> Ever play on Hypixel? It's got integration with Badlion client. However, this integration is done poorly, so all players not using Badlion get their logs spammed with a ridiculous amount of errors, inflating log sizes, and possibly causing lag. This mod silences these errors, removing the log spam.

### Why should it be in the modpack

Some players of FO play Hypixel. As explained above, this mod would help then play on Hypixel better. Also, it's a multiversion mod so 1.16.5+ is supported for one mod.

### Why shouldn't it be in the modpack

No downsides

### Categories

Performance optimization, New feature

**Comment by isXander** [comment]
Correction: any server with badlion integration that implements it poorly

**Comment by Julienraptor01** [comment]
Personnally i've been using it for a while now i got no problems and rid of the log spamming

**Comment by Madis0** [comment]
I still want some examples of the logs and performance impact.

**Comment by Julienraptor01** [comment]
> I still want some examples of the logs and performance impact.

I'm gonna try to get my olds logs to show you
I don't see any performance impact, bad or good.
The logs are simply more readeable.

**Comment by isXander** [comment]
It won't be much of a performance impact, just the processing of the packet channel.

**Comment by isXander** [comment]
```
[12:44:17] [Render thread/WARN] (Minecraft) Unknown custom packed identifier: badlion:mods
```

removes this from logs on lobby change

**Comment by Madis0** [comment]
Well, cleaning up logs just for the sake of it is not a very worthy goal IMO. So unless someone can convince me (benchmarks, videos, ...?) that this actually improves performance due to the reduced logs, this will not be added.

**Comment by Julienraptor01** [comment]
#494 has an example of badlion log spam on hypixel
