### ISSUE TITLE
Debugify - Enable Bug Fix

### ISSUE THREAD

**Issue by isXander** [Fabulously-Optimized/fabulously-optimized#284]
### What config to change

[MC-235035](https://bugs.mojang.com/browse/MC-235035)

### Why should it be changed

This would be great to add because it fixes quite an annoying crash that can happen to anyone using a datapack. This fix is so minimal even Forge implemented it themselves and shouldn't cause ANY problem with any other mod.

### Category

Mod config option

**Comment by Madis0** [comment]
Enabled in 3.4.1.
