### ISSUE TITLE
Debugify - Enable Fix

### ISSUE THREAD

**Issue by isXander** [Fabulously-Optimized/fabulously-optimized#285]
### What config to change

[MC-140646](https://bugs.mojang.com/browse/MC-140646)

### Why should it be changed

This is useful for anyone using any kind of text input from command blocks to even just the chat menu. This bug is extremely annoying and cumbersome to work round.

### Category

Mod config option

**Comment by Madis0** [comment]
@isXander Can you confirm that this issue does not exist with your code: https://github.com/j-tai/TieFix/issues/7

As the issue says, it got fixed in TieFix as well, but it did make me wary of enabling similar fixes in the future.

**Comment by isXander** [comment]
This fix uses tiefix as a reference implementation and this issue is not present in my code.

**Comment by Madis0** [comment]
Enabled in 3.4.1.
