### ISSUE TITLE
Debugify - Enable Fix

### ISSUE THREAD

**Issue by isXander** [Fabulously-Optimized/fabulously-optimized#286]
### What config to change

[MC-199467](https://bugs.mojang.com/browse/MC-199467)

### Why should it be changed

This bug is evident when players stay in the same chunks for more than around an hour with the same mobs. (Afk farm or simply just really busy) This bug looks really funky (as seen in the video) and affects a few mobs (specifically ones with wings).

### Category

Mod config option

### Additional details

though this is listed as server side the bug on Debugify tracker it's actually a client issue but the underlying problem affects both environments.

**Comment by Madis0** [comment]
Enabled in 3.4.1.

Edit: reverted in 3.15.0 and later due to #1123.
