### ISSUE TITLE
Reevaluate "always defer chunk updates" 

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#287]
### What config to change

Sodium setting "always defer chunk updates" should be disabled again. It could provide better FPS in some cases, but at the same time has some side effects that make it seem like server lag.

### Why should it be changed

Sxc
> I think I've has that issue before but with doors so when I open them they don't do the animation of opening them. It does the animation after some time

TacoMonkey
> I always turn it off because it makes everything delayed

Julienraptor01
> I personnally noticed that it has tendancy of delaying  animations
> And it can have some effects similar to server lag
> Which is more annoying than having less fps and/or lag spikes

### Category

Mod config option

**Comment by Julienraptor01** [comment]
The only thing i find good in this option is that it completly remove the stuttering i have with Lambdynamiclights when enabled

**Comment by Madis0** [comment]
> The only thing i find good in this option is that it completly remove the stuttering i have with Lambdynamiclights when enabled

Considering that I'd want to keep it enabled, it seems like a good thing then 😄

**Comment by Uranite** [comment]
This issue happens when you're laggy or when chunk loading is happening, set the chunk from 8 to 16 and when the chunk is loading open up some doors and the doors will be delayed

**Comment by RaptaG** [comment]
In the beginning I was against this idea but after some testing I found out that sometimes when swapping servers in-game eg. Minehut servers there's a render bug that you can't see anything. This can be stressful for the users and I think that ACDU should be disabled since it can be reopened by the user again

**Comment by Madis0** [comment]
Disabled in 3.6.0.
