### ISSUE TITLE
Remove TieFix

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#288]
### Mod name

TieFix

### What it does

Bugfixes and telemetry toggle

### Why should it be in the modpack

I want users to be able to toggle telemetry without disabling the mod itself (which MMC auto-update users couldn't do at all for example)

### Why shouldn't it be in the modpack

Bugfixes are now better done (faster updates, simpler config, more fixes) with Debugify, but Debugify currently does not want to add telemetry disabling as it is out of its scope. Need some ideas on how could this be solved...

### Categories

Replaces an existing mod

**Comment by Uranite** [comment]
https://youtu.be/Os9XNGe9ijw
According to this video the telemetry needs a launcher implementation and multimc doesnt have an implementation for telemetry
And by toggling it do you mean turning it on? I mean, why would anyone would want to enable it anyway

**Comment by Madis0** [comment]
> https://youtu.be/Os9XNGe9ijw According to this video the telemetry needs a launcher implementation and multimc doesnt have an implementation for telemetry 

Yeah, that's cool, but I support several launchers.

> And by toggling it do you mean turning it on? I mean, why would anyone would want to enable it anyway

Yes, I mean turning it on. Some users may want to help Mojang support their hardware better by enabling it.

**Comment by DioEgizio** [comment]
Honestly I don't think of a scenario where it makes sense to have telemetry enabled

**Comment by Scarlaid** [comment]
well, can [this](https://modrinth.com/mod/no-telemetry/versions) work?

**Comment by Madis0** [comment]
> well, can [this](https://modrinth.com/mod/no-telemetry/versions) work?

I want users to be able to toggle telemetry without disabling the mod itself (which MMC auto-update users couldn't do at all for example)

**Comment by DioEgizio** [comment]
> well, can [this](https://modrinth.com/mod/no-telemetry/versions) work?

Literally read

> I want users to be able to toggle telemetry without disabling the mod itself

**Comment by Scarlaid** [comment]
Forgot the "toggle"
Still, I don't think any of good reason to enable telemetry beside being a "bug reporter" or something, so why it should be togglable for normal players 🤷‍♂️

**Comment by DioEgizio** [comment]
This is also true

**Comment by Madis0** [comment]
Actually, you two do have a point. 

FO [does have its principles](https://fabulously-optimized.gitbook.io/modpack/readme/principles) and user privacy is one of them. Considering that MultiMC (and possibly other launchers) never implemented it and my vocality in the Quilt problem (#257), it does make sense to simply reintroduce No Telemetry.

Thank you for the input!

**Comment by RaptaG** [comment]
> > well, can [this](https://modrinth.com/mod/no-telemetry/versions) work?
> 
> > I want users to be able to toggle telemetry without disabling the mod itself (which MMC auto-update users couldn't do at all for example)

https://github.com/kb-1000/no-telemetry/issues/8

**Comment by Madis0** [comment]
Done in 3.5.0.
