### ISSUE TITLE
Debugify - Enable a few settings

### ISSUE THREAD

**Issue by isXander** [Fabulously-Optimized/fabulously-optimized#289]
- [MC-183776](https://bugs.mojang.com/browse/MC-183776) - After switching gamemodes using F3+F4, you need to press F3 twice to toggle the debug screen
  * Extremely annoying problem for anyone who uses debuging tools often. Minimal fix. Shouldn't cause incompatibilities
- [MC-89146](https://bugs.mojang.com/browse/MC-89146) - Pistons forget update when being reloaded
  * Should be enabled because this is the cause of many flying machine breakages (in singleplayer) and does not change gameplay

### Category

Mod config option

**Comment by Madis0** [comment]
I think I'll enable the second

**Comment by isXander** [comment]
What's wrong with the first?

**Comment by Madis0** [comment]
Just feels more like a niche use case.
