### ISSUE TITLE
Not Enough Animations

### ISSUE THREAD

**Issue by Minecon724** [Fabulously-Optimized/fabulously-optimized#291]
### Mod name

Not Enough Animations

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/not-enough-animations

### What it does

it adds some nice and smooth player animations

### Why should it be in the modpack

⬆️

### Why shouldn't it be in the modpack

idk

### Categories

Graphics optimization

**Comment by Madis0** [comment]
As cool as it may be (and maybe even Bedrock parity), it looks different from vanilla and it may give the players the wrong impression that this is actually what the others see as well. See also: #174
