### ISSUE TITLE
Perspective Mod Redux

### ISSUE THREAD

**Issue by Minecon724** [Fabulously-Optimized/fabulously-optimized#292]
### Mod name

Perspective Mod Redux

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/perspective-mod-redux

### What it does

This mod adds a 360 degree third person rotation mode.

### Why should it be in the modpack

very useful

### Why shouldn't it be in the modpack

idk

### Categories

New feature

**Comment by Madis0** [comment]
* The video literally says it is not allowed on Hypixel as it gives an unfair advantage
* It requires users to learn a new key that enables this, it's not the default on F5 (though I'm not sure it should be)
* I don't see a reason why 70% of players would actually need this if F5 already works very similarly and is in vanilla.
