### ISSUE TITLE
Better Grass resource pack

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#293]
As LambdaBetterGrass may not be supported for Fabric in the future (#257), a resource pack should be made to replace it.

Modelling the sides of the grass block would be [easy overall](https://www.curseforge.com/minecraft/texture-packs/better-grass-optifine), but getting it to adapt on the dirt edges would need some CTM (Continuity) trickery. 

The pack should also change grass-like blocks such as mycelium.

Contributions are welcome, and so is bundling your pack if you release it on Curseforge separately first.

**Comment by TheCoder3156** [comment]
LambdaBetterGrass no longer says its current release will most likely be the last fabric one anywhere. This is weird because I swear it was there. Did the developer change their mind? And if so is this still necessary?

**Comment by TheCoder3156** [comment]
Ideally yes, because it means one less mod to support but it is still strange that the announcement just disappeared.

**Comment by Madis0** [comment]
Yeah, I'm gonna keep the issue open just in case still.

**Comment by Madis0** [comment]
Lambda's Inspecio [just moved over](https://github.com/Queerbric/Inspecio/releases/tag/v1.4.0+1.18), seemingly irreversibly, making this issue more critical now.

**Comment by Madis0** [comment]
Seems like not that critical yet:

> LBG might end up with Quilt earlier than LDL due to the virtual resource pack stuff
> but for now that API doesn't exist :P

https://discord.com/channels/734886100388151378/734888845346078741/984511029885145139 [(via)](https://discord.gg/abEbzzv)

**Comment by Madis0** [comment]
LBG considering going Quilt for 1.19.3 again.

**Comment by Madis0** [comment]
Forgot to mention here, this pack has been made and bundled in FO since 4.6.0-beta.5, separately distributed since beta 6.
