### ISSUE TITLE
Custom GUI

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#300]
### Mod name

Custom GUI

### Curseforge link

None

### Other links

Modrinth: https://modrinth.com/mod/customgui

GitHub: https://github.com/omoflop/CustomGUI

### What it does

Allows users to create Custom GUI’s, like OptiFine!

### Why should it be in the modpack

Custom GUI’s are not in the modpack yet, only animated ones

### Why shouldn't it be in the modpack

No CF, different format from the OptiFine one, but [on the to-do list](https://discord.com/channels/824116179534348288/824116366134607912/893554116394098688 ) of [MCPP++](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/106), no 1.18+, but there’s a [Pull Request](https://github.com/omoflop/CustomGUI/pull/7) made for that, on their GitHub page.

### Categories

New feature, Works like Optifine

### Additional details

I’ve made an issue about CurseForge releases (https://github.com/omoflop/CustomGUI/issues/8).

**Comment by Madis0** [comment]
Rejected as #311 supports OF format directly and was added in 3.8.0.
