### ISSUE TITLE
Opt-in Cull Leaves

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#302]
### What config to change

Cull Leaves to be opt-in, aka disabled by default

### Why should it be changed

Pros:
* Performance improvement
* Some might like the aesthetic

Cons:
* Aesthetics - people may turn away from FO for this alone
* Might not be needed for performance anymore (for most people)
* Claimingly it is also opt-in in Optifine

### Category

Mod config option

### Additional details

It used to be opt-in in FO but [that changed in 2.1.0-alpha.3](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#210-alpha3-2021-07-15) because the performance was poor. Things might have changed now.

Either way I currently do not intend to remove the mod altogether.

**Comment by Lolezboi** [comment]
i think it should be off; it looks much better without and i can confirm that it's opt-in in optifine

**Comment by isXander** [comment]
Cull leaves looks awful imo. You can clearly see the culling. Maybe you could still cut the faces rendered in half by just rendering the sides facing you (only when there are adjacent leaves) which might improve the look. Could be a suggestion for the mod dev.

**Comment by isXander** [comment]
Though on the curseforge page, it shows a smart leaves resource pack that looks good?

**Comment by Madis0** [comment]
The resource pack should also be enabled in FO right now (according to options.txt), but I haven't verified the difference for a while.
Sodium also planned to introduce something similar at some point, though I don't know what the current state of it is.

**Comment by Madis0** [comment]
For reference;
## Cull Leaves + Smart Leaves
![2022-04-29_20 12 20](https://user-images.githubusercontent.com/8611110/165991728-e1c389bc-72f9-4ce7-aff4-f4ca35d866fe.png)
## Cull Leaves
![2022-04-29_20 12 42](https://user-images.githubusercontent.com/8611110/165991734-3fc35c59-6d19-4a65-bf2e-4aaa1d591ec8.png)
## Vanilla fancy leaves
![2022-04-29_20 13 03](https://user-images.githubusercontent.com/8611110/165991742-c4b4d9e7-7b9f-428c-aba7-d15dd39f18ce.png)
## Vanilla fast leaves
![2022-04-29_20 14 31](https://user-images.githubusercontent.com/8611110/165991887-80345945-423d-4f46-a9e1-c76b34c6e611.png)

**Comment by Julienraptor01** [comment]
The two cull leaves are really too transparent

**Comment by DonFlymoor** [comment]
I agree, it should be opt-in. For the longest time I thought tree leaves were just ugly by default.

**Comment by isXander** [comment]
I might be able to create an improved mod with a "thickness" setting where leaves are only culled if they are 2 deep into a tree.

**Comment by Madis0** [comment]
> I might be able to create an improved mod with a "thickness" setting where leaves are only culled if they are 2 deep into a tree.
> 
> Or maybe, instead of culling why not make the inside leaves fast leaves instead of culling.

Interesting. 
I think I'll still disable the culling by default as people seem to prefer that, but if you make the mod, you could also improve its findability, e.g. hijack into Sodium's leaf settings to add an option "Smart" (which would enable this mod and set leaves to fancy). Also add a toggle to vanilla graphics settings for people without Sodium.

**Comment by Maciejk1221** [comment]
Actually, the problem with Cull Leaves is Sodium setting called "Use Block Face Culling"
(you need to reload chunks for change to apply)

**Cull Leaves + Smart Leaves; without "Use Block Face Culling" enabled:**
![2022-04-30_09 25 07](https://user-images.githubusercontent.com/96501603/166096272-32ba2813-68f8-4d4b-846b-294581395851.png)

**Cull Leaves + Smart Leaves; with "Use Block Face Culling" enabled:**
![2022-04-30_09 25 25](https://user-images.githubusercontent.com/96501603/166096276-c4a47dc0-2643-4945-854b-120e5825c59a.png)

**Comment by Madis0** [comment]
I thought I enabled that, but guess not... well, what do the contributors here think of that option?

**Comment by isXander** [comment]
Block face culling seems like a performance thing.

**Comment by Madis0** [comment]
From another angle:
![2022-04-30_10 48 07](https://user-images.githubusercontent.com/8611110/166096919-8a3ba06d-aaff-44eb-9d76-7d9c0d2cfbe2.png)

**Comment by Julienraptor01** [comment]
What it cull leaves had some code that could bypass sodium block face culling.
So block face culling could still be on in sodium but cull leaves would have a setting under it like "disable for leaves".

**Comment by Julienraptor01** [comment]
https://discord.com/channels/859124104644788234/969981731883085925/969991782798622740
Cull leaves seems to create problems

**Comment by Madis0** [comment]
So, I've decided that Xander's CullLessLeaves defaults are a better alternative:
Basically just shows two layers of leaves before culling them out.
If you have any objections (e.g. still preferring to disable them entirely), tell them now.

![](https://camo.githubusercontent.com/bde55b058ef2563464a793cf9c8a36b4640d78a171c488277bc713237bfaf1b9/68747470733a2f2f692e696d6775722e636f6d2f476a59466a4a562e706e67)

**Comment by Madis0** [comment]
Did not make it opt in, instead replaced Cull Leaves with Cull Less Leaves.
