### ISSUE TITLE
Replace CEM with JsonEM

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#303]
### Mod name

JsonEM

### Curseforge link

None

### Other links

Modrinth: https://modrinth.com/mod/jsonem

GitHub: https://github.com/FoundationGames/JsonEM

### What it does

Supports Custom Entity Models

### Why should it be in the modpack

Because it provides support for all the mobs

### Why shouldn't it be in the modpack

No CF, different format from OptiFine’s ([asked for MCPP++ support](https://github.com/supsm/MCPPPP/issues/1#issuecomment-1112439136))

### Categories

Graphics optimization, Works like Optifine/Bedrock Edition/Forge/etc, Replaces an existing mod

### Additional details

I made an issue for the CurseForge upload (https://github.com/FoundationGames/JsonEM/issues/3) ~_(once again)_~

**Comment by supsm** [comment]
Madis how tf are you so fast

**Comment by supsm** [comment]
On a more serious note, I think it may be a good time to consider whether to use optifine format mods or other format mods.
Using the other formats would benefit modders and resourcepack creators, as this platform would let much more people be aware of these formats. Using the optifine format would benefit users, as most conversions aren't 100% complete and they may experience some issues when using the other formats.
It's something to further consider, and honestly I'm not sure which is better as a whole.

**Comment by Madis0** [comment]
> Madis how tf are you so fast

![image](https://user-images.githubusercontent.com/8611110/165811008-4d8ac950-182b-4998-bfb2-f5d8b4176982.png)
😁

**Comment by Madis0** [comment]
> On a more serious note, I think it may be a good time to consider whether to use optifine format mods or other format mods.

Currently, using Optifine format would still be better because people are not aware of the alternatives, nor would they want to install a single mod for a single resource pack feature. Case in point: #210 has still very low adoption (though then again it could be because vanilla resource packs can work similarly).

**Comment by supsm** [comment]
Hmm? That isn't really what I was referring to, I was thinking more like #72, #77, etc

**Comment by Madis0** [comment]
Your question was why won't FO use mods that provide new non-OF capabilities? The answer is that I still don't think FO has enough power to make them spread, and there is no incentive for me or the content creators either when there are currently barely any resource packs that use those mods.

**Comment by supsm** [comment]
I was talking about resource pack formats, e.g. fsb format vs mcpatcher format

**Comment by Madis0** [comment]
You're asking about whether your converter should convert from Optifine format or to Optifine format? 
In that case, still Optifine format is still more "standardized" and it will likely have implementing mods for various loaders, by various devs. 
Converting from Optifine format, on the other hand, may be more unsustainable as that resulting format could become abandonware at some point.

**Comment by RaptaG** [comment]
Also a note: It's unknown if it works alongside with ETF

**Comment by TruMiner** [comment]
minecraft wont crash if using both, it will just load the CEM mod models instead. you can disable cem mod anyway in the modmenu configuration if you want to use jsonem

**Comment by Julienraptor01** [comment]
> Also a note: It's unknown if it works alongside with ETF

JsonEM is compatible with ETF
JsonEM can run alongside CEM with no problems
CEM will take priority on JsonEM tho

**Comment by RaptaG** [comment]
I think I should close this, because of #584

**Comment by RaptaG** [comment]
And #498 should be closed for the same reason I think
