### ISSUE TITLE
Remove Smooth Boot

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#305]
### Mod name

Smooth Boot

### What it does

Optimizes startup and resource usage

### Why should it be in the modpack

Smooth Boot claims that they are compatible with each other
https://github.com/UltimateBoomer/mc-smoothboot/wiki#lazydfu

### Why shouldn't it be in the modpack

People claim it is useless when LazyDFU exists. Need more data to prove that.

Currently [LazyDFU claims to be superior](https://github.com/astei/lazydfu#smooth-boot), but [Smooth Boot says it can still can optimize the resource usage (threads)](https://github.com/UltimateBoomer/mc-smoothboot/wiki/Configuration~-Fabric-1.16+).

### Categories

New feature

### Additional details

https://github.com/UltimateBoomer/mc-smoothboot/issues/38

**Comment by Madis0** [comment]
So, according to the dev in the issue above it should still reduce some game stutters. I still want testers who can compare normal FO and without Smooth Boot on their machine.

**Comment by Uranite** [comment]
In my testing upon world join there is less stutter with smooth boot and it's also less stuttery when flying around loading new chunks with smooth boot
But I think smooth boot might cause this issue where new chunks load really slowly and I could consistently replicate this, it might be because there is less thread for whatever the chunk generation is on https://github.com/UltimateBoomer/mc-smoothboot/wiki/Configuration~-Fabric-1.16+

**Comment by Madis0** [comment]
Well, less stutter is more important than slighly slower chunks (as Starlight makes them faster either way). Closing the issue.

**Comment by Madis0** [comment]
@Julienraptor01 do you have speed/perf tests? E g. boot time vs CPU usage with and without the mod.

**Comment by Kichura** [comment]
From a personal point of view; Using smooth boot itself is already catastrophic from the get-go due to how complicated the configuration is and that it has a possibility of breaking on other devices since the config cannot be synced perfectly without compromises.

**Comment by Madis0** [comment]
Considering how I don't bundle a config for it at all and if I did, I could provide only the necessary subset of the json, I'd say that is a weak argument.

On the other hand, if you can benchmark the game with and without the mod as I suggested, that would bring a better point whether to keep it or not.

**Comment by Julienraptor01** [comment]
> Considering how I don't bundle a config for it at all and if I did, I could provide only the necessary subset of the json, I'd say that is a weak argument.
> 
> On the other hand, if you can benchmark the game with and without the mod as I suggested, that would bring a better point whether to keep it or not.

related to the config, the mod doesn't do what the wiki tell it does
https://github.com/UltimateBoomer/mc-smoothboot/issues/37

**Comment by Madis0** [comment]
Planned to be removed now for the following reasons:
* Positive effects are likely mostly nullified by LazyDFU already, aka LazyDFU provides better results with less drawbacks
* The mod may actually harm performance at the expense of "keeping it more stable" (actual claim made in the wiki), though the latter is also not verified by majority that it actually helps
* The mod seems to require per-device configuration to help with stability, defaults don't seem to be enough. Per-device configuration is infeasible to do in the modpack
* Claims from other people that the mod harms performance/is redundant

**Comment by Julienraptor01** [comment]
> Planned to be removed now for the following reasons:
> * Positive effects are likely mostly nullified by LazyDFU already, aka LazyDFU provides better results with less drawbacks
> * The mod may actually harm performance at the expense of "keeping it more stable" (actual claim made in the wiki), though the latter is also not verified by majority that it actually helps
> * The mod seems to require per-device configuration to help with stability, defaults don't seem to be enough. Per-device configuration is infeasible to do in the modpack
> * Claims from other people that the mod harms performance/is redundant

I think we should have an article in the wiki that present mods that could help specific players but need manual config

**Comment by Madis0** [comment]
> I think we should have an article in the wiki that present mods that could help specific players but need manual config

https://github.com/Fabulously-Optimized/wiki/issues/26
Feel free to contribute.

**Comment by Madis0** [comment]
Done in 4.6.0-beta.1. 
As it is in a beta, I can still be persuaded to revert this, in case someone can prove their perf is actually worse compared to alpha 13. But otherwise, good riddance 😄

**Comment by Madis0** [comment]
Found someone who said they actually benefit from this: https://discord.com/channels/859124104644788234/1087042168599871578

But I'm still wary of adding it back because the config is still not device-specific... 🤔
