### ISSUE TITLE
Mini Dynamic Lights

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#309]
### Mod name

Mini Dynamic Lights

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/mini-dynamic-lights

### Other links

https://github.com/ye-yu/fabric-dynamic-lights/
https://modrinth.com/mod/mdl
https://www.planetminecraft.com/mod/mini-dynamic-lights/ 

Video overview by the dev: https://drive.google.com/file/d/1P_zG-geYsz9CL01rulZVpCgKlcB69fX3/view

### What it does

Dynamic lights like Optifine

### Why should it be in the modpack

People have claimed that LambDynamicLights performance is poor, maybe this is better; LambDynamicLights may get discontinued in Fabric soon

### Why shouldn't it be in the modpack

Not yet 1.19, untested

### Categories

Works like Optifine/Bedrock Edition/Forge/etc, Replaces an existing mod

### Additional details

Should fix some reported bugs first

**Comment by Uranite** [comment]
![2022-05-01_20 55 53](https://user-images.githubusercontent.com/62639703/166149122-96be3df7-320c-4c30-9c7d-06d95c332a29.png)
Im having pretty bad stutter with it

**Comment by TacoMonkey11** [comment]
LDL (Entites: ON, FANCY)

<img width="2560" alt="Screen Shot 2022-05-01 at 11 21 57 AM" src="https://user-images.githubusercontent.com/75862693/166152628-9b72f52a-0288-49b6-b215-3d45b7bd1111.png">

MDL

<img width="2560" alt="Screen Shot 2022-05-01 at 11 25 08 AM" src="https://user-images.githubusercontent.com/75862693/166152769-e771106f-5c2e-4c78-8288-382707eb9545.png">

Currently LDL seems to be more performant, and also offers more features

**Comment by Madis0** [comment]
Removed 1.19 milestone because LambDynamicLights is out for that version and it supports Fabric, so this can continue testing before including (if at all).

**Comment by Madis0** [comment]
Hasn't been updated for over a year, so even if something happened to LDL, an Iris-shader would be a more sustainable alternative.
