### ISSUE TITLE
CullLessLeaves

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#310]
### Mod name

CullLessLeaves

### Other links

https://github.com/isXander/CullLessLeaves

### What it does

Improved alternative to Cull Leaves

### Why should it be in the modpack

Because the modpack already has Cull Leaves (OF parity) but this one looks better, might get better integration in graphics settings too

### Why shouldn't it be in the modpack

Not in CF, currently WIP

### Categories

Works like Optifine/Bedrock Edition/Forge/etc, Replaces an existing mod

### Additional details

#302 https://discord.com/channels/859124104644788234/969335721129287720/969909811686805544

**Comment by isXander** [comment]
no longer WIP

**Comment by Madis0** [comment]
Added on 3.7.0.
