### ISSUE TITLE
OptiGUI

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#311]
### Mod name

OptiGUI

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/optigui

### Other links

https://github.com/opekope2/OptiGUI

### What it does

Optifine custom GUI support

### Why should it be in the modpack

Optifine parity, better than #300 as it works directly

### Why shouldn't it be in the modpack

Untested

### Categories

Works like Optifine/Bedrock Edition/Forge/etc

**Comment by Uranite** [comment]
Things seems to be working fine
I tested ender chest, small chest, large chest, and barrel
furnace, blast furnace, and smoker
dropper and dispenser
some villagers
Shulkers
https://www.planetminecraft.com/texture-pack/colourful-containers-dark-mode-gui-optifine-required/

**Comment by RaptaG** [comment]
> Things seems to be working fine I tested ender chest, small chest, large chest, and barrel furnace, blast furnace, and smoker dropper and dispenser some villagers Shulkers https://www.planetminecraft.com/texture-pack/colourful-containers-dark-mode-gui-optifine-required/

You were faster than me 😝

**Comment by Uranite** [comment]
> > Things seems to be working fine I tested ender chest, small chest, large chest, and barrel furnace, blast furnace, and smoker dropper and dispenser some villagers Shulkers https://www.planetminecraft.com/texture-pack/colourful-containers-dark-mode-gui-optifine-required/
> 
> You were faster than me 😝

speeeeed

**Comment by RaptaG** [comment]
I did some testing (with the same pack as @Uranite) and it seems to work perfectly!
More specifically (the GUI's that "only work with OptiFine", according to [the description of the pack](
https://www.planetminecraft.com/texture-pack/colourful-containers-dark-mode-gui-optifine-required/)):

Villager GUI:
![2022-05-02_21 22 05](https://user-images.githubusercontent.com/77157639/166303892-a5b690a3-967a-4ef1-886d-fcb228d7d3f3.png)

Dropper:
![2022-05-02_21 22 15](https://user-images.githubusercontent.com/77157639/166304146-f4d8c83c-19c2-4a07-ad08-ecfd9062b606.png)

Ender Chest:

![2022-05-02_21 22 19](https://user-images.githubusercontent.com/77157639/166304155-2866fe4b-b3cb-4332-a8ab-55b6934ac066.png)

Chest:
![2022-05-02_21 22 41](https://user-images.githubusercontent.com/77157639/166304163-b3920fc2-e4ca-4251-81e7-6e511cc32499.png)

Large Chest:
![2022-05-02_21 22 46](https://user-images.githubusercontent.com/77157639/166304233-8da0f3ea-53e0-44c9-a5d6-e19926595d46.png)

I'd say that it should be added right here and right now! :)

**Comment by Uranite** [comment]
Also loading screen is broken with that texture pack
![Base Profile Screenshot 2022 05 03 - 12 35 45 40](https://user-images.githubusercontent.com/62639703/166409178-d387b286-5661-4533-945a-fc4db70c8f66.png)

**Comment by opekope2** [comment]
That's the resource pack I wanted to use when I switched to fabric+sodium. I didn't find the mod I needed so I coded my own.
Yes, I know Custom GUI exists, but its format lacks some Optifine features.

**Comment by RaptaG** [comment]
> Also loading screen is broken with that texture pack

This is a bug of the [Puzzle](https://github.com/PuzzleMC/Puzzle) mod

**Comment by Madis0** [comment]
@Uranite Thanks, reported to https://github.com/PuzzleMC/Puzzle/issues/29
cc @RaptaG

**Comment by Madis0** [comment]
Added in 3.8.0
