### ISSUE TITLE
Beenfo

### ISSUE THREAD

**Issue by Lolezboi** [Fabulously-Optimized/fabulously-optimized#317]
### Mod name

Beenfo

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/beenfo

### Other links

https://github.com/gbl/Beenfo is their github

### What it does

gives you a tooltip for hives/nests so you can see how many bees and how much honey is inside

### Why should it be in the modpack

the mod's quite straight-forward; when beekeeping this helpful tooltip lets you see the amout of bees you have

### Why shouldn't it be in the modpack

not too vanilla-like

### Categories

New feature

**Comment by RaptaG** [comment]
Although this looks useful, it's small mod that does a small job, meaning it wouldn't be a big deal if it gets added anyway..

**Comment by bensuperpc** [comment]
I tested with FO 3.8.1 on multi-player, it works fine for me.
Only flaw: If you want all the functionality of the mod (The number of bees in the hive ...), the mod must also be installed on the server side.

**Comment by Julienraptor01** [comment]
> I tested with FO 3.8.1 on multi-player, it works fine for me.
> Only flaw: If you want all the functionality of the mod (The number of bees in the hive ...), the mod must also be installed on the server side.

From their GH
So you can install the mod:

on the client only: You will get the tooltip, but won't be able to look into placed hives/nests

**Comment by Madis0** [comment]
Seemed like a good idea at first, but despite fixing an actual vanilla issue, including this would be way too niche.
