### ISSUE TITLE
Incompatible mod set!

### ISSUE THREAD

**Issue by KamiOh** [Fabulously-Optimized/fabulously-optimized#320]
### Describe the bug

download and install from this link
https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3777645
Changelog say:
*Updated Fabric Loader to 0.14.4
But it seems they forgot to update it. LOL

### Modpack version

3.7.0 for 1.18.2 (MultiMC)

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I removed or added some mods (mention, which ones)

### Additional context

![imagen](https://user-images.githubusercontent.com/13822730/167023455-304f021c-cb6f-40c3-99c5-bc7b48dcc45e.png)
![imagen](https://user-images.githubusercontent.com/13822730/167024151-e9f0ac1d-c9b1-431f-a7a6-cdbccd594bc8.png)
![imagen](https://user-images.githubusercontent.com/13822730/167024723-ef9bf3f9-fa30-4940-91fb-d5920e0fba6b.png)

**Comment by Madis0** [comment]
Hmm, I don't get it. I downloaded that zip now and it does include the correct version in the manifest:

```
   {
            "cachedName": "Fabric Loader",
            "cachedRequires": [
                {
                    "uid": "net.fabricmc.intermediary"
                }
            ],
            "cachedVersion": "0.14.4",
            "uid": "net.fabricmc.fabric-loader",
            "version": "0.14.4"
        }
```

**Comment by Madis0** [comment]
Are you actually running the pack in MultiMC? Is your MultiMC up to date? Maybe it's some caching issue on MultiMC end. 
Also make sure you follow the instructions just in case:
https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions

**Comment by KamiOh** [comment]
> Are you actually running the pack in MultiMC? Is your MultiMC up to date? Maybe it's some caching issue on MultiMC end. Also make sure you follow the instructions just in case: https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions

I use Tlauncher.
Previously had no problems with Fabulously Optimized for MultiMC
It seems that Tlauncher is still using fabric-loader-0.13.3 by default.
I manually installed fabric-loader-0.14.4 so it fixed the problem.
I apologize for opening issue.
![imagen](https://user-images.githubusercontent.com/13822730/167027866-2d9f9c84-be17-4905-9119-671fc0dc3087.png)

**Comment by Seurentis** [comment]
> I use Tlauncher.
Fabulously Optimized does not support piracy

**Comment by medicinalcocaine3434** [comment]
If you're going to pirate minecraft can you at least used patched mmc/polymc instead of sketchy proprietary software
