### ISSUE TITLE
Enable MC-26757 fix/remove ToolTipFix

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#322]
### What config to change

MC-26757 in Debugify

### Why should it be changed

One less mod, Bedrock-like behavior

However it behaves a bit differently than the existing mod and may not work well with really long items/lores (which actually shouldn't exist anyway because most users use vanilla lol)

### Category

Mod config option

**Comment by RaptaG** [comment]
I'd really like the modpack to have everything united in Debugify. It is said that it the way of fixing is Bedrock Edition parity, meaning in a different way than ToolTipFix. I have noticed [this](https://github.com/W-OVERFLOW/Debugify/issues/86) in the bug tracker of Debugify, which should be considered.<br />(It could also be a bug that can't be reproduced though)

**Comment by Julienraptor01** [comment]
We shouldn't replace tooltipfix by the debugify fix because of how it behaves.
This is tooltipfix
https://cdn.discordapp.com/attachments/859124104644788237/971725199261200404/unknown.png

While this is debugify
https://cdn.discordapp.com/attachments/859124104644788237/971725260393156648/unknown.png

**Comment by RaptaG** [comment]
> (Reposted from discord) We shouldn't replace tooltipfix by the debugify fix because of how it behaves.

I made a comment about that [here](https://github.com/W-OVERFLOW/Debugify/issues/86#issuecomment-1121058434) (the issue I mentioned above).

**Comment by Madis0** [comment]
![image](https://user-images.githubusercontent.com/8611110/169700569-6ee4510f-31d7-443a-9d2e-0fc1874b800e.png)
Julien tested this on Bedrock, so Xander was right - this is how Bedrock behaves, therefore Debugify's fix is not enough to replace this mod.

**Comment by RaptaG** [comment]
https://github.com/FabricMC/fabric/issues/2283

**Comment by Madis0** [comment]
> [FabricMC/fabric#2283](https://github.com/FabricMC/fabric/issues/2283)

I highly doubt Fabric would want to do this, but sure, we can see.

**Comment by RaptaG** [comment]
I said it in the Discord server too but I think I had to report it also here. It is said by isXander (the developer of Debugify) that [the fix will improve in the future](https://gist.github.com/fxmorin/9770473614e3e5e0703e44273dab33f7?permalink_comment_id=4184356#gistcomment-4184356). So I think that this issue should be reopened and get the _on hold_ label

**Comment by Madis0** [comment]
New screenshots: https://github.com/isXander/Debugify/issues/106#issuecomment-1157889230

I think I'll still keep TooltipFix for now, but I'm open for feedback.

**Comment by Madis0** [comment]
I prefer the mod for now.

**Comment by Madis0** [comment]
Yes, if it actually wraps instead of cutting off, I will consider.

**Comment by isXander** [comment]
Should be reopened with isXander/Debugify#82341b0fcba8afb2776de1e3735aa60ed4f91176

**Comment by isXander** [comment]
The new commit does not remove the bedrock parity but extends upon it, **only wrapping text when even centering it is too long**, making this fix even better than tooltipfix.

**Like tooltipfix,** there are some scenarios where the wrapping does not take place, Debugify modifies all render tooltip methods apart from one. This is a technical limitation to do with Minecraft having different variants of `Text`. One of which can't be handled. This method is only called in modded scenarios, namely Mod Menu.

## Debugify

![image](https://user-images.githubusercontent.com/43245524/192113184-cdabf844-e99c-4246-be4a-a2286f5e81ab.png)

Additionally, the centering is also smart, and stays on screen at all times...

![image](https://user-images.githubusercontent.com/43245524/192113193-bdde6942-2bba-4b5e-9942-0f1e76171369.png)

## Tooltip Fix

![image](https://user-images.githubusercontent.com/43245524/192113378-370e9bca-d99b-4ea6-9693-9d2abebd720a.png)

And tooltip fix never seems to want to move tooltips to the left, where less wrapping can take place...

![image](https://user-images.githubusercontent.com/43245524/192113398-0c7109dd-1e2b-4ef6-90a5-f517af9d37f7.png)

Additionally, I find tooltip fix to be a bit jarring as you can see the text wrapping changing even as you move the mouse just a little bit...

https://user-images.githubusercontent.com/43245524/192113463-ffe6cd05-15c0-4b28-83b8-1b755c3927f5.mp4

**Comment by Julienraptor01** [comment]
Could you add a vid of Debugify's fix just like the tooltipfix vid pls ?

**Comment by isXander** [comment]
> @isXander Could you add a vid of Debugify's fix just like the tooltipfix vid pls ?

Debugify wraps based on screen width, not remaining width, so it doesn't move.

https://user-images.githubusercontent.com/43245524/192115222-6577e16e-7125-4f51-8d7f-c7312c886660.mp4

**Comment by isXander** [comment]
Now officially released isXander/Debugify@2.7.1

**Comment by isXander** [comment]
What is the status of this? Maybe ask Opinionators?

**Comment by Madis0** [comment]
The status is _be patient, lmao_

But more seriously, I like this new implementation

- doesn't shift around, which is jarring/unnatural
- it's wide, which reminds the mod/datapack/whatever creator that this is in fact a "patched" display method, not the one you should be aiming for (while TooltipFix aims to make it look "nice", and that misses the )
- not too wide to be uncomfortable
- matches Bedrock I guess

**Comment by Madis0** [comment]
Done on 4.4.0.
