### ISSUE TITLE
User changed configs reset when upgrading

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#324]
### Describe the bug

Usually, since YOSBR is in the modpack, the configs won't reset/change, but despite that my configs **did** reset. I haven't disabled the mod nor delete its kept configs.

### Modpack version

3.7.0 to 3.8.0

### Launcher

MultiMC (auto-update)

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [X] I removed or added some mods (mention, which ones)

### Additional context

This is my [crashlog](https://0x0.st/omQU.log) too, the mods added by me can be seen inside of it, but I doubt that they might be causing issues.

**Comment by RaptaG** [comment]
>Your crashlog is unavailable

Fixed

> Could it be your script that interferes with this somehow?

No, my scripts change nothing including configs.

**Comment by Madis0** [comment]
Is it still applicable in 3.8.1?

**Comment by RaptaG** [comment]
Sadly, I can't reproduce due to the new packwiz installation with the new CF API. If it happens again, I'll reopen this issue.
