### ISSUE TITLE
ClickThrough

### ISSUE THREAD

**Issue by Lolezboi** [Fabulously-Optimized/fabulously-optimized#327]
### Mod name

ClickThrough

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/clickthrough

### Other links

Github: https://github.com/gbl/ClickThrough
Modrinth: https://modrinth.com/mod/clickthrough

### What it does

lets you click through signs and item frames into containers

### Why should it be in the modpack

a lot of people have signs or item frames on their chests for sorting and it's always a huge pain having to click on the edge of the chests so that you don't rotate the item in an item frame/right click on a sign

### Why shouldn't it be in the modpack

may cause problems with shop plugins (it does have this: "If your server has a chest shop economy, clicking those signs will not open the container, but execute a trade instead. By default, a sign counts as a chest shop sign if there's one of [buy][shop][sell] in the first row, or a price tag (B 3, 7 S, B3:7S) in the third row." but maybe some shop plugins are different)

### Categories

New feature

### Additional details

i've been using this for ages and never had any problems

**Comment by Madis0** [comment]
This will cause issues with servers that have "non-standard" interactions with signs, so it has to be rejected.

**Comment by Lolezboi** [comment]
i just tried it and it works perfectly you being told it wouldn't work was just assumptions
