### ISSUE TITLE
Custom entity model not working right, and it should have a random mob texture feature like optifine

### ISSUE THREAD

**Issue by juliocoliveira** [Fabulously-Optimized/fabulously-optimized#328]
### Describe the bug

Custom entity model not working right, how it looks:
![image](https://user-images.githubusercontent.com/6606725/168187598-4b409cb9-2e6e-4e8a-822b-b29d90a3a141.png)
How it should look:
![2022-05-12_21 22 25](https://user-images.githubusercontent.com/6606725/168187873-cfdeae21-e347-40eb-a0c7-0819316df898.png)
 
It this mod pack should have random mob textures like Optifine have.

I'm using a texture pack called Misa_1.18f

### Modpack version

3.8.0

### Launcher

MultiMC

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [X] I removed or added some mods (mention, which ones)

### Additional context

Added more mods: Xaeros Mini-map, Xaero's World Map, Minihud, Tweakero

**Comment by Madis0** [comment]
CEM is unfortunately still in alpha, so not everything works properly. [Try a workaround](https://fabulously-optimized.gitbook.io/modpack/readme/resource-pack-issues#custom-entity-models) or [see the list of known issues](https://github.com/dorianpb/cem/issues).
