### ISSUE TITLE
Disable chatPreview

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#329]
### What config to change

1.19 vanilla option: `chatPreview`

### Why should it be changed

User privacy (the server won't get your message before you hit enter) and improved UX (no warnings or toasts)

I don't think the preview is going to be widely used or widely useful, therefore it is probably better to disable it by default.

### Category

Vanilla option

### Additional details

https://minecraft.fandom.com/wiki/Java_Edition_22w19a#General

**Comment by Julienraptor01** [comment]
I agree with your opinion.
