### ISSUE TITLE
Problems with custom worldgen mods and a datapack

### ISSUE THREAD

**Issue by Genious28** [Fabulously-Optimized/fabulously-optimized#331]
### Describe the bug

Unable to load, create or re-create worlds.

### Modpack version

3.8.1

### Launcher

MultiMC/PolyMC

**Comment by Madis0** [comment]
Launcher/crash logs? Errors? Screenshots? Screencaps?

PolyMC is currently unsupported by FO, so test with only MultiMC.

**Comment by Genious28** [comment]
[crash-2022-05-14_16.55.29-client.txt](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8698572/crash-2022-05-14_16.55.29-client.txt)
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8698573/latest.log)

**Comment by Genious28** [comment]
I don't have a screenshot, but when loading existing worlds; it said something like a datapack being unstable/unsupported and that i need to enter safe mode. But clicking safe mode button did nothing.

When re-creating it said it is unable to do so because of an unexpected error.

And when creating a new world, after the loading animation and 'Loading World' message, it immediately changes to 'Saving World' and gets stuck.

**Comment by Genious28** [comment]
However, i redownloaded and reinstalled v3.8.1 and now it seems to be working on PolyMC.. :/

**Comment by Madis0** [comment]
You are using custom mods, I cannot test all possible combinations so it is critical to mention those and test without those every time you report a bug. That's also what the initial bug report form says, I don't know why you just deleted that part...

Anyway, I'm glad you got it fixed.

**Comment by Genious28** [comment]
Yes, i added more mods but i tried Binary Search and ended up with just the original mods from the modpack. And when the issue still persisted with just the original mods, i reinstalled it and it was still having issues. :/

**Comment by Genious28** [comment]
When Loading Old Worlds;
![image](https://user-images.githubusercontent.com/97228026/168556955-8362d84c-7198-4aea-95ca-8d9c5705c435.png)

When Recreating World;
![image](https://user-images.githubusercontent.com/97228026/168556978-dba88f08-7a62-4690-9a9b-b67f6b926da3.png)

When Creating New World; (Gets Stuck Here)
![image](https://user-images.githubusercontent.com/97228026/168557235-69a57afd-ee36-4b31-a9d1-aa5b9643ca20.png)

**Comment by Genious28** [comment]
Also, these are the mods i added ontop;
![image](https://user-images.githubusercontent.com/97228026/168557418-a62f8e10-c0ac-4b88-a0ee-d07969ab6c8d.png)

**Comment by Madis0** [comment]
But FO doesn't contain datapacks? Ask the creator of that data pack.

**Comment by Genious28** [comment]
Well, some mods try to catch mixin errors.. And end up in Datapack error handlers. and some datafixers seem to be broken as well as seen in `java.lang.IllegalArgumentException: Data fixer not registered for: minecraft:DUMMY in block_entity`. As far as i can tell, it's something related to lithium or Noise Generator `at net.minecraft.world.gen.chunk.NoiseChunkGenerator.handler$ddf000$hookConstructor(NoiseChunkGenerator:599) ~[?:?]`

**Comment by Genious28** [comment]
I just tested on MultiMC.. It's also facing the same problems with the list of most i added.

**Comment by Madis0** [comment]
Remove all custom mods and add them back one by one until you find the one that breaks it.

**Comment by Genious28** [comment]
Yea, that's what i'm gonna do.. But it breaks the instance, even if i remove all custom mods, the issue remains so.. This might take a while.

**Comment by Genious28** [comment]
I tested v3.8.0, it fails to load or recreate old worlds as well.

**Comment by Madis0** [comment]
Are those old worlds still using datapacks (especially if it's the same one you're using now)? Because the error screenshots regarding the datapacks you posted are from vanilla.

**Comment by Genious28** [comment]
Okay, thank god i had backup for my redstone world.. Yea, i realised they had been loaded inti by Amplified Nether and Nullscape. These are the only 2 World Generation mods I've used. Though, except for a ModTest World, no other dimension was ever loaded in either my Survival World or the Redstone World.

I guess, these two had broken the worlds.. Even if you don't load the Dimensions they overhaul, they still break the World if you remove them later on.

**Comment by Genious28** [comment]
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/8700016/latest.log)
Okay, Now it's not loading old worlds anymore (with custom mods), the backups that had never been loaded by mods.. Whereas Vanilla v1.18.2 loads the same backup without any issue. And it's not even identifying versions older than 1.14 even without custom mods.

**Comment by Madis0** [comment]
If you are still unable to solve your issue, try the Fabric Discord https://discord.gg/v6v4pMv channel #player-support

**Comment by Genious28** [comment]
Yea, but FO should identify pre-1.14 worlds?

**Comment by Genious28** [comment]
Also, i am noticing some weird horizontal distortions in FO, but none in Vanilla 1.18.2.

**Comment by Madis0** [comment]
> Also, i am noticing some weird horizontal distortions in FO, but none in Vanilla 1.18.2.

If you can reproduce it without any custom mods, feel free to open a new issue.

**Comment by Genious28** [comment]
I recorded a video but, it's not visible in the video.. Just on my Display, (4K@60Hz)

And yes, without custom mods..

**Comment by Madis0** [comment]
If it's not visible in the video, it may be a driver issue which is not something I can help with. Otherwise try adjusting full screen or windowed full screen (enable the mod in Mod Menu).
