### ISSUE TITLE
Horizontal Distortion (during any kind of visual movement)

### ISSUE THREAD

**Issue by Genious28** [Fabulously-Optimized/fabulously-optimized#332]
### Describe the bug

Weird Horizontal Distortions during any kind of movement, i.e; either when i move or a mob/block is moved.

### Modpack version

v3.8.1

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I removed or added some mods (mention, which ones)

### Additional context

Cannot record video as proof because it isn't visible in recording output file. Just on my Display, here's my system info just in case;

CPU: Core i5-9600k
GPU GTX 1650 4Gb
Display: 4K@60Hz

**Comment by Genious28** [comment]
Turning off Borderless Mining Mod fixed it.

**Comment by Madis0** [comment]
That is weird though, because the mod is disabled by default on FO.

**Comment by Genious28** [comment]
Yea, i usually enable borderless windowed mode to identify game windows using OBS.

**Comment by Madis0** [comment]
Okay. Check their issue tracker out, maybe they have an issue relevant to you: https://github.com/comp500/BorderlessMining/issues
