### ISSUE TITLE
Extended Clouds

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#333]
### Mod name

Extended Clouds

### Curseforge link

https://www.curseforge.com/minecraft/mc-mods/extended-clouds

### Other links

https://modrinth.com/mod/extended-clouds

### What it does

Makes the cloud distance match your rendering distance instead of hardcored 4 chunks

### Why should it be in the modpack

Very vanilla-like, an alternative to custom skies for those who like vanilla aesthetics #72, should not cause conflicts, Bedrock parity maybe? (haven't checked)

### Why shouldn't it be in the modpack

Performance needs testers on low-end computers
Could be considered opinionated, though at the same time it feels like something Mojang would do
No toggle/slider/options to customize it

Edit: I think there is a slider now, but there is also a report about it not working with Iris and crashing with Sodium Extra, hence marking as wip 

### Categories

Graphics optimization, New feature

### Additional details

CF API enabled

**Comment by RaptaG** [comment]
> An alternative to custom skies for those who like vanilla aesthetics

Yes, but still, it doesn't support custom skies.

([GitHub](https://github.com/alphaqu/extended-clouds) link btw.)

**Comment by Madis0** [comment]
As custom skies/clouds are now supported, I don't think there is a demand for this, especially due to lack of options and compatibility right now.
