### ISSUE TITLE
Remove Item Model Fix

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#339]
When https://github.com/W-OVERFLOW/Debugify/issues/82 is patched in Debugify. ~~It also fixes #192, sicne the only mod using the Cloth API is Item Model Fix.~~

**Comment by Julienraptor01** [comment]
Well Debugify#82 won't be fixed as they stated.
||I personally never encountered #192 so in which conditions does it appear ?||
I think the item model bug is a really annoying bug and the mod really doesn't cost performance so it should stay in.

**Comment by Madis0** [comment]
Item Model Fix does not use Cloth API (and from what I see, it never did), it uses Cloth Config API.

**Comment by RaptaG** [comment]
> Item Model Fix does not use Cloth API (and from what I see, it never did), it uses Cloth Config API.

If so, which mod(s) _do_ use Cloth API?
