### ISSUE TITLE
FO 3.8.2 to load with prime-run as wrapper command

### ISSUE THREAD

**Issue by AtomicJay** [Fabulously-Optimized/fabulously-optimized#341]
### Describe the bug

Today I created MultiMC instance for FO 3.8.2, put in the other mods I like to use (Xaero's Worldmap, Xaero's Minimal, Compass Ribbon, Sound Physics Remastered), along with putting Complementary Shaders in the shaderpacks folder, and set `prime-run` as the wrapper command so it would use my dedicated graphics card (NVIDIA RTX 3070 Max-Q) instead of using integrated graphics (Ryzen 9).

When I tried to launch it, the game window breifly appeared before closing. When I looked at MultiMC's console for the instance, it ended with:

`X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  150 (GLX)
  Minor opcode of failed request:  16 (X_GLXVendorPrivate)
  Value in failed request:  0xffffffffffffffff
  Serial number of failed request:  0
  Current serial number in output stream:  181
Process exited with code 1.`

I tried making a new FO 3.8.2 instance without adding any mods, let it load without setting `prime-run` as the wrapper command (which works fine), and then setting `prime-run` as the wrapper command, which gives me the same result as when I tried it before.

With FO 3.8.1, using `prime-run` as the wrapper command works fine.

### Modpack version

3.8.2

### Launcher

MultiMC

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [x] I removed or added some mods (mention, which ones)

**Comment by Madis0** [comment]
So I assume you didn't change your own mod versions from the those you used in 3.8.1?
In that case, try reverting one by one (and if successful, reporting issues to):
* Fabric Loader
* Fabric API
* Architectury API
* Sodium Extra

**Comment by AtomicJay** [comment]
I downgraded Sodium Extra to the version used in FO 3.8.1 and `prime-run` started working fine.

**Comment by AtomicJay** [comment]
Ok, I tried that and it fails to load. I'll report the issue. Thanks for the help!
