### ISSUE TITLE
TooltipTweaks

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#342]
### Mod name

TooltipTweaks

### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/tooltiptweaks

### Other links

https://modrinth.com/mod/tooltiptweaks

### What it does

Shows bee info, shulker box contents etc

### Why should it be in the modpack

Vanilla lacks bee info tooltip and shulker box contents are not displayed like bundles

### Why shouldn't it be in the modpack

More features/options than needed - to test what actually is needed and when would it be appropriate to add it (e.g. shulker box previews would not be enabled right now as detailed in #2)

### Categories

New feature

### Additional details

#66 #317 #2

**Comment by RaptaG** [comment]
https://github.com/bunten2005/tooltiptweaks-mod/issues/1

**Comment by RaptaG** [comment]
CurseForge upload added

https://github.com/bunten2005/tooltiptweaks-mod/issues/1#issuecomment-1137809111

**Comment by Lolezboi** [comment]
this seems like a really cool mod, yet still has a vanilla feel. nice!

**Comment by Madis0** [comment]
https://github.com/Fabulously-Optimized/fabulously-optimized/issues/2 and https://github.com/Fabulously-Optimized/fabulously-optimized/issues/317 were rejected, so this makes sense to close as well. Besides - abandonware :stuck_out_tongue:
