### ISSUE TITLE
MemoryLeakFix

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#347]
### Mod name

Memory Leak Fix

### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/memoryleakfix

### Other links

https://modrinth.com/mod/memoryleakfix
https://github.com/fxmorin/memoryLeakFix

### What it does

"Fixes multiple memory leaks"

### Why should it be in the modpack

Better memory usage for FO, CF API enabled, in MR

### Why shouldn't it be in the modpack

Untested

### Categories

Performance optimization

**Comment by Julienraptor01** [comment]
More info now :
https://github.com/fxmorin/memoryLeakFix/wiki/Current-Fixes

**Comment by RaptaG** [comment]
If it fixes memory usage things, then why not make an issue in [FerriteCore](https://github.com/malte0811/FerriteCore/issues)?

**Comment by Madis0** [comment]
> If it fixes memory usage things, then why not make an issue in [FerriteCore](https://github.com/malte0811/FerriteCore/issues)?

The same was asked here and there is no clear answer: https://www.curseforge.com/minecraft/mc-mods/memoryleakfix?comment=5

My guess is that the dev just wanted to create a quick fix without necessarily relying on a different mod. In terms of FO, I'm fine with either a separate or combined mod, so feel free to make an issue there.

**Comment by RaptaG** [comment]
> Feel free to make an issue there.

I did :) (https://github.com/malte0811/FerriteCore/issues/76)

**Comment by fxmorin** [comment]
That's not how this works xDDD

It does not fit into FerriteCore. Ferrite optimizes the way that operations are done for internal structure. The memory leak fix does not do anything related to this.

You guys really need to stop mod merging, it's terrible. I want to continue updating the memory leak fix, and having it be in another mod makes that harder and removes my credit for the amount of work I put into profiling the game.

Having multiple mods does NOT impact performance, I have more to say but ill be releasing that later...

**Comment by Madis0** [comment]
> You guys really need to stop mod merging, it's terrible. I want to continue updating the memory leak fix, and having it be in another mod makes that harder and removes my credit for the amount of work I put into profiling the game and making a fix.

There are benefits to merging mods that are not specifically about performance. The target should be small mods that provide one or two targeted fixes only - if the mod is meant to become larger, update often or is out of scope, merging is indeed not the way to go.

Benefits:

* Bigger mod can better make sure the fix works well with other fixes
* Bigger mod can make sure the fix is maintained across MC versions
* Less storage used on mod icon, metadata and boilerplate code as those already exist
* No additional libraries for config etc
* More likely to have an opt-out option (if it needs one)
* Potentially better distribution (e.g. Curseforge, Modrinth and GitHub)

As you said, I understand that your mod is out of scope for FerriteCore and you want to maintain it yourself, so we don't have to discuss this further unless you want to.

**Comment by Madis0** [comment]
Added in 3.9.0
