### ISSUE TITLE
Entity Collision FPS Fix Refabricated

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#350]
### Mod name

Entity Collision FPS Fix Refabricated

### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix-fabric

### Other links

https://github.com/CorgiTaco/No-Client-Side-Entity-Collision-Checks

### What it does

Improve FPS when entities collide, e.g. mob farms

### Why should it be in the modpack

Similar FPS improvement to FastChest/Entity Block.. whatever, just for mobs, CF API enabled

### Why shouldn't it be in the modpack

Modrinth? Could get included in Debugify as well.

### Categories

Performance optimization

### Additional details

https://github.com/W-OVERFLOW/Debugify/issues/93

**Comment by Julienraptor01** [comment]
> It does not seem to bring any perfomance on a multiplayer server. Possibly because of iris. That's a very rough test, but with what the mod claims to do it should not matter whether you are in multiplayer or singleplayer.

Why iris ?

**Comment by DioEgizio** [comment]
Iris included batched entity models

**Comment by Rajbir98** [comment]
Does removing iris makes the mod work and we get better performance

**Comment by RaptaG** [comment]
Patched in Debugify ( See https://github.com/isXander/Debugify/commit/7b8d40fde17fc3a51122b992f6aacf3b412b9dae )

**Comment by Madis0** [comment]
Enabled Debugify bugfix in 3.9.0.
