### ISSUE TITLE
Better Biome Blend

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#353]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/better-biome-blend

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/better-biome-blend

### Source/other link

https://github.com/FionaTheMortal/better-biome-blend

### What it does

Makes biome blending faster

### Why should it be in the modpack

Faster biome blending, claims to be compatible with Sodium now

### Why shouldn't it be in the modpack

It forcefully sets the blending to be 29x29; untested if it actually helps over vanilla/Sodium in 1.18+ and compared to lower blending values.
Here's one way to test it: https://www.curseforge.com/minecraft/mc-mods/better-biome-blend?comment=109

### Categories

Performance optimization, Graphics optimization

**Comment by Julienraptor01** [comment]
Doesn't sodium already improve biome blending ?

**Comment by Julienraptor01** [comment]
Yeah i found this
https://www.curseforge.com/minecraft/mc-mods/better-biome-blend?comment=118

**Comment by Julienraptor01** [comment]
I'm gonna test and see

**Comment by Rajbir98** [comment]
i feel it cuts of my performance with 2-3 fps

**Comment by YumatanGames** [comment]
I did installed and test it. I can't notice any significant change in performance, but honestly I can barely notice the visual changes too. It's noticeable if you do a side by side comparison, but during normal gameplay the normal sodium biome blend works well enough. I don't see a drawback in including this, but I see no major benefits either tbh...

**Comment by Kichura** [comment]
What i got from testing (All 3 tests used 15x15 biome blending):

![vanilla](https://user-images.githubusercontent.com/68134602/171999305-72f0b398-3f27-407a-9094-abc6bbb39b28.png) - Vanilla,

![sodium](https://user-images.githubusercontent.com/68134602/171999313-cb621acc-8940-4dd6-aaee-24310278ef0a.png) - Sodium,

![bbb](https://user-images.githubusercontent.com/68134602/171999331-f3589bc7-8e67-4547-8dbf-8aa6b0271773.png) - Better Biome Blend.

**Comment by Julienraptor01** [comment]
I think as BetterBiomeBlending looks really similar to Sodium and doesn't improve or decrease anything we shouldn't include it in FO

**Comment by Julienraptor01** [comment]
> What i got from testing (All 3 tests used 15x15 biome blending + fast graphics):
> 
> ![vanilla](https://user-images.githubusercontent.com/68134602/171999305-72f0b398-3f27-407a-9094-abc6bbb39b28.png) Vanilla,
> 
> ![sodium](https://user-images.githubusercontent.com/68134602/171999313-cb621acc-8940-4dd6-aaee-24310278ef0a.png) Sodium,
> 
> ![bbb](https://user-images.githubusercontent.com/68134602/171999331-f3589bc7-8e67-4547-8dbf-8aa6b0271773.png) Better Biome Blend.

take note that some resource pack and some graphic settings were changed

**Comment by Kichura** [comment]
Second test in case first one looked too horrible:


![vanilla](https://user-images.githubusercontent.com/68134602/172000549-cccb01f2-247b-4a50-a6b6-6a45b409c9f8.png) Vanilla,

![bbb](https://user-images.githubusercontent.com/68134602/172000559-0b184472-499e-4f03-9335-9a7e6566caa0.png) Better Biome Blend,

![sodium](https://user-images.githubusercontent.com/68134602/172000574-b0e1735f-7234-48f7-a132-29ea28669a08.png) Sodium,

![bbb+sodium](https://user-images.githubusercontent.com/68134602/172000581-ca071d9b-2c73-4152-ae90-6bd00923f4a2.png) BBB + Sodium.

**Comment by Julienraptor01** [comment]
here are some 8K screenshots of BBB and no BBB in FO
https://imgur.com/a/NQYZOAp

**Comment by Julienraptor01** [comment]
I wouldn't include it because while vanilla blending si too small by default here it's the opposite extreme, it's too blended.
(that's only my opinion on how it looks. I understand the idea of making it more blended but i think sodium blending on 7 is just right.)

**Comment by Madis0** [comment]
Visuals aside, are you seeing performance improvements?

**Comment by YumatanGames** [comment]
In my testing I didn't notice any change performance wise.

**Comment by Kichura** [comment]
> Visuals aside, are you seeing performance improvements?

very little. (+20 FPS gain from my PC)

**Comment by Julienraptor01** [comment]
I didn't see improvements however i was in extreme conditions

**Comment by Big-ed69** [comment]
In my testing biome blend looked significantly better but FPS was roughly the same if not 1 or 2 FPS lower.

**Comment by Uranite** [comment]
![image](https://user-images.githubusercontent.com/62639703/175115877-86ab29ff-23c2-4eeb-8a95-557cf79c17d9.png)
from CaffeineMC discord
https://discord.com/channels/602796788608401408/752637878462578778/981947355916038184

**Comment by Madis0** [comment]
Closing because testers and Jelly say it doesn't improve performance.
