### ISSUE TITLE
Reconsider Bobby

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#354]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/bobby

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/bobby

### Source/other link

https://github.com/Johni0702/bobby

### What it does

Bobby is a Minecraft mod which allows for render distances greater than the server's view-distance setting. It accomplishes this goal by recording and storing (in `.minecraft/.bobby`) all chunks sent by the server which it then can load and display at a later point when the chunk is outside the server's view-distance. (Credit: [NebelNidas](https://github.com/NebelNidas) via #46)

### Why should it be in the modpack

Comparing to FarSight, Bobby is:

- [Open Source](https://github.com/Fabulously-Optimized/wiki/blob/main/en-us/principles.md#principles)
- On [Modrinth](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/63)
- More customizable
- Providing [OF parity](https://github.com/Fabulously-Optimized/wiki/blob/main/en-us/give-up-optifine.md) by supporting 32+ render distances

### Why shouldn't it be in the modpack

FarSight was voted as a mod better than Bobby

### Categories

Replaces an existing mod, Works like OptiFine

### Additional details

On the public vote made in the past, the only thing the FO community was asked to vote about is performance. Since the beta version which included for the last time Bobby, more performance optimizations have been added, via Debugify and other mods too. Also, the mod's configuration allows you to disable the chunk caching. Fabulously Optimized aims on OptiFine parity and 32+ render distance is another feature FarSight does not cover. To sum up, I see no point for Bobby not to be in the modpack. Please don't forget that I had voted for [FarSight too](https://discord.com/channels/859124104644788234/955106952491458590/956278608740118558) (The link is from the [Discord Server](https://discord.gg/yxaXtaQqdB)). See also #46, the original issue.

**Comment by Madis0** [comment]
Counterpoints:

* Open-source is good, but I would not consider it a significant argument here (because performance is a bigger reason)
* Farsight plans to publish to Modrinth as well when Modrinth implements payments (as do hundreds of other mods)
* Modrinth is currently not entirely supported by FO anyway, so it does not matter that much yet
* There is a config file for Farsight, but I can't recall what options it had

**Comment by Julienraptor01** [comment]
> It works by having the client keep the chunk data, even when the server unloads that chunk up to a max distance of 32 chunks(configurable).

This is the only option

**Comment by Julienraptor01** [comment]
>> And Farsight can in fact cover 32+ render distance as said in config file

>Bobby allows you to do that directly via the video settings.

You can do an issue to farsight dev to add a config GUI.

>> (Well there are but not really. By default FO don't want to keep cache but i understand bobby could be included to give an option to the user to keep cache. But This can be done currently by user that want that by simply swapping the mods.)

> Wouldn't it be better to toggle that a few clicks?

Well maybe yes. But alone it's, i think, a too small reason to add bobby.

>> (The other reason i can see is that farsight is currently not on Modrinth but this will be resolved as soon as modrinth give payouts.)

> Bobby doesn't seem to care for payouts on mod distributing platforms, which is good. You see, that's the good thing with open source software in general; It's not depended on money.

OK i agree with this point but maybe the man just want to get a reward for his mod which is understandable. (Yes i'm a bit the devil's lawyer here but...)

>> However if bobby had an update in the future to make the performance better, i think we should reconsider it.

> Since the beta version which included for the last time Bobby, more performance optimizations have been added, via Debugify and other mods too...

Here you don't seem to understand me. If the performance of bobby is boosted by an external factor then farsight has a really high probability to be boosted too.

**Comment by isXander** [comment]
In my opinion, OSS is a big factor. Without people looking at code, you have no idea what nasty bugs could be lurking in the shadows.

My question is, why *not* OSS, what is there to hide?

**Comment by Julienraptor01** [comment]
> In my opinion, OSS is a big factor. Without people looking at code, you have no idea what nasty bugs could be lurking in the shadows.
My question is, why not OSS, what is there to hide?

Is boycotting closed-source mod worth losing performance ?

**Comment by fxmorin** [comment]
I would actually recommend https://www.curseforge.com/minecraft/mc-mods/distant-horizons instead.
Since it not only keeps chunks but also applies LOD, improving performance drastically while doing it.

**Comment by Madis0** [comment]
> I would actually recommend https://www.curseforge.com/minecraft/mc-mods/distant-horizons instead. Since it not only keeps chunks but also applies LOD, improving performance drastically while doing it.

Planned, cannot add yet: #240

**Comment by Madis0** [comment]
I want performance tests that claim this is now comparable with Farsight.

**Comment by YumatanGames** [comment]
Well I have one thing that for me makes Bobby better. It has the option to remember the chunks after you logged out or disconnected. For me this is a very important thing, as I like to log in and see all the surroundings of my base without having to do a fly by every time.

**Comment by Madis0** [comment]
> Well I have one thing that for me makes Bobby better. It has the option to remember the chunks after you logged out or disconnected. For me this is a very important thing, as I like to log in and see all the surroundings of my base without having to do a fly by every time.

I understand that some people like that, but it would not be enabled in FO anyways, because I want to keep people's privacy, abide by servers' rules and not fill up the hard drive.

**Comment by Julienraptor01** [comment]
> Well I have one thing that for me makes Bobby better. It has the option to remember the chunks after you logged out or disconnected. For me this is a very important thing, as I like to log in and see all the surroundings of my base without having to do a fly by every time. 

I don't know where's the message
(someone link it here pls)
But as the option of caching chunk would be off by default to not make MC take more and more size.
I kinda like the option in some cases but they are mostly edge cases.
However if you like this mod you can change farsight for it.
And if you are with MMC-autoupdate look in the wiki on how to do it.

**Comment by isXander** [comment]
> > Well I have one thing that for me makes Bobby better. It has the option to remember the chunks after you logged out or disconnected. For me this is a very important thing, as I like to log in and see all the surroundings of my base without having to do a fly by every time.
> 
> I understand that some people like that, but it would not be enabled in FO anyways, because I want to keep people's privacy (not keeping any server files they don't know of), abide by servers' rules (I think some don't allow world download mods... haven't found such ones though) and not fill up the hard drive.

The fact your talking about banning world download mods is just silly. You are always downloading the world so you can view it. Is there really any difference between ram and SSD? You can't use the chunk files anyway without a level.dat and other things.

**Comment by Madis0** [comment]
Alright, I'll admit that point was indeed a bit silly. Other points are valid though.

**Comment by YumatanGames** [comment]
The thing about Bobby is that you can say how long it should keep the chunks saved. If it's said something like 5 days for example, it would delete the data from the chunks you haven't being in a while, all while keeping the ones you see more often. That essentially means that the size won't be creeping up that much. 

In my view, anyway, it's better to have a feature but don't want to use them, then to want a feature that isn't there.

**Comment by Julienraptor01** [comment]
> The thing about Bobby is that you can say how long it should keep the chunks saved. If it's said something like 5 days for example, it would delete the data from the chunks you haven't being in a while, all while keeping the ones you see more often. That essentially means that the size won't be creeping up that much.
> 
> In my view, anyway, it's better to have a feature but don't want to use them, then to want a feature that isn't there.

Yes, i totally agree with that, if it doesn't decrease performance.
If at one point i find in my testing that bobby surpass farsight, i'll directly use and give the results.

**Comment by RaptaG** [comment]
> If at one point i find in my testing that bobby surpass farsight, i'll directly use it for myself and give the results here.

Ok! I hope this issue will have your review soon!

**Comment by RaptaG** [comment]
I think this issue should be closed, new features can be suggested in HTC.
