### ISSUE TITLE
Fabric Custom Skyboxes

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#355]
### Source/other link

https://github.com/roro1506HD/fabric-custom-sky/

### What it does

OptiFine custom skyboxes support :tada:

### Why should it be in the modpack

OptiFine custom sky parity!

### Why shouldn't it be in the modpack

Not on [CurseForge / Modrinth](https://github.com/roro1506HD/fabric-custom-sky/issues/3), no [1.18.2](https://github.com/roro1506HD/fabric-custom-sky/issues/2)

### Categories

Graphics optimization, New feature, Works like OptiFine/Bedrock Edition/Forge/etc

### Additional details

See [this comment](https://github.com/roro1506HD/fabric-custom-sky/issues/1#issuecomment-1143620908)
#72

**Comment by Madis0** [comment]
> The mod seems to be violating OptiFine's ARR license. After taking a quick glance at the sources and "decompiling OptiFine locally using fernflower", it appears to be a direct copy of OptiFine.

-FlashyReese
