### ISSUE TITLE
MoreCulling

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#357]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/moreculling

### CurseForge Mod Distribution

Allowed 

### Modrinth link

https://modrinth.com/mod/moreculling

### Source/other link

https://github.com/fxmorin/moreculling

### What it does

Culls various non-full blocks

### Why should it be in the modpack

Culling does help performance, as evident by Sodium, Entity Culling, Cull Less Leaves etc

### Why shouldn't it be in the modpack

* Performance boosts are not proven yet (tests are inconclusive)
* CIT is broken in item frames
* Several mods have incompatibilities

### Categories

Performance optimization

**Comment by YumatanGames** [comment]
I just did some testing and I did indeed had an incredible boost in performance, with over 800 FPS with 32 render distance, when before I had about 200-300

**Comment by YumatanGames** [comment]
I had a crash caused by this More Culling. Seems to be a conflict with Iris.

**Comment by Madis0** [comment]
> I had a crash caused by this More Culling. Seems to be a conflict with Iris.

Alright, you can report it to the mod dev. Overall there is no reason to report bugs here yet as the mod is in alpha (and the label here is WIP). When that changes, I'll actually consider adding it and will care about any potential bugs.

**Comment by isXander** [comment]
Vouch. Though note at the current moment this crashes with CullLessLeaves. A fix is being worked on.

**Comment by FireTner** [comment]
Works with Cull Leaves as far as I've noticed (predecessor of CullLessLeaves)

**Comment by RaptaG** [comment]
> Works with Cull Leaves as far as I've noticed (predecessor of CullLessLeaves)

Yeah this is known, Cull Leaves works but CullLessLeaves doesn't (it's gonna be fixed soon though).

**Comment by fxmorin** [comment]
Officially no longer in Alpha. https://modrinth.com/mod/moreculling/version/v0.4.0
CullLessLeaves also already have the fix @isXander just needs to make a release

**Comment by RaptaG** [comment]
Does not crash with CullLessLeaves as of https://github.com/isXander/CullLessLeaves/commit/55112fc3a8abbb6f267682fd74723e6b29c574d3 (the new version of CullLessLeaves is unreleased though).

**Comment by RaptaG** [comment]
CurseForge link: https://www.curseforge.com/minecraft/mc-mods/moreculling

**Comment by RaptaG** [comment]
Also Sodium Configuration is now a thing in MoreCulling

**Comment by RaptaG** [comment]
Compat version of CLL released

**Comment by RaptaG** [comment]
LambdaBetterGrass seems to be unsupported (see https://github.com/fxmorin/MoreCulling/discussions/31#discussion-4209006)

**Comment by Madis0** [comment]
> LambdaBetterGrass seems to be unsupported (see [fxmorin/MoreCulling#31 (comment)](https://github.com/fxmorin/MoreCulling/discussions/31#discussion-4209006))

Yeah, but it says it won't crash and some optimizations are supported. Please test the mod with FO to see if there are any more conflicts.

**Comment by isXander** [comment]
For people who say performance doesn't improve: you aren't in an environment where it is improved. It culls things like bamboo, item frames, chorus fruit etc. You have to test in jungles or end islands.

**Comment by RaptaG** [comment]
As you said, v.0.5.2 fixed it (see https://github.com/fxmorin/MoreCulling/commit/73fc5dd978ae617416d4af4c53d7c76f41b1d10b)

**Comment by Madis0** [comment]
Performance testing results were inconclusive, some mods had incompatibilities. Decided not to add it for 4.2.0 yet, but keeping an eye on it for the future.

**Comment by Madis0** [comment]
0.10.0 added a separate toggle for mods, so at least that could be disabled.

**Comment by Julienraptor01** [comment]
new comment in #424

**Comment by Madis0** [comment]
> Updated to 1.19.3!
>
> New Features: 
> - Cloud Culling 
> - Map Culling (in item frames)
>
> Fixes:
Modded blocks where not correctly being excluded from being culled

Seems worthy of a retry, could replace #512 too.
