### ISSUE TITLE
Chat Up to fix UI mis-alignment

### ISSUE THREAD

**Issue by ccrvincent** [Fabulously-Optimized/fabulously-optimized#361]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/chat-up

### CurseForge Mod Distribution

Allowed

### Source/other link

https://github.com/gnembon/chat-up

### What it does

Moves the chat UI section up to no longer overlap the armor UI.

### Why should it be in the modpack

Corrects a minor graphical issue.

### Why shouldn't it be in the modpack

Works in 1.18 but isn't flagged as such on CurseForge.

### Categories

Fixes a bug/makes another mod work

**Comment by Madis0** [comment]
While it seems like an easy fix for an obvious issue, I feel like there are many people who are actually used to this, so adding this mod would be opinionated and break their workflow.
