### ISSUE TITLE
Bug with GDLauncher

### ISSUE THREAD

**Issue by NoltoxGit** [Fabulously-Optimized/fabulously-optimized#362]
### Describe the bug

Hello!
I have a bug when download the Modpack with the GDLauncher.

When I try download the modpack with GD, I have error "_Instance Download Failed_".

### Modpack version

3.9.1

### Launcher

GDLauncher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I removed or added some mods (mention, which ones)

### Additional context

[Here is a video of the bug](https://youtu.be/thfvR6e99qo).

**Comment by Madis0** [comment]
This is known and I can't do anything about it:
https://github.com/gorilla-devs/GDLauncher/issues/1288

I suggest creating a Fabric instance in GDLauncher and copying the files over, similar to vanilla instructions: https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions#minecraft-launcher-the-vanilla
