### ISSUE TITLE
Adjust Zoomify for smoother zoom

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#366]
### What config to change

Reconfigure Zoomify so it feels more like [Ok Zoomer](https://www.curseforge.com/minecraft/mc-mods/ok-zoomer). 

But first, there has to be consensus on what changes are actually needed, because [I already changed the config of FO to match that in 3.9.0.
](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#390-2022-06-03)
### Why should it be changed

People like Ok Zoomer, but it was removed due to issues as detailed in #144 and now it is even Quilt-only. Yet, people still want it's look-and-feel as evident by #164 #243, so since I think Optifine's zoom is bad anyways (https://github.com/Fabulously-Optimized/wiki/issues/14), I would be glad to add Ok Zoomer-like configs as the default of FO.

### Category

Mod config option

### Additional details

Use this issue to share your configs so we can try and get consensus on what defaults to include. I personally would prefer no Cinematic Camera, but that's up to community's feedback as well.

Overall, I would also suggest adding this config as the default of Zoomify (for the community preference reasons as detailed above), but that's up to this mod dev as well.

**Please do not discuss the possibilities of re-including Ok Zoomer here, this is not the issue for that.**

**Comment by isXander** [comment]
Ease out Exp was made default in one of the recent Zoomify updates, so you can minimize the config further

**Comment by Madis0** [comment]
Zoomify will change the defaults to match Ok Zoomer in the next version, so FO will remove the config and just inherit that.

**Comment by RaptaG** [comment]
I believe I can take on this project.

**Comment by RaptaG** [comment]
> > I believe I can take on this project.
> 
> 
> 
> Take on what? I just said I will inherit default config, if you have suggestions, just test the latest (preview of) Zoomify and give feedback to isXander.

Oh ok sorry.
