### ISSUE TITLE
Remove Fabric Capes

### ISSUE THREAD

**Issue by osfanbuff63** [Fabulously-Optimized/fabulously-optimized#370]
Selling capes - or rather, in this case, making money off the modpack (via CF) which includes capes - is a violation of the Minecraft EULA.

> "sell cosmetic entitlements, except for "Capes," which we define as anything that attempts to visually emulate the feature of a Minecraft player Cape."

So this should probably be removed since violating the EULA is, well, violating the EULA.

**Comment by Madis0** [comment]
I do not agree.
I actively suggest people to obtain free capes, while simply giving the options to also use the capes they already paid for. If there is any problem with this, it should be communicated with the cape providers, not me.
