### ISSUE TITLE
Issue with Vanilla MC Launcher

### ISSUE THREAD

**Issue by CrippleKitten** [Fabulously-Optimized/fabulously-optimized#372]
### Describe the bug

When I want to start my game, it doesn't load and crashes, giving me a fabric bug report. I don't know how to solve it, as I am not that technically inclined.... please help

(I added the bug report as a screenshot)
![Fabric Loader bug FO](https://user-images.githubusercontent.com/107765305/174447507-2170d6ca-0f98-40f9-87fe-a2c0f3fdc531.PNG)

### Modpack version

Fabric-loader-1.19

### Launcher

Minecraft Launcher (vanilla)

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [ ] I removed or added some mods (mention, which ones)

### Additional context

I changed the FO pack from Fabulously+Optimized+3.9.1 to Fabulously+Optimized+3.10.0 because my Realms told me that it was out-of-date and I couldn't access it with the older modpack. I also updated Fabric, but now it won't even open my game.

**Comment by Madis0** [comment]
The error says you are trying to use FO 3.10.0 on Minecraft 1.19, which won't work. 

You either need to use Minecraft 1.18.2 with FO 3.10.0 or - considering your issue with realms - Minecraft 1.19 with FO 4.0.0-beta.1 or later.

**Comment by CrippleKitten** [comment]
> 
How do I fix that? because I am in the Vanilla loader and for that there is no beta yet... (not that I have found at least)

**Comment by Madis0** [comment]
These are the instructions: https://github.com/Fabulously-Optimized/wiki/blob/main/en-us/install-instructions.md#minecraft-launcher-the-vanilla

And currently the latest beta is here: https://www.curseforge.com/minecraft/modpacks/fabulously-optimized/files/3834984

**Comment by CrippleKitten** [comment]
I followed those instructions with the install of 3.10.0 and now with the beta that you linked. The game does start up now and let's me connect to realms. Tysm!
