### ISSUE TITLE
Heads Missing?

### ISSUE THREAD

**Issue by Tripp1e** [Fabulously-Optimized/fabulously-optimized#373]
### Describe the bug

The Heads of NPCs (on hypixel for Example) are missing
![Example on monumenta Server](https://user-images.githubusercontent.com/102437240/174666311-f597f463-9358-4b78-8ca5-52f4fce2cd93.png)
?

### Modpack version

3.10.1 from MultiMC/Modrinth

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I removed or added some mods (mention, which ones)

**Comment by Madis0** [comment]
1) Modrinth is currently not supported. I'd link you to CF but it's down, so fair enough.
2) I've had two testers who claim they can still see the heads, so it must be specific to you in some way. Any custom mods or resource packs?
3) If you have no custom mods, try reproducing this with a new Fabric instance with: Entity Texture Features, CEM and Fabric API.

**Comment by Tripp1e** [comment]
I have found out that it was the Server specific Texture Pack, though it is required and I dont know what in the texture pack caused this bug, so yeah, imma remove this bug, as it has nothing to do with the mod pack

**Comment by Madis0** [comment]
Thanks for clarifying. See this for some tips with that resource pack: https://fabulously-optimized.gitbook.io/modpack/readme/resource-pack-issues
