### ISSUE TITLE
Ctrl Q

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#375]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/ctrl-q

### CurseForge Mod Distribution

Allowed

### Source/other link

https://github.com/Mrredstone5230/Ctrl-Q

### What it does

Forces Ctrl+Q to drop a stack of items in macOS

### Why should it be in the modpack

Because macOS users use this modpack and it's probably very annoying for them

### Why shouldn't it be in the modpack

Not on Modrinth (requested) and GitHub versions are old, becomes irrelevant when #219 happens, untested

### Categories

Fixes a bug/makes another mod work

**Comment by RaptaG** [comment]
A patch was added in the latest version of Debugify.
