### ISSUE TITLE
Game crashes [1.18.2]

### ISSUE THREAD

**Issue by Taughtimp2786** [Fabulously-Optimized/fabulously-optimized#382]
### Describe the bug

When, I launch my game, it crashes.

### Modpack version

3.10.1

### Launcher

Minecraft Launcher (vanilla)

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I removed or added some mods (mention, which ones)

### Additional context

Installed mods: `https://pastebin.com/d1HR9GXn`
Game output: `https://pastebin.com/t2UnHJ6d`
Log: `https://pastebin.com/Er3z4V1E`

I didn't remove any mods that belonged to 'fabulously-optimized`.

**Comment by Madis0** [comment]
Remove your extra mods, especially Wurst, Quilt API, Essential. I do not provide support for hacked clients or Quilt.
