### ISSUE TITLE
Inventory Profiles Next

### ISSUE THREAD

**Issue by Carterpersall** [Fabulously-Optimized/fabulously-optimized#387]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/inventory-profiles-next

### Source/other link

https://github.com/blackd/Inventory-Profiles

### What it does

- Helps you keep your inventory sorted
- Can replace your quasi-broken tool
- Dump everything in that chest with one click
- Move the items you have that are also already in the chest                                         
- Lock item slots in place so that sorting ignores them
- Keep locked slots empty
- Allow you to press R+C to set your shortcuts
- Be pure client-side, so that it works everywhere

### Why should it be in the modpack

The mods dramatically improves the current disaster that is inventory organization.

### Why shouldn't it be in the modpack

This mod might deviate a bit too far from the vanilla-like methodology depending on the extent of what vanilla-like means to you.

### Categories

New feature

**Comment by Madis0** [comment]
It is an extra opinionated feature, one that player _has to learn_ to benefit from. The modpack should only provide "essential" tools that keep the vanilla feel, so players can add any opinionated mods by themselves.
