### ISSUE TITLE
Remove Don't Clear Chat History

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#388]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/dont-clear-chat-history

### CurseForge Mod Distribution

Allowed

### Modrinth link

Unofficially: https://modrinth.com/mod/dcch

### Source/other link

https://github.com/anar4732/DontClearChatHistory

### What it does

Keeps the history of written chat commands, so if you leave the server/world by accident or intentionally, you can get your last typed commands back. As of version 1.2, it also keeps the chat log itself, which I never wanted (#123) and that inspired me to remove this mod.

### Why should it be in the modpack

* Written chat commands can be useful when you accidentally or temporarily left the server and now join back
  * E.g. you were in private messages with someone and can rewrite the message now
  * Note that this doesn't affect game restarts, which will still clear the history
* Having full chat log itself may also be useful in some cases of accidental disconnects, server restarts etc

### Why shouldn't it be in the modpack

* Having full chat log is something I never wanted, see #123 
  * It is very confusing to join a different server and see unrelated chat history, may cause accidental chats with people that have never been there 
  * There is no option to disable this; and seeing how the communication is lacking with the mod author, there probably won't ever be one either
* Vague license
  * Previously it was ARR by CF but CC0 on mod itself, now it's clearly ARR on both
  * The source was published as readable on GitHub for some reason
* Inconsistent updates - in 1.18 the mod was not updated for a long time #242 
* Was never on Modrinth, probably will never be
  * So currently Modrinth FO users get a different mod with different behaviour than CurseForge FO users, which is really bad  
  * The Modrinth fork is based on that previous vague license; as the mod is now more clearly ARR, it can never reach full parity with v1.2 either
* There have been claims from people that the mod is "not very useful" and "they don't understand why it's there"
  * Notably game restarts always cleared the command history as well, so the usefulness may have been dubious from the start

### Categories

New feature

### Additional details

To be clear:
* Reverting to an older version and keeping that enabled with overrides is not an option, as Minecraft updates can still eventually break it. It's better to remove it now altogether to keep it simple.
* Using the Modrinth version is not an option because CF would not allow it (the mod it forks is literally updated on CF after all, plus forks are usually not allowed)
* Removing this mod would not affect the other chat mod #126 which is still great

**Comment by DioEgizio** [comment]
Personally I liked DCCH, it was a nice addition

**Comment by Julienraptor01** [comment]
I think we should suggest to the dev to add an option to clear chat log.
We should also suggest him to put it on Modrinth.
That would resolve this issue as we could still have the command history which is really useful but not the chat history which can be confusing some time and all user would have the same mod.

**Comment by RaptaG** [comment]
I personally have no use for DCCH or MCH, I disable them both with the MultiMC auto-upgrade mod disable scripts.

**Comment by Julienraptor01** [comment]
Just to resume :
We have 2 things here
The chat history which is the thing you can read and the command history which you can navigate by pressing up and down.
MCH extend the chat history so that if by example you play during a long period on a server, the start of the conversation won't be deleted due to having too many message in the chat history which is really nice but only useful when you play during long times or are on a server with a lot of chat activity.
DCCH make 2 things
First it makes that the command history is not deleted when changing world/server.
This is useful in the case where by example you test command in your survival world then switch to a server to reproduce them. It can also be useful when you get disconnected frequently from a server where you enter the same sets of commands.
One flaw was pointed tho.
If you are not careful, yes, you could like talk on some server then go to another and retype the same message by error.
For me this is more a user problem than a real flaw of the mod.
Secondly it makes so that the chat history is not deleted when changing world/server. 
This is useful in the same case where you play on a server but have a lot of disconnections or when you hop between your survival world and a server and don't want to lose the conversation.
However, yes, it could be desorienting in some cases. Where you play on some server then change server and still have the old history.
So to resolve this we have multiple solutions
Either have 2 toggles in DCCH, one for chat history and one for command history or maybe have some separator added in chat like "-----Leaved x server-----", "-----Joined y server-----" or maybe add "/history clear chat" and "/history clear command" which could be shortened in "/hc ch" and "/hc co" however that would need some user learning so it's a solution but not the besy

**Comment by RaptaG** [comment]
> Just to resume :
> We have 2 things here
> The chat history which is the thing you can read and the command history which you can navigate by pressing up and down.
> MCH extend the chat history so that if by example you play during a long period on a server, the start of the conversation won't be deleted due to having too many message in the chat history which is really nice but only useful when you play during long times or are on a server with a lot of chat activity.
> DCCH make 2 things
> First it makes that the command history is not deleted when changing world/server.
> This is useful in the case where by example you test command in your survival world then switch to a server to reproduce them. It can also be useful when you get disconnected frequently from a server where you enter the same sets of commands.
> One flaw was pointed tho.
> If you are not careful, yes, you could like talk on some server then go to another and retype the same message by error.
> For me this is more a user problem than a real flaw of the mod.
> Secondly it makes so that the chat history is not deleted when changing world/server. 
> This is useful in the same case where you play on a server but have a lot of disconnections or when you hop between your survival world and a server and don't want to lose the conversation.
> However, yes, it could be desorienting in some cases. Where you play on some server then change server and still have the old history.
> So to resolve this we have multiple solutions
> Either have 2 toggles in DCCH, one for chat history and one for command history or maybe have some separator added in chat like "-----Leaved x server-----", "-----Joined y server-----" or maybe add "/history clear chat" and "/history clear command" which could be shortened in "/hc ch" and "/hc co" however that would need some user learning so it's a solution but not the besy

Your arguments made me change my mind, I'm fine with DCCH but MCH is still useless for me.

**Comment by Julienraptor01** [comment]
> > Just to resume :
> > We have 2 things here
> > The chat history which is the thing you can read and the command history which you can navigate by pressing up and down.
> > MCH extend the chat history so that if by example you play during a long period on a server, the start of the conversation won't be deleted due to having too many message in the chat history which is really nice but only useful when you play during long times or are on a server with a lot of chat activity.
> > DCCH make 2 things
> > First it makes that the command history is not deleted when changing world/server.
> > This is useful in the case where by example you test command in your survival world then switch to a server to reproduce them. It can also be useful when you get disconnected frequently from a server where you enter the same sets of commands.
> > One flaw was pointed tho.
> > If you are not careful, yes, you could like talk on some server then go to another and retype the same message by error.
> > For me this is more a user problem than a real flaw of the mod.
> > Secondly it makes so that the chat history is not deleted when changing world/server. 
> > This is useful in the same case where you play on a server but have a lot of disconnections or when you hop between your survival world and a server and don't want to lose the conversation.
> > However, yes, it could be desorienting in some cases. Where you play on some server then change server and still have the old history.
> > So to resolve this we have multiple solutions
> > Either have 2 toggles in DCCH, one for chat history and one for command history or maybe have some separator added in chat like "-----Leaved x server-----", "-----Joined y server-----" or maybe add "/history clear chat" and "/history clear command" which could be shortened in "/hc ch" and "/hc co" however that would need some user learning so it's a solution but not the besy
> 
> Your arguments made me change my mind, I'm fine with DCCH but MCH is still useless for me.

Then you don't play for a long time enough 🤣

**Comment by isXander** [comment]
What if I made a fork which adds a bunch of blank lines between server switching and published it to both curseforge and modrinth?

**Comment by Madis0** [comment]
@isXander I certainly do not want you to "fork" an ARR mod, plus I do not want those blank lines, I don't want the chat itself to persist at all.
We need a mod that does something similar to what DCCH originally did or remove it altogether. 4.x.x will not release before this is resolved (among other ongoing issues).

**Comment by DioEgizio** [comment]
We'll be can still fork https://github.com/wafflecoffee/DCCH

**Comment by isXander** [comment]
You don't want the chat to persist but you dont want to clear history? I don't understand

**Comment by Madis0** [comment]
> You don't want the chat to persist but you dont want to clear history? I don't understand

The mod originally only persisted the typed chat, aka the commands and phrases you say and can go to with up/down keys in the chatbox. Now it persists the chat log as well - the things you and others have typed and see. The former is wanted, the latter is not.

**Comment by Madis0** [comment]
Assuming someone published Emma's fork versions to CurseForge, how would they do that while keeping the original author and CurseForge happy? By changing the mod's name? That would create a name disparity between CF and MR, creating confusion.

**Comment by Madis0** [comment]
[Discussed this in CF Dev Discord](https://discord.com/channels/900128427150028811/900187061989036034/993763623082139650) [(via)](https://discord.gg/257dCwUNvu) and came to the conclusion that forking and republishing the mod would not be a good idea due to it's previous vague license anyway, so if it doesn't add an option or revert the change before FO stable release, I will remove the mod from FO.

**Comment by osfanbuff63** [comment]
> @isXander I certainly do not want you to "fork" an ARR mod, plus I do not want those blank lines, I don't want the chat itself to persist at all. We need a mod that does something similar to what DCCH originally did or remove it altogether. 4.x.x will not release before this is resolved (among other ongoing issues).

Technically, you can't tell people that they can't contribute, even if it's licensed under ARR, [GitHub's TOS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users) explicitly allows it. However, you can choose not to contribute to an ARR project.

I know we have this issue somewhat solved, but still I think I should mention that.

**Comment by DioEgizio** [comment]
> > @isXander I certainly do not want you to "fork" an ARR mod, plus I do not want those blank lines, I don't want the chat itself to persist at all. We need a mod that does something similar to what DCCH originally did or remove it altogether. 4.x.x will not release before this is resolved (among other ongoing issues).
> 
> Technically, you can't tell people that they can't contribute, even if it's licensed under ARR, [GitHub's TOS](https://docs.github.com/en/site-policy/github-terms/github-terms-of-service#5-license-grant-to-other-users) explicitly allows it. However, you can choose not to contribute to an ARR project.
> 
> I know we have this issue somewhat solved, but still I think I should mention that.

Not really, actually. Just to display

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking).

**Comment by Madis0** [comment]
Removed in 4.0.0-beta.11. 

* I've thought long about it: if the dev decided to add options now, it would still increase the disparity between CF and MR versions of FO. 
* And if the dev also decided to publish to Modrinth for some reason, the mod would still grow larger than it needs to, potentially also having unrelated options in the future.
