### ISSUE TITLE
Python script to update MMC instance.cfg

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#389]
1. Get version number from `Desktop\Fabulously Optimized-x.x.x.zip` (aka CF file, I think that logic is already there in some python script I have)
2. Update version number on the file `(github repo path)\MultiMC\Fabulously Optimized x.y.z\instance.cfg`
3. Copy that file to `Desktop\Fabulously Optimized x.x.x.zip\Fabulously Optimized x.x.x\instance.cfg`

Ideally that action should be in the file `MultiMC to Git.py` instead of the current copy action in line 19.
The file paths should be variables similar to the ones I already have in scripts. 

PRs are welcome.

**Comment by RozeFound** [comment]
Get version from what exactly? Filename or manifest inside?

**Comment by RozeFound** [comment]
Why not curseforge manifest?

**Comment by Madis0** [comment]
Yes, the manifest could be used for that, I'm not sure if it would just be any easier to do that.

**Comment by RozeFound** [comment]
x.x.x is just a placeholder or actual part of filename?

**Comment by Madis0** [comment]
Placeholder of the version.

**Comment by RozeFound** [comment]
In 2, you mean update name var?
