### ISSUE TITLE
Say whenever something can’t be translated in the descriptions

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#394]
The disclaimers and videos (when the are not in a non-English language) of FO are in English and are untranslatable. In my Pull Request for the Greek I mention where something’s not in Greek (see line 5 and the brackets in line 68). This should be applied everywhere I believe..

**Comment by Madis0** [comment]
You are free to add a sidenote like

> link123 (in English)

My comment regarding #392 was that you _added a bold text_ to your translation, which draws attention and may leave users wonder, what needs to be bolded in Greek and not in English.

So what are you asking me to do here?

**Comment by RaptaG** [comment]
This sidenote to to be in every translation to avoid misunderstandings

**Comment by Madis0** [comment]
It's not that simple...
* English itself obviously doesn't need a sidenote at all
* Some languages have localized content already
* Some cultures/countries don't need the sidenote as the people are more likely to speak English anyway
* How this sidenote is conveyed best depends on the language as well

So basically, if you want to add a sidenote, add it. Just don't highlight it in any way, keep it in the same format as the surrounding text.

**Comment by RaptaG** [comment]
OK, I did
