### ISSUE TITLE
CIT Resewn

### ISSUE THREAD

**Issue by Comquister** [Fabulously-Optimized/fabulously-optimized#396]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/cit-resewn

### CurseForge Mod Distribution

Allowed

### What it does

It adds support for textures that precision optifine

### Why should it be in the modpack

Since fabulously-optimized is supposed to be optifine's replacement, I think it would be good to have texture functionality

### Why shouldn't it be in the modpack

I honestly don't know why I wouldn't be 

### Categories

New feature

### Additional details

I used a translator to be able to answer - sorry if English is bad

**Comment by Madis0** [comment]
The mod already exists in the modpack [since version 2.2.0 🙂](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#220-2021-09-29)
