### ISSUE TITLE
Limiting CPU load

### ISSUE THREAD

**Issue by vlad0-0** [Fabulously-Optimized/fabulously-optimized#397]
### What config to change

Add a chunk generation thread limit (or something like limit of scheduled instructions) 

### Why should it be changed

This could fix fps drop on weak cpus and avoid cpu usage of 100%

### Category

Mod config option

### Additional details

Perhaps there is a way to make spiral generation so that the area of generated chunks consistently expands from the player's position

**Comment by Madis0** [comment]
This isn't the place to request new features that don't already exist in any mod. Since you're talking about chunk generation, I suggest proposing your idea to Starlight: https://github.com/PaperMC/Starlight/issues

**Comment by vlad0-0** [comment]
Good, thanks
