### ISSUE TITLE
Exordium

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#398]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/exordium

### CurseForge Mod Distribution

Not allowed

### Modrinth link

https://modrinth.com/mod/exordium

### Source/other link

https://github.com/tr7zw/Exordium

### Mod file size

130.13 KB

### License

(any other license)

### What it does

Render the HUD and screens at a lower framerate to speed up what's really important: the worldrendering.

Renders the HUD at a lower fixed framerate, freeing up CPU and GPU time for the world rendering. There is no good reason to render the hotbar at 100+ fps.

### Why should it be in the modpack

Performance optimizations

### Why shouldn't it be in the modpack

Still a work in progress, has a high chance of breaking other mods' visuals or making them flicker.

### Categories

Performance optimization

### Additional details
Without Exordium:
![image](https://user-images.githubusercontent.com/77157639/177148092-f7ab5555-0909-4937-9479-b6bcee75ab8e.png)

With Exordium:
![image](https://user-images.githubusercontent.com/77157639/177147995-70d4495e-da4b-4d6d-a76b-355323b7e2ab.png)

(Credit @Ultrasonic1209)

Mod previously known as FasterGUI.

**Comment by nsde** [comment]
Sounds like a huge performance improvement!

**Comment by intergrav** [comment]
## Hey!
Exordium (FasterGui) has been released on [Modrinth](https://modrinth.com/mod/exordium). It's still a beta so keep that in mind, just giving a status update.

**Comment by Madis0** [comment]
Now on CurseForge, though distribution is not allowed (so GDLauncher users may struggle).
I am currently biased in inclusion due to the mod not working with my mod yet, but it is a beta anyway. Feel free to test with various HUD mods and report back.

**Comment by Julienraptor01** [comment]
> Now on CurseForge, though distribution is not allowed (so GDLauncher users will have a slightly slower download). I am currently biased in inclusion due to the mod not working with my mod yet, but the dev suggested one approach I'll try and this is still a beta anyway. Feel free to test with various HUD mods and report back.

It annoy me too because it has problems with REI but the cause is REI not doing correct render apparently

**Comment by bensuperpc** [comment]
This mod works fine for me, there is a slight improvement in performance (5-10%)
**Nice surprise**: [BetterF3](https://modrinth.com/mod/betterf3) performances are 2-3 times better with Exordium, BetterF3 causes huge FPS drops when displayed (With F3)

Tested on Linux (Manjaro) and Windows 10 with Fabulously Optimized 4.4.3

**Comment by nsde** [comment]
I also experience FPS drops when pressing F3, with and without the mod. Is there a mod which limits the logging or debug 
calculations to just the essentials?

**Comment by Julienraptor01** [comment]
> I also experience FPS drops when pressing F3, with and without the mod. Is there a mod which limits the logging or debug 
> calculations to just the essentials?

Yes F3 is laggy and uneeded pls don't use it or don't use BetterF3 mod and instead just go in the extras tab in video settings and enable Show FPS, Show FPS Extended (and Show Coordinates if you want but it's not useful for debuging)

**Comment by Julienraptor01** [comment]
> I also experience FPS drops when pressing F3, with and without the mod. Is there a mod which limits the logging or debug 
> calculations to just the essentials?

Yes F3 is laggy and uneeded pls don't use it or don't use BetterF3 mod and instead just go in the extras tab in video settings and enable Show FPS, Show FPS Extended (and Show Coordinates if you want but it's not useful for debuging)

**Comment by bensuperpc** [comment]
> > I also experience FPS drops when pressing F3, with and without the mod. Is there a mod which limits the logging or debug
> > calculations to just the essentials?
> 
> Yes F3 is laggy, it's known. Using the F3 isn't needed. Pls don't use it for testing. Don't use BetterF3 mod neither and instead just go in the extras tab in video settings and enable Show FPS, Show FPS Extended (and Show Coordinates if you want but it's not useful for debuging)

I didn't use the F3 for these reasons, i noticed this during my tests ^^
In addition I used an instance of vanilla FO and another with my mods (Like Fastload, BetterF3, Isometric Renders...)

**Comment by Madis0** [comment]
Downgraded the status of this to WIP. 
It is a nice mod, giving a good performance boost, but at the moment there is a too high chance of breaking other mods or worse, making them flicker.

**Comment by Madis0** [comment]
After the rewrite, there are a lot more bugs and performance issues, and #490 serves as a nice alternative to this. Therefore, the mod is rejected.
