### ISSUE TITLE
Amecs

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#4]
**Mod name**
Amecs

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/amecs

**Modrinth link**

**Other link**
https://github.com/Siphalor/amecs

**What it does**
Keybind view search, allow conflicting keybinds, keybind modifiers, autojump and skin layer toggles

**Why should it be in the modpack**
Improves vanilla UX, adds useful keybinds

**Why shouldn't it be in the modpack**
Modpack doesn't have that many additional keybinds yet for it to be useful

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [X] New feature
- [ ] Optifine parity

**Additional details**

**Comment by Madis0** [comment]
Rejected:

- This is still a relatively "small"/"simple" modpack, I don't think there will be that many keybinds to justify adding a mod that adds search
- Allowing conflicts can have unintended consequences
- Modifier keys are not needed for most people
- Skin layer toggles may be seen as cheats (when the person does toggle it often)

**Comment by Samisafool** [comment]
I think this should be reconsidered, maybe have the mod keybinds that were disabled set to alt + key or whatever, so people still have quick access?

**Comment by Samisafool** [comment]
one of the mod config screens? Could be because they might access it daily, but not constantly, for example swapping shaders or messing with one of the mods. Well whatever, it's your choice

**Comment by Julienraptor01** [comment]
> one of the mod config screens? Could be because they might access it daily, but not constantly, for example swapping shaders or messing with one of the mods. Well whatever, it's your choice

People can just use the default mods keybinds or bind them to what they like
There is enough keys on a keyboard to set every bind which could exist with FO mods
So there is no point in amecs in FO unlike in the very big modpacks like AoF where à mod like amecs is needed to be able to bind everything
