### ISSUE TITLE
My friend is having a rendering bug, and it might be lighting based.

### ISSUE THREAD

**Issue by stritzs** [Fabulously-Optimized/fabulously-optimized#407]
### Describe the bug

Hello, my friend is using your modpack. He is on mac, and is getting a lot of weird rendering glitches on some of the blocks on our server. Only he sees it, and we don't know what the problem is.

 https://imgur.com/a/NGI4Sqn 

### Modpack version

3.2.3

### Launcher

Minecraft Launcher (vanilla)

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I removed or added some mods (mention, which ones)

### Additional context

I added minihud, tweakeroo, and litematica.

**Comment by Madis0** [comment]
1. 3.2.3 is very old. [Please update to the latest version.](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions#minecraft-launcher-vanilla)
2. Remove the extra mods to make sure they don't cause it
3. I noticed you are using "fancy grass" on LambdaBetterGrass. While that shouldn't be an issue in itself, it's worth trying if the "fast" option has the same issue.

**Comment by Madis0** [comment]
Due to lack of response, I assume you got it fixed.
