### ISSUE TITLE
No Telemetry

### ISSUE THREAD

**Issue by arichorn** [Fabulously-Optimized/fabulously-optimized#409]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/no-telemetry

### Modrinth link

https://modrinth.com/mod/no-telemetry

### Source/other link

https://github.com/kb-1000/no-telemetry

### What it does

Disables the usage data collection, aka telemetry, introduced in Minecraft 1.18-21w38a

### Why should it be in the modpack

It makes mojang stop collecting your data so this being included in the modpack might be a good idea

### Why shouldn't it be in the modpack

well if any of the other mods you have in Fabulously Optimized does the same functions then it doesn't need to be added.

### Categories

Works like OptiFine/Bedrock Edition/Forge/etc

**Comment by Madis0** [comment]
Telemetry has been disabled from the day 1.18 was introduced and it will be done so in the future, just the mods that provide it have been swapped two times right now (currently Debugify) 😛 

So yes, this mod specifically isn't needed right now.
Related to #135

**Comment by arichorn** [comment]
I must suck at finding mods that help. I didn't think the Debugify mod would higher advantages
