### ISSUE TITLE
Mixin Conflict Helper

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#410]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/mixin-conflict-helper

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/mixin-conflict-helper

### Source/other link

https://github.com/isXander/MixinConflictHelper

### What it does

Throws an user-readable message when the user uses two mods that conflict with each other

### Why should it be in the modpack

Would help a lot of users debug their mod selection, seems so essential that it should be in loader (but neither Fabric or Quilt was interested :cry: )

### Why shouldn't it be in the modpack

- Currently messes up actual crashes (edit: only somewhat, this is mostly done by Fabric Loader itself)
- Doesn't give the actual crash along with the issue template 
- Unsure how it acts with mods that define incompatibility in manifest
- Presumably it wouldn't help on any mods that are currently on the modpack itself

### Categories

New feature, Fixes a bug/makes another mod work

**Comment by isXander** [comment]
Might be useful to know behaviour on MacOS is untested, swing GUIs are known to be pretty broken there and will need testing.

**Comment by Sheep7798** [comment]
I tested it on an M1 Mac (with ManyMC) and it crashed :

[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9093949/latest.log)

**Comment by isXander** [comment]
Unrelated to MacOS

**Comment by Sheep7798** [comment]
I got it to launch, but when I put Cull Less Leaves and More Culling together, the game crashes without the gui

[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9094446/latest.log)

**Comment by Sheep7798** [comment]
Ok, thank you for your help!

**Comment by isXander** [comment]
Are you sure it didn't appear in the background?

**Comment by isXander** [comment]
With the new mod?

**Comment by isXander** [comment]
@Sheep7798 new version! https://github.com/isXander/MixinConflictHelper/actions/runs/2678121669 send logs!

**Comment by Sheep7798** [comment]
Logs :
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9122636/latest.log)

**Comment by isXander** [comment]
you have given me the wrong log then. what you described is not there and the log says v1.0.2 when the version is v1.1.0

**Comment by isXander** [comment]
however in that case, I believe this build will have fixed the issue. 
https://github.com/isXander/MixinConflictHelper/actions/runs/2678596158
@Sheep7798

**Comment by Sheep7798** [comment]
It works now !!!
<img width="571" alt="Capture d’écran 2022-07-15 à 21 37 23" src="https://user-images.githubusercontent.com/106376800/179298832-2a73cc69-4e04-4bf0-8627-6877bf38ad80.png">

**Comment by isXander** [comment]
Weird that the buttons are backwards on MacOS.

**Comment by isXander** [comment]
still on hold?
