### ISSUE TITLE
Flashing when blocks are placed or broken

### ISSUE THREAD

**Issue by Comicalben** [Fabulously-Optimized/fabulously-optimized#413]
### Describe the bug

I got this bug where every time I place or break blocks, there's this weird flashing where I can see either the sky color or a weird x-ray effect. I was in creative mode at the time, but I had the same issue in survival.

This repeatedly happened every time I broke or placed a block, I thought it might have been the Vanilla Tweaks resource pack I downloaded, but after removing it, the same thing happened, and after putting it back in, the same thing happened. I tried changing rendering settings, closing the game, and opening it up again, but the same thing kept happening, I break or place blocks, and I get that flashing

 just to see what would happen, I tunneled through a hill in creative mode, and as I was breaking all those blocks in a straight line, I could see the other side of the hill flashing in and out.

I tried to open the game up again and screen record it, but when I did, the issue was gone. I don't know if the issue will come back again, and I'm sorry I can't show a recording

### Modpack version

4.0.0-beta.8

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Here is the customized vanilla tweaks resource pack I installed. I'm not sure if it's related, since the issue happened when I turned the resource pack off, but I might as well show it just in case

[VanillaTweaks_r873687.zip](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9115427/VanillaTweaks_r873687.zip)

**Comment by Madis0** [comment]
Adjusting options that have the word "chunk" in it in video settings will probably help.

**Comment by Madis0** [comment]
No response, assuming it is fixed.
