### ISSUE TITLE
Falling Leaves - Mod Inclusion

### ISSUE THREAD

**Issue by MaxJW** [Fabulously-Optimized/fabulously-optimized#417]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/falling-leaves-fabric

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/fallingleaves

### Source/other link

https://github.com/RandomMcSomethin/fallingleaves

### Mod file size

140.56 KB

### What it does

Adds nice little falling leaf particles to leaf blocks.

### Why should it be in the modpack

Adds a nice little particle effect when walking through forests, I think this follows with the optimized vanilla-style gameplay!

### Why shouldn't it be in the modpack

Some customization options for different leaf blocks might be confusing, should it apply to all leaf blocks?

### Categories

Graphics optimization

**Comment by Madis0** [comment]
Sorry, this mod is opinionated. The goal of the modpack is to give users tools to let them customize their experience instead of adding new content myself.
