### ISSUE TITLE
Auto-updating MultiMC version doesn't work on PolyMC 1.4.0

### ISSUE THREAD

**Issue by scoot404** [Fabulously-Optimized/fabulously-optimized#423]
### Describe the bug

Not sure what broke specifically, but the auto-update's failing with the error:
```
The process failed to start.
Pre-Launch command failed with code 0.
```

### Modpack version

Latest 1.19

### Launcher

MultiMC (auto-update)

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

[Link to the log](https://mclo.gs/91dvczh)

**Comment by Madis0** [comment]
Currently I do not support PolyMC at all. Try MultiMC and see if it works for you.

**Comment by Madis0** [comment]
A PolyMC dev confirmed that this is a PolyMC bug.

**Comment by nchristopher** [comment]
As a temporary fix, go to the instance's settings, then custom commands, and replace `"$INST_JAVA"` with the path to Java's binary. You can find the one the instance uses in the "Java" tab, also in the instance's settings.
