### ISSUE TITLE
Phosphor

### ISSUE THREAD

**Issue by LCBOI** [Fabulously-Optimized/fabulously-optimized#426]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/phosphor

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/phosphor

### Source/other link

https://github.com/CaffeineMC/phosphor-fabric

### Mod file size

86 kb

### What it does

Its a mod that optimize minecraft's lighting.

### Why should it be in the modpack

It can optimize minecraft's lighting for a smoother gameplay.

### Why shouldn't it be in the modpack

Idk

### Categories

Performance optimization

**Comment by Madis0** [comment]
This was decided against by the community in #21.
