### ISSUE TITLE
Disable MidnightControls Auto Switch mode

### ISSUE THREAD

**Issue by Julienraptor01** [Fabulously-Optimized/fabulously-optimized#428]
### What config to change

Auto Switch Mode
![image](https://user-images.githubusercontent.com/49841713/181738644-2f5d5a94-9ab2-4ade-a718-54ac4177044c.png)

### Why should it be changed

Because if i have a controller plugged-in my pc it auto switch to it and show the HUD while unnecessary.
Because it has caused issues in the past like if you have Joy-Cons with Joy-Con drift issue it'll constantly send input to the game even if you play keyboard.
It will also create problem if you have a wireless controller in a case where some button or joystic is pressed by inadvertance.
https://discord.com/channels/859124104644788234/922363933980000286/1000701966147661914
https://discord.com/channels/859124104644788234/859124571005648946/1000617259548557442

### Category

Mod config option

### Additional details

Auto Switch can be useful but it's prone to cause problems like this

**Comment by Madis0** [comment]
Because the controller keybinds button is found next to normal keybinds button, this could be done while still being obvious that users can use a controller. Still, looking for feedback on this.

**Comment by RaptaG** [comment]
I believe that Auto Switch is very useful + BE parity feature. I usually swap from my controller to my keyboard at certain times and it would be very annoying to change the controller mode manually every time I use my controller. You can make an issue in MidnightControls to disable the controller HUD after a customizable controller inactivity time.

**Comment by Julienraptor01** [comment]
> I believe that Auto Switch is very useful + BE parity feature. I usually swap from my controller to my keyboard at certain times and it would be very annoying to change the controller mode manually every time I use my controller. You can make an issue in MidnightControls to disable the controller HUD after a customizable controller inactivity time.

What about the Joy-Con drift problems, etc ? Because they drift, they make activity.

**Comment by RaptaG** [comment]
> What about the Joy-Con drift problems, etc ? Because they drift, they make activity.

Make an issue about it too :ioa:

**Comment by Julienraptor01** [comment]
> > What about the Joy-Con drift problems, etc ? Because they drift, they make activity.
> 
> Make an issue about it too :ioa:

No this is a Nintendo issue you can't fix that 🤣
You can only make it not being problematic by making it not do inputs.

**Comment by osfanbuff63** [comment]
> > > What about the Joy-Con drift problems, etc ? Because they drift, they make activity.
> > 
> > Make an issue about it too :ioa:
> 
> No this is a Nintendo issue you can't fix that 🤣
> You can only make it not being problematic by making it not do inputs. 

*technically* you can fix it - https://youtu.be/JluAuIJ-tSY

**Comment by Julienraptor01** [comment]
> > > > What about the Joy-Con drift problems, etc ? Because they drift, they make activity.
> > > 
> > > 
> > > Make an issue about it too :ioa:
> > 
> > 
> > No this is a Nintendo issue you can't fix that 🤣
> > You can only make it not being problematic by making it not do inputs.
> 
> _technically_ you can fix it - https://youtu.be/JluAuIJ-tSY

Technically yes but in reality well...
It's more up to the contructor than you

**Comment by Madis0** [comment]
https://github.com/TeamMidnightDust/MidnightControls/issues/81 is now implemented

**Comment by Julienraptor01** [comment]
> https://github.com/TeamMidnightDust/MidnightControls/issues/81 is now implemented, so unless anyone has counter-arguments, this is what I will do with the next version.
> You might want to test it as well to be sure how it works though.

So now by default Auto-Switch will be disabled and a pop-up will appear to tell the user they can use a controller ?

**Comment by Madis0** [comment]
In FO, yes.

**Comment by Julienraptor01** [comment]
> In FO, yes.

Perfect thanks 👍

**Comment by Madis0** [comment]
Implemented in 3.12.2 and 4.2.0-beta.1
