### ISSUE TITLE
FastAnim

### ISSUE THREAD

**Issue by Atticuss320** [Fabulously-Optimized/fabulously-optimized#430]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/fastanim

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/fastanim

### Mod file size

119.51 KB

### What it does

it optimizes entity animation calculations.

### Why should it be in the modpack

improves performance

### Why shouldn't it be in the modpack

not tested, no repo

### Categories

Performance optimization

**Comment by Madis0** [comment]
- Someone suggested that to me, but nobody has yet tested whether it actually improves something
- I don't know a no code repo or issue tracker, so I can't report problems if they occur
- I don't want to consider until it is on CurseForge

**Comment by Julienraptor01** [comment]
Here's the GH profile of the dev https://github.com/AViewFromTheTop

**Comment by Atticuss320** [comment]
found it on curseforge https://www.curseforge.com/minecraft/mc-mods/fastanim

**Comment by RaptaG** [comment]
Although interesting looking, this mod has some annoying bugs, which can only be reported on the CF comment section, since it has no git repo. Also, the way its `fabric.mod.json` is made, it forces the client to be on 1.19.1 and to fix it you have to manually change it. I believe this should be on hold for now.

**Comment by osfanbuff63** [comment]
> Also, the way its fabric.mod.json is made, it forces the client to be on 1.19.1 and to fix it you have to manually change it.

Can't even use dependency overrides? Wow xD

**Comment by RaptaG** [comment]
> Can't even use dependency overrides? Wow xD

I think it's possible tbh

**Comment by Atticuss320** [comment]
FastAnim got a recent bugfix and performance update

**Comment by Atticuss320** [comment]
Also it has an official 1.19.2 version now so dependency overrides are not needed anymore

**Comment by Madis0** [comment]
A lack of issue tracker or any kind of support channel is still concerning... but they seem to reply on CF comments at least so there's that. Feel free to test it again.

**Comment by Samisafool** [comment]
I think this should be closed. Madis0's comment about an issue tracker was ignored.

**Comment by Julienraptor01** [comment]
i tested this mod and it doesn't improve the perfomances, it's even the opposite, it makes it worse
Hypixel skyblock hub whitout it
50 / 60 / 75

with it
40 / 50 / 60

**Comment by Madis0** [comment]
* Testers see no difference or less FPS with the mod
* Still no issue tracker
* Still no source 

Rejected.

**Comment by Atticuss26** [comment]
fair enough
