### ISSUE TITLE
Remove Not Enough Crashes

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#439]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/notenoughcrashes

### Source/other link

https://github.com/natanfudge/not-enough-crashes

### Mod file size

162.99 KB

### License

(any other license)

### What it does

- Makes crashes be an in-game screen instead of launcher one, similar to the Out Of Memory errors
- Uploads crashes to a pastebin-like site for easy sharing
- Blames mods that might be the cause of the crash
- Allows playing after the crash occurred

### Why should it be in the modpack

- All aforementioned features improve the UX for normal players
- There is a config to adjust stuff for FO

### Why shouldn't it be in the modpack

- Ironically there have been several cases where NEC actually makes the crash harder to debug
   - So asking users to reproduce their crash without NEC makes me question NEC's purpose in the first place 
- Mod blaming is not always correct which causes more problems
  - The mod also suggests users to contact the individual mods first and foremost, which does not make sense for these type of crashes in a modpack (people should ask in FO discord first)
- Crashy's highlights are unneeded, raw logs are usually easier to debug for me and other devs
- Crash uploads overall are nice but not directly necessary because people know how to attach files in Discord and there could be bots who upload it to sites afterwards
- Playing after the crash occurred creates an inconsistent state, which can cause even more issues
- Occasional problems with mod's own updates (inconsistent platforms, improperly marked etc)

### Additional details

Funnily enough, NEC has been in FO since FO 1.0.0.

**Comment by sarim** [comment]
I also vote for removing it.  It silently eats errors and keeps minecraft running, which causes from afterwards.
