### ISSUE TITLE
Shortcut for clearing chat (F3+D) doesn't work

### ISSUE THREAD

**Issue by qasterr** [Fabulously-Optimized/fabulously-optimized#441]
### Describe the bug

Normally, whenever you press F3+D, the chat gets cleared. However, when you do that in the 1.19 version of the modpack, nothing happens. This seems to be the other F3 command that doesn't work as others such as F3+G (Show chunk boundaries) work.

The command seems to work without problems in 1.18.2, so it seems to be a 1.19 issue.

### Modpack version

Fabulously Optimized 4.0.0-beta.7

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
4.0.0-beta.7 is outdated, this bug has been fixed a long time ago. Please update to the latest beta: https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions#multimc
