### ISSUE TITLE
Blur

### ISSUE THREAD

**Issue by Minecon724** [Fabulously-Optimized/fabulously-optimized#442]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/blur-fabric

### CurseForge Mod Distribution

Allowed

### Source/other link

https://github.com/Motschen/Blur

### Mod file size

163.30 KB

### License

(any other license)

### What it does

adds a nice blur to inventories

### Why should it be in the modpack

^

### Why shouldn't it be in the modpack

unsure

**Comment by Madis0** [comment]
Sorry, Fabulously Optimized prefers to not add any mods that match a specific art style, plus the blur expects a performant computer as well. 

You can add this mod to your instance by following these instructions: https://fabulously-optimized.gitbook.io/modpack/readme/adding-more-mods
