### ISSUE TITLE
FeyTweaks

### ISSUE THREAD

**Issue by Disguys** [Fabulously-Optimized/fabulously-optimized#443]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/feytweaks

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/feytweaks

### Source/other link

https://github.com/feytox/FeyTweaks

### Mod file size

179.86 KiB

### License

(any other license)

####  Sign optimization
- Fully hide the text on the signs at a distance (ON by default)
- Hiding text out of view (ON by default)
- Hiding the outline of glowing text (ON by default)
- Convert text outline to shadow: normal mode and fast mode [Beta]
- Fully hide the text glow effect at a distance
- Glow effect optimization [Бета]
#### Beacon optimization
- Fully hide the beacon beams at a distance
- Hiding beams out of view (ON by default)
- Beacon beams optimization (ON by default)

### Why should it be in the modpack

FPS boost with a large number signs.

### Why shouldn't it be in the modpack

Small blick of signs if watch through zoom.

### FPS without FeyTweaks mod on 68 signs.
![2022-08-21_17 36 00](https://user-images.githubusercontent.com/60795989/185792073-2c9e606b-3313-44a1-b65c-3f7886f9aa02.png)
### FPS with FeyTweaks mod on 68 signs.
![2022-08-21_17 44 26](https://user-images.githubusercontent.com/60795989/185792148-f3db2597-7124-4ca4-99bd-c561ca1cbc72.png)

**Comment by Madis0** [comment]
Hmm. I believe the performance gains, but because it changes the way the signs work, the default options must be carefully considered and tested. 

For example:

- Hiding the text or its glow at a distance - what distance? Pretty sure Minecraft will stop rendering the signs at a distance altogether, so I'm curious about those differences.
- Convert text outline to shadow - cool as an option but I wouldn't enable it by default
- Glow, beacon beam optimization - not sure how exactly that's done
- Hiding signs/beacon beams out of view - that one would be great

**Comment by Julienraptor01** [comment]
>     * Would MoreCulling or Enhanced Block Entities nullify any of those effects? Maybe one of those already includes some of these features.

The question is good As EBE does alredy improve signs.
I know it was breaking the BlanketCON when i used it with the picturesign as the thing wouldn't render when sign was like in the ground etc

**Comment by fxmorin** [comment]
Just wanted to point out that I don't like the comparison images. Since it looks like FeyTweaks just removes the glowing outline.
As for MoreCulling compatibility, it shouldn't affect anything. MoreCulling just disables the text rendering completely if you are behind the sign

**Comment by Madis0** [comment]
> Rejected, because the only useful tweak (beacon beam culling) is already available in a different FO mod, just not enabled yet.
