### ISSUE TITLE
Raised

### ISSUE THREAD

**Issue by Radplay** [Fabulously-Optimized/fabulously-optimized#448]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/raised

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/raised

### Source/other link

https://github.com/yurisuika/Raised

### Mod file size

22.97 KB

### License

(any other license)

### What it does

Slightly raises the hotbar, fixing the issue of it being cut off at the bottom

### Why should it be in the modpack

The hotbar looks much nicer with the mod installed

### Why shouldn't it be in the modpack

It's a minor change, some people may not notice it

**Comment by Madis0** [comment]
Thanks for the suggestion, for now I'll reject it though:

- The bug itself seems too minor to me, even more than the [Item Model Fix](https://www.curseforge.com/minecraft/mc-mods/item-model-fix)
- People may be used to it overall or just not care
- Resource packs may be built with this bug in mind

If you can find the Mojang bug for it, you can [suggest it for Debugify](https://github.com/isXander/Debugify/issues) so it will get an easy toggle inside FO regardless.
