### ISSUE TITLE
Lower Entity Distance to 50

### ISSUE THREAD

**Issue by EquityX** [Fabulously-Optimized/fabulously-optimized#450]
### What config to change

Entity Distance from 100 to 50.

### Why should it be changed

In worlds with lots of Entities like HermitCrafts Season 7 shopping district, this can noticeably reduce stuttering while giving a boost to max frame rate. Also from my testing, 50 Entity distance seems to be much closer to parity with Bedrock than the default 100.

**Comment by RaptaG** [comment]
I personally have my entity view distance to 500% (max) and there are no notable performance drops. I play survival singleplayer and on survival servers with FO. I believe this is pointless, since it’s improving the  performance only on specific cases.

**Comment by isXander** [comment]
This setting is very much a case-by-case basis, most people are not in huge districts of entities. This can be changed according to the environment.

**Comment by Madis0** [comment]
Decided against this as it can be a (major) disadvantage in combat, both PvE and PvP.

**Comment by TechPro424** [comment]
Where can I find the option incase I want to change it myself?

**Comment by Madis0** [comment]
> Where can I find the option incase I want to change it myself?

Video Settings -> Quality -> Entity Distance.
