### ISSUE TITLE
Invisible Frames

### ISSUE THREAD

**Issue by EquityX** [Fabulously-Optimized/fabulously-optimized#451]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/invisible-frames

### CurseForge Mod Distribution

Allowed

### Mod file size

10.28 KB

### License

(any other license)

### What it does

Makes item frames invisible if they contain an item.

### Why should it be in the modpack

Gives a way to have invisible item frames in survival with an easy way to toggle invisibility by shift clicking while also giving an increase to performance in areas with a lot of item frames if they are all invisible.

### Why shouldn't it be in the modpack

Changes Item frame behavior from vanilla.

**Comment by Madis0** [comment]
Indeed it changes vanilla behavior and is opinionated, so not a good fit for this modpack.
