### ISSUE TITLE
EBE 0.7.1 is causing chests to be invisible

### ISSUE THREAD

**Issue by b12arr0** [Fabulously-Optimized/fabulously-optimized#454]
### Describe the bug

Upon loading either a SP game or joining a MP game, chests(single and double) are showing as invisible. 

### Modpack version

4.2.0-beta 6

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
Please see this wiki: https://fabulously-optimized.gitbook.io/modpack/readme/resource-pack-issues
