### ISSUE TITLE
Source packwiz mods from Modrinth

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#459]
I should start sourcing packwiz mods from modrinth to boost their downloads and improve reliability (because CF goes down often).
While packwiz plans to add a command for that, mmc-export could also be used for that, [as evident by my test](https://github.com/Fabulously-Optimized/fabulously-optimized/releases/tag/v4.3.0-pw.1).

The task itself is changing [CurseForge to Packwiz-Modrinth.py](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CLI%20tools/CurseForge%20to%20Packwiz-Modrinth.py) code to use mmc-export instead of packwiz itself:

1. Import MultiMC zip to mmc-export
2. Export it as packwiz zip
3. Extract the packwiz zip to the correct location
4. Delete the packwiz zip

In code it could be done similarly to `mmc_export_modrinth_export`: run only when the variable is set, execute a similar command in the system, then do copy/move/delete actions as needed. [Tests are in releases, marked as x.x.x-pw.x](https://github.com/Fabulously-Optimized/fabulously-optimized/releases)

`--scheme` can be used to get a consistent filename for easy unzipping.

**Comment by RozeFound** [comment]
Well, I finally implemented priority for providers, so you can source most of the mods from modrinth, and thoose which wasn't found, from GitHub or CurseForge.
