### ISSUE TITLE
Bobby

### ISSUE THREAD

**Issue by NebelNidas** [Fabulously-Optimized/fabulously-optimized#46]
**Mod name**
Bobby

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/bobby

**Modrinth link**
https://modrinth.com/mod/bobby

**Other link**
https://github.com/Johni0702/bobby

**What it does**
Bobby is a Minecraft mod which allows for render distances greater than the server's view-distance setting. It accomplishes this goal by recording and storing (in .minecraft/.bobby) all chunks sent by the server which it then can load and display at a later point when the chunk is outside the server's view-distance.

**Why should it be in the modpack**
Because players can see further than what the server's view-distance is set to, if they want to.

**Why shouldn't it be in the modpack**
Starlight currently has an issue with it, but Phosphor works fine: https://github.com/Spottedleaf/Starlight/issues/38

**Categories**

- [ ] Performance optimization
- [x] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Comment by Madis0** [comment]
It is an interesting mod, but seems to have the same problems as #7 and more (huge caches)

**Comment by Madis0** [comment]
From Discord:
> I’ve used Bobby with [Fabulously Optimized] for a while now on a private realms server and I’ve had some performance problems with it trying to render large mountain ranges all at once when it’s caching them but otherwise it [has] been great 👍

Anyone else have tried it with latest FO releases?

**Comment by TiboOpGithub** [comment]
It's a very good mod that I use often but I don't think it fits in the modpack as it stores all chunks that take up a lot of space. After playing with the mod for half a year or so, I already have about 8GB of chunk data in the bobby folder. I think Farsight is a better option since it removes the chunks after playing and so it hardly takes up space but is also less useful.

**Comment by Madis0** [comment]
@TiboOpGithub That's a good point, and regardless of which mod I add, I will disable the chunk saving feature anyway. (As I wrote above, this was added to Bobby recently: https://github.com/Johni0702/bobby/issues/25 )
But my current question is performance - does it decrease performance by any means? When loading cached chunks, when loading new chunks?

**Comment by TiboOpGithub** [comment]
> @TiboOpGithub That's a good point, and regardless of which mod I add, I will disable the chunk saving feature anyway. (As I wrote above, this was added to Bobby recently: [Johni0702/bobby#25](https://github.com/Johni0702/bobby/issues/25) ) But my current question is performance - does it decrease performance by any means? When loading cached chunks, when loading new chunks?
Oh I didn't know that! In that case, it's actually an improvement since in most cases your computer can load chunks before the server has yet to provide them. It certainly does not lower the performance and can be an added value in FO

**Comment by Madis0** [comment]
Well, Bobby surely has the network benefit, but regarding the rendering itself, I'm now aiming towards #240 or equivalent, as those seem to provide a more tangible benefit for computers with lower performance. [Maybe even alongside Bobby.](https://gitlab.com/jeseibel/minecraft-lod-mod/-/issues/99)

**Comment by TiboOpGithub** [comment]
I tested it on server and #240 works with bobby but #240 does have some problems which is why

**Comment by TiboOpGithub** [comment]
I don't know if it depends on the computer, but it worked for me with bobby

**Comment by Probattler** [comment]
With my tests, I loaded an entire hypixel duels lobby, i was getting around 15-30fps which sometimes goes down to 5-10 fps overall much better fps than #240 , and worse fps by a little bit than #184.

**Comment by Madis0** [comment]
I've yet to compare these on my machine, but I'll probably do a vote between Bobby and FarSight similar to Starlight-Phosphor once most mods of 1.18.2 are updated.

**Comment by Madis0** [comment]
New vote here

**Comment by Madis0** [comment]
Farsight results are in!
Github: 0👍 1👎 1😕
Discord: 14👍 3👎 1😕
Sum: 14👍4👎2😕

70% of voters thought Farsight runs better than Bobby,
20% of voters thought Bobby runs better than Farsight and
10% of voters did not notice a difference.

Therefore, Fabulously Optimized will use Farsight from now on.
If you were one of the 20%, feel free to follow this tutorial: 
https://github.com/Fabulously-Optimized/fabulously-optimized/wiki/Adding-more-mods

**Comment by Samisafool** [comment]
This isn't exactly fair. Voting in 2 places means some people will vote 2 times and others will vote only 1 time, skewing the results (considering the low amount of people who actually vote)

And some people on discord will just press :+1: without reading the message, maybe next time host it on discord only and use F and B emojis as reactions.

**Comment by Madis0** [comment]
Thanks for the feedback, considering it for the next time. 
Overall this isn't the place to discuss the meta of voting though, so you are also welcome to join our Discord if you'd like to do that.

**Comment by Julienraptor01** [comment]
> This isn't exactly fair. Voting in 2 places means some people will vote 2 times and others will vote only 1 time, skewing the results (considering the low amount of people who actually vote)
> 
> And some people on discord will just press :+1: without reading the message, maybe next time host it on discord only and use F and B emojis as reactions.

We can verify on discord and on GitHub who reacted so there's no problem on running platforms, if some people vote on both we'll only count one.
And if people want to use dupe accounts to vote multiple times they can theoritically do it so it's flawed to but why would anyone do that ? To get their mod in FO ? Well we are not electing someone president, i feel taking our time to try to do too much control wouldn't be worth it.

For people pressing +1 on discord well same can happen on GitHub and it could still happen with your F and B technique and same point as right up, we trust the users for global testing, if users decide to random vote, well they are gonna get random perfs. Random voting is a disadvantage for everyone
About only doing F and B reaction
Currently for testing we do compare 1st mod to vanilla (aka no tested mods), then second mod to vanilla
Then see which one outperform vanilla the most. This has the good point of being able to show if some mod is even worth it and comparing against a clear reference.

After you have read that just post a reaction so we can hide this cause it's not the good place to discuss it.
