### ISSUE TITLE
Automatic publishing to CurseForge/Modrinth

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#462]
It would be nice to have an Action that would automatically publish new releases to Modrinth. CurseForge is a bit harder because it has to have MultiMC, special changelogs etc so that's not needed atm.

**Comment by osfanbuff63** [comment]
The [`mc-publish`](https://github.com/Kir-Antipov/mc-publish) should work, even though this is a modpack. We'd need to build it first, but we can publish it using that because it [uses `files` inputs](https://github.com/Kir-Antipov/mc-publish#files-primary), so we can just upload the `.zip` (or `.mrpack` if applicable) via that.

I should be able to take on this one, but not sure when it will happen, since this isn't a super high priority issue, correct?

**Comment by Madis0** [comment]
> I should be able to take on this one, but not sure when it will happen, since this isn't a super high priority issue, correct?

Yeah, test whenever because I'm not sure if it is even possible with my file structure.

> We'd need to build it first, but we can publish it using that because it [uses files inputs](https://github.com/Kir-Antipov/mc-publish#files-primary), so we can just upload the .zip (or .mrpack if applicable) via that.

Do we really need to build it though? Can't we attach the Action to releases instead of commits and therefore just take the mrpack from the release?

**Comment by osfanbuff63** [comment]
> > I should be able to take on this one, but not sure when it will happen, since this isn't a super high priority issue, correct?
> 
> Yeah, test whenever because I'm not sure if it is even possible with my file structure.
> 
> > We'd need to build it first, but we can publish it using that because it [uses files inputs](https://github.com/Kir-Antipov/mc-publish#files-primary), so we can just upload the .zip (or .mrpack if applicable) via that.
> 
> Do we really need to build it though? Can't we attach the Action to releases instead of commits and therefore just take the mrpack from the release?

In theory, yes - I haven't thought of that.

**Comment by osfanbuff63** [comment]
Leaving this open until we get a new release to tell whether #492 works.

**Comment by Madis0** [comment]
We did it!

**Comment by Madis0** [comment]
Well, actually there is an issue with pre-releases:

> it gets the changelog and minecraft version from latest pre-release
> but files and version number from latest stable release 🤷
> I guess the problem is the release-downloader's interpretation of "latest"

**Comment by Madis0** [comment]
robinraju's release-downloader v1.9 now includes a boolean `preRelease`, which fixes my problems, even though I have to toggle it before I make any alpha versions again.
