### ISSUE TITLE
Enable MC-112730 and MC-228976 in Debugify

### ISSUE THREAD

**Issue by osfanbuff63** [Fabulously-Optimized/fabulously-optimized#465]
### What config to change

Enable both MC-112730 and MC-228976 in Debugify.

### Why should it be changed

These are marked in [the wiki](https://fabulously-optimized.gitbook.io/modpack/readme/changed-options#fixed-bugs) as fixed, but we haven't actually done it.

**Comment by Madis0** [comment]
Fixed in 4.3.2
