### ISSUE TITLE
Error on connecting to a specific server

### ISSUE THREAD

**Issue by vordenken** [Fabulously-Optimized/fabulously-optimized#475]
### Describe the bug

Most of the time I get an error while trying to connect to a mp server. 
Here's a screenshot of the error message: 
![Screenshot 2022-09-16 at 15 30 05](https://user-images.githubusercontent.com/62395860/190652043-aca803de-b7a9-4d42-b976-e31745835495.png)

The Minecraft log doesn't show any messages which is weird? 

### Modpack version

4.3.2

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

I'm using PolyMC Launcher on my Mac (m1). I don't have this problem with vanilla Minecraft or other modpacks.

**Comment by Madis0** [comment]
Thanks for the report. 

As of FO 4.3.3 you can work around it by going to Mods -> search "No Chat Reports" -> config button -> Technical -> Enable mod. A better fix will come later.

**Comment by Madis0** [comment]
Fixed in 4.4.2.
