### ISSUE TITLE
why all entities are transparent?

### ISSUE THREAD

**Issue by timget** [Fabulously-Optimized/fabulously-optimized#477]
### Describe the bug

my armor and other entities are  ugly transparent
here is screenshot: https://ibb.co/6bByN9g

### Modpack version

1.19.2

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

![2022-09-18_15 21 09](https://user-images.githubusercontent.com/98276694/190926884-df999d4f-d652-456d-9cf8-e45263e9d169.png)

**Comment by Madis0** [comment]
You seem to be using resource packs, so have a look at https://fabulously-optimized.gitbook.io/modpack/readme/resource-pack-issues

If that doesn't help, send latest.log from the instance folder.

**Comment by timget** [comment]
> You seem to be using resource packs, so have a look at https://fabulously-optimized.gitbook.io/modpack/readme/resource-pack-issues
> 
> If that doesn't help, send latest.log from the instance folder.

I used only built in resoursepacks.. but I tried to turn them off, but that didn't help.
 Here is latest.log
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9603238/latest.log)

**Comment by Madis0** [comment]
tlskincape seems to be the issue, try disabling that.

**Comment by timget** [comment]
it helped, sorry, almost forgot about that mod :)
