### ISSUE TITLE
CEM's first-launch crash

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#478]
### Describe the bug

Sometimes there is a crash on the first launch, never on the second. I assume it is because some mod doesn't like YOSBR, but the exact cause is currently unknown.

![image](https://user-images.githubusercontent.com/8611110/191085259-0d2cf25b-cd8d-46e7-8456-0135405f4a1a.png)

### Modpack version

4.3.3

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

https://mclo.gs/s8xLdWw

**Comment by osfanbuff63** [comment]
ARRP is included in Enhanced Block Entities, so that's likely the mod in question...does it use YOSBR right now?

**Comment by isXander** [comment]
This seems like Fabric Loader itself, I have problems with this bug myself that seem to be random. If it crashes like this, I have a 50% chance it will work on next launch attempt.

**Comment by Madis0** [comment]
> This seems like Fabric Loader itself, I have problems with this bug myself that seem to be random. If it crashes like this, I have a 50% chance it will work on next launch attempt.

Interesting. I doubt it is reproducible with 0 mods or only fapi though.

**Comment by Madis0** [comment]
It was suggested that this could be fixed by explicitly including CompleteConfig, but that didn't fix it for me: https://mclo.gs/9TXelmZ

**Comment by Madis0** [comment]
I think it is already resolved as of 4.6.0-alpha.6.

**Comment by Madis0** [comment]
In 1.19.3 there actually seems to be a different error but a similar cause and workaround. Reported as https://github.com/dorianpb/cem/issues/106
