### ISSUE TITLE
DashLoader

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#48]
**Mod name**
DashLoader

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/dashloader

**Modrinth link**

**Other link**
https://github.com/alphaqu/DashLoader

**What it does**
Makes Minecraft startup faster

**Why should it be in the modpack**
Minecraft startup in 4 seconds! https://discord.com/channels/507304429255393322/725837054092771368/832646722287042580

**Why shouldn't it be in the modpack**
May cause incompatibilities with some mods, including Hydrogen

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

In initial testing it certainly isn't 4 seconds, maybe even slower than comparable mods
Edit: now in CF, needs retesting
Edit 2: apparently it needs newer Sodium

**Comment by Madis0** [comment]
Tested in FO 2.0.0b2 using Curseforge Launcher and it offers absolutely no benefit as it recreates the cache on every launch. 
I don't know if any of the current mods are to blame - well, there is not even Sodium yet - but this just doesn't suit this pack as far as I see.

**Comment by Madis0** [comment]
Now has a fallback system that "supports 90% of the mods". https://www.curseforge.com/minecraft/mc-mods/dashloader/files/3538640

Not for 1.18 yet and have not tested that version but could be worth reconsidering.

**Comment by Madis0** [comment]
Tested on personal profile (similar to FO) and it loaded faster indeed, but crashed instantly on any world/server join.
Maybe next major version...

**Comment by Madis0** [comment]
More counter-arguments:
> 3.0.0 was a major rewrite, yet 3.0.1 was still created to "fix everything". Don't know what it means code-wise, but again it doesn't instill confidence.

By Emma (paraphrased):
> Enhanced Block Textures now has DashLoader compat, but it cannot be used together with LambaBetterGrass. When the three mods are used, every chest faces North

**Comment by MicrocontrollersDev** [comment]
> Enhanced Block Textures now has DashLoader compat, but it cannot be used together with LambaBetterGrass. When the three mods are used, every chest faces north.

This appears to be fixed in the latest DashLoader version, I have no issue using the three mods together. Alpha on discord has also confirmed he fixed the issue.

**Comment by OmriOn** [comment]
I have found that DashLoader improves load times by a lot (At least on my laptop) and I think it should be in the mod pack.

**Comment by Madis0** [comment]
> I have found that DashLoader improves load times by a lot (At least on my laptop) and I think it should be in the mod pack.

Could you make video comparisons?

**Comment by OmriOn** [comment]
> > I have found that DashLoader improves load times by a lot (At least on my laptop) and I think it should be in the mod pack.
> 
> Could you make video comparisons?

How do I upload a video on Github?

**Comment by Madis0** [comment]
Drag the file to comment box or upload to a hosting service like YouTube.

**Comment by code004Accepted** [comment]
On my device, the difference of loading time was approximately 4~5 seconds. 

https://user-images.githubusercontent.com/36566134/206906908-c7efa220-060c-40db-a75b-521ad49626ad.mp4

This mod can be considered but it doesn't bring a huge performance, at least on my side.

(Note: I have started the game with the mod before recording, thus the mod had already cached)

**Comment by TheBossMagnus** [comment]
In my case -3/4s with lazydfu and around 20 mods. But cause some incompatibility/log warning
