### ISSUE TITLE
Invisible Mobs

### ISSUE THREAD

**Issue by Jack1424** [Fabulously-Optimized/fabulously-optimized#481]
### Describe the bug

I recently updated Fabulously Optimized from a 1.19 version (I can't launch the game, so IDK the exact version number) to version 4.3.3 on 1.19.2. Before updating, my game ran great. I used a few extra mods and ComplementaryShaders, and the game ran without any issues. I took a break from playing for a while, and when I returned, I realized that I was still running on 1.19 and wanted to update to 1.19.2. I followed the usual installation instructions and installed Fabulously Optimized version 4.3.3 (auto update) in MultiMC. 

I moved my additional mods and their configuration files over and updated ComplementaryShaders to the latest version. Once again, everything worked great, except for the fact that when shaders were enabled (and only when shaders were enabled), all mobs would go invisible after a few seconds. I moved to a non-auto-update version of Fabulously Optimized with no additional mods in a new and separate instance, and the issue still occurred. I thought that this was just a problem with ComplementaryShaders, so I asked for support on their Discord server. They asked me to test if the problem occurred with other shader packs, so I tested running BSL shaders (again in the "vanilla" FO instance). After enabling BSL shaders, the game crashed whenever I tried to create a new world. I tried launching with BSL shaders disabled and had the same problem. I now cannot launch any instance of an FO mod pack that I have on MultiMC (even the 1.19 version that worked perfectly before). Other instances in MultiMC launch fine.

### Modpack version

4.3.3

### Launcher

MultiMC

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Log (ComplementaryShaders, pre BSL test, no crash just invisible mobs): https://mclo.gs/zuwfkz4

Log (BSL Shaders): https://mclo.gs/G5hGi7T
Crash report (BSL Shaders): https://mclo.gs/CJIG9oB

Log (1.19 MultiMC instance, post BSL test): https://mclo.gs/2x1i1ku
Crash report (1.19 MultiMC instance, post BSL test): https://mclo.gs/eNbOnYJ

**Comment by timget** [comment]
same

**Comment by timget** [comment]
lol my mobs an
![190926884-df999d4f-d652-456d-9cf8-e45263e9d169](https://user-images.githubusercontent.com/98276694/191161864-0e53a6f3-b067-4928-9d9c-fc4f329b9798.png)
d cape are transparent when I updated fabulously (WHYY??)

**Comment by Jack1424** [comment]
For me, the mobs weren't transparent, they were completely invisible. I could only see their shadows and death particles.

**Comment by Madis0** [comment]
Try disabling the mod Entity Texture Features.

**Comment by Traben-0** [comment]
the crashes both have something to do with biome multi noise with the same issue IllegalArgumentException: SubTree needs at least one child, so the crashes are not an ETF issue, the invisible entities may be ETF related but I havent replicated it myself yet

**Comment by Madis0** [comment]
Wait a minute... why are you using 1.19 instead of 1.19.2, @Jack1424? Please update to the latest 1.19.2 version and if you _need_ 1.19, [read this](https://fabulously-optimized.gitbook.io/modpack/readme/chat-reporting-faq#alternative-approaches).

**Comment by Jack1424** [comment]
I tried to create a new instance on 1.19.2 and these issues began.

**Comment by Madis0** [comment]
If it's a separate issue, then it needs a separate bug report... 

In any case I don't care about 1.19 bugs because I've made it very clear that it is no longer supported. So just [move your mods and worlds over](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions) and use 1.19.2.

Did you try disabling ETF on 1.19? Does the issue occur without shaders?

**Comment by Jack1424** [comment]
I just imported a new instance of 1.19.2 auto-update FO in MultiMC. The game launches but then crashes when I click on Singleplayer.

Log: https://mclo.gs/N1PNXSY
Crash Log: https://mclo.gs/6bkh4qs
