### ISSUE TITLE
Mod Settings for Fabric

### ISSUE THREAD

**Issue by Thanos1716** [Fabulously-Optimized/fabulously-optimized#483]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/mod-settings

### CurseForge Mod Distribution

Edit: Allowed

### Modrinth link

https://modrinth.com/mod/mod-settings

### Source/other link

https://github.com/magicus/modsettings

### Mod file size

38.56 KB

### License

(any other license)

### What it does

Adds main menu and pause menu button that integrates well with Mod Menu (I suggest changing the `mods_button_style` config option to `classic` if the button is included), and a configurable hotkey (F12 by default), all to access a global mod settings menu.
I am aware that Puzzle could do a better job of this in the long run (in terms of global settings), but as of now, Puzzle is missing integration with a lot of mods, so it is difficult for new users to find general settings. Things like Capes, NoChatReports and Fabrishot settings are difficult to find as they have to look for the mod in Mod Settings and then find the small config button in the top right, even if Puzzle is enabled.

### Why should it be in the modpack

It allows users to manage all of the configs for all mods at once, is easier to access than default Mod Menu settings, and feels no more modded than Mod Menu itself.
Uses the Mod Menu API to request configs, so has _very_ good mod compatibility.

### Why shouldn't it be in the modpack

There is no mod search, and since there is no config file for this mod, the mods are permanently ordered alphabetically, and there is no option to hide mods or any other configuration options.

### Additional details

Personally I find this mod very useful, but I see why it might not line up with the principles quite right.
An ideal solution would be if Puzzle integrated something similar to this into itself.

**Comment by Madis0** [comment]
Quoting myself from elsewhere:
> I've thought of it
but it doesn't describe the mods, so you wouldn't know what each mod does anyway
> plus there is no way to hide stuff, e.g. you can see cloth config and malilib there

plus indeed, it lacks search. 
Some mods are customizable without a config GUI (e.g. config file or elsewhere) and many mods don't need to be configured by most users at all. 

So I'd say that Mod Menu + FO's Mod Menu Helper still provide a better experience.
