### ISSUE TITLE
Enable MC-577 in Debugify

### ISSUE THREAD

**Issue by isXander** [Fabulously-Optimized/fabulously-optimized#484]
### What config to change

Enable bug fix [MC-577](https://bugs.mojang.com/browse/MC-577) in Debugify.

This bug fixes the issue where players could not drop items or close inventory while in the inventory if their keybinds were bound to mouse buttons.

### Why should it be changed

I wouldn't think it to be uncommon that someone would want to utilise a gaming mouse's side buttons to execute these common actions, and the fact this bug has been around for so long is concerning.

### Additional details

This is a clone of the forum post in FO discord for tracking purposes.

**Comment by RaptaG** [comment]
I support this idea since I use mouse buttons for my inventory.

**Comment by Madis0** [comment]
Low interest, not necessarily forgotten
