### ISSUE TITLE
Custom Entity Models YoungSoulluoS Fork

### ISSUE THREAD

**Issue by Thanos1716** [Fabulously-Optimized/fabulously-optimized#498]
### CurseForge link

none

### Modrinth link

none

### Source/other link

https://github.com/YoungSoulluoS/cemFork

### Mod file size

1.11 MB

### License

(any other license)

### What it does

This is simply a fork of [Custom Entity Models (but for Fabric)](https://www.curseforge.com/minecraft/mc-mods/custom-entity-models-cem) and I thought I'd put it here since the original has not been updated for a while

### Why should it be in the modpack

It is more up-to-date than the original, including CEM support for new mobs and fixing other ones, as well as having a fully compatible (from my testing) fork of the now very popular [Fresh Animations by FreshLX](https://www.curseforge.com/minecraft/texture-packs/fresh-animations/) Optifine resourcepack [(Fabric fork by YoungSoulluoS)](https://github.com/YoungSoulluoS/Fresh-Animations-CEM-fork), which is obviously not as ideal as the original FA working (most mobs turn invisible with it), but is definitely ahead of the original CEM for Fabric

### Why shouldn't it be in the modpack

- It has nothing but the original CEM for Fabric Curseforge and Modrinth links at time of writing, so may be difficult to include in a modpack
- Its a fork and comes with those issues

### Additional details

Putting this here for now as it would provide better Optifine resources support, however naturally it comes with all the issues of a fork

**Comment by Madis0** [comment]
Interesting. I guess I could keep this issue open for reference, but I am actually expecting [ETF](https://github.com/Traben-0/Entity_Texture_Features) to implement a better support for this because he is also working on the feature.

**Comment by RaptaG** [comment]
> Interesting. I guess I could keep this issue open for reference, but I am actually expecting [ETF](https://github.com/Traben-0/Entity_Texture_Features) to implement a better support for this because he is also working on the feature.

So maybe close this issue?
