### ISSUE TITLE
Neutral chat icons

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#499]
**Can Fabulously Optimized reflect the chat state in a more neutral way, while still being more informative than vanilla?**

- Disable vanilla's chat icons and keep No Chat Reports' - current state; works, but is biased towards chat reporting being bad
- Disable vanilla's and No Chat Reports' chat icons - no clutter, but users may think that chat reporting is enabled everywhere or nowhere
- Disable No Chat Reports' chat icons and keep vanilla's - no awareness, users may get misled by the vanilla's unsigned chat icons
- **Disable vanilla's chat icons, retexture No Chat Reports' ones - currently considered**
- Disable No Chat Reports itself - no awareness + loss of privacy by signing messages where not required + annoying toast
- More ideas?

---

As of Minecraft 1.19.2, these are the chat indicators:

- ![](https://i.ibb.co/ftRMqHL/exclamation.png) is displayed for unmodified, unsigned chat (e.g. vanilla servers); the bar on the left is red
   - Tooltip: `This message is not secure, which means that it might have been modified by the server`
   - As of 1.19.3, this icon is removed, the bar on the left is gray and the tooltip is `Unverified message. Cannot be reported.`
- A toast might appear if the server allows unsigned chat:
```
"Chat messages can't be verified"

Messages sent on this server may be
modified and might not reflect the
original message
```
- Gray bars are displayed for system messages, or all messages in servers that disable chat reporting 

Pros:

- Consistency - that's what everyone sees nowadays

Cons:

- Users cannot know, which servers enforce chat reporting
- Users see unsigned messages as "bad" (until 1.19.3)
- Users don't know that chat reporting is a thing in the first place (until 1.19.3... if they hover)
- Users don't know the risks of chatting with chat reporting
- Users do not know about Realms' chat surveillance
- Users don't know what the "can't be verified" message means
- Users don't know why in some servers chats cannot be reported even if they don't see the toast

---

As of No Chat Reports 1.13.9, these are the chat indicators:

- ![red ⚠️ with two exclamation marks](https://i.ibb.co/WcVggrL/chat-status-icons-extended.png) - only on Realms: chat is constantly monitored by Mojang and can be reported
- ![red ⚠️](https://i.ibb.co/tzd8CvB/red.png) - any sent chat messages can be reported
- ![yellow ℹ️](https://i.ibb.co/YXQdJRr/yellow.png) - chat signing is not enforced, NCR users' (incl. FO users') chats are not signed while vanilla clients' may be (depending on the server)  
- ![green ✅](https://i.ibb.co/LPXNKRM/green.png) - chat signing is disabled for all parties

Pros:

- Users can know whether chat reports exist in the server
- Users can know what the effects of chat reports are
- Users can know about the chat surveillance of Realms
- The "can't be verified" toast is removed
- The "message is not secure" icon is removed

Cons:

- Icons and communication are biased towards the chat reporting being bad
- ~~The green state is rarely shown, so yellow is mostly misleading~~ (fixed in 1.19.3)
- ~~Users may not understand, why their messages are displayed differently to others in vanilla servers~~ (fixed in 1.19.3)

**Comment by cafestifflered** [comment]
I was going to comment on the other issue, but you closed it (understandable). All I want to contribute here is that I appreciate you hearing my concerns. The icons are a symptom of the bigger issue for me, which is the attachment of FO with the controversial and opinionated No Chat Reports mod and, by association, the #saveminecraft movement which has caused some server owners and content creators to be harassed.

A mod that implemented the fantastic transparency and privacy features that align with your goals, which you described in the other thread, but is not NCR, is completely acceptable to me if that change was ever made.

Thanks again for hearing me out

**Comment by Madis0** [comment]
> The icons are a symptom of the bigger issue for me, which is the attachment of FO with the controversial and opinionated No Chat Reports mod and, by association, the #saveminecraft movement which has caused some server owners and content creators to be harassed.

Well, that just sounds very political, doesn't it? 
I have no interest in #saveminecraft, I made no mention of it in the Chat Reporting FAQ and I do not endorse anyone to take part of it.

NCR, on the other hand, is the first and most popular mod for influencing this Mojang-added feature towards the better. So that's exactly what I want to do, use its features to FO users' advantage. I don't see why I should swap the mod just for the sake of politics?

**Comment by cafestifflered** [comment]
Of course. It's definitely political, but that's the nature of the topic and the mod, which is at the core of my concern.

Finding a way to utilize NCR without having some opinionated or political statement connected will be difficult, but I understand why you're doing it. It wouldn't be possible to swap the mod, anyway, because I don't know of any other that exists right now.

At the end of the day I wholesale wish NCR didn't need to be included, but that's a matter of opinion, and at minimum I can still applaud your effort to create this actionable item to adjust it to be more aligned with your neutrality principle.

**Comment by Madis0** [comment]
Here's a first draft of simplified tooltips:

```
"gui.nochatreports.status_secure": "Everyone's chat messages cannot be reported to Mojang.",
"gui.nochatreports.status_unintrusive": "Your chat messages cannot be reported to Mojang, others' messages might be.",
"gui.nochatreports.status_insecure": "Everyone's chat messages can be reported to Mojang.",
"gui.nochatreports.status_realms": "Everyone's chat messages can be reported to Mojang, and Mojang is passively monitoring for potential offenses.",
"gui.nochatreports.status_insecure_whitelist_all_servers": "Everyone's chat messages can be reported to Mojang.",
```

[(original ones can be found here)](https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.2-Fabric/src/main/resources/assets/nochatreports/lang/en_us.json#L6)

The icons could perhaps be a play on the Mojang logo "M":
* Realms: M + camera or eyes
* Insecure: M
* Unintrusive: crossed M
* Secure: crossed M

In any case, I wouldn't release this change before the release of 1.19.3, because they are changing some chat icons already.

**Comment by Julienraptor01** [comment]
> 

i think think the oversimplified tooltips are barely ok, but "it's fine"
but i'm totally against the icon chnage since it wouldn't really inform the user, they wouldn't really mean anything anymore

**Comment by cafestifflered** [comment]
You could go with a chat bubble icon instead of a Mojang logo? This would give a clear indicator as to what the icon is referring to while still utilizing "crossed or grayed out" and "camera or eyes"

**Comment by Madis0** [comment]
But chat reporting is not chat itself, that can get confusing.

**Comment by mrfloris** [comment]
From an accessibility point of view, the washed colors against a tiny but grey background, I can't quickly identify what is what unless I take the time to learn about it. The existing icons are fine, and display accurately the state of the chat msg (modified or not), swapping things around just for the sake of 'but I want it that way', isn't helping either. It just adds additional confusion for visual aid as it is then different on one server over the other.

Please review a few accessibility standards so you can maybe get some influence about being (more) inclusive. 

Sidenote; saying "mojang is monitoring" is just a false statement. The community members review what they find offensive and can report this, mojang then reviews that report. A huge difference. Posting such tooltips is a political banner/protest and is more misleading than what this plugin's intentions are trying to seemingly 'fix'.

**Comment by Madis0** [comment]
> From an accessibility point of view, the washed colors against a tiny but grey background, I can't quickly identify what is what unless I take the time to learn about it. 

I don't understand. You identify them quickly because they are _three distinct shapes_ above that gray background. 
Besides, that icon is on the right bottom corner and appears as soon as you toggle chat textbox, while vanilla ones appear on each text row as soon as you hover them. 

> The existing icons are fine, and display accurately the state of the chat msg (modified or not), swapping things around just for the sake of 'but I want it that way', isn't helping either.

Some servers show ![](https://camo.githubusercontent.com/b30d41b0ae7f55eb61bbce78d0b1e9f62a47a2e0d2ff2dd39464cf670c0bfbb8/68747470733a2f2f692e6962622e636f2f6674524d71484c2f6578636c616d6174696f6e2e706e67) next to chat messages, some do not. Some servers have the toast warning, some do not. How is that consistent?

> It just adds additional confusion for visual aid as it is then different on one server over the other.

Huh? When one server forces chat reporting and the other doesn't, of course the icons should be different.

> Sidenote; saying "mojang is monitoring" is just a false statement. The community members review what they find offensive and can report this, mojang then reviews that report. A huge difference. Posting such tooltips is a political banner/protest and is more misleading than what this plugin's intentions are trying to seemingly 'fix'.

It is not false for Realms.
https://help.minecraft.net/hc/en-us/articles/8047895358605-Our-Commitment-to-Player-Safety#h_01G95X76WR1PM97XBXDE7G25KE
> For Bedrock and Java Realms as well as partnered Bedrock servers, we leverage an automated proactive chat filtering system.
> 
> We use it to classify, filter, and escalate online harms for human review and moderation to promote safe and welcoming interactions on Minecraft games. That includes behaviors such as harassment, abuse, and hate speech.

**Comment by mrfloris** [comment]
That you can see them is great for you - if it wasn't a visual issue for someone like me, I wouldn't even have mentioned it. I am not going to defend this point obviously, I don't have to defend my disabilities. If you believe that this is an improvement to those who a disability then that's on you, by all means, continue and ignore the courtesy feedback.

**Comment by Madis0** [comment]
> That you can see them is great for you - if it wasn't a visual issue for someone like me, I wouldn't even have mentioned it. I am not going to defend this point obviously, I don't have to defend my disabilities. If you believe that this is an improvement to those who a disability then that's on you, by all means, continue and ignore the courtesy feedback.

Nope, your feedback has been acknowledged and forwarded upstream. My confusion was due to your wording, as these icons you commented on were not proposed but actually live on NCR (and therefore FO).

So if we decide to change icons, we can indeed make them more accessible as well.

**Comment by Madis0** [comment]
> The icons could perhaps be a play on the Mojang logo "M":
> 
> Realms: M + camera or eyes
> Insecure: M
> Unintrusive: crossed or grayed out M
> Secure: crossed or grayed out M

On that idea, a police badge icon seems suitable. I recall that being used in some websites for "authority" and "content reporting", at the same time it is less opinionated than :warning: or ✅.

Example icon:
<img src="https://clipartcraft.com/images600_/police-badge-clipart-transparent-background-5.png" alt="drawing" width="200"/>
Of course FO would use something more pixelated and vanilla-like. 
Graphics designers are free to contribute here, otherwise I'll just make something for this later. [Original icons](https://github.com/Aizistral-Studios/No-Chat-Reports/blob/1.19.2-Fabric/src/main/resources/assets/nochatreports/textures/gui/chat_status_icons_extended.png)

So the idea is:

- Realms: police badge with eye instead of the star
- Insecure: police badge
- Unintrusive: crossed or grayed out police badge
- Secure: crossed or grayed out police badge

**Comment by osfanbuff63** [comment]
> And of course, all of this will just be a bundled resource pack you can freely opt into or out from at any time.

Just to clarify, this is separate from Mod Menu Helper? If not, IMO it probably should be, so you can get the Mod Menu features with or without these icons.

**Comment by Madis0** [comment]
Yes, it will be separate.

**Comment by Madis0** [comment]
Initial RP start on #501. Still needs improved wording and testing

**Comment by Avenred** [comment]
maybe a whistle instead of a police badge? or possibly a 'flag' as that's often used as an icon for reporting. I think they're easier to tell apart as a small icon as compared to a police badge

**Comment by Madis0** [comment]
> maybe a whistle instead of a police badge? or possibly a 'flag' as that's often used as an icon for reporting. I think they're easier to tell apart as a small icon as compared to a police badge

I thought about it, but both flag and whistle seem to be suitable for "call-to-action", not to describe the current state of things. Currently I do not plan to change the "report player" button icon itself.

**Comment by Madis0** [comment]
Here's the planned design:
![chat_status_icons_extended](https://user-images.githubusercontent.com/8611110/202794607-60062d15-802b-4a10-8731-8afe12f991af.png)
Compare that with the original:
![image](https://user-images.githubusercontent.com/8611110/202794797-d14a7323-dcc6-45c5-86da-5f0fcbfb818e.png)

From left to right:

1. Signatures required
2. Signatures force disabled by server
3. Signatures optional
4. Realms (signatures + monitoring required)
5. Unknown status (in 1.19.3, this will be the case for all servers until you chat)
6. Mod error (simplified to unknown status)

If you'd like, you can [download the pack for testing](https://kinolien.github.io/gitzip/?download=https://github.com/Fabulously-Optimized/fabulously-optimized/tree/chat-reporting-helper/Chat%20Reporting%20Helper) right now, **make sure to use 22w46a or newer snapshot**.

**Comment by Madis0** [comment]
Now live on 4.6.0-alpha.1! Feedback still accepted here and translation instructions are here: https://fabulously-optimized.gitbook.io/modpack/readme/language-support#translating-chat-reporting-helper

**Comment by Avenred** [comment]
I have a couple thoughts on the new icons:

1) the grey background against a grey police badge has almost no contrast, making it hard to see:
![image](https://user-images.githubusercontent.com/13921970/208546684-3367f523-28fb-4ebe-8db2-6e9f514e0b9b.png)

2) "some kind of plugin" should be "a plugin"
![image](https://user-images.githubusercontent.com/13921970/208546836-b827ebd0-1ed1-4be8-abc8-a4170cedb73c.png)

3) the icon for "Realms (signatures + monitoring required)" just looks incredibly creepy with that eye. maybe you could replace it with the mojang logo? or, just make the eye look less... weird

4) I'm still not a fan of the police badge shape. it's hard to tell what it's trying to communicate, especially with the low contrast I mentioned above

To be clear, I'm not against changing the default icons. I think that the red triangle makes the server seem dangerous, or that there's something wrong with chat. But, I really don't think that a low contrast police badge is the way to go.

**Comment by Madis0** [comment]
Okay, great that you got it to work!

> Also, "Others' messages may be reportable" might be easier to understand as "Messages sent by other players may be reported to Mojang, unless a plugin is installed on the server.", since it better reflects the original no chat reports message.

Well, per original suggestion of "being too NCR-centric" and because it is vague (players can't usually know which plugins are installed), I wanted to refrain from doing that. 
Instead, it says "Confirm on Social Interactions" as a suggestion on how the player can verify the reportability right away. In the future NCR might have even better logic to determine whether the server disabled reporting for all or not.

**Comment by Madis0** [comment]
![chat_status_icons_extended](https://user-images.githubusercontent.com/8611110/209291085-8f0ba916-e84e-498f-8fba-91ce571476d8.png)
The contrast has been drastically increased in 4.6.0-alpha.10. The eye was replaced with a "recording" icon.
