### ISSUE TITLE
Enhanced Attack Indicator

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#50]
**Mod name**
Enhanced Attack Indicator

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/enhanced-attack-indicator

**Modrinth link**
N/A

**Other link**

**What it does**
Shows attack indicator on more cases, like drawing a bow and breaking a block

**Why should it be in the modpack**
Improves the UX by a small tweak

**Why shouldn't it be in the modpack**
May cause confusion as it behaves slightly differently from vanilla

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

This is waiting on Mojang for the combat update to come out, which will determine whether this mod is even necessary

**Comment by TheMadHau5** [comment]
Can be added, especially if block breaking, eating, and cooldown items are disabled be default. (i.e. the attack indicator while drawing bow/crossbow/trident remains)

**Comment by Madis0** [comment]
Decided to reject this as the combat update is still in somewhere far future and it is unclear if it would be even needed then.

Adding it now would only increase confusion for PvP users who are used to the way the indicator works now.
