### ISSUE TITLE
Better Ping Display

### ISSUE THREAD

**Issue by Michael1297** [Fabulously-Optimized/fabulously-optimized#504]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/better-ping-display-fabric

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/better-ping-display-fabric

### Source/other link

https://github.com/vladmarica/better-ping-display-fabric

### Mod file size

15.89 KB

### License

(any other license)

### What it does

A mod for displaying each player's ping in the player list as a number, with various configuration options.

### Why should it be in the modpack

this is a very useful feature for players on a pvp server

### Why shouldn't it be in the modpack

not vanilla-like

**Comment by osfanbuff63** [comment]
By the way, source is at https://github.com/vladmarica/better-ping-display-fabric.

**Comment by Madis0** [comment]
Why does the exact ping matter? What does the player do with that info?
I've used a similar mod in the past and I always found the ping to be less accurate in Minecraft compared to other multiplayer games.

**Comment by Michael1297** [comment]
The exact ping makes it clear whether the opponent used cheats or it's problems with the Internet or server.

**Comment by Madis0** [comment]
So the target audience is.. who? Server admins? 
I feel like players should just report of any suspicion to admins and admins will do their own checks (including this, if necessary) to determine whether the player needs punishing or not.

**Comment by Michael1297** [comment]
Players on PVP servers and servers with mini-games such as skywars and bedwars and others

**Comment by Madis0** [comment]
Sorry, I still don't see the appeal yet. Users can already see the ping range by the icon, so if the player has 5 full bars and they seem to be cheating, then they could indeed be. 
What would a typical player get from seeing the _precise_ number? I bet most non-technical players don't know what to do with that info.

**Comment by Michael1297** [comment]
I've been playing with this feature for a very long time, and I'm used to using it. I won't insist on adding this mod.
