### ISSUE TITLE
FabricSkyBoxes Interop

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#505]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/fabricskyboxes-interop

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/fabricskyboxes-interop

### Source/other link

https://github.com/FlashyReese/fabricskyboxes-interop
https://discord.com/channels/859124104644788234/1036542544823189505 (in FO Discord)

### Mod file size

41.13 KB

### License

(any other license)

### What it does

Provides OptiFine compatibility to #72 

### Why should it be in the modpack

So we can finally have OptiFine skies support!

### Why shouldn't it be in the modpack

Untested

**Comment by CreepahJacket** [comment]
https://modrinth.com/mod/fabricskyboxes-interop
modrinth link

**Comment by Madis0** [comment]
Added in 4.5.0.
