### ISSUE TITLE
Saturn.

### ISSUE THREAD

**Issue by Jauniu** [Fabulously-Optimized/fabulously-optimized#509]
### Modrinth link

https://modrinth.com/mod/saturn

### Source/other link

https://github.com/AbdElAziz333/Saturn

### Mod file size

20,2 KB

### License

(any other license)

### What it does

Optimizes Minecraft's memory usage. It works on both the client and server, and it doesn't require to be installed on both sides.

### Why should it be in the modpack

The author of this mod AbdElAziz has created some other mods that should improve minecraft performance. I only tested Saturn. For now, seems that it is quite effective and compatible with “Fabulously Optimized” modpack. Decent memory usage reduction and improved smoothness of the game on client side. I think it is worth testing and trying it.

### Why shouldn't it be in the modpack

Not updated on Curseforge. Pretty new, could expect bugs.

### Additional details

I would like for you guys to check other mods of this author “AbdElAziz”. Mods like: 
Smooth Boot (Reloaded): https://modrinth.com/mod/smooth-boot-reloaded
Pluto: https://modrinth.com/mod/pluto
Canary: https://modrinth.com/mod/canary

**Comment by Madis0** [comment]
Saturn is a Forge mod, presumably a fork of MemoryLeakFix #347 which is already in this modpack. Similarly, all other mods you mentioned are Forge ports of Fabric mods that are also on FO.

Only mod by the dev that is not yet included and is for Fabric, is Fastload #365.
