### ISSUE TITLE
Lightingg/Rendering Issue?

### ISSUE THREAD

**Issue by Genious28** [Fabulously-Optimized/fabulously-optimized#510]
### Describe the bug

I didn't Update but created a new Profile/Instance, made a few additional mod changes and setting changes.. But This issue comes up on purely Fabulously Optimised Modpack as well. :/

![Screenshot Recording 2022-11-04 17-51-47](https://user-images.githubusercontent.com/97228026/199978979-eb47e338-fd6a-4a6d-a1e9-c64aed9a0ec4.png)

### Modpack version

4.4.5

### Launcher

MultiMC

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Replaced Zoomify with Camera Utils

Added ReplayMod
Added MaliLib
Added Litematica
Added MiniHUD
Added WorldEdit

**Comment by Genious28** [comment]
Changing Resolution, Render Distance, Fog, etc.. has no effect.
Also, StarLight and Sodium, both are Enabled; Don't they conflict? they're both for Optimising Lighting/Rendering so they should technically conflict if not intentionally made compatible.

**Comment by Madis0** [comment]
Starlight and Sodium do not conflict. 
To me this seems more like disabled mipmaps? Check that setting.

If not, send a screenshot without your extra mods and send the `latest.log`.

**Comment by RaptaG** [comment]
Does this happen without FO?

**Comment by Genious28** [comment]
> Does this happen without FO?

Unfortunately, yes.. Sorry for taking your time.. but do you have any suggestions to fix this?
![2022-11-04_18 12 20](https://user-images.githubusercontent.com/97228026/199980844-a4aa1ebc-d219-4822-bbea-fde704736597.png)

**Comment by Genious28** [comment]
> Starlight and Sodium do not conflict. To me this seems more like disabled mipmaps? Check that setting.
> 
> If not, send a screenshot without your extra mods and send the `latest.log`.

[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/9938526/latest.log)
Logs for Vanilla 1.19.2

**Comment by Madis0** [comment]
Did you try the mipmaps setting?

**Comment by Genious28** [comment]
> Did you try the mipmaps vanilla setting?

it's at 4

**Comment by Genious28** [comment]
setting it at 0 makes it WAYY worse

**Comment by Genious28** [comment]
tried adding Shaders, Complementary Shaders to be exact, still there :(
I'll stop bothering you guys now lol

**Comment by Madis0** [comment]
I guess try asking in Fabric's Discord, maybe they can suggest a mod or fix for you: https://discord.gg/v6v4pMv

**Comment by Genious28** [comment]
> I guess try asking in Fabric's Discord, maybe they can suggest a mod or fix for you: https://discord.gg/v6v4pMv

I don't think it's a mod Issue.. It's probably a driver fault, I messed around with setting about a week ago so i'll try changing them back in Nvidia Control Panel ig.

**Comment by Genious28** [comment]
Yeap, changed Image Settings to 'Let the 3D Application Decide' and that fixed it.
