### ISSUE TITLE
FastQuit

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#519]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/fastquit

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/fastquit

### Source/other link

https://github.com/KingContaria/FastQuit

### Mod file size

21.86 KB

### License

(any other license)

### What it does

Makes leaving a singleplayer world faster, continuing the saving process in the background. Safety precautions are taken to ensure it works even if you try to quit the game etc 

### Why should it be in the modpack

Allows the user to skip the world leaving waiting screen and do something else faster, e.g. joining a server or changing settings. 

### Why shouldn't it be in the modpack

Needs more testing to ensure safety precautions are fine

**Comment by KingContaria** [comment]
file size has increased quit a bit (to ~78KB) mainly because of added icon file and MixinExtras implementation

**Comment by Timolino456** [comment]
Have used this mod for quite some time now. Has worked without any issues so far.
