### ISSUE TITLE
 Advanced Tooltips

### ISSUE THREAD

**Issue by Julienraptor01** [Fabulously-Optimized/fabulously-optimized#521]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/advanced-tooltips

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/advanced-tooltips

### Source/other link

https://github.com/ReviversMC/advanced-tooltips

### Mod file size

145 KB

### License

(any other license)

### What it does

Well inspecio #66 but fabric

### Why should it be in the modpack

Enhance tooltips, provide more informations to inform the player

### Why shouldn't it be in the modpack

For same reasons similar mods are not currently in FO i guess ?

### Additional details

Since #2, #317, #342 are tracked and opened here i tought it was a good idea to complete the set

**Comment by Madis0** [comment]
https://github.com/Fabulously-Optimized/fabulously-optimized/issues/2 and https://github.com/Fabulously-Optimized/fabulously-optimized/issues/317 were rejected, so this makes sense to close as well. Besides - abandonware :stuck_out_tongue:
