### ISSUE TITLE
Translation platform

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#526]
The content that can be translated is increasing:

- Mod Menu Helper
- Listing description
- Wiki (currently only German has a complete translation, Russian tried but scrapped due to the amount of content)
- Chat Reporting Helper #499 
- Vanilla Installer #110 
- Website, whenever that comes

Therefore, it might be a wise idea to consider a translation platform, such as Crowdin, Transifex or Weblate.

My personal preference by a wide margin is Crowdin, and it has both a [free](https://crowdin.com/pricing#crowdin-pricing-key-features) and a [FOSS](https://crowdin.com/page/open-source-project-setup-request) plan.

However, there are some concerns with it:

- Mod Menu Helper has strict width constraints. [There is now a tool](https://fabulously-optimized.github.io/Mod-Menu-Helper-Size-Checker/), but a translation platform would not take advantage of it. I could apply a character limit, but that would also apply for two rows at once, which renders it widely inefficient...
- Listing description has no automation (which can be both good and bad though), so I'd still update it once in a while
- Proofreaders are needed to ensure quality, there may be some potential of spam

**Comment by osfanbuff63** [comment]
> Vanilla Installer

note: not implemented yet, but it's on the roadmap: https://github.com/Fabulously-Optimized/vanilla-installer/issues/43

But it's safe to assume that it will be implemented at some point down the road. (I think that will our next project once we've released a version lol)

**Comment by Madis0** [comment]
Now that I think of it... Maybe it's better to abandon wiki translations altogether.

* They get outdated very fast
* They are too massive to have actual translation interest
* They are hard to proofread to know if they are still up to date
* They probably weren't viewed by many users anyway
* Users are more likely to view listing translations

**Comment by andrii-bodnar** [comment]
Would be happy to help with the Crowdin integration 🙂 

The localization process could be automated via native [Crowdin GitHub connector](https://store.crowdin.com/github) or via the [Crowdin GH Action](https://github.com/marketplace/actions/crowdin-action).

Also, it should be easy to convert the "Mod Menu Helper Size Checker" into a [Crowdin App](https://developer.crowdin.com/crowdin-apps-about/). This app can implement the [Editor Panel Module](https://developer.crowdin.com/crowdin-apps-module-editor-right-panel/), listen [events](https://developer.crowdin.com/crowdin-apps-js/#event-module-actions) and update the Size Checker input to validate text rendering. So translators will see the actual result during the translation process.

There is a good example of the Crowdin Editor app - [ICU Message Format Helper](https://github.com/Martin005/crowdin-icu-helper)

**Comment by Madis0** [comment]
Well, at the moment I've signed up for it and it is connected, but not all existing translations were imported for the listing description, which I'm not sure how to fix yet.

> Also, it should be easy to convert the "Mod Menu Helper Size Checker" into a [Crowdin App](https://developer.crowdin.com/crowdin-apps-about/).

Are you willing to PR the necessary changes to allow that? It is definitely something I'd be interested in.

**Comment by andrii-bodnar** [comment]
> not all existing translations were imported for the listing description

Could you please provide more details about that?

**Comment by Madis0** [comment]
Well...
![Screenshot_20221201-121042_Berry Browser](https://user-images.githubusercontent.com/8611110/205026165-806d29a6-0533-4cea-866e-0322f80ce786.png)

[While it clearly is translated.](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/Description/et-EE.md)

I read that they use machine learning or something for formats that are not strict (html, md etc) but I'm not sure how can I help it detect it better.

**Comment by andrii-bodnar** [comment]
Yes, it's using an ML algorithm to match translations. Probably, in this case, it wasn't able to recognize some translations

There is a Crowdin app that helps in such cases - [Document Aligner](https://store.crowdin.com/aligner)

**Comment by Madis0** [comment]
> There is a Crowdin app that helps in such cases - [Document Aligner](https://store.crowdin.com/aligner)

Tried that out but apparently "FOSS account" (which I requested) owners can only create approved FOSS projects😅 So because this uses temporary projects, it doesn't work for me unless I create a new account.

**Comment by Madis0** [comment]
Working towards implementing this soon.

**Comment by Madis0** [comment]
Done. https://crowdin.com/project/fabulously-optimized
Instructions: https://fabulously-optimized.gitbook.io/modpack/readme/language-support#modpack
