### ISSUE TITLE
Alt-tabbing out of fullscreen displays black screen for a second

### ISSUE THREAD

**Issue by Mintyseer** [Fabulously-Optimized/fabulously-optimized#546]
### Describe the bug

Alt-tabbing out of fullscreen displays a black screen for a second. This is similar to alt-tabbing out of other games from fullscreen when their resolution and refresh rate is not the same as the desktop. However, in this case the second of black screen happens irregardless of what the in-game resolution is, be it Current, the resolution of the desktop, or anything else. Deleting the mod Borderless Mining does nothing.

The game does seem to be using integrated graphics even though I have a dedicated GPU. Not sure if this is related.

### Modpack version

4.6.0-alpha.5

### Launcher

Prism Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
Does _enabling_ Borderless Mining help? As it is not enabled by default, even though it is included.

> The game does seem to be using integrated graphics even though I have a dedicated GPU. Not sure if this is related.

That should be set on your GPU's helper program I believe. As I don't have one, I can't help you with that yet.
