### ISSUE TITLE
Wavey Capes

### ISSUE THREAD

**Issue by Alexciao** [Fabulously-Optimized/fabulously-optimized#560]
### CurseForge Mod Distribution

None

### Modrinth link

https://modrinth.com/mod/wavey-capes

### Source/other link

https://github.com/tr7zw/WaveyCapes

### Mod file size

315.67 KiB

### License

(any other license)

### What it does

Gives various options for animating Minecraft capes.

### Why should it be in the modpack

The mod looks really good visually and gives a nice effect... that's kinda it.

### Why shouldn't it be in the modpack

Doesn't have a lot of downloads, so may have bugs that didn't get found yet.

**Comment by Julienraptor01** [comment]
Well there is this very big problem (i'm a user of the mod and i very much noticed it)

**Comment by Kichura** [comment]
Eleborate by "big problem" please?

**Comment by Julienraptor01** [comment]
> Eleborate by "big problem" please?

I forgot to paste the link but it's updated

**Comment by Kichura** [comment]
Ah the darken cape thing, yeah that's going to end up ugly if it's on this modpack for time being.

**Comment by Madis0** [comment]
The mod enforces a specific not-vanilla-like visual style, so it is out of scope. FO prefers mods that give users vanilla-like visual options or more capabilities to customize (e.g. for resource packs, shader packs).
