### ISSUE TITLE
Let Me Despawn

### ISSUE THREAD

**Issue by Mukul1127** [Fabulously-Optimized/fabulously-optimized#563]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/let-me-despawn

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/lmd

### Source/other link

https://github.com/frikinjay/let-me-despawn

### Mod file size

85.75 KiB

### License

(any other license)

### What it does

Removes mobs even if they pick up an item, they won't despawn only if you name them.

### Why should it be in the modpack

It will improve performance, especially on bigger worlds.

### Why shouldn't it be in the modpack

Hasn't had an update on Github in an while.
Maybe went Closed Source, Might also just be unmaintained?

**Comment by Julienraptor01** [comment]
the problem is it change expected vanilla behavior commonly used

**Comment by Kichura** [comment]
This mod is actually designed for modded fabric servers only and since fabulously optimized goes against this topic since it's actual purpose is mods that optimize + are designed to also work on other servers instead of LAN only, this will be rejected.

**Comment by Mukul1127** [comment]
> This mod is actually designed for modded fabric servers only and since fabulously optimized goes against this topic and because it's actual purpose is mods that optimize + are designed to also work on other servers instead of LAN only, this will be rejected.

I didn't know that, thanks
