### ISSUE TITLE
Very Many Players

### ISSUE THREAD

**Issue by GDMgmer3992** [Fabulously-Optimized/fabulously-optimized#564]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/vmp-fabric

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/vmp-fabric

### Source/other link

https://github.com/RelativityMC/VMP-fabric

### Mod file size

463.33 KB

### License

(any other license)

### What it does

Makes time source to use built-in Java time source instead of GLFW via JNI calls
Uses our own chunk-sending mechanism (optionally with packet-level rate-limiting)
Adds packet-level per-player render distance
Makes vanilla TCP connections more responsive using packet priority from raknetify
Mitigates several kinds of bot attacks with split event loops and optimizations
Uses AsyncAppender to improve logging performance and keep logging IO off the main thread

### Why should it be in the modpack

It Improves A Lot Of Performance And Doesn't Interfere With Vanilla Experiences

### Why shouldn't it be in the modpack

Still in early development and things may break (But It Doesn't)

### Additional details

MIT License
Discord Link : https://discord.gg/Kdy8NM5HW4

**Comment by Madis0** [comment]
Neither singleplayer or LAN have _very many players_, so this mod is just out of scope for the modpack.
