### ISSUE TITLE
Chat Patches (Previously Where's My Chat History?)

### ISSUE THREAD

**Issue by Samisafool** [Fabulously-Optimized/fabulously-optimized#572]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/chatpatches

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/chatpatches

### Source/other link

https://github.com/mrbuilder1961/ChatPatches

### Mod file size

86.21 KiB

### License

(any other license)

### What it does

```
This mod does quite a few things:

    Increases the maximum amount of chat messages to 16,384
    Adds a timestamp in front of all messages, formatted as [HOUR:MINUTE:SECOND] in pink text, with a tooltip that renders a complete date
    Keeps chat history and previously sent messages across ALL worlds and servers
    Lets you modify vanilla player names to anything more appealing than triangle brackets
    Minimize spam by enabling the counter that shows how many duplicate messages have been sent in a row
    Shift the chat hud up by 10 pixels, so it doesn't overlap with the armor bar
    All of this is configurable, with much more to offer!
```

From the page

### Why should it be in the modpack

Can remove MCH since it replaces it
Much better AND configurable

### Why shouldn't it be in the modpack

Defaults aren't ideal/vanilla-like
Tons of extra features (not vanilla-like)
It might break on some servers
Extra dep (YACL)

**Comment by Madis0** [comment]
I remember someone mentioning that this mod had stolen code from others, though I currently cannot verify that. Either way, I can go over features in detail to answer the need:

* Increases the maximum amount of chat messages to 16,384 - #126 
* Adds a timestamp in front of all messages, formatted as `[HOUR:MINUTE:SECOND]` in pink text, with a tooltip that renders a complete date - unwanted feature that changes vanilla expectations
* Keeps chat history and previously sent messages across ALL worlds and servers - very unwanted feature, see #388 
* Lets you modify vanilla player names to anything more appealing than triangle brackets - ...why? again, breaks expectations 
* Minimize spam by enabling the counter that shows how many duplicate messages have been sent in a row - I have heard/experienced that this kind of feature is actually taxing on performance, plus it can be unwanted in various scenarios (e.g. server sending some newlines to highlight a piece of text)
* Shift the chat hud up by 10 pixels, so it doesn't overlap with the armor bar - unwanted, breaks vanilla expectations
* much more to offer! - so, does it have any feature you specifically want in FO?

**Comment by Julienraptor01** [comment]
The thing is yes Chat patches can be useful i some situation but needs to be configured depending on who use it and and on which server they play. 
If you enable all features by default and you join a server like Hypixel your chat will just be extremly cluttered and unorganized since the timestamp feature take a LOT of space by example. 
And well the thing is that FO don't need all these features anyway and the people who want these features should add it themselves.

**Comment by Samisafool** [comment]
> Minimize spam by enabling the counter that shows how many duplicate messages have been sent in a row - I have heard/experienced that this kind of feature is actually taxing on performance, plus it can be unwanted in various scenarios (e.g. server sending some newlines to highlight a piece of text)

How would it be taxing? It just searches the text, it can't be that taxing... I've never seen such claims. Many "fps" clients also have it and nobody complains about those dropping fps when it's enabled. I will ask the mod author to add an option to not have the counter on empty lines or messages not sent by players.

![image](https://user-images.githubusercontent.com/59611020/215334018-02efd077-354e-43b9-9f0a-3bc516d1b1cc.png)

This is the earliest reference of someone saying it has stolen code, and it's you (I realise now that this had already been proposed. I suck at new mod requests lol wtf). I don't think it would be that big a problem since it's open source, and you can just remove it if any licensing issues arise?
