### ISSUE TITLE
Ok Boomer

### ISSUE THREAD

**Issue by RozeFound** [Fabulously-Optimized/fabulously-optimized#577]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/ok-boomer-zoom

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/ok-boomer

### Source/other link

https://github.com/wisp-forest/ok-boomer

### Mod file size

46.92 KiB

### License

(any other license)

### What it does

Alternative to Zoomify

### Why should it be in the modpack

Has less options but more intuitive config
Can zoom into screens (not working for me, have no idea why)
Mouse sensitivity is adaptive to zoom scale

### Why shouldn't it be in the modpack

New dependency (owo-lib)
Doesn't have "zoom" in the name

**Comment by Madis0** [comment]
More intuitive config in what way?
Zooming into screens seems like a novelty, but I am not sure why most people would need it when GUI Scale option is available.
> Mouse sensitivity is adaptive to zoom scale
And Zoomify isn't? I thought it was already

**Comment by RozeFound** [comment]
Well, let's call it "looks better", and not an "intuitive".
Zooming into screens might be useful for GUI elements which are just smaller then others, but I don't think there's any in vanilla... Or to get more detailed look on icons, idk

> And Zoomify isn't? I thought it was already

And no, it isn't, still.

**Comment by Madis0** [comment]
> Well, let's call it "looks better", and not an "intuitive".

Okay... Though as you said Zoomify does have more features overall, so I'd just propose suggestions to improve the options, rather than switching mods. In fact, to some extent I already did: https://github.com/isXander/Zoomify/issues/98

> Zooming into screens might be useful for GUI elements which are just smaller then others, but I don't think there's any in vanilla... Or to get more detailed look on icons, idk

Doesn't seem like an actual, useful use case atm... Visually impaired users have a lot of tools already, including Minecraft's GUI Scale, screen resolution, screen scaling, etc.

> And no, it isn't, still.

Ok, requested. https://github.com/isXander/Zoomify/issues/117

**Comment by RozeFound** [comment]
Well, I feel defeated. I really do want to throw off Zoomify, because I hate it for no reason, but, I guess, I can't do much about it.

**Comment by RozeFound** [comment]
This request is very subjective btw, I've just see an alternative to Zoomify and wanted it to be included so hard, sorry for that.

**Comment by Madis0** [comment]
> Well, I feel defeated. I really do want to throw off Zoomify, because I hate it for no reason, but, I guess, I can't do much about it.
> This request is very subjective btw, I've just see an alternative to Zoomify and wanted it to be included so hard, sorry for that.

Well, if you get any valid reasons why Zoomify is bad, we can discuss removing it and then consider a new mod to replace it. Otherwise, I don't swap mods for no reason because there are lots of criteria to consider (usability, sustainability, size, amount of features etc.).

> Looks like Zoomify actually have relative sensitivity according to it's modrinth page, but this feature isn't in FO for some reason (disabled by default? or just insignificant).

I don't know about that, FO currently does not bundle a config for Zoomify. Ask the developer.

**Comment by Madis0** [comment]
Closed due to lack of good arguments on how this mod is better than the currently included one, Zoomify.

**Comment by RozeFound** [comment]
Actually I'm not gonna give up on this. I've updated the issue and demand reopening the issue

**Comment by Madis0** [comment]
I don't think your new arguments are more compelling...

> More user-friendly settings than Zoomify

In what way?

> Can zoom into screens, may help with accessibility

May, but the user may also just change the GUI scale

> Relative sensitivity actually works unlike Zoomify

Well, it could work in Zoomify if you could explain what it does. In isXander/Zoomify#117, I was not able to explain it nor confirm whether it exists there or not. Maybe do a video comparison?

> Name puts a smile on your face

Not a convincing argument

**Comment by RozeFound** [comment]
> May, but the user may also just change the GUI scale

While this option is objectively not very useful for vanilla, people who use mods with weird GUI scale (like AE2 for example) will say thanks

**Comment by RozeFound** [comment]
Also file size is 20 times less then Zoomify, but to be fair with it's dependency the difference is only about 50kb

**Comment by Madis0** [comment]
One additional thing to note: isn't Ok Boomer a fork of Ok Zoomer? 

And as such:
* is the dev of Ok Zoomer even happy about its existence, considering that she moved to Quilt?
* does not have the same issues Ok Zoomer had, which led to its removal in FO in the first place?

**Comment by RozeFound** [comment]
> isn't Ok Boomer a fork of Ok Zoomer?

No it's not.

And as such:
- Don't know and don't care.
- No, it doesn't.

**Comment by RozeFound** [comment]
Because the author of Zoomify don't understand and don't care about such improvements.

**Comment by ItsProfessional** [comment]
> Because the author of Zoomify don't understand and don't care about such improvements.

Well... nor does the maintainer of FO.
