### ISSUE TITLE
Entity Model Features

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#584]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/entity-model-features/

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/entity-model-features/ (may not be approved yet)

### Source/other link

https://github.com/Traben-0/Entity_Model_Features

### Mod file size

487 kB

### License

(any other license)

### What it does

OptiFine's Custom Entity Models

### Why should it be in the modpack

https://github.com/Fabulously-Optimized/fabulously-optimized/issues/92 has been in alpha for years, this mod is by the creator of #231 so it seems more promising

### Why shouldn't it be in the modpack

CEM might've had some specific features this does not yet, but then again CEM did not work out of the box with many RPs anyway

### Additional details

Notably it is also half the size of CEM at the moment (1.03 MB vs 0.487 MB) which is interesting
Switching the mod would also fix #478

**Comment by Traben-0** [comment]
https://github.com/Traben-0/Entity_Model_Features

https://www.curseforge.com/minecraft/mc-mods/entity-model-features/files
https://modrinth.com/mod/entity-model-features/versions

**Comment by Madis0** [comment]
now available on 4.7.0-beta.3
