### ISSUE TITLE
Mod request - Methane

### ISSUE THREAD

**Issue by amazing-blobfish** [Fabulously-Optimized/fabulously-optimized#594]
### CurseForge link

no link

### CurseForge Mod Distribution

None

### Modrinth link

https://modrinth.com/mod/methane

### Source/other link

https://github.com/AnOpenSauceDev/Methane-mod

### Mod file size

17.19 KB

### License

(any other license)

### What it does

Methane improves performance by removing lightmaps which can be toggled

### Why should it be in the modpack

it can offer a large fps boost while keeping the game "vanilla"

### Why shouldn't it be in the modpack

Methane is ON by default, which can be annoying at times

**Comment by Madis0** [comment]
- Removing fog and lighting is a game-breaking feature, definitely goes against the FO's goal of feeling vanilla. 
- Fog is already very comfortable in Sodium Extra
- I don't consider fullbright exactly a "cheat", but it is also not something I want to deliberately include either, as the game still expects you to use light sources and/or night vision.
