### ISSUE TITLE
"Client Incompatible!" message when launching with java Realms

### ISSUE THREAD

**Issue by bashflow-lab** [Fabulously-Optimized/fabulously-optimized#595]
### Describe the bug

using FO with Java Realms prompts the message - "Your client is not compatible with Realms. Please use the most recent version of Minecraft."
client is updated and able to log in normally. only difference is when using FO with CurseForge to login vs the normal Minecraft client. 

### Modpack version

Fabulously Optimized-4.5.6.zip

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Julienraptor01** [comment]
Well exactly as the version says Realms only support the latest version of Minecraft aka 1.19.3 currently
FO 4.5.6 is Minecraft 1.19.2
You need to either use FO 4.6.0 or to change of server hosting

**Comment by osfanbuff63** [comment]
Realms has updated to 1.19.3 - so you must use the beta version of FO for 1.19.3 (currently 4.6.0-beta.10), because 4.5.6 is for 1.19.2, which Realms no longer supports.

**Comment by Kichura** [comment]
Not an FO issue.
