### ISSUE TITLE
Game crashing on launch

### ISSUE THREAD

**Issue by Deikusa** [Fabulously-Optimized/fabulously-optimized#597]
### Describe the bug

Hi!
Whenever I try to launch the game, it breaks. I haven't added any mods, it's freshly updated, I tried repairing the mod pack, it didn't help. It seems that indium is causing the issue, I tried downgrading the mod, but I causes different errors.
Hope it gets resolved, or my errors are pointed out.
![Zrzut ekranu 2023-03-04 174023](https://user-images.githubusercontent.com/126975164/222918088-0546432a-7b5a-43ff-a3b5-e3f278c20e3f.png)
[crash.txt](https://github.com/Fabulously-Optimized/fabulously-optimized/files/10889168/crash.txt)

### Modpack version

4.6.0-beta.10 for 1.19.3(CurseForge) - (Beta)

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
You seem to be using Inventory Profiles Next 1.6.3, while [the latest is 1.9.2](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4370584). That is probably your issue.

**Comment by Deikusa** [comment]
> You seem to be using Inventory Profiles Next 1.6.3, while [the latest is 1.9.2](https://www.curseforge.com/minecraft/mc-mods/inventory-profiles-next/files/4370584). That is probably your issue.

Sorry for the inconvenience, when updating from 4.5.6 it didn't remove the mod. Now everything is in prefect working order. Thank you
