### ISSUE TITLE
Controlify

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#598]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/controlify

### CurseForge Mod Distribution

None

### Modrinth link

https://modrinth.com/mod/controlify

### Source/other link

https://github.com/isXander/Controlify

### Mod file size

710.29

### License

(any other license)

### What it does

Adds controller support like #330 but instead of forking old code, it's written from scratch for compatibility

### Why should it be in the modpack

Quoted points from the dev:

- Focus of mod compatibility and makes it very easy for other mods to support it well
   - The dev already helped improve compatibility with Iris and promised to help with Sodium Extra
- 4-way button navigation in GUIs
- Slot snapping in containers
- Split-screen play etc

### Why shouldn't it be in the modpack

- The JAR is larger from MidnightControls so it better have the features to justify it
- I don't own a controller so I cannot compare the two personally, only by others' experiences

### Additional details

Suggested by dev himself

**Comment by isXander** [comment]
I would also like to point out that controller compatibility is a lot better than Midnight Controls. Resource packs can add their own additional controller types and textures, along with mappings for joysticks, none of this is hardcoded.

**Comment by isXander** [comment]
Controlify is in a state where I think I'm ready to release coinciding with Minecraft 1.19.4 release.

**Comment by Madis0** [comment]
> I'm sure your clean code is great
but practically your mod is bigger and has less features [than MidnightControls] at the moment 😛
so there are ways to go [before considering it]
