### ISSUE TITLE
Better Fast Grass block in Game Mode Switcher

### ISSUE THREAD

**Issue by notlin4** [Fabulously-Optimized/fabulously-optimized#600]
### Describe the bug

Grass block in creative tab appears as Better Fast Grass resources pack better grass block when Using Game Mode Switcher in Minecraft.
![Game Mode Switcher](https://user-images.githubusercontent.com/121224522/224487320-4a0be209-32f5-40ca-a2ea-430a74ed8568.png)

### Modpack version

4.6.0-beta.11

### Launcher

Minecraft Launcher (vanilla)

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
Well, that's how it appears in every inventory and in-game. I could revert the way it looks in inventories while keeping the in-game look, but I think that would not make any sense, because the in-game look _is_ different.
