### ISSUE TITLE
IMBlocker

### ISSUE THREAD

**Issue by GodGun968** [Fabulously-Optimized/fabulously-optimized#602]
Merged with IMBlocker
The new one is on top
the old one is on the bottom

### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/imblocker
https://www.curseforge.com/minecraft/mc-mods/imblockerfabric

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/imblocker-original
https://modrinth.com/mod/imblocker

### Source/other link

https://github.com/reserveword/IMBlocker
https://github.com/mrjesen/ImBlockerFabric

### Mod file size

~50 KB

### License

GNU GENERAL PUBLIC LICENSE
Apache License 2.0

### What it does

IMBlockerFabric is a mod that It can Hide IME(InputMethod)
when you don't need to input text! 

### Why should it be in the modpack

This mod fixes the typing bug exist in Minecraft which annoying Asian players for a long time
You can now type multi-byte characters in game using Input Methods (tested in windows platform, with Chinese and Japanese)
Support MC from 1.14 to the lastest version
Support Windows & Linux.

### Why shouldn't it be in the modpack

Does not apply to players who do not use the input method, The mod will take up their storage space (but in fact does not take up much)

### Additional details

Great help for players using input methods

**Comment by Madis0** [comment]
Interesting. 
On what condition does the IME appear when it shouldn't? And how would you workaround it without a mod?

**Comment by GodGun968** [comment]
IME should not appear anywhere except where text is required.
If is no this mod, I usually use win+space to switch to the English input method to play the game, and then switch back when I need to input text.
Of course, you can also use shift to temporarily switch to the English input state, but once you sneak etc. , the input method will appear again.
IME showing up when not needed is as annoying as "whether you enable Sticky Keys"

**Comment by GodGun968** [comment]
Are you still there？ I am looking forward to your reply

**Comment by Julienraptor01** [comment]
> Are you still there？ I am looking forward to your reply
> 
> 

GH issues isn't meant as an instant chat, if you want instant chat with us i suggest that you come one our [discord](https://discord.gg/fabulously-optimized-859124104644788234)

**Comment by Madis0** [comment]
Yes. The idea is interesting, I'm not sure if I would add _this mod exactly_ to solve it, but it seems like a real issue people have and therefore something to consider at some point, in some way.

**Comment by Julienraptor01** [comment]
Maybe we could ask @isXander to include it in Debugify and that this patch would be able to auto-toggle if activated based on the user user input

**Comment by GodGun968** [comment]
> Maybe we could ask @isXander to include it in Debugify and that this patch would be able to auto-toggle if activated based on the user user input

seems like a good idea

**Comment by GodGun968** [comment]
> > Are you still there？ I am looking forward to your reply
> 
> GH issues isn't meant as an instant chat, if you want instant chat with us, i suggest that you come in our [discord](https://discord.gg/fabulously-optimized-859124104644788234)

oh Well, at least reply on github can appear in front of me in a timely manner

**Comment by GodGun968** [comment]
> Yes. The idea is interesting, I'm not sure if I would add _this mod exactly_ to solve it, but it seems like a real issue people have and therefore something to consider at some point, in some way.

Having said that, I would also hope to add this mod to the FO

**Comment by Julienraptor01** [comment]
> > Yes. The idea is interesting, I'm not sure if I would add _this mod exactly_ to solve it, but it seems like a real issue people have and therefore something to consider at some point, in some way.
> 
> Having said that, I would also hope to add this mod to the FO
> 
> 

Not that you can add mods to your own instance
https://fabulously-optimized.gitbook.io/modpack/readme/adding-more-mods

**Comment by GodGun968** [comment]
Yes, I know, but it would have saved me some trouble if it had been included in the FO

**Comment by Madis0** [comment]
https://github.com/isXander/Debugify/issues/222

**Comment by GodGun968** [comment]
[another mod](https://www.curseforge.com/minecraft/mc-mods/ingameime/) 
It not only solves this problem but also solves the problem that the input method is not displayed in full screen
But its compatibility is not good

**Comment by Madis0** [comment]
>I don't feel like I could fix this bug myself, it needs a custom native library for linux, and I don't know C++. I also have no way of testing this or fully understand the issue. I feel this is best left a dedicated mod.

- isXander

That is understandable. But to consider FO inclusion, I'd like to have more info.

- Which languages does this help with, besides Chinese Simplified and Traditional?
- Does it work on Windows, Mac and Linux?
- Does it even work on FO 4.7.0? (seeing there was a comment that claimed otherwise about a mod that is in FO)
- More of a cultural question, but if the mods are so important to a many players to speak their language, how come the download counts are only 30k and 80k respectively? Do the others just use Forge or do they just switch it manually?

**Comment by Madis0** [comment]
I've thought long and hard about it and I'm gonna have to say no. I'm sure it's useful to you and people speaking similar languages as you, but it does not have any use for at least 70% of FO users.

**Comment by GodGun968** [comment]
I still want this :)

**Comment by TheBossMagnus** [comment]
> I still want this :)

you can add it manually

**Comment by GodGun968** [comment]
I know, I've done that so many times it's getting a little boring

**Comment by ajs256** [comment]
> I know, I've done that so many times it's getting a little boring

You can make your own modpack that forks FO!
