### ISSUE TITLE
AppleSkin

### ISSUE THREAD

**Issue by Julieisbaka** [Fabulously-Optimized/fabulously-optimized#606]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/appleskin

### CurseForge Mod Distribution

Allowed

### Mod file size

123.45kb

### License

All Rights Reserved / ARR

### What it does

This mod shows you your hunger saturation which is vanilla friendly but very helpful and lag-free.

### Why should it be in the modpack

It should be in the mod pack because it fits the vanilla feel (and thus the feel of the mod pack) but is still beneficial and useful. I, myself use this mod a lot and I would be happy if this would be made into this mod pack.

### Why shouldn't it be in the modpack

no reason it fits perfectly

### Additional details

nope

**Comment by Julienraptor01** [comment]
From discord

**Comment by Madis0** [comment]
As Julien quoted, I don't think AppleSkin is needed at the moment because the concept of saturation and exhaustion is not exactly obvious to everyone; flashing hearts and chicken chunks are also potentially confusing (even if very useful).

**Comment by Julieisbaka** [comment]
ok
