### ISSUE TITLE
Lag when editing settings

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#610]
### Describe the bug

When pressing vanilla menu buttons and sliders (does **not** happen in Mod Menu and Sodium UI) frame rates drop.

### Modpack version

4.7.0-beta.1

### Launcher

Prism Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

It could be a vanilla bug (?)

**Comment by Madis0** [comment]
Sounds like an immediatelyfast thing. Try testing with that mod only.

**Comment by RaptaG** [comment]
With or without it?

**Comment by Madis0** [comment]
With only Fabric and that mod, as the bug may not be FO-specific.

**Comment by RaptaG** [comment]
Aliright

**Comment by RaptaG** [comment]
It's not an IF related issue, since it did not present when running it with only Fabric installed. It could be a mod incompatibility with one the FO mods

**Comment by Madis0** [comment]
Okay. Can you give more examples on where it does and doesn't apply? Does it apply in mod config screens?

**Comment by RaptaG** [comment]
It only applies when using **vanilla** menus, such as pressing buttons and moving sliders in the Accessibility Settings, pressing the Resource Pack button. But to be honest, it could really just be a one-time-present issue just on my end.

**Comment by Madis0** [comment]
Is the issue still present in beta 3 @RaptaG?

**Comment by RaptaG** [comment]
Tested a new instance, it is _not_ present!
