### ISSUE TITLE
EBE Models Optimized

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#616]
### CurseForge link

None

### CurseForge Mod Distribution

None

### Modrinth link

https://modrinth.com/resourcepack/ebe-models-optimizedpack

### Source/other link

https://github.com/7777777-4547/EBE-Models-OptimizedPack

### Mod file size

19.1 KB

### License

(any other license)

### What it does

Applies some more culling and overall improves the EBE optimizations

### Why should it be in the modpack

Better FPS

### Why shouldn't it be in the modpack

Just a resource pack which has already been requested to be added in EBE itself

**Comment by Madis0** [comment]
Considering EBE itself is slow to update and Mojang may update the model stuff more often than not, I have a feeling that including this in FO may cause more trouble than worth. And also CF publishing is a must-have, don't want to deal with their reviews again.

**Comment by Julienraptor01** [comment]
i think someone asked Foundation to directly add it to the mod and it's actually the best thing that could happen since it keep exactly the same behavior

**Comment by RaptaG** [comment]
Implemented in latest EBE
