### ISSUE TITLE
"Substitute missing model parts" in EMF

### ISSUE THREAD

**Issue by TruMiner** [Fabulously-Optimized/fabulously-optimized#618]
In the config of Entity Model Features, I would recommend making "Substitute missing model parts" set to ON by default for Fabulously Optimized, as that option fixes a lot of packs.

(Edited by Madis0 to reflect discussed change)

**Comment by Madis0** [comment]
The mod is already being tested in FO 4.7.0-beta.3.

But I'm curious about
> In the config of the mod, I would recommend making "Substitute missing model parts" set to ON by default for Fabulously Optimized, as that option fixes a lot of packs.

Any examples? Because I thought it would actually be the opposite for packs that reshape mobs in a way they have to remove their limbs, so this would presumably make them uglier.

**Comment by TruMiner** [comment]
For example, the resource pack I use only changes the pig's head in CEM, so the model only has the head. If that feature is left disabled, the body is gone completely. (Same goes for the wings on the chicken in the resource pack)

I think it only substitutes missing parts if the part is not present, so it shouldn't break anything

**Comment by Madis0** [comment]
Can you give me the link to your resource pack?

**Comment by TruMiner** [comment]
https://modrinth.com/resourcepack/justtimms-vanilla-additions

**Comment by TruMiner** [comment]
^ in the resource pack, take a look at the pig and chicken. Without the setting enabled, the chickens have no wings and the pigs have no body or legs. With the setting enabled, the chickens gain their wings back and the pigs gain their body and legs back.

**Comment by Madis0** [comment]
I discussed this with the dev and decided not to enable this by default at the moment because it breaks a high-demand resource pack, but I [will mention it in the wiki](https://github.com/Fabulously-Optimized/wiki/blob/1.19.4/resource-pack-issues.md) as a possible solution.

> As I understand, if a part isn't replaced, OptiFine will use the vanilla one. That option was an attempt to make that work, but I didn't get it 100% so it remains an option for now.
> Eventually I will [figure out] exactly what optifine does and [remove] the option [entirely].
> [...]
> Try it with [Fresh Animations]. A few mobs break, Guardians get double heads. It's very close to but not perfect.

[Source](https://discord.com/channels/950942125225283634/1072123965088223252/1092308414249578546) [(via)](https://discord.com/invite/rURmwrzUcz)
