### ISSUE TITLE
Discord link is invalid

### ISSUE THREAD

**Issue by nsde** [Fabulously-Optimized/fabulously-optimized#622]
### Describe the bug

https://fabulously-optimized.github.io/discord

...redirects to...

https://discord.com/invite/fabulously-optimized-859124104644788234

...which doesn't exist.

Please fix that.

### Modpack version

-

### Launcher

Minecraft Launcher (vanilla)

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Julienraptor01** [comment]
What you say is false ?
The link does actually work

**Comment by osfanbuff63** [comment]
Yeah, I can't seem to reproduce this either. The link exists and opens `#links` in the FO discord.

**Comment by Madis0** [comment]
Link still works. Try opening it in a private/incognito window to see, and ensure your client is up to date.

**Comment by Kichura** [comment]
Cannot reproduce.

**Comment by nsde** [comment]
UPDATE – probably because of the same reason, Discord deleted my account for using too many VPNs/Tempmails :/

**Comment by Julienraptor01** [comment]
> UPDATE – probably because Discord deleted my account & blocked my *actual* IP for using too many VPNs/Tempmails :/

Probably not for VPNs but for temp mails 100%, they tought banning people with temp mails was a good idea to limit throwaway accounts 💀
