### ISSUE TITLE
World Host

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#624]
### CurseForge Mod Distribution

None

### Modrinth link

https://modrinth.com/mod/world-host

### Source/other link

https://github.com/Gaming32/world-host

### Mod file size

1.98 MiB

### License

(any other license)

### What it does

Lets anyone host their singleplayer server to anyone, not just LAN

### Why should it be in the modpack

- Unlike competing mods, it does not require the mod or any software on the receiving client (!!!)
- Integrated seamlessly into LAN button
- NCR is able to convert messages to system ones like LAN
- Geyser aka Bedrock support is planned
- The dev is very reactive to my requests 
- The mod/server seems sustainable

### Why shouldn't it be in the modpack

- Not yet on CF
- Some UX things to smoothen out
- It's big
- May not be compatible with other LAN mods
- Potential privacy/bandwidth concerns (though the UUIDs are very random anyway), so an opt-out toggle would be nice

### Additional details

It also has a friend list, but FO would disable that by default to prevent ecosystem lock-in, and because it is not necessary for primary functions anymore anyway.

**Comment by ZephemusX** [comment]
You should reconsider keeping the friends list, he says that having someone as a friend reduce the ping, maybe is worth it if you are playing with someone far away, I haven't tried yet, but I will let you know, also I don't think it looks bad in the multiplayer menu, looks really "vanilla" to me.

**Comment by Madis0** [comment]
It may reduce the ping, but it also raises expectations of people towards that feature - they may start to request cross-server chat, direct server joining, in-game friendlist, friend list sync and probably a lot more things which may be completely out of scope of that mod. The mod or its server may also disappear at any time, which can make the users mad as they've invested time and network effect towards that; without a friend list most users may not even notice the mod missing or consider it a minor inconvenience.

I want to keep the expectations low and interface simple, so as long as the proxy server exists, I don't see myself enabling the friend list.

**Comment by RaptaG** [comment]
e4mc was added instead of World Host since it was more suitable for FO.
