### ISSUE TITLE
Opt-in LambDynamicLights

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#625]
LambDynamicLights is a mod that provides the "dynamic lights" feature from OptiFine. For example, light is emitted when holding a torch or being on fire. However, due to the way it works - creating fake light blocks in chunks - it harms performance, even though we have Starlight that should optimize the light in chunks. 

Over time I've used approaches to mitigate the issue, including toggling it to "fastest" and disabling entity lighting altogether - may have helped a bit, but the issue is still there. There was also an alternative mod being considered at some point #309, but in testing it didn't bring better performance and is now abandoned anyway.

We need to do something about this. Here are my ideas:

- Keep LambDynamicLights and disable by default from config - hinders discoverability, while still keeping it easily accessible
- Remove the mod and bundle, default-enable a shader instead that mimics the feature* - likely better performance, but potentially less features and such shader may not exist yet anyway
- Keep LambDynamicLight as a disabled mod - aka disabled within the launcher; the last time I tried this, not all launchers behaved correctly so this may not be a good option
- Something else? I do not plan to remove the feature entirely, only change the provider (mod, shader, ...) or presentation (opt-in vs opt-out).

`*` Here I mean an Iris shader that only does dynamic lights _on the held item in your PoV_ and nothing else. This kind of single-feature shader may not exist yet, but I can talk to some shader dev(s) to see if they would be willing to create and maintain that. For candidates, please suggest shaders that exist now, have low performance requirements and include dynamic lighting.

Thoughts?

**Comment by Julienraptor01** [comment]
i agree on disabling by default and finding / making a shader to give an alternative as LDL performance is quite bad from all my tests

**Comment by ccrvincent** [comment]
If going the route of a shader, I would _love_ if entity lighting was also an option, even if disabled by default.  Despite the performance hit I still conditionally turn it on when actively exploring so I can throw a torch down a deep hole to see what's at the bottom.

Which reminds me, I really should look and see if my current shader has that as an option.

**Comment by Madis0** [comment]
> I have to get someone to make the shader, bundle it for people to test and then run a public vote on which one to keep - mod or shader
> (where mod would still be opt-in if kept, but shader might be opt-out)

**Comment by Aquoo** [comment]
I tested Sildur's basic shaders 2.1 fast with some settings that make it only have handheld lightening but it causes more lag than LDL so it shouldn't be considered.

**Comment by Madis0** [comment]
Yeah, so far I haven't found anyone who would be willing to make a shader with this feature only, and I am not considering to include bigger shaders with everything else turned off anyway.

So now the question is - [did FO 4.8.0 changes](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#480-2023-04-20) improve the performance enough or would it still be better to disable the mod? I'd appreciate some testers: 

> Since FO 4.8.0, LambDynamicLights' water check has been disabled for new users, which supposedly improves performance.
> 
> But I want you to confirm that, so please test FO in four ways:
> - With water sensitivity check enabled*
> - With water sensitivity check disabled*
> - With mod turned off from in-game
> - With mod disabled or removed altogether 
> 
> *Other settings should be set as follows:
> 
```
mode = "fastest"
[light_sources]
    block_entities = false
    entities = false
    self = true
    tnt = "simple"
    creeper = "simple"
```
> 
> And testing should be done by holding, throwing light source items near and far from water
