### ISSUE TITLE
Some mods are leaving CurseForge

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#626]
JellySquid and IMS announced that Sodium and Iris will no longer be updated on CurseForge.

https://www.curseforge.com/minecraft/mc-mods/sodium
![image](https://user-images.githubusercontent.com/8611110/232334333-f52d5ceb-6764-4fdb-a536-a6e0412a6257.png)

https://www.curseforge.com/minecraft/mc-mods/irisshaders
![image](https://user-images.githubusercontent.com/8611110/232334354-f90aab57-0bd9-439d-aa63-fe10f55c7844.png)

Edit: Mod Menu

![Screenshot_20230416_114834](https://user-images.githubusercontent.com/8611110/232287616-e600c95b-8c42-4586-a3e0-67ff2693f512.png)
https://www.curseforge.com/minecraft/mc-mods/modmenu

Edit 2: MemoryLeakFix and MoreCulling

![image](https://user-images.githubusercontent.com/8611110/232571286-8092d89b-816a-48b0-b68f-dc83ce9ced8c.png)
https://www.curseforge.com/minecraft/mc-mods/memoryleakfix
![image](https://user-images.githubusercontent.com/8611110/232571409-7af84132-b6dc-467b-bd1f-0fecfa5f33a4.png)
https://www.curseforge.com/minecraft/mc-mods/moreculling

# FAQ

## Why?

Joint announcement of Sodium and Iris:

> Sodium will no longer be updated on CurseForge, due to the continued technical issues with their website, and the immense difficulty in uploading new releases to it.
>
> What happened?
> 
> CurseForge's website continues to have massive technical issues when it comes to project management. We've been hoping for the longest time that something might improve with the situation, but the new site's design is catastrophically broken (with even basic edits to the description not working). The newest development is that they're now prioritizing modpacks that rip off our mod's branding in search results, despite our repeated attempts to report the projects.
> 
> One of the biggest reasons we continued to publish on CurseForge was because of their author's rewards program, which gave us a share of funds from ad revenue on the project page. But over the past few months, the revenue we receive has continued to decline, despite the fact that our monthly downloads have increased steadily month-to-month. Worse yet, Modrinth has introduced their own rewards program which pays out 100% of the ad revenue generated on your page.
> 
> Case in point, we've waited long enough for the situation to improve, and it hasn't. We are not interested in continuing to support the CurseForge platform when objectively superior alternatives exist, which respect both authors and users.

https://discord.com/channels/602796788608401408/1077645005042233374/1096923623106805890 [(via)](https://caffeinemc.net/discord)

https://discord.com/channels/774352792659820594/817181278931517453/1096933398280413214 [(via)](https://discord.gg/jQJnav2jPu)

> Mod Menu for 1.19+ will no longer be available on CurseForge. Get the latest versions of Mod Menu on Modrinth
>
> Why is Mod Menu leaving CurseForge?
The primary reason Mod Menu is leaving CurseForge is because its inability to handle Minecraft versions well. It does not separate breaking versions like 1.19.4, 1.19.3, and 1.19.2 in the sidebar, collapsing all of them under "Minecraft 1.19", causing people to download the wrong versions. Instead of adding a category for 1.19.3 snapshot mods, they added a 1.20-Snapshot version, so now there's a ton of 1.19.3 and 1.19.4 snapshot mods under the 1.20 heading for some reason. I have simply had enough and am going to live a more peaceful life without having to deal with the headaches, issues, and messages this website has caused.
>
> Existing versions of Mod Menu for 1.18.2 and lower will continue to be available on CurseForge, but all 1.19+ releases have been archived and new versions will no longer be uploaded to CurseForge. Use Modrinth instead.
>
> Can I still use Mod Menu in CurseForge modpacks?
> Yes, Mod Menu is licensed under the MIT License, and you are welcome to redistribute Mod Menu's files in your modpack regardless of platform. 

https://discord.com/channels/593960128794066944/725169919599050752/1096972483237781514 [(via)](https://discord.gg/jEGF5fb)

## What about Lithium?

It is not managed by JellySquid so it is up to the current maintainer, 2No2Name. The decision is not known yet.

It is not currently on [CurseForge's allowed list](https://support.curseforge.com/en/support/solutions/articles/9000197913-non-curseforge-mods), nor can it be requested at the moment:
> Mods must NOT already have projects on CurseForge.

## What about other mods?

 ¯\\\_(ツ)_/¯

## How did CurseForge respond?

>Hey everyone,
>
>I wanted to address the recent topic that was raised [...].
>
>We are of course sorry to see some authors unsatisfied and choose a different platform. It is of course each author’s choice to make. We know that there is still work to be done on the platform and the new website, and while we are striving to make progress, we do want to try and focus on the most burning issues and concerns that are brought forth through our ideas portal. 
>
>With that, we would like to address some of the points raised in the posts and during the discussion:
>- Not showing sub-versions(1.19.x…) on the sidebar of the website: We have plans to fix and upgrade a lot of UI/UX of the beta website this year. The side-bar is one of the areas we’ll address. And we’ll take the sub-versions feedback into consideration as we figure out a better way to display files across all games
>- Snapshot versions: We have a 1.19 and a 1.20 snapshot version. Just as tagging any version or mod loader, it is up to the Author to choose how to tag a file.
>- Edits to the description not working: We aren’t really sure what this refers to. There are still some gaps between how the description looks between old and new websites. That is something that we’re actively working and fixing as we go. We aren’t aware of any major issues at this point but as always, feel free to report these on cf-feedback.
>- There’s no prioritization for Modpacks: The case being referenced is when a search query was the exact name match for a project but slightly differs. For “Relevancy” results, exact name hits have a high weight. This is a result of one of the main complaints on the old search in the legacy website never really hitting what you’re searching for. It is definitely not perfect and we are still tweaking it.
>- Branding: This was a dilemma regarding licensing, as Lithium is open-source. Regardless, after reviewing it with the moderation team, it was decided to take it down. We recommend not to use the report on the site for copyright issues as there’s no open communication channel that way, and we recommend to follow the new guidelines here: https://support.curseforge.com/en/support/solutions/articles/9000222335-submitting-a-copyright-claim-on-curseforge.
>- Reward Points - As we commented in the past, industry decline since the last quarter of last year causes revenue issues with anything ad related. This affects the entire platform regardless of increase in download count. We should expect to see things improve after April, as the trend normally goes. We are making several efforts to improve revenue, including tweaking the ad configuration, working with a new sales team and creating new partnerships.
>- Modpacks over Mods - Modpacks of course do not take priority and any comment to that is just speculation. The case here is that the exact name in the search query has a very big weight when searching by relevance, as explained above
>- UI - Source button is live and has been for a while (example: https://beta.curseforge.com/minecraft/mc-mods/emerald-craft-mod). Regarding Light Theme - we are following the long accumulated feedback by the community requesting a darker theme which was the initial focus.
>- Quilt Support - A Quilt tag exists (same as Forge or Fabric). We are not ruling out Quilt support in the client altogether but currently do not support it as only around 1% of files are tagged Quilt.
>- Issues with Allowed External Mods - We are not aware of any issues. If there are any, feel free to report so we can address it.
>- Image Gallery - As we have mentioned, this will be added after the switch. You will be able to choose which images show, in what order, or turn it off completely. 

https://discord.com/channels/900128427150028811/905069615393157150/1097202897860702228 [(via)](https://discord.gg/Q4bB5zE75f)

## What does it mean to Fabulously Optimized?

We've actually been there already: 

* Versions [1.7.0](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#170-2021-03-02) to 1.12.3 included the Modrinth-exclusive [Hydrogen](https://modrinth.com/mod/hydrogen)
* [Some versions](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#210-beta1-2021-07-18) included Sodium when it previously pulled off from CurseForge for a while (due to lost account access; until I happened to discuss the deal with a CF rep and they helped Jelly bring it back)
* Version [2.1.0](https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/CHANGELOG.md#200b4-2021-07-01) added Iris, which bundled Sodium while it wasn't on CurseForge

Both Sodium and Iris are already listed on [CurseForge's allowed list](https://support.curseforge.com/en/support/solutions/articles/9000197913-non-curseforge-mods).

**In the best case scenario it means a short (0-3 day) delay in CurseForge versions of FO, every time these mods update.**

## Explain that best-case scenario a bit more.

1. Fabulously Optimized releases an update
2. The update is "instantly" live on GitHub; _MultiMC (auto-update)_ and _Prism Launcher (Modrinth)_ users can download right away
3. Do one of these mods update in that?
    * No - nothing will change and FO update will get approved within an hour
    * Yes - CF people need to check the new mod jar and the update may take 0 to 3 days to get approved
4. You get an announcement and can download it on _CurseForge Launcher_, _vanilla launcher_

## And in the worst case?

Well, this paragraph can me intepreted in many ways:

> If a specific version of a CurseForge-hosted mod is not on the site, this means the author has chosen not to upload it for some reason. These versions are not allowed to be included in modpacks.

Due to the historical points above, I would interpret it as "versions that are not public", aka Discord-exclusive alpha versions and the like. Because, as said, Sodium _has been_ in FO while it was not hosted in CurseForge any longer.

But if it is indeed the case, well, I'll just talk to the mods and CurseForge to ensure a fair outcome.

## There are new forks of these mods on CurseForge, should I install them?

Fabulously Optimized does not advise installing suspicious forks, especially while the original ones are still maintained. Sharing these links in our community is not allowed either.

Edit: [CF updated its rules](https://medium.com/overwolf/curseforge-guidelines-update-mod-cloning-ban-and-copyright-compliance-9e9398d37c37) and these forks are taken down.

## Could Fabulously Optimized leave CurseForge?

_Not now_ is the official answer. If the leaving trend continues and it is getting hard to keep up, it might, but right now it doesn't seem necessary.
If it would happen, then we'd do all in our power to make the transition smooth.

## Do I have to do anything as a user?

Yes - [some installation instructions have changed](https://github.com/Fabulously-Optimized/wiki/blob/main/install-instructions.md) and you have to familiarize yourself with them.

---

## 2023-06-12 status update

1.20 has arrived and with that, Lithium got also appended to this list. Therefore, as of 5.0.0-alpha.1 there are 5 external mods because More Culling is not up to date yet.

[The malware incident](https://support.curseforge.com/en/support/solutions/articles/9000228509-june-2023-infected-mods-detection-tool/) happened at the same time, which did not affect FO in itself, but postponed the release of its first alpha by a few days due to review delays.

But besides that, things seem to be stable in terms of mod reviews and delays.

**Comment by Madis0** [comment]
The situation seems to be stable now.
- Still only 6 mods (though they are important)
- CF allows all 6 to be included externally
- It is possible to avoid most CF publishing delays with some techniques
- Currently Sodium is uploaded and archived by CF (to fix a disallowed forked mod issue), which makes it technically even easier to include in CF manifest, but harms vanilla users (#627)

**Comment by cinder-block-garry** [comment]
it is back! i think
