### ISSUE TITLE
e4mc

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#628]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/e4mc

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/e4mc

### Source/other link

https://git.skye.vg/me/e4mc_minecraft

### Mod file size

142.08 KiB

### License

(any other license)

### What it does

Lets anyone host their singleplayer server to anyone, not just LAN

### Why should it be in the modpack

- Unlike competing mods, it does not require the mod or any software on the receiving client (!!!)
- Integrated seamlessly into LAN button
- NCR is able to convert messages to system ones like LAN
- Unlike #624, it's smaller and already on CF
- Pronounceable IP in the style of `random-words.eu.e4mc.link`
- Probably compatible with other LAN mods as it affects that screen even less

### Why shouldn't it be in the modpack

- At least one user got constant timeouts with it
- Sustainability questions not yet asked
- Geyser not planned, unlike #624

**Comment by RaptaG** [comment]
Added in 4.8.0

**Comment by FrapzHaash** [comment]
didnt work for me

**Comment by Madis0** [comment]
> didnt work for me

There were server load issues, should work now.
