### ISSUE TITLE
Chunks FadeIn incompat with latest Iris (1.6.1)

### ISSUE THREAD

**Issue by floriaaan** [Fabulously-Optimized/fabulously-optimized#629]
### Describe the bug

Hi,

Just updated the modpack to latest (4.7.3) and can't boot because of incompatibility between Iris 1.6.1 and Chunks FadeIn (1.0.2-1.19.4, the version included in FO 4.7.3).

Just need to update Chunks FadeIn to [1.0.3-1.19.4](https://modrinth.com/mod/chunks-fade-in/version/v1.0.3-1.19.4)

### Modpack version

4.7.3

### Launcher

Prism Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [x] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
Fabulously Optimized has never included Chunks FadeIn. Are you sure you are at the right place?

**Comment by Julienraptor01** [comment]
Chunk Fade-In is a mod you added, not one from FO

**Comment by floriaaan** [comment]
Whoops! My bad, I was sure that it was included in FO.

Closed
