### ISSUE TITLE
Modrinth modpack

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#63]
Create and publish a modpack to Modrinth, because that's where the cool Fabric kids are :)
The files are added per #62, now just needs to be updated and packed when Modrinth adds the support.

https://github.com/modrinth/labrinth/wiki/Modpack-Format

Preferably automatically: https://github.com/comp500/packwiz/issues/34

Edit: I'll probably do this whenever it's possible, release of FO 2.1.0 won't be affected by this
Edit 2: this is fully automated now, releasing the first mrpacks on Github for testing

**Comment by Madis0** [comment]
Preview is now available: https://knossos-4imn3jq70-emmaffle.vercel.app/modpack/fabulously-optimized

**Comment by Madis0** [comment]
[Site redesign announced](https://blog.modrinth.com/redesign/), so the official link is:
https://modrinth.com/modpack/fabulously-optimized

**Comment by Madis0** [comment]
Planned launcher:
![](https://user-images.githubusercontent.com/44736536/156939087-6db03183-b652-4dcd-ba24-f5fb8098796e.png)

[via](https://github.com/modrinth/theseus/pull/20)

**Comment by TiboOpGithub** [comment]
That looks good! Currently using it in the regular minecraft launcher unless for fabulously optimized 1.18.1 but when the modrinth modpacks are out I would use it. Even if Fabulously Optimized is fast with modrinth modpacks then it will be in the top 10 modrinth modpacks I expect.

**Comment by Madis0** [comment]
As of May 9th, all existing pack versions should break, due to the new Curseforge API and not allowing to directly link to files.

The current Modrinth availability state as of FO 3.7.0 is 34 out of 48 mods, this is not enough to publish a half-baked pack. It might be worth it to ask the rest of the mods to support Modrinth, but I'm not yet sure this should be a requirement for future FO mod inclusion. Maybe Modrinth will support Curseforge API? 

Will let you know of any updates.

**Comment by Madis0** [comment]
Modrinth modpacks are now publicly listed (in Alpha!) 
https://modrinth.com/modpacks

* No official launcher yet, though they have installation instructions for MultiMC development version
* They are now working on payouts to get more mods onto the platform
* Still no support for downloads is provided here because it can be unstable and unsustainable for now
* fofirst_place

https://blog.modrinth.com/modpacks-alpha/

**Comment by Madis0** [comment]
The first integrity test is out! Read more at https://modrinth.com/modpack/fabulously-optimized/version/3.8.2-mr.1

**Comment by Madis0** [comment]
Second integrity test was done as well and no major imparities were found, so continuing with a (hopefully) more regular release schedule. Do continue reporting any imparities though.

**Comment by sarim** [comment]
Modrinth modpack works flawlessly with ferium. (used ferium to install modpack, gdlauncher to play). But didn't work with polymc.

**Comment by RaptaG** [comment]
> But didn't work with polymc.

PolyMC is sadly not supported by FO officially yet. Also, this bug is reported in the PolyMC issue tracker so it's going to be fixed soon.

**Comment by sarim** [comment]
Good to know. Whats the officially supported launcher? ferium was working yesterday, but today its downloading the 1.18.2 version. There's no way to specify version.

**Comment by Madis0** [comment]
> Good to know. Whats the officially supported launcher? ferium was working yesterday, but today its downloading the 1.18.2 version. There's no way to specify version.

See https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions
Modrinth is currently not supported at all as it can have bugs and inconsistencies, is there just for testing.

**Comment by Madis0** [comment]
3.10.0 and few other latest versions had Don't Clear Chat History missing due to a bug in the script. That version has been re-uploaded AS -mr.1 and the 4.0.0-beta.1 has it fixed.

On a general note, Modrinth support by FO is waiting on:
* Farsight, which is waiting on author rewards, which is coming soon
* A launcher with good UX and easy updates - see #297 for more info

**Comment by Madis0** [comment]
As of 4.0.0-beta.8, Modrinth version no longer includes JARs! 
This means that it is becoming becoming more sustainable as a platform because mods are cross-posting to it.
(Though obviously things can still change in the future versions if some mod does not post to Modrinth as fast as it does to other platforms.)

**Comment by Madis0** [comment]
Another step for parity!
4.0.0-beta.11 removed Don't Clear Chat History, so CF and MR users will have near-identical set of mods now (except for Farsight, still).

**Comment by RaptaG** [comment]
Yeah!

**Comment by nsde** [comment]
Is this issue still needed? I'm asking because there is a Modrinth modpack for FO.

**Comment by osfanbuff63** [comment]
> Is this issue still needed? I'm asking because there is a Modrinth modpack for FO.

Yes, because Modrinth downloads are still experimental. If I understand correctly, we're mostly waiting to add support for launchers like PolyMC (#456, waiting on PolyMC/PolyMC#60), and then we should be good to remove the experimental notice and close this issue.

**Comment by nsde** [comment]
OK!

**Comment by Madis0** [comment]
Another step for sustainability: MultiMC (auto-update) now prefers Modrinth mods!
That way the downloads actually increase download count for the dev and you get more stable, potentially faster downloads!

**Comment by nsde** [comment]
Sounds great :)

**Comment by nsde** [comment]
Especially because I like Modrinth. It's open source afterall :)

**Comment by Madis0** [comment]
Fabulously Optimized now supports Prism Launcher and Modrinth downloads! The issue will still be kept open for Modrinth Launcher news, whenever that comes.

**Comment by arthomnix** [comment]
Is there any reason Modrinth isn't supported on MultiMC? It seems to work fine

**Comment by Madis0** [comment]
> Is there any reason Modrinth isn't supported on MultiMC? It seems to work fine

Yes:

- CurseForge downloads benefit me financially, and are a familiar place for people to download from
- MultiMC has no modpack updater feature, so an auto-update pack has been provided in GitHub to workaround that
- MultiMC stable currently has a broken modpack downloader from Modrinth, meaning you can only download the latest stable version (have a try lol)
- There is still a slight imparity in CF vs MR versions (Farsight vs Hold That Chunk), so MultiMC users can get the same mods as most other launchers
- Overall I want to support only one (best) source per launcher to make providing support consistent

**Comment by arthomnix** [comment]
It looks like MultiMC is getting Curseforge pack import support again soon, will that be supported?

**Comment by Madis0** [comment]
> It looks like MultiMC is getting Curseforge pack import support again soon, will that be supported?

I don't think so. Downloading from CurseForge via an API nowadays does not even increase the download count, and some mods need to be downloaded manually.

**Comment by arthomnix** [comment]
Any reason Modrinth downloads are supported on Prism, since some of those problems still apply? Is it just because they have a modpack updater?

**Comment by Madis0** [comment]
Yes, they have a working modpack downloader and updater 😄
I hope to close the gap between CF and MR ASAP though.

**Comment by arthomnix** [comment]
Is MR support on MultiMC going to be considered once the working pack downloader is stable, since the default MultiMC pack isn't updatable anyway?

**Comment by osfanbuff63** [comment]
> Is MR support on MultiMC going to be considered once the working pack downloader is stable, since the default MultiMC pack isn't updatable anyway?

From above:
> - Overall I want to support only one (best) source per launcher to make providing support consistent

**Comment by arthomnix** [comment]
There are already two sources for MultiMC (the normal and auto-updating versions), it may be easier to replace the normal version with MR (once the fixed pack downloader goes stable) since that's already supported for Prism anyway

**Comment by Madis0** [comment]
Then vanilla users would be troubled... 
There is not much difference whether I would distribute that for vanilla as just a set of three folders or one that's compatible with something 😄

**Comment by RaptaG** [comment]
Wait, why isn't this closed? Modrinth is fully supported now, isn't it?

**Comment by osfanbuff63** [comment]
Yes, as Prism relies on it. I think this is safe to close.

**Comment by RaptaG** [comment]
Oh

**Comment by Madis0** [comment]
Per #627, MultiMC users are now also advised to download from Modrinth instead of CurseForge.

**Comment by Madis0** [comment]
> ## Modrinth App now in open beta
> 
> The Modrinth App is now in open beta! If you already have it, make sure to run accept the update prompt.
> 
> Among other things, it now allows importing instances from other launchers. In my testing, the Modrinth-based instances of FO on other launchers are also updatable on Modrinth App :tada:
> 
> [Update blog post](https://blog.modrinth.com/p/launcher)
> 
> [**Preliminary install/update/etc instructions for FO**](https://github.com/RaptaG/wiki/blob/patch-1/install-instructions.md#modrinth-app)
> 
> Things to test for:
> - Was your Java detected automatically? Note that this doesn't mean it'll be _installed_ automatically if you don't have it.
> - Linux users - how smooth is the installation on your distro? Are you satisfied with the provided options? Give feedback on [#497](https://github.com/modrinth/theseus/issues/497)
> 
> Known issues:
> - FO's `options.txt` defaults are not currently applied ([#504](https://github.com/modrinth/theseus/issues/504))
> - If you want to change mods, you can't auto-update the modpack later ([#505](https://github.com/modrinth/theseus/issues/505))
> - There is no way to see what modpack version you have installed ([#503](https://github.com/modrinth/theseus/issues/503))
> - Cannot upgrade to a specified version (e.g. latest for 1.19.4 instead of 1.20.1) ([#194](https://github.com/modrinth/theseus/issues/194))
> 
> Once the app is stable and the aforementioned known issues are fixed, it will be officially supported by FO :)

**Comment by Madis0** [comment]
> Modrinth App 0.5.4
>
> Modrinth App has been updated and all previously known blocking issues have been fixed. 
>
> Are there any new ones? Try it out and let me know! If not, then we might just start supporting it soon enough.
>
> :scroll: [Changelog](https://github.com/modrinth/theseus/releases/tag/v0.5.4)
>
> FO **Preliminary instructions:** [Install](<https://github.com/RaptaG/wiki/blob/patch-1/install-instructions.md#modrinth-app>) | [Update](<https://github.com/RaptaG/wiki/blob/patch-1/update-instructions.md#modrinth-app>) | [Add mods](<https://github.com/RaptaG/wiki/blob/patch-1/adding-more-mods.md#modrinth-app>) | [Disable mods](<https://github.com/RaptaG/wiki/blob/patch-1/disabling-mods.md#modrinth-app>)
>
> **Remember, if your launcher UI does not match the instructions above, you're on an older version, [so update it first!](https://modrinth.com/app)** 
> _Unfortunately, you can't yet check which launcher version you're running, see [#737](https://github.com/modrinth/theseus/issues/737)._

and also #656 is finally planned for 5.4.0, which would bring full parity between CurseForge and Modrinth.

So, during the 5.4.0 testing period the Modrinth App can continue to get improvements and when done, it would make sense to release 5.4.0 and Modrinth App support together. 

---

It is also possible that Modrinth App will become the no. 1 recommended launcher for FO, because it supports FO well and literally promotes it as the first on homepage :stuck_out_tongue: But I think that may need to wait a bit more while it gets a full stable release overall.

**Comment by Madis0** [comment]
Very interesting stats:
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/8611110/baafde14-5353-4e9c-bedf-7374784f9cf2)

> My interpretation
> * Modrinth is growing by a lot lately
> * Modrinth-compatible launchers don't care about betas 
> * Modrinth still lacks the archival options, which skews the download stats of older (major) versions :(

I plan to support Modrinth App when the version indicator gets released (for my support purposes), and make it the first when it moves out of beta (because some people are still having issues with logins and Linux stuff).

**Comment by Madis0** [comment]
[Fabulously Optimized now supports Modrinth App!](https://wiki.download.fo/readme/install-instructions#modrinth-app)

The app is still in beta, but I think it is in a usable state for most.
