### ISSUE TITLE
Distribute CRH separately

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#631]
I've been wondering whether I should do it or not for a while, and I probably should. Need to add more vanilla strings (toast etc) and think of translation/distribution flow first.

**Comment by RaptaG** [comment]
I suggest you do that too, preferably under the MIT license

**Comment by Madis0** [comment]
- CF https://www.curseforge.com/minecraft/texture-packs/chat-reporting-helper
  -  MR https://modrinth.com/resourcepack/chat-reporting-helper
  -  PMC https://www.planetminecraft.com/texture-pack/chat-reporting-helper
