### ISSUE TITLE
StringOutOfBoundsException crash

### ISSUE THREAD

**Issue by BreeadHead** [Fabulously-Optimized/fabulously-optimized#632]
### Describe the bug

I tried highlighting some text in a command block using shift + right arrow, but when scrolling to the right enough, it just crashes. 
I messed around with it, and it happens in singleplayer and realms, it doesn't work going left, only right. It seems to happen when the whole bar appears highlighted. 

![image](https://user-images.githubusercontent.com/69173157/233221729-242b9c33-f4db-44f4-ae2a-8ca97df902f9.png)

### Modpack version

4.7.3

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

### Additional context

https://mclo.gs/dch3y0D

**Comment by Madis0** [comment]
Try updating Debugify to the latest version, I think that'll fix it.

**Comment by Madis0** [comment]
Fixed.
