### ISSUE TITLE
MacOS Input Fixes

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#637]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/macos-input-fixes

### CurseForge Mod Distribution

Not allowed

### Modrinth link

https://modrinth.com/mod/macos-input-fixes

### Source/other link

https://github.com/hamarb123/MCMacOSInputFixes

### Mod file size

65.69 KiB

### License

(any other license)

### What it does

Fixes macOS-specific stuff

### Why should it be in the modpack

Makes FO more usable on macOS without additional setup

### Why shouldn't it be in the modpack

- Technically not marked as 1.19.4-compatible in CF/MR
- CF distribution not allowed
- Untested by me, though one user has given good feedback on it

**Comment by orionzleon** [comment]
The downside to this mod is that it adds options to the settings menu, even for Windows users.
I use the mod EmuNO (see #732)

**Comment by Madis0** [comment]
Adds options to where?

**Comment by orionzleon** [comment]
The "Mouse Settings" screen. It is in the mod's desciption:

> Menu Options (under Mouse Settings Screen):
> - Option for trackpad scrolling sensitivity (macOS only)
> - Option to enable momentum scrolling on hotbar (macOS only)
> - Option to disable workaround for smooth scrolling in interfaces (macOS only)
> - Option to reverse scrolling of the whole game
> - Option to reverse scrolling of the hotbar

**Comment by Madis0** [comment]
Hmm, that is indeed an issue.

**Comment by Madis0** [comment]
> Fixes [MC-122296](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fbugs.mojang.com%252fbrowse%252fMC-122296)
>
> Fixes [MC-121772](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fbugs.mojang.com%252fbrowse%252fMC-121772)
> 
> Fixes [MC-59810](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fbugs.mojang.com%252fbrowse%252fMC-59810)
> 
> Fixes [MC-22882](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fbugs.mojang.com%252fbrowse%252fMC-22882)

FYI, 1.20.2 fixes the first two and Debugify fixes the third, so only the last one remains.

**Comment by orionzleon** [comment]
I just tested this on Windows, and it's actually not very intrusive to Windows users. In fact, Windows users might appreciate it as it adds the option to reverse the scrolling.

**Comment by Bruhnanza** [comment]
Debugify has the option to fix [MC-22882](https://bugs.mojang.com/browse/MC-22882) it is just disabled by default.

I tested it and it works, so unless there is a specific fix within the mod that is not otherwise available this mod is not needed.

**Comment by Madis0** [comment]
Enabled the aforementioned bugfix in 5.8.0.
