### ISSUE TITLE
ModernFix

### ISSUE THREAD

**Issue by MenacingPerson** [Fabulously-Optimized/fabulously-optimized#649]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/modernfix

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/modernfix

### Source/other link

https://github.com/embeddedt/ModernFix

### Mod file size

472.26 KiB

### License

(any other license)

### What it does

Improves performance

https://github.com/embeddedt/ModernFix/wiki/Summary-of-Patches

### Why should it be in the modpack

Superfluous question, see above

### Why shouldn't it be in the modpack

I don't see any reason why it shouldn't, best I can think of is mod conflicts

**Comment by TheBossMagnus** [comment]
![Screenshot_20230525-110540.png](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/92474350/24b2c665-bf8a-4960-8cc4-d520b2a98f70)

But I think it's an experimental mod (the fabric version is marked as beta on mr) and in the log you can find lots of mixing warnings..

**Comment by Madis0** [comment]
> while I didn't test it yet, I read that it has some issues with Continuity
and that Continuity is willing to cooperate to help fix them

either way, tracked for 1.20

**Comment by Zorklis** [comment]
Every time I install it, I feel like the fps are too unstable to keep the mod

**Comment by TheBossMagnus** [comment]
> Every time I install it, I feel like the fps are too unstable to keep the mod

Some numbers? I didn't notice any fps difference with this mod...

**Comment by Zorklis** [comment]
more culling crashes with this

**Comment by TheBossMagnus** [comment]
> more culling crashes with this

Worked fine for me.
Maybe it's another bug of MoreCulling already fixed in the latest update related to hanging signs

**Comment by RedGreenBlue09** [comment]
This mod significantly improves resource pack loading for me.

**Comment by AzureAqua** [comment]
It may be worth enabling the dynamic resources option by default in ModernFix as well on 1.19.4+. This should drastically reduce loading time and memory usage even further, with the main downside being possibly missing textures with some specific mods, or in the case of FO broken continuity textures for 1.19.2 and below, but this should have been fixed in newer releases.
