### ISSUE TITLE
I can see through blocks. I can see other chunks.

### ISSUE THREAD

**Issue by SoB0red** [Fabulously-Optimized/fabulously-optimized#650]
### Describe the bug

I can see through blocks, the only mods I installed besides Fabulously are appleskin, malilib, litematica, held item info, better sodium video settings, even when I deleted those mods, the bug remains. I didn't have any resourcepacks on when recording. Yes, I tried restarting and re-logging into the world, but the bug is still there. 

### Modpack version

4.6.1

### Launcher

Minecraft Launcher (vanilla)

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Video with bug: https://youtu.be/HCW2q-fQ_QQ

**Comment by Madis0** [comment]
Please [update to the latest version](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions) of FO and try without your extra mods.

**Comment by SoB0red** [comment]
> Please [update to the latest version](https://fabulously-optimized.gitbook.io/modpack/readme/update-instructions) of FO and try that version without your extra mods.

Ok, I did it, nothing changed literally installed the most recent version(4.9.3) from CurseForge but bug is still there, i have a  video proof if you need it. https://youtu.be/ptHtqwfLKXs(if its in low quality rn that means its still processing it to HD, sorry)

**Comment by SoB0red** [comment]
Closing issue, sodium dev explained to me its sodium bug 
![зображення](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/98276694/6f26b355-4b26-4c35-b400-e38e75258600)
