### ISSUE TITLE
Visuals Completely Freezing

### ISSUE THREAD

**Issue by BattleGuy03** [Fabulously-Optimized/fabulously-optimized#653]
### Describe the bug

Every few minutes or so, my game will freeze for a couple of seconds, and then everything will begin working again, except for the graphics. The entire screen is completely frozen, but it's still responding, making sound, and whenever I press the inventory or pause keys, the mouse appears, and I can click where menu buttons would normally be to activate them, even though the screen is frozen, This leads to me having to restart my game every few minutes, which is very annoying for recording or playing on multiplayer servers.

Other mods: Just Enough Items, Just Enough Resources
It still happens even with them turned off.

### Modpack version

Modpack version 4.7.3 for Minecraft version 1.19.4

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
> maybe a mod's config was changed in some way that caused it and the mod stayed enabled in FO
> but since a fresh instance fixed it, I'm gonna close the thread 🙂
