### ISSUE TITLE
Remove Farsight and Hold That Chunk

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#656]
### What config to change

Remove Farsight from CurseForge edition and Hold That Chunk from Modrinth edition of the modpack.

### Why should it be changed

- Despite several discussions, Farsight dev still does not allow its distribution on Modrinth
    - Farsight is closed-source, so it cannot be forked either 
- Fabulously Optimized's usage on Modrinth is the highest it has ever been, and only increasing
- The split situation has been around for over 7 months 
- Hold That Chunk still does not have feature parity with Farsight, and has some bugs
   - It is also not very actively developed in the recent months
- Some players have a concern that any of these mods decrease performance 
- Some players prefer another alternative, like Bobby or Nvidium, both of which do the same but are unsuitable for FO
   - Bobby is unsuitable because: #46 #556 #354
   - Nvidium is very experimental and Nvidia-only

### Additional details

#46 #556 #354 #437 #184

**Comment by Madis0** [comment]
An alternative mod is being worked on that gets the best features from both.

**Comment by Jeffrey131313** [comment]
Farsight doesn't cache, reloads every time I leave a zone

**Comment by Jeffrey131313** [comment]
Farsight doesn't cache, reloads every time I leave a zone.So I think bobby's better than it.

**Comment by Madis0** [comment]
This question has been up in the air for a long time now, and I've realized that there is no "right mod" to include in FO. All mods are relative and do their thing a bit differently, serving different use cases. And there are also players that use the chunk distance of 8 or less and don't know the difference either way.

Therefore, Farsight and Hold That Chunk **will** be removed with FO version 5.4.0.

Here is a list of mods you can pick from and install for yourself:

* [Farsight](https://legacy.curseforge.com/minecraft/mc-mods/farsight-fabric) - temporary chunk cache, extended render distances up to 64 chunks
* [Hold That Chunk](https://www.curseforge.com/minecraft/mc-mods/hold-that-chunk) - temporary chunk cache that gets cleared over time
* [Bobby](https://www.curseforge.com/minecraft/mc-mods/bobby) - temporary or stored chunk cache, can work with singleplayer worlds as a seed-based blueprint
* [Nvidium](https://modrinth.com/mod/nvidium) - NVIDIA GPU-specific mod that works as an add-on to Sodium and does the same as Farsight if I understand correctly
* [Distant Horizons](https://www.curseforge.com/minecraft/mc-mods/distant-horizons) - temporary chunk cache that renders chunks differently, so should perform better, but is currently in alpha and no shader support
* _Unnamed mod_ - I know that one mod similar to these is being built, but the name and repo are not yet known.

With all that said, I'm gonna leave Distant Horizons issue #240 open for future consideration. That mod is very alpha-quality right now, but unlike the others it actually overhauls the distant chunk rendering system to allow for better game performance, regardless of whether chunks are cached (there is an option) or not.

**Comment by Madis0** [comment]
Completed in 5.4.0

**Comment by seriousfreezing** [comment]
I'd recommend checking out this thread again, as Distant Horizons is almost into its beta and has more decent shader support than before.
