### ISSUE TITLE
Entities displayed in wrong place + block esp

### ISSUE THREAD

**Issue by szekelyd69** [Fabulously-Optimized/fabulously-optimized#657]
### Describe the bug

The two picture describes the problem. Plus on Meteor, block esp doesnt work.
![2023-06-02_16 41 02](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/113088439/535980e9-1724-4d96-b925-b5e67b9ab7ef)
![2023-06-02_16 40 56](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/113088439/ce5fc4ae-4cbd-4151-9c00-135e7ed3625e)

### Modpack version

1.19.3 4.6.1

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Kichura** [comment]
Auto-Closed because FO does not wish to resolve issues that involve the use of hacking programs / cheat mods.
