### ISSUE TITLE
Mod Request: Mouse Tweaks

### ISSUE THREAD

**Issue by Oscillate18** [Fabulously-Optimized/fabulously-optimized#660]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/mouse-tweaks

### Mod file size

75.54 KiB

### License

(any other license)

### What it does

Mod adds various qol features, allowing the use of dragging items into chests and around crafting inventories.

### Why should it be in the modpack

Adds significant QOL changes that improve the experience without altering the core gameplay.
Very lightweight.
One of the most popular mods, with over 171m downloads on curseforge.
Available both on curseforge and modrinth.
Always updated, has had versions since 1.4.2 on curseforge.

### Why shouldn't it be in the modpack

Cannot see any obvious reasons.

**Comment by Madis0** [comment]
Well, it has to be _learned_ by the user, which is something I don't like when adding new mods. Also, I don't really see what value it adds over vanilla, as these kinds of mouse gestures are already possible in one way or another.

**Comment by Oscillate18** [comment]
I agree that it has to be learned, but it is something that is very easily learned and not intrusive so if a user does not know about the functionality it does affect their gameplay in any way. There are arguably more intrusive mods like sodium which change the whole video settings menu, all those extra options have to be learnt since they are no longer in one scrollable menu like before.

The scroll wheel feature is particularly useful. Let's say you want to take 7 diamonds out of a chest as an example, in vanilla you would have to click the item out of the chest and then click 7 times to put the items in your inventory and move the item back again. With this feature you can just hover over the item and use the scroll wheel to accurately take those items directly into your inventory, saving so much time. It is very subtle but extremely useful.

**Comment by Madis0** [comment]
Sorry, I still don't think this mod is suitable for this modpack.
