### ISSUE TITLE
Recent beta throwing exception for animatica/borderless mining

### ISSUE THREAD

**Issue by garpunkal** [Fabulously-Optimized/fabulously-optimized#666]
### Describe the bug

<img width="272" alt="image" src="https://github.com/Fabulously-Optimized/fabulously-optimized/assets/13114807/487a4922-f8ee-44ba-b615-3485d748a7cc">

### Modpack version

5.1.0-beta.1

### Launcher

Minecraft Launcher (vanilla)

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
Please follow the installation instructions.
https://fabulously-optimized.gitbook.io/modpack/readme/install-instructions#minecraft-launcher-vanilla
