### ISSUE TITLE
Controlify currently unusable (due to inability to break blocks)

### ISSUE THREAD

**Issue by HasuMigu** [Fabulously-Optimized/fabulously-optimized#668]
### Describe the bug

Currently as it stands, Controlify has a concurrent issue regarding the inability to hold buttons.  I have manually deleted the .json file for controlify as having both steam-input and NS registered causes conflict which is also an issue that the owner of controlify seems aware about. I also want to disclose that switching buttons somewhere else such as the face buttons doesn't solve this issue. Midnight Controls, despite feeling like a hack still does what it needs to do and I hope this issue will get fixed soon. This open issue describes the situation as the most similar to mine despite me using steam-input or Linux's Nintendo Switch controller drivers.

The issue on controlify's repo: ~~[https://github.com/isXander/Controlify/issues/74](https://github.com/isXander/Controlify/issues/74)~~
[https://github.com/isXander/Controlify/issues/106](https://github.com/isXander/Controlify/issues/106)
### Modpack version

5.1.0-beta.3

### Launcher

Prism Launcher

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
Please test whether you can reproduce it on 5.1.0-beta.7.

**Comment by HasuMigu** [comment]
On 5.1.0-beta.7, the oppposite scenario happens. My player cannot stop breaking blocks. I also tested this with Nintendo Switch Linux or Steam Input.

**Comment by Madis0** [comment]
Alright, please comment on the original issue with logs, video or anything else applicable.

**Comment by Madis0** [comment]
Please retest on beta 8.

**Comment by HasuMigu** [comment]
I have tested it again on the newest version of Fabulously Optimized, the issue went back to the former -- not being able to break blocks
I have tested this on the steam deck and currently in a party as I'm making this comment, I'll provide logs as soon as I can and report this.

**Comment by Madis0** [comment]
Too lazy to update FO today but please try v1.4.2: https://www.curseforge.com/minecraft/mc-mods/controlify/files/4635546

**Comment by HasuMigu** [comment]
Nothing changed in version 1.4.2+1.20 in regards to this issue

**Comment by Madis0** [comment]
https://www.curseforge.com/minecraft/mc-mods/controlify/files/4636573

**Comment by HasuMigu** [comment]
The bug fix doesn't fix the issue, it does fix the the use being activated twice in the same tick. There was an older version (1.3.2) that was working for someone but I have yet to test that for myself plus it's likely missing many features.

**Comment by Madis0** [comment]
https://modrinth.com/mod/controlify/version/1.4.4+1.20

**Comment by HasuMigu** [comment]
The issue is finally fixed. Once Fabulously Optimized updates to include this new version, the issue will be officially closed.
