### ISSUE TITLE
Controllable (Fabric)

### ISSUE THREAD

**Issue by KennyDevT** [Fabulously-Optimized/fabulously-optimized#669]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/controllable-fabric

### CurseForge Mod Distribution

None

### Source/other link

https://github.com/MrCrayfish/Controllable

### Mod file size

15.81 MB

### License

GNU General Public License version 3 (GPLv3)

### What it does

Let's you play with a controller.

### Why should it be in the modpack

It is, in my opinion, much nicer than controlify and offers a smoother experience.

### Why shouldn't it be in the modpack

It's not available on Modrinth. It can be slow to update. It requires the FRAMEWORK library. It needs special hooks to interact with other mods.

**Comment by Madis0** [comment]
No plan to add this at the moment, as indeed, it is:
* not on Modrinth
* requires another library
* requires special hooks for mod interaction
* is a lot bigger 

Feel free to swap the mods on your instance or suggest any missing features to Controlify.
