### ISSUE TITLE
Horse Stats Vanilla

### ISSUE THREAD

**Issue by TheMadHau5** [Fabulously-Optimized/fabulously-optimized#67]
**Mod name**
Horse Stats Vanilla

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/horsestatsvanilla

**Modrinth link**
https://www.modrinth.com/mod/horsestatsvanilla

**Other link**
https://github.com/d4rkm0nkey/HorseStatsVanilla

**What it does**
Allows you to see the stats of the horse you're riding in the inventory gui. Shows the speed, jump height and max health of the horse.

**Why should it be in the modpack**
Allows you to see the stats of your horses. This can be useful, for example for breeding, or for even just taming the best horse among a herd.

**Why shouldn't it be in the modpack**
Notes by Madis0: may be confusing and "not vanilla enough", may be considered an "unfair advantage" (though it can be nerfed with settings)

**Categories**
- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by CodeF53** [comment]
could be considered cheaty.

Cuts out a fair amount of the challenge involved in horse breeding.
Normally you have to design systems to test each variable, rate limiting you by how fast you test them.

But, it could be argued that the challenge in the horse breeding logic is stupid, as even the best horse (which can take literal days to get) is worse than elytra.

**Comment by Madis0** [comment]
@CodeF53 Good points, I wondered about showing the stats myself. Luckily there are options that can nerf the visibility of the values, e.g. show only when tamed. Will see.

**Comment by TheMadHau5** [comment]
@CodeF53 I did think of that, but considered it negligible as horse breeding is random anyway (two perfect horses breed to a suboptimal one).

**Comment by CodeF53** [comment]
> @CodeF53 I did think of that, but considered it negligible as horse breeding is random anyway (two perfect horses breed to a suboptimal one).

Thing is, this mod removes the step of checking if the random odds are in your favor

**Comment by CodeF53** [comment]
I feel like if this passes, it would be a valid compromise for the mod.

https://github.com/d4rkm0nkey/HorseStatsVanilla/issues/9

**Comment by Madis0** [comment]
I've decided this mod is out of scope for the pack as it provides a non-vanilla-like extra feature (like WTHIT, health bar mods etc; other mobs incl pets don't have anything like this) and even with the conditional display feature, can be considered cheaty.
