### ISSUE TITLE
Game crashes upon clicking on multiplayer menu

### ISSUE THREAD

**Issue by NVGAT** [Fabulously-Optimized/fabulously-optimized#670]
### Describe the bug

When I click on the multiplayer menu, I see a "Saving world" screen and the game crashes. Logs provided below. Every mod I've added to FO can be seen in the log file.

### Modpack version

5.1.0-beta3

### Launcher

Prism Launcher

### Other things

- [X] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Logs: https://mclo.gs/5BCPjAL

**Comment by Madis0** [comment]
Remove Essential mod.
