### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by magicdiablo** [Fabulously-Optimized/fabulously-optimized#672]
### Describe the bug

Game crashes on startup.  I rebooted with same result and error codes.
Created a new instance and still crashes.

Disabling Xaero's Minimap fixes issue.

Updating Xaero's to latest version also fixes issue.

### Modpack version

5.1.0-Beta.4

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

Log File
https://mclo.gs/I6iGkxq

**Comment by Madis0** [comment]
> Updating Xaero's to latest version also fixes issue.

Yep, outdated Xaero minimap was the issue.
