### ISSUE TITLE
Distant Horizons

### ISSUE THREAD

**Issue by Loweredgames** [Fabulously-Optimized/fabulously-optimized#674]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/distant-horizons

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/distanthorizons

### Source/other link

https://gitlab.com/jeseibel/minecraft-lod-mod

### Mod file size

2.52 MiB

### License

All Rights Reserved / ARR

### What it does

What does Distant Horizons do?
Simply put, it add simplified terrain past Minecraft's default view distance to improve performance and allow for longer draw distances.
Now you can finally enjoy that lookout tower you built on top of a mountain!

### Why should it be in the modpack

It makes you see further and can be more useful. you can also find your way around the world. 
for the moment it is not compatible with iris.

### Why shouldn't it be in the modpack

The mod is still in an alpha version and you have to wait for updates. in the future it could be updated constantly. with many features too...

### Additional details

Please keep it open until the mod arrives in at least a stable state.
Thanks you

**Comment by Madis0** [comment]
#240
