### ISSUE TITLE
BedrockIfy

### ISSUE THREAD

**Issue by Aquoo** [Fabulously-Optimized/fabulously-optimized#678]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/bedrockify

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/bedrockify

### Source/other link

https://github.com/juancarloscp52/BedrockIfy

### Mod file size

1,35 MB

### License

(any other license)

### What it does

Implements some useful Minecraft Bedrock Edition features into Minecraft Java Edition.

### Why should it be in the modpack

1. Adds a lot of bedrock parity;
2. Most options are configurable, so you can change it to be more similar to vannila minecraft.

### Why shouldn't it be in the modpack

1. The mod is really big, so i don't know if it brings enough parity to justify its size.
2. By default settings, the mod is not very vannila-like, having to be modified to have the hud be the same as vannila minecraft.

**Comment by Madis0** [comment]
Thank you for the suggestion. 
Yes, it achieves the Bedrock parity, which is something FO cares about, but more important than that is the balance and expectations - Java players don't really need or want most of these features. 
May reconsider when there becomes a demand for some specific Bedrock feature(s) that this mod provides.
