### ISSUE TITLE
Hand Clipping through walls

### ISSUE THREAD

**Issue by Sno-Red** [Fabulously-Optimized/fabulously-optimized#679]
### Describe the bug

just trying to play but my hand/items keeps going though the wall and its super disorienting. does anybody know the fix? ive found a couple of other threads but they are super old and using completely different mods and forge not fabric. BTW i am using a modified version of the modpack.
Other similar threads:
https://github.com/BuildCraft/BuildCraft/issues/3624
https://github.com/BuildCraft/BuildCraft/issues/4168
https://hypixel.net/threads/my-mc-hand-is-going-through-walls.1106057/
other threads mentioned turning off fast render but i cant find something like that in the fabric options (i might just be stupid).

Mods used:
  [✔] advancementinfo-1.20-fabric0.83.0-1.4
  [✔] animatica-0.6+1.20
  [✔] antighost-1.20-fabric0.83.0-1.1.5
  [✔] appleskin-fabric-mc1.20-2.5.0
  [✔] bettermounthud-1.2.2
  [✔] borderless-mining-1.1.8+1.20.1
  [✔] capes-1.5.2+1.20-fabric
  [✘] chunksending-fabric-1.20.1-2.5 (disabled)
  [✔] CITResewn-1.1.3+1.20
  [✔] cloth-config-11.0.99-fabric
  [✔] continuity-3.0.0-beta.2+1.20
  [✔] Controlify-1.3.2+1.20
  [✔] Debugify-1.20.1+1.1
  [✔] dynamic-fps-2.4.0
  [✔] e4mc-3.2.0+1.19.4-fabric
  [✔] enhancedblockentities-0.9+1.20
  [✔] entity_model_features_fabric_1.20-0.2.11
  [✔] entity_texture_features_fabric_1.20-4.4.4
  [✔] entityculling-fabric-1.6.2-mc1.20
  [✔] fabric-api-0.84.0+1.20.1
  [✔] fabric-api-0.85.0+1.20.1
  [✔] fabric-chunkpregen-0.3.7
  [✔] fabric-language-kotlin-1.9.6+kotlin.1.8.22
  [✔] fabricskyboxes-0.7.1+mc1.20
  [✔] fabrishot-1.10.0
  [✔] fabrishot-1.9.2
  [✔] fadeless-1.0.1
  [✔] farsight-fabric-1.20.1-3.7
  [✔] fastquit-3.0.0-beta.2+1.20+
  [✔] ferritecore-6.0.0-fabric
  [✔] fsb-interop-1.3.2+mc1.20-build.36
  [✔] ImmediatelyFast-1.1.15+1.20.1
  [✔] indium-1.0.18+mc1.20
  [✔] InventorySorter-1.9.0-1.20
  [✘] iris-mc1.20-1.6.4.jar (disabled)
  [✔] Jade-1.20-fabric-11.1.4
  [✔] jei-1.20.1-fabric-15.2.0.22
  [✔] journeymap-1.20.1-5.9.10-fabric
  [✔] lambdynamiclights-2.3.1+1.20.1
  [✔] language-reload-1.5.8+1.20.1
  [✔] lithium-fabric-mc1.20.1-0.11.2
  [✔] main-menu-credits-1.1.2
  [✔] memoryleakfix-fabric-1.17+-1.1.1
  [✔] midnightlib-fabric-1.4.1
  [✔] mixintrace-1.1.1+1.17
  [✔] modelfix-1.14-fabric
  [✔] modmenu-7.1.0
  [✔] morechathistory-1.19.1-1.1.1
  [✔] moreculling-1.20-0.18.1
  [✔] MouseTweaks-fabric-mc1.20-2.25
  [✔] NoChatReports-FABRIC-1.20.1-v2.2.2
  [✔] optigui-2.1.2
  [✔] puzzle-1.5.1+1.20
  [✔] reeses_sodium_options-1.5.1+mc1.20-build.74
  [✔] Rrls-1.20.1-3.1.0-fabric
  [✔] Searchables-fabric-1.20.1-1.0.1
  [✘] smoothchunk-fabric-1.20.1-3.0 (disabled)
  [✔] sodium-extra-0.4.20+mc1.20-build.103
  [✔] sodium-fabric-mc1.20-0.4.10+build.27
  [✔] worldedit-mod-7.2.15
  [✔] yet-another-config-lib-fabric-3.0.2+1.20
  [✔] yet-another-config-lib-fabric-3.0.3+1.20
  [✔] yosbr-0.1.2
  [✔] Zoomify-2.10.0
  
  Mods added:
  [✔] worldedit-mod-7.2.15
  [✔] InventorySorter-1.9.0-1.20
  [✔] fabric-chunkpregen-0.3.7
  [✘]chunksending-fabric-1.20.1-2.5 (disabled)
  [✘]smoothchunk-fabric-1.20.1-3.0 (disabled)
  [✔]midnightlib-fabric-1.4.1
  [✔]appleskin-fabric-mc1.20-2.5.0
  [✔]MouseTweaks-fabric-mc1.20-2.25
  [✔]jei-1.20.1-fabric-15.2.0.22
  [✔]Searchables-fabric-1.20.1-1.0.1

### Modpack version

5.1.0-beta.6 for 1.20.1

### Launcher

Prism Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [X] I added/removed some mods or resource packs (mention, which ones)

### Additional context

![huge_2023-07-05_00 15 00](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/47543170/97719205-fd7c-4886-957a-ddc78d1b0bb2)
BTW this bug appears to only happen on Servers.

**Comment by Madis0** [comment]
Have you tried disabling your extra mods one by one to find the issue? Also, you have several mods with duplicate versions, e.g. Fabrishot.

**Comment by RaptaG** [comment]
> Also, you have several mods with duplicate versions, e.g. Fabrishot.

This shouldn't be a problem as Fabric Loader ignores non-latest version when two versions of the same mod are present.

**Comment by Madis0** [comment]
Closed due to lack of response.
