### ISSUE TITLE
Fix Keyboard on Linux

### ISSUE THREAD

**Issue by Aquoo** [Fabulously-Optimized/fabulously-optimized#680]
### CurseForge Mod Distribution

None

### Modrinth link

https://modrinth.com/mod/fix-keyboard-on-linux

### Source/other link

https://github.com/ishland/fix-keyboard-on-linux

### Mod file size

9.23 KB

### License

MIT License

### What it does

Fixes some annoying bugs related to the keyboard on linux.

### Why should it be in the modpack

1. FIxes a bug.

### Why shouldn't it be in the modpack

1. Not on curseforge;
2. Only affects a very small portion of the userbase;
3. The bug might not happen on all distros.

**Comment by Kichura** [comment]
The fact that this is licensed under ARR is worrying already.

**Comment by Thanos1716** [comment]
I am on Linux and these keyboard issues have not affected me ever, under Arch Linux, X11 display server, DWM (and originally KDE) with PrismLauncher

**Comment by Aquoo** [comment]
> The fact that this is licensed under ARR is worrying already.

put the wrong license earlier sorry

**Comment by Aquoo** [comment]
> I am on Linux and these keyboard issues have not affected me ever, under Arch Linux, X11 display server, DWM (and originally KDE) with PrismLauncher "Linux" is very broad, would be interested which distro they are using

I myself can't test the mod because I don't use linux, but they should have especified if it happens on a lot of distros or only a few

**Comment by Kichura** [comment]
Rejecting this for multiple reasons:

1. You can have this bug be merged to debugify, *(although it's considered unneeded since linux is very niche in terms of keyboard detection)*
2. 1.20.2 will be fixing this anyways which essentially means people don't need to include this mod in first place.
