### ISSUE TITLE
Font / texture corruption

### ISSUE THREAD

**Issue by Eliastar01** [Fabulously-Optimized/fabulously-optimized#683]
### Describe the bug

At seemingly random, though recurring, the default font for Minecraft will begin to corrupt and get worse through a play session. On one occasion, the texture for shulker boxes became corrupted with a random pattern of black pixels.
Here is an example of the font corruption:
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/139254159/fff75362-3920-4037-a2e9-0831ba2251f2)
I do not have a screenshot of block texture corruption as of now.
I can consistently get the bug to occur after playing for over an hour. The bug fixes itself after closing and reopening the game, until enough time passes for it to occur again.

### Modpack version

5.1.0

### Launcher

CurseForge Launcher

### Other things

- [ ] I updated FO to a newer version (mention, what version to what version)
- [ ] I added/removed some mods or resource packs (mention, which ones)

**Comment by Madis0** [comment]
Beta 9? Logs? Sure you didn't change any mods/RPs?

**Comment by Madis0** [comment]
Also, are you sure this issue is exclusive to FO anyway? Can you try with vanilla and Sodium only?

**Comment by RaphiMC** [comment]
Can you dump the atlas textures by pressing F3 + S and then upload them all here (In a zip preferrably)

**Comment by Madis0** [comment]
Closed due to lack of response. Probably a hardware issue (e.g. VRAM).
