### ISSUE TITLE
Controlify Update

### ISSUE THREAD

**Issue by RealVishy** [Fabulously-Optimized/fabulously-optimized#684]
### What config to change

The current bugs with controlify not breaking blocks correctly have been resolved in the latest build. This should replace the currently shipped 1.4.3 with the newest release of 1.4.4.

### Why should it be changed

This change will fix the bug not allowing for blocks to be broken using the current version of the controlify mod. The issue is resolved as seen by this closed bug report.
[Controlify#106](https://github.com/isXander/Controlify/issues/106)

**Comment by Madis0** [comment]
Yep, soon.
