### ISSUE TITLE
Swap pencil with emoji in MMH

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#686]
### What config to change

Swap the option-indicating pencil with some emoji

### Why should it be changed

Pencil doesn't really represent "options" and now we use some more relevant emoji, like a cog or wrench

### Additional details

1.20+

**Comment by RaptaG** [comment]
I think the gear `⚙️` is the best choice

**Comment by Madis0** [comment]
IIRC the gear didn't look good in-game. Needs more testing.

**Comment by Madis0** [comment]
Added in 5.5.0-beta.1.
