### ISSUE TITLE
Coordinates will not display on the overlay

### ISSUE THREAD

**Issue by EmperorsCovenSteve** [Fabulously-Optimized/fabulously-optimized#688]
### Describe the bug

The overlay will not display coordinates. However it displays FPS just fine.

Running on an AMD GPU in case that's important

### Modpack version

5.1.0

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

![2023-07-18_16 53 47](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/139926112/d0289e52-ef99-4507-a966-dcc83fb229b6)

**Comment by Madis0** [comment]
Can you reproduce with this? https://www.curseforge.com/minecraft/mc-mods/sodium-extra/files/4649495

**Comment by EmperorsCovenSteve** [comment]
It works just fine with only Sodium Extra (and the stuff that needs).

**Comment by Madis0** [comment]
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/8611110/38e6f0ba-f891-493f-9db0-4ad8cec79905)
Cannot reproduce on FO 5.1.1, send your _latest.log_.

**Comment by Madis0** [comment]
Closed due to lack of response.
