### ISSUE TITLE
Better Recipe Book

### ISSUE THREAD

**Issue by RaptaG** [Fabulously-Optimized/fabulously-optimized#690]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/brb

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/brb

### Source/other link

https://github.com/mrshmllow/BetterRecipeBook

### Mod file size

157.39 KiB

### License

(any other license)

### What it does

Adds a Brewing Stand recipe book and many other QoL improvements of the existing recipe book.

### Why should it be in the modpack

It has useful features such as (and not only):

- Brewing Stand UI
- Keeps crafting screens centered when you open the recipe book
- Show furnace recipes
- Recipe Book scrolling
- Unlock all recipes when you log in to a server/world (and suppress the "Recipe Unlocked" toast when enabled)
- Remove the "Bounce" animation when you unlock a new recipe

### Why shouldn't it be in the modpack

Some people don't use the recipe book at all

### Additional details

I suggest we use the config I made in T.O.M, it is vanilla-like and it has a "FO" config style:

https://codeberg.org/RaptaG/T.O.M/src/branch/main/modpack/config/yosbr/config/brb.toml

**Comment by Julienraptor01** [comment]
https://github.com/Fabulously-Optimized/fabulously-optimized/issues/148

**Comment by RaptaG** [comment]
This is more updated, port any info you want though

**Comment by Madis0** [comment]
Previous reasons apply.
