### ISSUE TITLE
Vanadium

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#693]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/vanadium-mod

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/vanadium

### Source/other link

https://github.com/theomenden/TheOmenDen.Vanadium

### Mod file size

430.85 KB

### License

(any other license)

### What it does

Color support a la Colormatic

### Why should it be in the modpack

Colormatic has been removed for a long time

### Why shouldn't it be in the modpack

Still experimental

**Comment by Poopooracoocoo** [comment]
it's now on [modrinth](https://modrinth.com/mod/vanadium) 👀 the developer's been doing amazing work!!

**Comment by Madis0** [comment]
The dev agreed to upload this and [Bismuth](https://github.com/theomenden/TheOmenDen.Bismuth) to CurseForge now. Bismuth appears to be a different implementation of the same idea, though it is said to work on 1.19.4 instead.

**Comment by AlucardMG36** [comment]
The dev for Bismuth and Vanadium here - 
Just resubmitted to Curseforge as they needed an updated description. 

I am continuing to update the compatibility of both mods, and will be updating these on a frequent timeline. If you need me to provide a schedule for releases or some other demonstration, I will be more than happy to do so.

**Comment by Madis0** [comment]
> The link for the curseforge upload is here - but noted on Curseforge I had to call it "Panchromium" for the page in order for the slug to be satisified: https://legacy.curseforge.com/minecraft/mc-mods/panchromium

Why is the name/slug different when https://legacy.curseforge.com/minecraft/mc-mods/vanadium doesn't exist?

**Comment by AlucardMG36** [comment]
> > The link for the curseforge upload is here - but noted on Curseforge I had to call it "Panchromium" for the page in order for the slug to be satisified: https://legacy.curseforge.com/minecraft/mc-mods/panchromium
> 
> Why is the name/slug different when https://legacy.curseforge.com/minecraft/mc-mods/vanadium doesn't exist?

I don't know - Curseforge wouldn't let me upload it as Vanadium and forced me to change the name

**Comment by Madis0** [comment]
Okay, I see. According to cflookup, the slug is already used for a modpack, that's why it can't be used by you I guess. 

What about keeping the name the same and the slug something like `vanadium-mod` or `vanadium-colors`?
Because using a different name definitely looks weird and hurts the discoverability of the mod.

**Comment by AlucardMG36** [comment]
That makes a good amount of sense to do. I'll take that approach. 
My initial thought was that "Well, Vanadium was known as Panchromium, so that'll be fine" 
I'll get on that! Thank you for the suggestion.

**Comment by AlucardMG36** [comment]
Updated.
Mod is now Vanadium Colors on Curseforge.
Slug is: https://legacy.curseforge.com/minecraft/mc-mods/vanadium-mod

**Comment by Madis0** [comment]
Good. Can you please also "allow distribution outside CF" under the profile settings? That would help users with custom launchers download your mod as well.

**Comment by AlucardMG36** [comment]
Done.

**Comment by AlucardMG36** [comment]
"We _primarily focus_" not "We only focus" - I'll probably update the description at somepoint, but I'm also incredibly lazy.

Also, since I use an IDE that's licensed to The Omen Den (which I own) - it made more sense at the time. 
Plus having a diverse portfolio is always a nice to see.

**Comment by AlucardMG36** [comment]
I will be keeping the names as is.

**Comment by AlucardMG36** [comment]
@Madis0 - Bismuth has been approved, and updated - should allow for distribution, and is available on CF as well as Modrinth.
CF: https://legacy.curseforge.com/minecraft/mc-mods/bismuth-ii
Modrinth: https://modrinth.com/mod/bismuth-2

**Comment by Madis0** [comment]
Ehh, I would also call that Bismuth Colors.

**Comment by AlucardMG36** [comment]
> Ehh, I would also call that Bismuth Colors.

Changed.
https://www.curseforge.com/minecraft/mc-mods/bismuth-colors

**Comment by Madis0** [comment]
Rejected per #796, which got the same features and was added to FO.
