### ISSUE TITLE
Overlay will not display coordinates

### ISSUE THREAD

**Issue by EmperorsCovenSteve** [Fabulously-Optimized/fabulously-optimized#695]
### Describe the bug

Continuation of: https://github.com/Fabulously-Optimized/fabulously-optimized/issues/688#event-9903501982 (stuff came up and i forgot about it, im sorry if this is weird)

Coordinates will not display on my main world (from an earlier version), but they will on any world created in the latest version. FPS display works just fine

### Modpack version

5.2.1

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

![2023-07-30_18 59 42](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/139926112/15012e8d-431e-451f-b1b3-66f0733c05e5)
![2023-07-30_18 58 43](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/139926112/9a83e05d-73c1-43ed-871b-15b63e791020)
[log.txt](https://github.com/Fabulously-Optimized/fabulously-optimized/files/12210382/log.txt)

**Comment by Madis0** [comment]
Try updating Sodium Extra to the latest version. If that fails, try using only that latest version of Sodium Extra without other mods.

**Comment by EmperorsCovenSteve** [comment]
Didnt work with only Sodium Extra, so i guess ill go take it up with them. Thanks again for being patient
