### ISSUE TITLE
Make /ghost pause menu text clickable

### ISSUE THREAD

**Issue by Aeases** [Fabulously-Optimized/fabulously-optimized#697]
### What config to change

isxander-main-menu-credits.json
Make the "Fix ghost blocks with /ghost" text in the pause menu clickable, when clicked it should run the commnand "/ghost"

![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/96164686/9f6ae12e-0370-4a27-a124-24a436cb53ac)

https://github.com/Fabulously-Optimized/fabulously-optimized/commit/fc5aa28a2beb764111dd9952f0de5ee4677b747e

### Why should it be changed

Stops you from having to manually type out the command if you prefer to click, and the text is there anyway why not make it clickable?

### Additional details

I was going to make a PR, but it says to make an issue here first, [here's the changes](https://github.com/Fabulously-Optimized/fabulously-optimized/compare/main...Aeases:requisite:fo-clickable-ghost)

**Comment by Madis0** [comment]
Huh, that's clever, didn't even think of this before.
Will include in the next version.

**Comment by Aeases** [comment]
Reckon i should submit the PR or nah?

**Comment by Madis0** [comment]
Nah, I wouldn't be able to merge it directly either way, I'll just copy the code.
