### ISSUE TITLE
Add the fresh animations texture pack

### ISSUE THREAD

**Issue by Waseem973** [Fabulously-Optimized/fabulously-optimized#698]
### CurseForge link

https://www.curseforge.com/minecraft/texture-packs/fresh-animations

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/resourcepack/fresh-animations

### Source/other link

https://www.planetminecraft.com/texture-pack/fresh-animations-v1-0/

### Mod file size

485.2 KB

### License

Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.

### What it does

This is actually a resource pack request instead of a mod request but had to choose it to be a mod request because there isn't a "texture pack" request. This resource pack adds custom, trailer-like animations to the game, which makes animations super cool.

### Why should it be in the modpack

The animations this texture pack provides feel essential to the game and are pretty cool in my opinion.

### Why shouldn't it be in the modpack

Maybe some people might not like it (but probably unlikely), however, if they do not like it, they can simply stop using it, just like how the modpack has the better grass texture pack on by default, some might not like it and disable it.

### Additional details

All this texture pack does is add animations to the game, it doesn't change anything else.

**Comment by Madis0** [comment]
Fabulously Optimized should look and feel vanilla-like by default, while providing every mod and config required to allow users to use resource packs like this one. So it is better installed manually when wanted.
