### ISSUE TITLE
Better Advancements

### ISSUE THREAD

**Issue by orionzleon** [Fabulously-Optimized/fabulously-optimized#702]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/better-advancements

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/better-advancements

### Source/other link

https://github.com/way2muchnoise/BetterAdvancements

### Mod file size

71.62 KiB

### License

(any other license)

### What it does

The mod Better Advancements does the same thing as the AdvancementInfo mod, which is currently included in the modpack.
This mod (Better Advancements) should replace the AdvancementInfo mod because while it does the same thing, the visual aesthetic is a lot better.

### Why should it be in the modpack

The mod Better Advancements also has an option to only show the parts of the advancement that you have completed. This keeps it more vanilla-like becuase unless you turn on the setting, it does not tell you what part you need, but only what parts you already have.
For example, if you are trying to get the visit every biome advancement, it won't tell you what biome you need to find, but only what biomes you already visited. (Again, if the player WANTS to show what biome they need, then they may turn in on the the mod settings)
As for the aesthetic part of it listed above, it shows the requirements when you hover over it which looks a lot better, because it looks more built in and looks more like vanilla minecraft.

### Why shouldn't it be in the modpack

There are none, as this is a better version of AdvancementInfo, which is currently included in the modpack.

### Additional details

The Modrinth link to AdvancementInfo is:
https://modrinth.com/mod/advancementinfo

**Comment by orionzleon** [comment]
I have tested this mod thoroughly myself, and even though they are labeled as beta, they have been fine for me so far with no bugs.

**Comment by craftish37** [comment]
Tested, do not interfere with any other feature and provides a more vanilla feeling than advancementinfo

**Comment by orionzleon** [comment]
Will this be changed in the next version of FO?

**Comment by Madis0** [comment]
Likely not, as I focus on other changes atm, nor have I actually tested it. Just as long as the issue is open, it is being considered.

**Comment by orionzleon** [comment]
Some more info on this mod:
Most modpacks (etc. All The Mods) use Better Advancements.

As for the problem about showing criteria details, this mod has a better vanilla implementation. If you put `"criteriaDetail": "Default",
  "criteriaDetailRequiresShift": true` in the config file, then it will not turn off showing what you need to complete an advancement, but you will need to hold down the shift key to view it (This could be in the FO wiki).

**Comment by Madis0** [comment]
Yeah, I recently tested it out as well, and noticed that it doesn't respect resource packs (reported to dev).
As for the inclusion overall, I'm currently thinking if even AdvancementInfo is still wanted in FO so I'll ask users to state their opinion on that first, soon.

**Comment by orionzleon** [comment]
Im pretty sure EVERYONE appreciates the bigger advancements screen (compared to the tiny one in vanilla minecraft), so something should still be added for that.

**Comment by orionzleon** [comment]
But yes, you should ask everyone if they use it to check criteria. Maybe you can do it along with the mod removal vote that's happening in discord.

**Comment by orionzleon** [comment]
Just as info, I added the 1.20.1 version in the latest 1.20.2 alpha, and it has been working.

**Comment by Madis0** [comment]
> Just as info, I added the 1.20.1 version in the latest 1.20.2 alpha, and it has been working.

In my testing, the game launched but loading a world froze. And I can confirm that important changes were made to the advancement UI code that do imply that none of the mods keep working without changes.

Anyway, a major dealbreaker for this mod is that it does not work with most resource packs as it uses its own textures. I've suggested the dev to change it, but considering how long the mod has been around and the two platforms it supports, I don't really expect a change to be made soon.

**Comment by Madis0** [comment]
#746 was added instead.
