### ISSUE TITLE
Crash on 5.3.0-beta.1+ when opening Mod Menu or Controlify settings

### ISSUE THREAD

**Issue by JPenuchot** [Fabulously-Optimized/fabulously-optimized#704]
### Describe the bug

Hey,

The latest beta has been crashing whenever Controlify menu or mod list gets opened. Apparently this is related to YACL image previews, and it could be an outdated or incompatible mod messing up with Sodium.

Here are the initial issue reports on Controlify and Sodium's bug trackers:
https://github.com/isXander/Controlify/issues/142
https://github.com/CaffeineMC/sodium-fabric/issues/1987

### Modpack version

5.3.0-beta.2

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by JPenuchot** [comment]
The issue is being tracked here: https://github.com/isXander/YetAnotherConfigLib/issues/101

**Comment by Madis0** [comment]
Resolved on 5.3.0-beta.5
