### ISSUE TITLE
Full Brightness Toggle

### ISSUE THREAD

**Issue by orionzleon** [Fabulously-Optimized/fabulously-optimized#705]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/full-brightness-toggle

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/full-brightness-toggle

### Source/other link

https://github.com/ricksouth/serilum-mc-mod-sources/tree/main/sources/Full%20Brightness%20Toggle

### Mod file size

33.88 KiB

### License

All Rights Reserved / ARR

### What it does

This mod adds a simple keybind to toggle fullbright, so you can see in the dark. (Default keybind is G)

### Why should it be in the modpack

It is a very widely used feature. If someone thinks that it is not vanilla-like to have light without torches, then they just don't configure the keybind.

### Why shouldn't it be in the modpack

People might not like it because it removes the need for light sources.
It also depends on the mod Collective. (https://modrinth.com/mod/collective). Collective is a mod that provides the main source code for all of the author's mods.

**Comment by Madis0** [comment]
I don't want to add new keybinds as they need to be learned and can be pressed accidentally. I also don't want to add specific options for fullbright, as [Mojang intentionally removed it](https://bugs.mojang.com/browse/MC-51418) and there are already a lot of ways it can be done - from [mods](https://modrinth.com/mods?q=bright&g=categories:%27fabric%27&e=client) to [resource packs](https://modrinth.com/resourcepack/fullbright-ub).
