### ISSUE TITLE
CalcMod

### ISSUE THREAD

**Issue by shadeydo** [Fabulously-Optimized/fabulously-optimized#706]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/calcmod

### CurseForge Mod Distribution

Not allowed

### Modrinth link

https://modrinth.com/mod/calcmod

### Source/other link

https://github.com/js802025/calcmod/tree/1.20

### Mod file size

599 KB

### License

(any other license)

### What it does

A calculator in your Minecraft chat with extra features to determine farm rates, generate random numbers, convert between Overworld and Nether coordinates, and a bunch of other nerdy things.

|/calc craft piston 3 sb|
|-|
|[![Craft feature example](https://i.ibb.co/2yyZT55/final.png)](https://i.ibb.co/6Yw0NsC/giphy.gif)|

### Why should it be in the modpack

- As un-intrusive as it gets, a small QoL addition that only lives in the Minecraft chat
- Has time saving shortcuts catered towards technical minecrafters and redstoners, but easily accessible to all.
- All features are well documented in the in-game help command, as well as the [CalcMod listing page](https://modrinth.com/mod/calcmod)
- Works on either client or server

### Why shouldn't it be in the modpack

- File size is on the bigger side due to the library used to process equations

**Comment by Madis0** [comment]
There are a lot of ways to use a calculator nowadays, so I would say having it in-game is very niche and again - has to be learned how to use.
Also, the item calculation thing looks nice, but I have a feeling most users who need it would use Litematica for something like that.
