### ISSUE TITLE
RemoveReloadingScreen is broken

### ISSUE THREAD

**Issue by dima-dencep** [Fabulously-Optimized/fabulously-optimized#710]
### Describe the bug

See https://github.com/juliand665/Dynamic-FPS/issues/100

### Modpack version

5.3.0-beta.4

### Launcher

CurseForge Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
I mean, I saw this but the loading screen still loads successfully?

**Comment by Kichura** [comment]
This looks awful, and because this can essentially hang the client; might need to be looked into since removereloadingscreen can impact other mods out of nowhere due to the way it's designed to work.

**Comment by LostLuma** [comment]
FWIW I plan to release a fixed version of Dynamic FPS pretty soon now (pending review/comment from the owner) which will disable the loading overlay optimization with rrls present. Just took a while because I got covid which made me not do much.

**Comment by Kichura** [comment]
This issue is now marked as resolved.
