### ISSUE TITLE
"Failed to copy packs"

### ISSUE THREAD

**Issue by Zeron100Z** [Fabulously-Optimized/fabulously-optimized#716]
### Describe the bug

When going to create a new Singleplayer world, it will fail to load right after clicking "Create New World", saying it cannot copy packs, joining existing servers is fine, it only seems to impact creation of new worlds

### Modpack version

5.3.0-beta.7

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

[](https://mclo.gs/uwIrIF5)

**Comment by Zeron100Z** [comment]
(github didn't send the link in the additional context, so):
https://mclo.gs/uwIrIF5

**Comment by Madis0** [comment]
Are you using datapacks? If so, can you confirme that you have not currently _opened_ any of them? (E.g. if you open a zip in 7-zip, then no other program can access it).

**Comment by Zeron100Z** [comment]
only datapacks that are selected are fabric mods and minecraft itself

**Comment by Madis0** [comment]
Okay. Please try restarting your computer though, just in case.

**Comment by Madis0** [comment]
Can you still confirm the issue on 5.3.0?

**Comment by Madis0** [comment]
No response, assuming fixed.
