### ISSUE TITLE
Super Better Grass

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#718]
### CurseForge link

https://curseforge.com/minecraft/mc-mods/super-better-grass

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/super-better-grass

### Source/other link

https://github.com/dima-dencep/super-better-grass

### Mod file size

774 KB

### License

(any other license)

### What it does

OptiFine's Better Grass - #6 ported back to Fabric

### Why should it be in the modpack

Because most people prefer to have the Better Grass from OptiFine that is "fancy", not "fast" (like in the currently bundled resource pack).

### Why shouldn't it be in the modpack

- Not yet available on MR
- Untested
- LambdAurora may not like this and as such, may try to take the mod down from the platforms (though the fork appears to follow the license properly)

**Comment by Radplay** [comment]
Seems to be working just fine:
![2023-09-10_10 34 57](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/63958709/10fdf47b-1144-4cd4-9b6f-72db28127a03)
![2023-09-10_10 35 21](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/63958709/54f3bf13-43b8-4a63-b51b-a294ed3b4157)

**Comment by Madis0** [comment]
The mod has been removed from Modrinth for good, so any attempt to bring it back there by me would probably be frowned upon. Similar tensions have come up in the CurseForge listing comments, so... yeah, it's better to avoid adding it to FO.
