### ISSUE TITLE
Remove Fabrishot

### ISSUE THREAD

**Issue by ItsProfessional** [Fabulously-Optimized/fabulously-optimized#720]
### What config to change

Remove fabrishot

### Why should it be changed

Most people probably don't want to "Take insanely large screenshots because why not" and those who want to can add it themselves.

**Comment by Madis0** [comment]
Interesting perspective. 
Well, the reason this was added in the beginning was that it is OptiFine parity. And with FO currently having shader support, extended render distance and many resource pack features, it is not far-fetched to say that there is a target audience for this.

**Comment by Madis0** [comment]
Moved with more arguments and public voting to #741
