### ISSUE TITLE
Remove Zoomify

### ISSUE THREAD

**Issue by RozeFound** [Fabulously-Optimized/fabulously-optimized#723]
### Original issue

#233

### Why should it be in the modpack

"People have been requesting for customizable zoom and some are put off by Wi Zoom's origin, this one has no server-side limits which is great"

### Why shouldn't it be in the modpack

Distracting amount of customization options, no relative sensitivity, profiles are misleading

### Additional details

You can replace it with [something better](https://github.com/Fabulously-Optimized/fabulously-optimized/issues/577).

**Comment by Madis0** [comment]
Oh yeah, I should've clarified when the remove form should _not_ be used. But no, I will not remove Zoomify entirely, and you haven't managed to convince me in what way Ok Boomer is better.
