### ISSUE TITLE
(Neo)Forge Early Loading Screen for Fabric

### ISSUE THREAD

**Issue by ItsProfessional** [Fabulously-Optimized/fabulously-optimized#726]
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/forge-early-loading-screen-fabric

### Source/other link

https://github.com/Jab125/forge-early-loading-screen

### Mod file size

367.08 KiB

### License

(any other license)

### What it does

This mod adds the early loading screen from FML to fabric.

### Why should it be in the modpack

Allows the user to see the mod loading progress, rather than waiting a while for the minecraft to launch

If the user has added a lot of content mods on top of FO, then having a screen showing information is quiet helpful than waiting for 45 seconds for the game to launch and hoping it won't crash.

### Why shouldn't it be in the modpack

Not available on CurseForge, still in beta (the mod is essentially a clone of FML's earlydisplay, so it while the mod is in beta, in reality it isn't).
Currently the mod shows a running fox on the early loading screen, which might be unexpected to some users launching the modpack. I have opened an issue to allow disabling that in the config, though.

### Additional details

Licensed under LGPL-2.1-only
Mod supports the "Monochrome Logo" setting.

**Comment by Madis0** [comment]
You know, in the early days of FO, I actually considered something like this. But ended up scrapping the idea, because other than the Forge likeness, most users have nothing to do with the data it gives.

> Allows the user to see the mod loading progress, rather than waiting a while for the minecraft to launch

In this case, I'd rather optimize the startup speed than distract the user with data.

> If the user has added a lot of content mods on top of FO, then having a screen showing information is quiet helpful than waiting for 45 seconds for the game to launch and hoping it won't crash.

Mods usually crash before or during loading screen... Title screen crashes aren't very common.

Rejected.
