### ISSUE TITLE
More Culling Extra

### ISSUE THREAD

**Issue by Radplay** [Fabulously-Optimized/fabulously-optimized#727]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/morecullingextra

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/morecullingextra

### Source/other link

https://github.com/fxmorin/MoreCullingExtra

### Mod file size

39,29KB

### License

(any other license)

### What it does

An "addon" to MoreCulling, with some additional performance improvements:

- Glass Panes cull against glass & beacons
- Glass culls against beacons
- Beacons cull against glass

### Why should it be in the modpack

It could benefit performance in certain situations

### Why shouldn't it be in the modpack

- Not updated on CurseForge anymore
- Untested
- Similarly to ArdaGrass, the update policy is questionable

**Comment by Madis0** [comment]
I'm not so sure we need glass culling specifically, as glass is already culled in vanilla for the most part. And these things culled with glass may not look right.

**Comment by Madis0** [comment]
Breaks vanilla visual expectations, doesn't bring much benefit.
