### ISSUE TITLE
Remove More Chat History

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#731]
### Original issue

#126

### Why should it be in the modpack

- Allows seeing chat messages that were sent older than 100 messages
- Useful in long game sessions

### Why shouldn't it be in the modpack

- Having more than 100 messages makes scrolling to any specific message harder
- The vanilla log files already contain all messages, and allow easy interactions (search, copy)
- The usefulness is mostly present in survival servers - not minigame servers
- High amount of chatlog may introduce some sort of lag
- The mod may be considered a bloat or conflict if the user is adding any other chat mods that do the same or more

### Voting

Should the mod be removed? Vote or argument below!

:+1: This mod should be **removed** from FO
:-1: This mod should be **kept** in FO

* If you think the mod _idea_ is great to keep included, but the _mod being voted for_ is not, vote to _keep_ the mod. Then, find or create an issue for a replacement mod with your idea and discuss there.
* You can simply interact with emoji, but arguments are considered more valuable and hold more weight in the final decision.
* Mod size, platform and other metadata are not an important criteria for this vote. You just focus on the idea and purpose.
* Everyone can vote, regardless of if you've used the mod in the past.

**Comment by Julienraptor01** [comment]
reposting from myself on discord
> Allows seeing chat messages that were sent older than 100 messages

Just a fact
> Useful in long game sessions

or in servers that spam your chat such as Hypixel
> Having more than 100 messages makes scrolling to any specific message harder

no ? it only make harder to scroll to older messages that wouldn't even be accessible
> The vanilla log files already contain all messages, and allow easy interactions (search, copy)

i wouldn't say easy interaction, accessing the current log is tedious if you aren't using a special launcher such as MultiMC
and so i wouldn't say that searching and copying in them is easy for regular users
and this mod doesn't change anything about that
> The usefulness is mostly present in survival servers - not minigame servers

straight up wrong ?
it's even more useful in minigame servers that send a lot of info in chat especially in multiple messages so they can ensure of the formatting
> The mod may be considered a bloat or conflict if the user is adding any other chat mods that do the same or more

maybe

so to state my opinion, i think this mod is easily a good +

**Comment by orionzleon** [comment]
I find this mod very useful in minigame servers such as Hypixel. Hypixel spams you with so many messages, it's very easy to miss one.

**Comment by Madis0** [comment]
Thank you for your responses!
They will be read and considered, and afterwards a decision will be announced. But for now, time for the next vote! :rocket:

**Comment by Madis0** [comment]
Will not be removed.
