### ISSUE TITLE
Add EmuNO and remove Debugify fixes for MacOS

### ISSUE THREAD

**Issue by orionzleon** [Fabulously-Optimized/fabulously-optimized#732]
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/emuno

### Source/other link

https://github.com/RyanModDev/emuno

### Mod file size

9.59 KiB

### License

(any other license)

### What it does

It fixes MacOS bugs like Ctrl+Left=Right, Ctrl+Q, and Shift+Scroll. The reason it should be added is becuase Debugify does not fix the Ctrl+Q issue.

### Why should it be in the modpack

Debugify does not fix the Ctrl+Q issue, and EmuNO does.
It also gets updated pretty quickly (1.20 support 2 days after release).

### Why shouldn't it be in the modpack

None

### Additional details

1.20.1 JAR works in 1.20.2 with no problems.

**Comment by Madis0** [comment]
The lack of CurseForge is already problematic, but overall I'm not sure if I want to introduce Mac-specific mods right now.

**Comment by orionzleon** [comment]
This mod does nothing for windows users, so if windows users install the modpack, the mod would do nothing. But thats fine if you dont add this right away.

**Comment by Madis0** [comment]
Windows users are not the point, macOS has clients (including official) that use CurseForge as well.

**Comment by orionzleon** [comment]
If I understand modpacks well enough, it could be added as on override, right?

**Comment by Madis0** [comment]
Yes, in theory it is possible to get approval from the dev and CurseForge and have it as an override. But in practice it is a big pain for me and I already have like 5 mods where I have to deal with this 💀 

So please, consider convincing the dev or maybe finding an alternative.

**Comment by orionzleon** [comment]
I have made an issue in the Github for EmuNo: https://github.com/RyanModDev/EmuNO/issues/2

**Comment by Madis0** [comment]
FYI, shift+scroll is actually fixed as of 1.20.2. https://bugs.mojang.com/browse/MC-122296 https://bugs.mojang.com/browse/MC-121772

**Comment by orionzleon** [comment]
I am asking this because I am not very educated in software licensing, so if I were to upload this mod on Curseforge and maintain the Curseforge version myself, how would I do that legally?

**Comment by orionzleon** [comment]
I have uploaded this to Curseforge, it is currently under review. When it is approved, it will be at https://legacy.curseforge.com/minecraft/mc-mods/emuno

**Comment by Madis0** [comment]
Did you read [CurseForge's rules](https://support.curseforge.com/en/support/solutions/articles/9000197279-project-and-modpack-moderation-policies)?

> **Plagiarism**: Don't steal. Do not upload work that does not belong to you. Unless you have explicit permission from the Owner. You must also include due credit. You will most likely be banned for breaking these rules.

**Comment by orionzleon** [comment]
Yes, I just read the rules. I will delete the project from Curseforge right now.

**Comment by orionzleon** [comment]
Update, I have discovered a game-breaking bug with this mod, I will close this issue.

**Comment by Madis0** [comment]
Sure, but please report the issue to the original dev as well.

**Comment by orionzleon** [comment]
Ok I will try, if fixed I can reopen the issue.

**Comment by orionzleon** [comment]
Bug has been fixed.

**Comment by ryanccn** [comment]
https://legacy.curseforge.com/minecraft/mc-mods/emuno

**Comment by orionzleon** [comment]
@Madis0 The mod was published to Curseforge last week

**Comment by Bruhnanza** [comment]
Both of the unresolved bugs that is mod fixes are already available in Debugify.
- [MC-59810](https://bugs.mojang.com/browse/MC-59810) Enabled by default
- [MC-22882](https://bugs.mojang.com/browse/MC-22882) Disabled by default

**Comment by Madis0** [comment]
Enabled the aforementioned bugfix in 5.8.0, so this mod is no longer needed.
