### ISSUE TITLE
Add RenderDistanceCycler

### ISSUE THREAD

**Issue by orionzleon** [Fabulously-Optimized/fabulously-optimized#733]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/renderdistancecycler

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/renderdistancecycler

### Source/other link

https://github.com/kyrptonaught/renderdistancecycler

### Mod file size

14.52 KiB

### License

(any other license)

### What it does

It re-adds the F3+F shortcut that was used to change render distance, and was removed in 1.19.

### Why should it be in the modpack

It re-adds a very widely used feature, especially by speedrunners, that was removed.

### Why shouldn't it be in the modpack

Very little downloads (about 200), no 1.20 version

### Additional details

The 1.19 version works in 1.20 as well so that should not be a major issue.

**Comment by Madis0** [comment]
I've never even heard about that shortcut being in vanilla, so it seems very niche. Don't want to introduce new things that have to be learned by users either.
