### ISSUE TITLE
Remove Controlify

### ISSUE THREAD

**Issue by orionzleon** [Fabulously-Optimized/fabulously-optimized#734]
### Original issue

#598

### Why should it be in the modpack

For people who want to play minecraft java with a controller

### Why shouldn't it be in the modpack

Does anybody ACTUALLY use this mod?

### Confirm

- [X] This mod removal request was written in good faith, taking into consideration why the mod was added in the first place. This is not a mod replacement request - for that purpose I should use the normal mod request form.

**Comment by Madis0** [comment]
Currently removal will not be considered, as there are indeed target users for this.

**Comment by orionzleon** [comment]
Ok, that's fine
