### ISSUE TITLE
Chat is blocked

### ISSUE THREAD

**Issue by Gabeilxer212** [Fabulously-Optimized/fabulously-optimized#739]
### Describe the bug

I can see in game chat i just cant type in it. It gives an error saying that i should relog. It doesnt fix the problem.

### Modpack version

1.20.2 Alpha

### Launcher

CurseForge Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

i used gdlauncher not curseforge, its not an option

**Comment by Madis0** [comment]
Server IP? Screenshot?

**Comment by Madis0** [comment]
Okay, I probably understand the issue. 

In the server, click ![optional](https://i.ibb.co/hstcjW7/neutral.png) 2 times until it says "Signing mode: **Always**". Then try chatting again.
