### ISSUE TITLE
Varied Mob Textures

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#75]
**Mod name**
Varied Mob Textures

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/varied-mob-textures

**Modrinth link**

**Other link**

**What it does**
Provides support for varied and randomized mob textures

**Why should it be in the modpack**
Optifine provides this too

**Why shouldn't it be in the modpack**
Usable only via #73, "project currently suspended", not for 1.17

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [x] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

**Comment by nsde** [comment]
I'm using a resourcepack with varied blocks from VanillaTweaks and it works fine - without this mod.

**Comment by Madis0** [comment]
> I'm using a resourcepack with varied blocks from VanillaTweaks and it works fine - without this mod.

This is about mobs and possibly other entities. The randomized blocks should indeed work already because of Continuity.

**Comment by Madis0** [comment]
Superseded by #231.
