### ISSUE TITLE
Resourcify

### ISSUE THREAD

**Issue by Excederus** [Fabulously-Optimized/fabulously-optimized#770]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/resourcify

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/resourcify

### Source/other link

https://github.com/DeDiamondPro/Resourcify

### Mod file size

2.56MB (1.20.2 Fabric version)

### License

(any other license)

### What it does

Allows you to download and update resourcepacks, shaderpacks and datapacks hosted on Modrinth from within Minecraft

### Why should it be in the modpack

Makes it very easy to install RP, SP, DP:
- without resorting back to a third-party launcher (which might require to "unlock" the instance to allow for additional content to be added)
- without having to manually download from a website and moving the files to the instance folder

Which in both cases I have seen people struggle with and ask for help.

Since FO also includes Optifine parity mods I thought this one would fit right in.

### Why shouldn't it be in the modpack

Does not have CurseForge support, so some packs that a user might want could be not available.

Could get overlooked/missed, since the mod only presents itself in the form of 2 smaller buttons inside the respective menus.

### Additional details

Since FO comes with some packs pre-installed, I am unsure what would happen to packs installed afterwards through this mod when FO updates with a RP override or something (but then those same concerns arise from just installing additional packs through traditional means)

**Comment by Madis0** [comment]
I don't like adding features that already exist in good launchers (CurseForge Launcher, Modrinth App, Prism Launcher) because that's redundant for most and specifically encourages vanilla launcher use. While there is still planned to make a vanilla installer for FO, the recommended way will remain to be installs from custom launchers.
