### ISSUE TITLE
Borderless Mining

### ISSUE THREAD

**Issue by CodeF53** [Fabulously-Optimized/fabulously-optimized#78]
# Borderless Mining
## [Curseforge](https://www.curseforge.com/minecraft/mc-mods/borderless-mining) &nbsp; [Github](https://github.com/comp500/BorderlessMining)  

**What it does**
Makes the fullscreen option use a borderless window that fills the screen, allowing you to have Minecraft open on one monitor, while using other programs on another monitor - as normally Minecraft minimizes when you unfocus it. 
Adds an option for disabling the mod ingame, and has a configuration menu accessible through Mod Menu.

**Why should it be in the modpack**
So minecraft doesn't constantly minimize itself when you tab out.

**Why shouldn't it be in the modpack**
Some people may not like it.
 - Perhaps have it disabled by default in options.txt #30.

**Categories**

- [ ] Performance optimization
- [ ] Graphics optimization
- [x] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Comment by CodeF53** [comment]
While it doesn't currently support 1.17, it has a pull request that will make it support it.
https://github.com/comp500/BorderlessMining/pull/12

**Comment by Madis0** [comment]
I remember it being suggested before, and my reasoning was:
>  To me the mod seems to fix something few players would want instead of being a general-purpose mod for everyone. People also report issues with screenshots, screen recording and overlays...

In terms of your argument
> So minecraft doesn't constantly minimize itself when you tab out.

well, the pack already has Dynamic FPS so it doesn't really matter if it minimizes or not, because it's 1 FPS anyway :D

I know there are several games that have this option, but right now, in computers supported by Minecraft 1.17, does it really improve the performance for anyone? I would like to hear from those whom it does for.

**Comment by CodeF53** [comment]
It's not about performance.

Given a multi monitor setup, when a user clicks into discord or something
to copy something over from their instance of minecraft, it closes.
Also, in setups with lower specs, it can take awhile for minecraft to open
back up again after it minimizes itself.

The problems with screen recording/screenshots are kinda BS, (it actually
makes screen recording easier imo), but that's why I suggested it be
disabled by default.

**Comment by Madis0** [comment]
Alright, will consider when the 1.17 version comes out.

**Comment by Felix14-v2** [comment]
> While it doesn't currently support 1.17

Borderless mining 1.0.6 for Minecraft 1.16 works fine in MC 1.17 even without code rewriting. You just need to remove dependency on minecraft 1.16 from the fabric.mod.json.

**Comment by Madis0** [comment]
@Felix14-v2 https://github.com/comp500/BorderlessMining/issues/13#issuecomment-871636344

**Comment by CodeF53** [comment]
https://modrinth.com/mod/borderless-mining-reworked

**Comment by Madis0** [comment]
https://www.curseforge.com/minecraft/mc-mods/borderless-mining-reworked 
as well

**Comment by Madis0** [comment]
[It is now available for 1.17.1.](https://www.curseforge.com/minecraft/mc-mods/borderless-mining/files/3549149)
I think I'll add it to 1.18 once it comes available there and then backport to 1.17.1 afterwards.

**Comment by nsde** [comment]
I think this would be really useful for speedrunners, as LiveSplit for example has to overlay the game, which doesn't work on fullscreen.

**Comment by CodeF53** [comment]
It's now available for 1.18 on modrinth and curseforge

**Comment by nsde** [comment]
Great!

**Comment by Madis0** [comment]
Added to 2.6.0 and other current versions, although disabled by default as it doesn't work with the Sodium Extra's resolution slider.
