### ISSUE TITLE
FabricSkyBoxes is broken by another mod

### ISSUE THREAD

**Issue by OilFreak** [Fabulously-Optimized/fabulously-optimized#785]
### Describe the bug

Custom Sky Boxes will flicker when looking around. Upon disabling all _FO_ mods except FabricSkyBoxes and its dependencies, skyboxes will work as intended.

### Modpack version

5.6.4

### Launcher

MultiMC

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
How can your custom skyboxes work without the mod? What resource pack are you using?

**Comment by OilFreak** [comment]
DookuCraft

**Comment by Madis0** [comment]
Okay. Give logs too.

**Comment by Madis0** [comment]
Tested [Dokucraft High](https://dokucraft.co.uk/resource-packs/high/) on FO 5.6.4 and 5.8.0-beta.2 - no flickers. That said, on 5.8.0-beta.2 Sodium [complains about the resource pack](https://wiki.download.fo/readme/resource-pack-issues#core-shaders-incompatible-with-sodium), so some issues are indeed plausible, which need to be changed by the resource pack author.

Again, if you could send logs (right click on the instance → Minecraft Folder → logs → drag latest.log into this textbox), there is a possibility we can help you better.

**Comment by Madis0** [comment]
No response, cannot confirm myself.
