### ISSUE TITLE
BadOptimizations

### ISSUE THREAD

**Issue by ItsThosea** [Fabulously-Optimized/fabulously-optimized#787]
### CurseForge link

https://curseforge.com/minecraft/mc-mods/badoptimizations

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/badoptimizations/

### Source/other link

https://github.com/ItsThosea/BadOpitmizations

### Mod file size

~370 KB

### License

(any other license)

### What it does

- Cancels lightmap updates if unnecessary
- Caches current sky color to avoid recalculating it
- Prevents calling some methods when not needed e.g. debug renderers without debug nodes

### Why should it be in the modpack

- Very simple. Config to disable possibly problematic optimizations.
- Improves performance. On my own testing with Fabulously Optimized 1.20.4 (I have an RTX 3060 and a 12th gen i7-12700):
   - 1926-1955 FPS without BadOptimizations and without any toasts:
   -   <img src="https://github.com/Fabulously-Optimized/fabulously-optimized/assets/104597976/523f9117-5dfb-469a-a1e3-2e5c32597057" width="256">
   - 1351-1384 FPS without BadOptimizations and with advancement toasts:
   -   <img src="https://github.com/Fabulously-Optimized/fabulously-optimized/assets/104597976/859f710b-036e-4080-9e94-ceaaf5a9bbf9" width="256">
   - 2008-2023 FPS with BadOptimizations and without any toasts:
   -   <img src="https://github.com/Fabulously-Optimized/fabulously-optimized/assets/104597976/a27fcfab-c9ac-4fb0-9dfa-fc2efc61b2f4" width="256">
   - 1414-1458 with BadOptimizations and with advancement toasts:
   -   <img src="https://github.com/Fabulously-Optimized/fabulously-optimized/assets/104597976/5a01d4a7-0789-465d-a08f-aaa54386deb7" width="256">

### Why shouldn't it be in the modpack

- Performance impact is usually small but mostly varies on PC.
- Might have some hidden compatibility issues.

_1/3/2024 edit: adjust for 1.5.0
5/10/2024 edit: I can't stand to read the old thing I typed out even tho this got rejected_

**Comment by cochcoder** [comment]
I've done some testing and I can conform that this decrease of performance is due to not liking Intel iGPUs, I have made a issue on this mod's github page to track any improvments: [#20](https://github.com/ItsThosea/BadOptimizations/issues/20)

**Comment by cochcoder** [comment]
@Madis0 my issue has been fixed and this mod would make a great addition to this modpack!

**Comment by Madis0** [comment]
Maybe. Could reevaluate the mod after 1.20.5 is released and in a reasonably stable state.

**Comment by ItsThosea** [comment]
Oh.right...1.20.5...🫠

**Comment by nyabinary** [comment]
> Maybe. Could reevaluate the mod after 1.20.5 is released and in a reasonably stable state.

1.20.6 is out now :3

**Comment by Madis0** [comment]
> > Maybe. Could reevaluate the mod after 1.20.5 is released and in a reasonably stable state.
> 
> 1.20.6 is out now :3

Well, FO for 1.20.6 is not in a stable or even beta state yet. Still, you are free to test the mod to see if it still has any benefit in FO.

**Comment by Niterux** [comment]
BadOptimizations breaks Polytone (with a Polytone-compatible resource pack equipped) at the moment, I've also had issues with it turning the sky completely grey. For how micro-optimizations-ey these changes seem it feels like it's not worth to add it to the modpack for the instabilities and incompatibilities it causes.

**Comment by ItsThosea** [comment]
I fixed that issue a long time ago, ive just been heavily procrastinating to push them.

**Comment by nyabinary** [comment]
Seems to improve FPS a lil bit for me :p

**Comment by girshcatt** [comment]
> BadOptimizations breaks Polytone (with a Polytone-compatible resource pack equipped) at the moment, I've also had issues with it turning the sky completely grey. For how micro-optimizations-ey these changes seem it feels like it's not worth to add it to the modpack for the instabilities and incompatibilities it causes.

Is this happening with newest polytone and sodium 0.6.0 beta 2? Give me some resource packs to test please
