### ISSUE TITLE
Change release type on GitHub

### ISSUE THREAD

**Issue by Tiagoquix** [Fabulously-Optimized/fabulously-optimized#791]
### What config to change

For releases on GitHub that are not final (i.e. are either "alpha" or "beta"), release it as `Pre-release` (orange tag) instead of `Release` (green tag).

### Why should it be changed

Because releases that are not final should not be tagged as something that is final.

**Comment by Madis0** [comment]
Indeed, that's the intent - fixed now. Must've forgotten due to the current build process issue - #462.
