### ISSUE TITLE
MemoryLeakFix

### ISSUE THREAD

**Issue by cochcoder** [Fabulously-Optimized/fabulously-optimized#793]
### CurseForge link

No longer mantans on CurseForge

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/memoryleakfix

### Source/other link

https://github.com/FxMorin/MemoryLeakFix

### Mod file size

49.34 KB

### License

(any other license)

### What it does

This mod applies various fixes to stop memory leaks. 

### Why should it be in the modpack

This mod allows memory usage to stay low and not get any higher than it should be. 

### Why shouldn't it be in the modpack

Not available on CurseForge.

**Comment by Madis0** [comment]
Huh, didn't notice that suggestion before.

Anyway, MemoryLeakFix used to be in FO and got removed when it stopped being compatible. Now it is available again, but I am skeptical that it actually benefits much (compared to ModernFix and FerriteCore), and I've heard of potential incompatibilities with some other (non-FO) mods.

So, I decided not to reinclude the mod unless someone requests it (you) and provides good arguments on why I should reintroduce the mod.

**Comment by cochcoder** [comment]
Outside of the current and future memory leaks that this mod will fix, I have also noticed that it increases memory utilization by 30%. While this may seem backwards, it does hold some benefits. Such as making areas that render thousands of entities feel more responsive and smoother, as well as improving chunk loading. Before I would be able to fly into unloaded chunks and it wouldn't be able to keep up with me, after the mod was added there would always be one or two chunks ahead of me. On top of this, the frame rate was more stable/smooth as I was loading and unloading chunks with and without buildings. I'd like to note that throughout of all of this I never went past 55% memory utilization of 4GB while before it never went above 25% ululation. 

Stigmatization: 

      - Memory utilization up to 55% rather than 25% when using 4GB of ram
      - Faster chuck loading
      - More responsive in high entity areas
      - More stable/smooth frame rate *smooth as in the frame rate would decrease without too much jitter/jumps

**Comment by Madis0** [comment]
Indeed it does seem backwards, as 3 of your mentioned things are to be done through other mods, that take the goal of using less RAM for the same purpose, such as ModernFix. Additionally, the dev himself said he doesn't have much time to fix bugs/work on this mod at the moment.

**Comment by cochcoder** [comment]
> Indeed it does seem backwards, as 3 of your mentioned things are to be done through other mods, that take the goal of using less RAM for the same purpose, such as ModernFix.

Yes, but you can't deny that this mod makes complex chunks (chunks that have large amount of entities, redstone machines, and complex builds) and loading chunks a lot more responsive at the cost of using up to 2.2GB rather than 1GB.

> Additionally, the dev himself said he doesn't have much time to fix bugs/work on this mod at the moment.

In my past experience with this mod there would rarely have any issues apart from not always being available for the newest version of MC due to the slow update cycles.

**Comment by Sir-Crazynut** [comment]
I don't have quite the technical description of how well the mod works, but I install it myself next to FO and loads of other mods and I have never had any problems with incompatibilities (having only used the 1.20.4 beta), while having noticed the same smoothness with chunks loading. I have particularly noticed faster loading times for new world/chunk generation with MemoryLeakFix

**Comment by cochcoder** [comment]
It seems like this mod happens to improve the utilization of available memory. I plan on doing some more tests, like limiting available memory, once the dev gets some time to update the mod.

**Comment by TheBossMagnus** [comment]
The developer stated that the mod has little to no effect on the modern mc versions and by such is no longer maintained

**Comment by cochcoder** [comment]
> The developer stated that the mod has little to no effect on the modern mc versions and by such is no longer maintained

Where does the dev state that?

**Comment by TheBossMagnus** [comment]
> > The developer stated that the mod has little to no effect on the modern mc versions and by such is no longer maintained
> 
> Where does the dev state that?

[here](https://discord.com/channels/636633673524969483/999495893956956250/1247485982253518868) ([via](https://discord.gg/RTzTUbvw))

**Comment by cochcoder** [comment]
Can you send a screenshot?

**Comment by TheBossMagnus** [comment]
sure
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/92474350/d98acf39-571d-4a24-ace5-102f1aa0374e)

**Comment by cochcoder** [comment]
> sure ![image](https://private-user-images.githubusercontent.com/92474350/345154968-d98acf39-571d-4a24-ace5-102f1aa0374e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NDU4OTcsIm5iZiI6MTcxOTk0NTU5NywicGF0aCI6Ii85MjQ3NDM1MC8zNDUxNTQ5NjgtZDk4YWNmMzktNTcxZC00YTI0LWFjZTUtMTAyZjFhYTAzNzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE4Mzk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwYTc2YTM0ZWNjNDg0N2Q1OTA2OWFkNzk3YmQyYjE5ZDVlNjgwN2Y3OTg0NGU5YTk1OTk1NTVhZDFlMDA1OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5MK1LJejnF8PwEstQ3U-W1-l7klMmR5oj4Ee1MIgap8)

Thx, why haven't they archived the project or added a notice?

**Comment by TheBossMagnus** [comment]
Ask them, I'm not FX🤣...

**Comment by cochcoder** [comment]
Forgot to close this...
