### ISSUE TITLE
RyoamicLights

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#797]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/ryoamiclights

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/ryoamiclights

### Source/other link

https://github.com/ThinkingStudios/RyoamicLights

### Mod file size

409.64 + 204.22 = 613.86KB

### License

(any other license)

### What it does

LambDynamicLights forward-ported, using Architectury build process and ObsidianUI (204KB lib)

### Why should it be in the modpack

LambDynamicLights is not yet available in 1.20.6 and its dev explicitly said to be busy right now

### Why shouldn't it be in the modpack

- Potential for drama a la #718
   - Although Lambda was not necessarily against (Neo)Forge ports, and may not be against Fabric-to-Fabric ports
   - Notably Lambda planned to relicense her mods
- The original should still be updated relatively soon

**Comment by onurmercury** [comment]
LambDynamicLights now works with [this patch](https://github.com/LambdAurora/LambDynamicLights/compare/1.20.2...joestr:LambDynamicLights:1.20.4-support).

**Comment by tomocrafter** [comment]
It seems original one just updated today to support 1.20.4
https://github.com/LambdAurora/LambDynamicLights/releases/tag/v2.3.4%2B1.20.4

**Comment by Madis0** [comment]
Yup.

**Comment by n0proxy** [comment]
Is this being reconsidered for 1.21?

**Comment by mpustovoi** [comment]
It seems that [LambDynamicLights](https://github.com/LambdAurora/LambDynamicLights ) will have a 1.21 release soon, so there will be no need for RyoamicLights from then on.
Although, RL could be a temporary replacement for LDL (even though RL contains its own unique dependency), since it's been already supporting versions from 1.20.5 to 1.21.1.
I've been using RL all this time, and I haven't seen any problems.

**Comment by Madis0** [comment]
Rejected due to licensing concerns.

> I'm well aware there are at least two updated forks of LDL [including this one], however the original creator of LDL does not seem to like Fabric forks of it [...].

**Comment by mpustovoi** [comment]
Well, then I don't get it why LDL is marked with an MIT license.
