### ISSUE TITLE
ShulkerBox Tooltip and BetterF3

### ISSUE THREAD

**Issue by SxliHahaYez** [Fabulously-Optimized/fabulously-optimized#798]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip , https://www.curseforge.com/minecraft/mc-mods/betterf3

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/shulkerboxtooltip , https://modrinth.com/mod/betterf3 

### Mod file size

Shulkertooltip: 1.16 MiB.  BetterF3: 1.69 MiB.

### License

(any other license)

### What it does

Shulkertooltip shows the content in a preview manner of a shulker box and other containers as-well like chests with nbt data without having to place it and opening the shulker box the mod is configurable to the way you want the preview to be.

BetterF3 it simplifies and makes the F3 menu more easy to understand and this one is also configurable to personalize how you want the F3 menu to be removing and adding features  to the F3 menu.

### Why should it be in the modpack

Shulkertooltip is a quality of life mod that does a little tweaking to a feature in minecraft that causes mild inconvenience for most people and fixes it.

BetterF3 makes the F3 menu more easy to understand for people that are not that technical into minecraft making it readable for everyone and its more easy on the eye.

### Why shouldn't it be in the modpack

Shulkertooltip may not be that useful for much people as it is a little issue that they dont really phase thru in the end game where they have shulkers.

BetterF3 i cant really find a problem of this mod sorry :( it may be that it is a little tedious to configure it

**Comment by notlin4** [comment]
Please refer to #798, #639, and #2.
Also, if there are suggestions involving multiple mods, they should be separated.
