### ISSUE TITLE
IP As Server Name

### ISSUE THREAD

**Issue by RedVortexDev** [Fabulously-Optimized/fabulously-optimized#815]
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/ip-as-server-name

### Source/other link

https://github.com/Now-this-is-crazy/IPAsServerName

### Mod file size

14.01 KiB

### License

MIT

### What it does

The mod makes it so when adding a new server to the server list and a name isn't provided, it will get saved with the IP as the server name

### Why should it be in the modpack

The mod is really helpful in instances where the player has many servers in their server lists, some offline, some deleted, etc. making it so the player doesn't need to go into the Edit menu to find out what the server is (to maybe decide if to delete the server or not).
There have been uncountable times where I have found myself in this exact situation since sometimes providing a server name sometimes is just too annoying.

### Why shouldn't it be in the modpack

The mod is very minor, and you can find out what the server is if by just if its online (MOTD)

### Additional details

The mod should work on all versions of the game, making it instantly upgradeable to future versions of the game

**Comment by Madis0** [comment]
Sorry, I don't see the value. If the user wants it, it is trivial to do it with vanilla tools, no mod needed.
- If the server is online, it should have a proper MOTD and icon
- If the server is offline, knowing the IP won't help you that much anyway
- The mod would bring back a privacy concern that Minecraft 1.6 actually removed (option `hideServerAddress`).
