### ISSUE TITLE
CIT Resewn Fork

### ISSUE THREAD

**Issue by UltimatChamp** [Fabulously-Optimized/fabulously-optimized#818]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/cit-fork

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/cit

### Source/other link

https://github.com/UltimatChamp/CustomItemTextures

### Mod file size

387.86 KiB

### License

MIT

### What it does

MCPatcher's CIT w/o OptiFine. A reliable fork of CITResewn!

### Why should it be in the modpack

- Optifine parity!
- The original mod may not get updated until 1.21, since the author's been dormant, since mid-Jan.
- There's already a positive consensus on a CIT Resewn fork.
- Contains some bug fixes from the existing PRs on GitHub.

### Why shouldn't it be in the modpack

idk, y not?

### Additional details

- ~~The mod is, currently, under 'Review' on Modrinth.~~
- This is a temporary fork. The mod will be archived once the original mod gets updated.

**Comment by UltimatChamp** [comment]
Now, listed on Modrinth, too!

**Comment by Madis0** [comment]
Added in 5.8.0.
