### ISSUE TITLE
Mobs have laggy and jumpy movement in single player

### ISSUE THREAD

**Issue by BigFatGandalf** [Fabulously-Optimized/fabulously-optimized#820]
### Describe the bug

In a single-player world, mobs have delayed hit reactions and movement, occasionally jumping to a different spot as well. 

### Modpack version

5.6.3

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
Please update to the latest version and retry.

**Comment by BigFatGandalf** [comment]
> Please update to the latest version and retry.

The latest update seems to have fixed the issue, thank you!
