### ISSUE TITLE
Very low fps

### ISSUE THREAD

**Issue by AceVisconti49** [Fabulously-Optimized/fabulously-optimized#823]
### Describe the bug

Hello modpack creator! I have a problem with this modpack. When I downloaded it, Fabrik wrote to me about a compatibility problem with several mods. After that, I went to the vanilla version of Minecraft and I started having strong FPS drawdowns and freezes, although this had not happened before. Unfortunately, the reinstallation did not work, I want to return the old fps back, how can I do this?

### Modpack version

5.8.0

### Launcher

Minecraft Launcher (vanilla)

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
Your text implies that you're using FO with added custom mods, and I do not know which mods they are. Please test FO without adding other mods first, and report back if FPS is better in that case.

**Comment by AceVisconti49** [comment]
Before downloading the modpack, I didn't have any mods. After downloading the fabric and the modpack that appeared in the game, I got an error: incompatible mods were found! net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or with each other! A potential solution has been found that can solve your problem: - Install cloth-config version 11.0.99 or later. More detailed information: - The mod "Additional culling" (moreculling) 1.20.4-0.22.1 requires the version of cloth-config 11.0.99 or later, which is missing! on net.fabric

**Comment by Madis0** [comment]
That is odd and should never happen. Please try to follow the instructions again: https://download.fo/install

**Comment by AceVisconti49** [comment]
I just want to know why my fps was normal before the jump, and then the lags started

**Comment by Madis0** [comment]
I just want to ensure that you even installed the mod pack properly, because by following the instructions the Fabric errors should not show up. By improper install, various issues can occur.

**Comment by AceVisconti49** [comment]
Can I somehow completely delete these files to get my old fps back?

**Comment by Madis0** [comment]
Sure. 
Fabulously Optimized adds its content to `mods`, `config` and `resourcepacks` folders, all of which are located in `%appdata%\.minecraft` (presuming you're using Windows). Removing Fabric Loader overall is a bit more elaborate, but you can switch to a different installation or delete it in your launcher.

**Comment by Madis0** [comment]
Were you able to solve your issues?
