### ISSUE TITLE
Fast Paintings

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#824]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/fast-paintings

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/fast-paintings

### Source/other link

https://github.com/MehVahdJukaar/FastPaintings

### Mod file size

146.73 KiB + 869.18 KiB = 1015.91 KiB

### License

All Rights Reserved / ARR

### What it does

Optimizes paintings, like #23 optimizes (other?) block entities

### Why should it be in the modpack

For the same reason as (other?) block entities are optimized, paintings could also use optimization

### Why shouldn't it be in the modpack

- According to Modrinth, it is required on client and server. Not sure if that's an error or what is the technical reason for that if true.
- According to CurseForge, it changes vanilla behaviour by adding new mechanics like particles. Not sure if these can be disabled
- Requires a huge library
- Is ARR, even though source is available - may hinder its sustainability

### Additional details

As suggested in https://legacy.curseforge.com/minecraft/modpacks/fabulously-optimized/?comment=998

**Comment by Madis0** [comment]
> The Modrinth Page seems compiled inaccurately as seen in the issue
> Also it might be redundant cause moreculling
> - TheBossMagnus

> iirc, prevents from joining Hypixel, due to Moonlight Lib (869KiB).
> - UltimatChamp

> seems like an extremely invasive(for an optimization mod) both-side change
> turning paintings into blocks will bring a significant amount of unsolvable parity issues and I'd be firmly against
- skyevg

https://discord.com/channels/859124104644788234/1221872453035495624/1221872453035495624
[(via)](https://download.fo/discord)

Per those issues, closed.

**Comment by Fyoncle** [comment]
> > The Modrinth Page seems compiled inaccurately as seen in the issue
> > Also it might be redundant cause moreculling
> > 
> > * TheBossMagnus
> 
> > iirc, prevents from joining Hypixel, due to Moonlight Lib (869KiB).
> > 
> > * UltimatChamp
> 
> > seems like an extremely invasive(for an optimization mod) both-side change
> > turning paintings into blocks will bring a significant amount of unsolvable parity issues and I'd be firmly against
> > 
> > * skyevg
> 
> https://discord.com/channels/859124104644788234/1221872453035495624/1221872453035495624 [(via)](https://download.fo/discord)
> 
> Per those issues, closed.

Per what issues? The link is wrong
