### ISSUE TITLE
Disconnected from specific server when chat message is sent

### ISSUE THREAD

**Issue by Thensi72** [Fabulously-Optimized/fabulously-optimized#825]
### Describe the bug

When on Minemalia Creative(ip: play.minemalia.com and then click servers then click creative) and a chat message is sent, you get disconneted from the server.

### Modpack version

5.8.0

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

here is picture(of when i sent the message "a" in chat) and log and 2nd picture possibly related(before the disconnection):
log: https://mclo.gs/jNS2Gkf
![2024-03-25_03 51 46](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/79134753/cffb6ee2-c4c9-4fce-b521-ee0fe3e917b6)
![2024-03-25_03 52 19](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/79134753/50521918-fb40-4b4c-9cb7-9e2404796eab)

**Comment by Madis0** [comment]
Well, they do say "use 1.20.1 for best experience" so it may be a server bug. Try the equivalent version of FO.

**Comment by Madis0** [comment]
That said, you're using offline mode, so you're on your own.
