### ISSUE TITLE
Crash when changing resolution

### ISSUE THREAD

**Issue by bowhero22** [Fabulously-Optimized/fabulously-optimized#827]
### Describe the bug

Fabulously Optimized just crashes when changing resolution from Video Settings > Fullscreen Resolution.
(I just used pure Fabulously Optimized modpack with no mods added.) 

Java vendor : GraalVM
Java version : 17
Crash Log : 
[hs_err_pid9980.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/14810477/hs_err_pid9980.log)

Fabric Log : 
[latest.log](https://github.com/Fabulously-Optimized/fabulously-optimized/files/14810479/latest.log)

### Modpack version

5.8.1

### Launcher

MultiMC (auto-update)

### Confirm

- [x] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
Please try Adoptium or Oracle Java.

**Comment by Madis0** [comment]
Closed due to lack of response. Others can confirm it works well with suggested JVMs (my previous comment).
