### ISSUE TITLE
Stuck on 60 fps

### ISSUE THREAD

**Issue by Arturcik22** [Fabulously-Optimized/fabulously-optimized#833]
### Describe the bug

Ive been going trought every mod and cand find why im stuck on 60 fps. Even if I disable v sync and the framerate to unlimited still the same. Please help this modpack is supposed to give more fps not cap it

### Modpack version

5.9.2

### Launcher

Minecraft Launcher (vanilla)

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

![2024-04-21_15 02 14](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/166835147/4c4f5764-c3d5-4e12-9655-737ef049c355)
![2024-04-21_15 02 20](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/166835147/7137cded-d3c2-43b6-8b97-08be37d8b2a4)

**Comment by Madis0** [comment]
Please ensure your drivers are up to date and your GPU knows Minecraft is a game. See here: https://wiki.download.fo/readme/improving-performance

**Comment by Arturcik22** [comment]
> Please ensure your drivers are up to date and your GPU knows Minecraft is a game. See here: https://wiki.download.fo/readme/improving-performance

Of course I am, Minecraft vanilla runs more than 60fps without this modpack

**Comment by Madis0** [comment]
That is plausible, but did you follow the instructions?
