### ISSUE TITLE
Remove ModDetectionPreventer

### ISSUE THREAD

**Issue by JustAlittleWolf** [Fabulously-Optimized/fabulously-optimized#834]
### Original issue

https://github.com/Fabulously-Optimized/fabulously-optimized/issues/802

### Why should it be in the modpack

To prevent servers from looking into what mods are installed on the client.

### Why shouldn't it be in the modpack

The developer of the mod (me) has recently lost interest in the project, and it seems like server admins have found another way to see what mods are installed. This has led to at least one ban (https://github.com/JustAlittleWolf/ModDetectionPreventer/issues/6), most likely as a direct consequence of having this mod installed. In the current state that makes the mod a hazard for some players.

### Confirm

- [X] This mod removal request was written in good faith, taking into consideration why the mod was added in the first place. This is not a mod replacement request - for that purpose I should use the normal mod request form.

**Comment by Madis0** [comment]
_Sigh._ Sad to hear, but will make the change soon.

**Comment by Madis0** [comment]
5.10.0 and 5.11.0-alpha.1 have been released with the mod removed. Thank you!
