### ISSUE TITLE
[UPDATE] Capes 1.5.3 (1.20.4 MAX)> Capes (1.20.5+)

### ISSUE THREAD

**Issue by alex89912** [Fabulously-Optimized/fabulously-optimized#836]
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/capes

### Mod file size

75.45 KiB

### License

(any other license)

### What it does

Crashes instanly on clicking the button in Skin Customization

### Why should it be in the modpack

It already is

### Why shouldn't it be in the modpack

Idk

**Comment by Madis0** [comment]
Yep, will be done with the next update.

**Comment by alex89912** [comment]
Thanks!
