### ISSUE TITLE
Make syncChunkWrites false by default

### ISSUE THREAD

**Issue by Kichura** [Fabulously-Optimized/fabulously-optimized#839]
### What config to change

`syncChunkWrites=true` -> `syncChunkWrites=false` via the vanilla's `options.txt` file.

### Why should it be changed

By default this feature causes region files to be opened in synchronous mode and is only enabled in Windows since 1.16 Pre-Release 3, However it has some unintended side effects such as causing world savings to become horribly slower than expected which is apparent in certain Linux distros when exiting minecraft servers using the `stop` command.

### Additional details

While this doesn't really change anything in terms of optimizations *(or might for some?)*, it does resolve some annoyances when dealing with backend lags in this case. However this is disabled by default on many servers such as PaperMC which is the reasoning why i thought of making this issue in first place.

**Comment by Madis0** [comment]
I'm confused. [The wiki](https://minecraft.wiki/w/Options.txt) and your post says it is enabled by default on Windows, but you mention that "world savings become horribly slower [...] in certain Linux distros [...]".

So what does it have to do with Windows?

**Comment by Kichura** [comment]
> I'm confused. [The wiki](https://minecraft.wiki/w/Options.txt) and your post says it is enabled by default only on Windows, but you mention that "world savings become horribly slower [...] in certain Linux distros [...]".
> 
> So what does Linux distro slowness have to do with Windows?

This option is actually the default on vanilla servers which means it's still bad to leave it enabled, but since managing region files in synchronous mode is absolute crap regardless of OS - pretty much should not be enabled at all in case any more performance loss happen.

**Comment by Madis0** [comment]
> This option is actually the default on vanilla servers [regardless of the OS] 

So... it is a server problem, if it is default enabled on there but not on all clients?

I feel like there is not really a reason for FO to touch it, considering Mojang did not add any UI option to touch it, and because FO has FastQuit anyway.

**Comment by Kichura** [comment]
> > This option is actually the default on vanilla servers [regardless of the OS]
> 
> So... it is a server problem, if it is default enabled on there but not on all clients?
> 
> I feel like there is not really a reason for FO to touch it, considering Mojang did not add any UI option to touch it, and because FO has FastQuit anyway.

FastQuit does not solve the problem when the value was set to true, therefore this is not an ideal workaround for that.

**Comment by Madis0** [comment]
Decided against this, do not want to risk it.
