### ISSUE TITLE
No Mining Cooldown

### ISSUE THREAD

**Issue by luhgarlicbread** [Fabulously-Optimized/fabulously-optimized#840]
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/no-mining-cooldown

### Source/other link

https://github.com/Daxanius/NoMiningCooldown

### Mod file size

18.5 KB

### License

(any other license)

### What it does

Removes the ~300ms delay between breaking blocks in Minecraft. It provides a noticeable improvement to gameplay!

### Why should it be in the modpack

The mod will benefit everyone by allowing us to mine blocks faster. Simple! The vanilla Minecrat experience will remain as the mod does not alter anything than removing the ~300ms delay between breaking blocks.

### Why shouldn't it be in the modpack

The only downside I can think of is that it's toggleable and idk if it's on by default, though I think it is. The toggle bind can be set under miscellaneous in the controls settings, and when you toggle it, there is a message indicator displayed in chat.

### Additional details

This mod is awesome and really has provided and noticeable improvement to my Cubecraft Skyblock gaming!! :D

**Comment by Madis0** [comment]
Unexpected and cheaty/anticheat concern.
