### ISSUE TITLE
Animated textures lag

### ISSUE THREAD

**Issue by ToPlayer6478** [Fabulously-Optimized/fabulously-optimized#854]
### Describe the bug

If you look at an animated object or block (From a third-party resource pack), the FPS drops from 160-180 to 30-50, and if there are a lot of objects, the effect also multiplies and the game may simply hang. In my situation, I installed a resource pack with an animated dancing Hu Tao from the Genshin Impact game, before installing the modpack, the resource pack worked fine, there were no FPS drops, but after playing on the server, I decided to buy a totem of immortality on / ah, and going to the totems section, I simply hung up. Please fix this bug or tell me which mod affects third-party animated textures

The text was written with the help of a translator and may contain errors, I apologize in advance

LAUNCHER IS NOT CURSEFORGE APP
My launcher is Legacy Launcher

### Modpack version

5.6.6

### Launcher

CurseForge App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

LAUNCHER IS NOT CURSEFORGE APP
My launcher is Legacy Launcher
![изображение](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/135963040/9c60dba3-57cd-4368-9dc1-35a3fac1db3c)
![изображение](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/135963040/7de9e402-510a-41a0-8d4c-5d7d30fa41ba)

**Comment by Madis0** [comment]
> which mod affects third-party animated textures

Animatica affects those, so you can try replacing it with MoreMCMeta.

That said, you are clearly using an unsupported launcher and you have added custom mods, so this issue is considered invalid. If you switch to [any of our supported launchers](https://download.fo/install), feel free to come to our Discord and get more help.
