### ISSUE TITLE
1/20/6 broken

### ISSUE THREAD

**Issue by lynrayy** [Fabulously-Optimized/fabulously-optimized#855]
### Describe the bug

When i add my config from 1.19.4 game not starts because 
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/59417884/7c196833-892e-47a8-a36c-f1f9ed04fd33)

And even if i removing config, game still not starts - i must reinstall modpack

### Modpack version

https://i.imgur.com/vbPsuT4.jpeg

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by lynrayy** [comment]
P.s i am not moving any mod files between modpacks

**Comment by Kichura** [comment]
Update indium.

**Comment by lynrayy** [comment]
Not working!!!

> Update indium.

**Comment by lynrayy** [comment]
https://youtu.be/H256e0geP8c

**Comment by TheBossMagnus** [comment]
Probably something went wrong in the transfer process.
Check if fabric-dependency-overrides.json is present in the config folder.

**Comment by TheBossMagnus** [comment]
> Probably something went wrong in the transfer process.
> Check if fabric-dependency-overrides.json is present in the config folder (and if it's like the one in the 1.20.6 pack)

**Comment by lynrayy** [comment]
I don't have this one
Only fabric_loader_dependencies.json

**Comment by TheBossMagnus** [comment]
My bad, the one you said is the one to be checked

**Comment by lynrayy** [comment]
They are different

**Comment by lynrayy** [comment]
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/59417884/f02ea769-6188-41d3-b02d-247b0161db64)

**Comment by Madis0** [comment]
That looks like you installed FO 4.5.3 at some point and did not [update it as indended](https://wiki.download.fo/readme/update-instructions#prism-launcher). For now you can just copy the fabric_loader_dependencies.json over if you want, but I highly recommend creating a new FO instance, moving your things there and in the future updating as instructed in FO wiki (link above).

**Comment by lynrayy** [comment]
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/59417884/0ca98bf2-0466-42c8-b785-f61ed7882fc9)
I just installed FO by this way

**Comment by lynrayy** [comment]
It can't be not updated or something

**Comment by lynrayy** [comment]
> Either way, just copy the file over.

Copy file from old modpack to the new, or NOT copy old file to the new config (preserve new fabric loader config file)?

**Comment by Madis0** [comment]
My bad, it might've just been a bug with Prism Launcher. Please update the launcher first and then [update FO with these instructions.](https://wiki.download.fo/readme/update-instructions#prism-launcher)

**Comment by lynrayy** [comment]
My old modpack is broken because i was tampering with mods, i can't update this way
I need to transfer my old config to the new modpack

**Comment by lynrayy** [comment]
> Copy file from old modpack to the new, or NOT copy old file to the new config (preserve new fabric loader config file)?

Yeah, looks like all problems because of this file. I must preserve it in new modpack

**Comment by lynrayy** [comment]
![image](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/59417884/f671c1c9-1bea-4d4a-97ae-aa65f6418a15)
Transfering like this helped
