### ISSUE TITLE
Hey Wiki

### ISSUE THREAD

**Issue by its-miroma** [Fabulously-Optimized/fabulously-optimized#856]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/hey-wiki

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/hey-wiki

### Source/other link

https://github.com/mc-wiki/minecraft-mod-heywiki

### Mod file size

118.31 KiB

### License

(any other license)

### What it does

Allows users to quickly open the Minecraft Wiki in-game, with useful keybinds/commands.

### Why should it be in the modpack

- Helpful for newbies, who may want to understand what a certain mechanic is
- Useful for experienced players, who may already consult the wiki regularly, as a QOL improvement
- Helps the transition away from Fandom
- _Minecraft: Bedrock Edition_ has similar in-game guides

### Why shouldn't it be in the modpack

- It promotes an external (although well established) website
- It adds non-vanilla commands to the game
- It does not support all languages (only those on <https://minecraft.wiki>)

**Comment by Madis0** [comment]
I can see the motivation why you suggested this mod, however I'll have to reject it:

- As evident by mod's own downloads, there isn't a very high interest for this vs similar mods like Jade and WTHIT.
- Bedrock Edition has _in-game_ guides indeed, this one leads out of the game.
- Requires learning the key.
- Fabulously Optimized is targeted for people who are new to modding or new to Java Edition, not new to Minecraft overall. For newer versions of the game, there are already a lot of resources to learn what's new.
