### ISSUE TITLE
Connected textures don't want to work well.

### ISSUE THREAD

**Issue by Njit2098** [Fabulously-Optimized/fabulously-optimized#858]
### Describe the bug

I've been having this issue for a few months now, can't figure out what causes it though...
![2024-06-18_20 10 53](https://github.com/Fabulously-Optimized/fabulously-optimized/assets/167520200/249c8107-1fe2-4286-9164-8937795fa77d)
(The glass isn't connecting very good)

Is this a driver problem or a mod-type of problem?

### Modpack version

1.21 (also verions below)

### Launcher

Modrinth App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
There is a glass-related resource pack bundled, is it also enabled for you?

**Comment by Njit2098** [comment]
There is "Default connected textures" and "Glass pane culling fix", both of them are on.

**Comment by Madis0** [comment]
Okay, in that case it is the Sodium translucent block culling issue, will be fixed when Sodium 0.6 releases.

**Comment by Njit2098** [comment]
Alright! Thanks for the help!! Have a good day :D
