### ISSUE TITLE
ViaFabricPlus

### ISSUE THREAD

**Issue by IzeAack** [Fabulously-Optimized/fabulously-optimized#859]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/viafabricplus

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/viafabricplus

### Source/other link

https://github.com/ViaVersion/ViaFabricPlus

### Mod file size

10.5 MB ([for 1.21 v3.4.0](https://github.com/ViaVersion/ViaFabricPlus/releases/tag/v3.4.0))

### License

any other license (GPL-3.0)

### What it does

Connection to older versions and new versions and bedrock edition

### Why should it be in the modpack

For bedrock players to play their exclusive servers and for older players to play old servers

### Why shouldn't it be in the modpack

[Could flag anti-cheats but is less likely compared to ViaFabric](https://github.com/ViaVersion/ViaFabricPlus/issues/13)
[Extra proof that could flag anti-cheats](https://github.com/ViaVersion/ViaFabricPlus/issues)
Bedrock featured servers don't work
[Can be a bit buggy](https://github.com/ViaVersion/ViaFabricPlus/issues)

### Additional details

Can play betacraft and classicube
Can play these versions:
"Release (1.0.0 - latest release)
Beta (b1.0 - b1.8.1)
Alpha (a1.0.15 - a1.2.6)
Classic (c0.0.15 - c0.30 including [CPE](https://wiki.vg/Classic_Protocol_Extension))
April Fools (3D Shareware, 20w14infinite)
Combat Snapshots (Combat Test 8c)
Bedrock Edition 1.21.0 ([Some features are missing](https://github.com/RaphiMC/ViaBedrock#features))"

**Comment by Madis0** [comment]
Rejected for the same reasons as #15.

**Comment by IzeAack** [comment]
ok
