### ISSUE TITLE
FarPlaneTwo

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#86]
**Mod name**
FarPlaneTwo

**Curseforge link**

**Other links**
https://github.com/PorkStudios/FarPlaneTwo

**What it does**

Renders high distances at low detail

**Why should it be in the modpack**

Potentially extreme performance improvement

**Why shouldn't it be in the modpack**

Very much in progress, Fabric support not yet confirmed

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

https://youtu.be/1QKktMk33QE

Edit: [Sodium is also working on this](https://discord.com/channels/602796788608401408/778685768041627719/882437766233849929) [(via)](https://jellysquid.me/discord), which will probably come way earlier than this mod.
Edit 2: the link above is now broken (channel deleted), but some info can be found by searching [on their Discord](https://jellysquid.me/discord) for "LoD". It has also been claimed that it may not be exactly the same thing, but a similar implementation.

**Comment by Rajbir98** [comment]
Its not updated to 1.16 or 1.17 am i right

**Comment by Madis0** [comment]
For now it is Forge 1.12.2, but the developer is looking after other versions (and possibly modloaders) when that is done.

**Comment by fredster33** [comment]
@Madis0 mind adding an invite to the server that the Sodium link is in? Otherwise, as I'm not in that server, I just see this. https://gyazo.com/3df49a4f9164e960312039d44106552f

**Comment by Madis0** [comment]
@fredster33 Ah, sorry, it is https://jellysquid.me/discord

**Comment by fredster33** [comment]
Got it, thanks :)

**Comment by nsde** [comment]
I guess we can close this for no, as there still isn't any Fabric version.

**Comment by Madis0** [comment]
Good point, #240 is a lot closer to being a real thing while this is just a future promise for now. 
News can be followed on https://github.com/PorkStudios/FarPlaneTwo/issues/16 though.
