### ISSUE TITLE
Itsbroken

### ISSUE THREAD

**Issue by Goodbye2d** [Fabulously-Optimized/fabulously-optimized#862]
### Describe the bug

so i got a TLauncher running 1.20.1 FO, but when i tried to launch, after about 10 second, it just said mod error, crashed. i trued reeinstalling library, i got no mods other than FO

### Modpack version

5.4.1

### Launcher

Minecraft Launcher (vanilla)

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Radk6** [comment]
TLauncher is confirmed spyware and is not supported by FO.
