### ISSUE TITLE
Datapack installer for ease of use with Modrinth app

### ISSUE THREAD

**Issue by Switch672** [Fabulously-Optimized/fabulously-optimized#864]
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/mod/dp-installer

### Source/other link

https://github.com/MacaylaMarvelous81/DatapackInstaller

### Mod file size

5.87 KiB

### License

(any other license, specifically MIT)

### What it does

Automatically copies data packs in **datapacks** (for Modrinth) or **installed_datapacks** folders to the world's temp folder. This allows datapacks to be installed from the Modrinth App, and potentially others, to be installed easily to worlds upon creation.

### Why should it be in the modpack

Datapacks are a vanilla feature, they're just kind of annoying to install.

### Why shouldn't it be in the modpack

It's not available on CurseForge, but I don't know if it even would have functionality in the CurseForge app.

### Additional details

It's completely standalone

**Comment by Madis0** [comment]
That seems like something the launchers should do themselves: let you pick the world to apply the data pack on upon install. That said, I don't even see the datapacks get installed now, because for me they don't appear in the instance's `datapacks` either.

**Comment by Madis0** [comment]
Should be done by the launcher(s) itself.
