### ISSUE TITLE
Borderless Mining vs. Cubes Without Borders

### ISSUE THREAD

**Issue by Tiagoquix** [Fabulously-Optimized/fabulously-optimized#869]
### Original issue

#814, #78

### Why should it be in the modpack

Cubes Without Borders seems to be the new and better alternative.

### Why shouldn't it be in the modpack

Borderless Mining seems to be... outdated?

### Additional details

https://github.com/Fabulously-Optimized/fabulously-optimized/blob/main/INCLUDED-MODS.md#functional

Both mods are described with same details, this is confusing. Why include both?

### Confirm

- [X] This mod removal request was written in good faith, taking into consideration why the mod was added in the first place. This is not a mod replacement request - for that purpose I should use the normal mod request form.

**Comment by Madis0** [comment]
> Both mods are described with same details, this is confusing. Why include both?

The table indicates that the latest stable versions from 1.16.5 to 1.19.4 used Borderless Mining, and the current stable version 1.20.4 uses Cubes Without Borders.
