### ISSUE TITLE
Recipe Cache

### ISSUE THREAD

**Issue by Madis0** [Fabulously-Optimized/fabulously-optimized#87]
**Mod name**
Recipe Cache

**Curseforge link**
https://www.curseforge.com/minecraft/mc-mods/recipe-cache

**Other links**
https://gitlab.com/biom4st3r/optimizedcrafting

**What it does**
"Caches recipe lookup for crafting and furnaces to lessen server lag caused by crafting stacks of items and large amounts of furnaces ticking"

**Why should it be in the modpack**

Could improve singleplayer crafting and smelting performance, seems better supported than #41 / #43 

**Why shouldn't it be in the modpack**

May have the same issues as #41 and #43, haven't tested it yet

**Categories**

- [x] Performance optimization
- [ ] Graphics optimization
- [ ] New feature
- [ ] Optifine parity
- [ ] Fixes a bug/dependency
- [ ] Replaces an existing mod

**Additional details**

Waiting for input from mod devs who know about the technical side of this, pros and cons. Don't want to risk it for now.

**Comment by Rajbir98** [comment]
Its a nice mod I have tried it

**Comment by RozeFound** [comment]
Isn't this pack used to play on vanilla servers?

**Comment by Madis0** [comment]
> Isn't this pack used to play on vanilla servers?

The modpack can be used to play on any servers, don't quite get your question here.

The mod itself would only work on singleplayer, which is not ideal (similar to some features of Lithium), but the discussion here is that is the caching significant enough to feel that it is _faster_ in singleplayer? Does the crafting-smelting work as it should, every time? I'll try suggesting this in Lithium as well to get their input on it.

**Comment by RozeFound** [comment]
I mean, I've think this pack is mostly (or even only) for playing on servers not in singleplayer. But anyway I understand your point.

> that is the caching significant enough to feel that it is faster
Crafting/smelting does't seems like something that affecting performance at all. I don't think it worth the risk of broken smelting.

**Comment by Madis0** [comment]
There is no update yet, still looking for some "expert audit" to determine whether caching those things is a good idea or not. Have to be really careful because this mod is server-side (world-affecting) after all...

**Comment by Madis0** [comment]
Rejected for:
- being abandoned
- not on Modrinth
- seems "risky", no audit was received
