### ISSUE TITLE
Add MC version in release notes

### ISSUE THREAD

**Issue by Tiagoquix** [Fabulously-Optimized/fabulously-optimized#874]
This does not fit into any other issue type, so I think this is the most appropriate one.

I think it would be cool if every release on GitHub stated the version it's intended to.

For example: https://github.com/Fabulously-Optimized/fabulously-optimized/releases/tag/v5.10.3 is for 1.20.4, but there could be a line in the release notes saying "This is for Minecraft version 1.20.4".

That's all.

**Comment by Madis0** [comment]
Done for the first page of releases and the stable version. Too lazy to do for all of them 😁
