### ISSUE TITLE
Connected grass/glass and no easy way to disable it 

### ISSUE THREAD

**Issue by SergioK29** [Fabulously-Optimized/fabulously-optimized#879]
### What config to change

Why is grass/glass connected by default? Its quite jarring, not even optifine has connected grass by default anymore 

### Why should it be changed

There seems to be no way to even change it, i looked in video settings for 15 minutes

**Comment by Radk6** [comment]
Connected glass is enabled by default to match OptiFine. As for connected grass, it can be turned off by disabling the fast better grass resource pack (it'll be replaced with a mod in the future)

**Comment by Madis0** [comment]
> Why is grass/glass connected by default? Its quite jarring, not even optifine has connected grass by default anymore
> Connected glass is enabled by default to match OptiFine.

More specifically, it is enabled by default for _discoverability_ - if it wasn't enabled by default, a lot of people would not know that the modpack even provides it.

But yes, you can disable connected grass by disabling a resource pack, and same for glass if you're using the default resource pack. If not, then check out the mod settings of Continuity.
