### ISSUE TITLE
Add DarkTitleBar

### ISSUE THREAD

**Issue by Xleby4ek** [Fabulously-Optimized/fabulously-optimized#882]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/darktitlebar

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/darktitlebar

### Source/other link

https://git.froggi.es/williamist/DarkTitleBar

### Mod file size

19.8 KiB

### License

(any other license)

### What it does

A very simple minecraft mod to add a dark-mode title bar on Windows 10 1809 and above. (only if your system is in dark mode)

### Why should it be in the modpack

I have a dark version of Windows and all windows are dark except minecraft, it would be nice if it had a dark window too

### Why shouldn't it be in the modpack

It is useless on Linux and MacOS, but it does not interfere with anything

### Additional details

I like this mod, please add it

**Comment by TheBossMagnus** [comment]
Personally against it, it's such a minor thing that i don't think it's worth the additional time spent maintainance-wise
