### ISSUE TITLE
CTD when trying to open video settings

### ISSUE THREAD

**Issue by Artiscow** [Fabulously-Optimized/fabulously-optimized#887]
### Describe the bug

Always crash to desktop when trying to open video settings.
Does not happen with 6.1.0-beta.5 for 1.21.1

### Modpack version

6.1.0-Beta.7 for 1.21.1

### Launcher

Modrinth App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
Are you sure you have not updated any mods manually? Please send latest.log or latest crashlog.

**Comment by Artiscow** [comment]
Hm, reinstalled Beta 7 for the third time and now it works fine, maybe it was something on my end. Sorry about the trouble!
