### ISSUE TITLE
Crash when clicking on "Video Settings"

### ISSUE THREAD

**Issue by zozogame1** [Fabulously-Optimized/fabulously-optimized#895]
### Describe the bug

When I click on the video settings, the game just crashes.

### Modpack version

6.1.0

### Launcher

Prism Launcher

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

Crash log: https://mclo.gs/WwzHfw2

**Comment by Madis0** [comment]
Sodium 0.6 betas are not yet supported, I advise you to "update" your instance again to 6.1.0 to fix it. 

The next time you update mods, pay attention to avoid not updating FO-included mods.

**Comment by zozogame1** [comment]
That's what I did. I only updated the modpack and not directly the mods because I know it will break. I am currently on FO 6.1

**Comment by zozogame1** [comment]
1. Thanks for telling me that the problem was sodium 
2. I don't how I ended up with the beta, maybe an older version of FO where Sodium's beta were still supported ?

**Comment by Madis0** [comment]
If you didn't update the mods on your own, it might've been some other mod you tried to add that wanted a specific version of Sodium, which updated it.
