### ISSUE TITLE
TAA Project (shaderpack)

### ISSUE THREAD

**Issue by 1by1Xayd** [Fabulously-Optimized/fabulously-optimized#896]
### CurseForge Mod Distribution

Unknown

### Modrinth link

https://modrinth.com/shader/taa

### Mod file size

19 KB

### License

(any other license)

### What it does

Fixes "jagged edges" on blocks.

### Why should it be in the modpack

Minecraft wont hurt eyes so much.
Without shader: ![without](https://cdn.modrinth.com/data/aE6ouBYi/images/547040e47d988e0980278f7d9655d0471492963c.jpeg)
With shader: ![with](https://cdn.modrinth.com/data/aE6ouBYi/images/14cb6f4227272f1611a59f6cf8935c4aebb7fcaf.jpeg)

### Why shouldn't it be in the modpack

Not available in curseforge(I am not gonna upload it to curse forge cuz i wanna distibute it on modrinth only...)

### Additional details

Shaderpack is made by me

**Comment by 1by1Xayd** [comment]
![main showcase](https://cdn.modrinth.com/data/aE6ouBYi/images/66c3bcee41f09f440863d3d54fd7c6c801946a0f.jpeg)

**Comment by Madis0** [comment]
Doesn't Minecraft already have antialiasing options? What is the unique value of your pack instead of just enabling the vanilla setting?

I do remember that people have been looking for _anisotropic filtering_ though, which no mod has been able to provide so far.

> Not available in curseforge(I am not gonna upload it to curse forge cuz i wanna distibute it on modrinth only...)

You do understand that if FO were to include this, it would also be distributed in CurseForge as well? And if you don't upload it there directly, it would just require your permission and you would not receive any benefits when people download it.

**Comment by 1by1Xayd** [comment]
I don't get any money from the shaderpack anyway, you can upload it to curseforge! Minecraft doesnt have any anti-aliasing options. Maybe you got a mandela effect?

**Comment by 1by1Xayd** [comment]
I am from Russia by the way.

**Comment by 1by1Xayd** [comment]
Google:
Minecraft, by default, doesn't enable anti-aliasing on its own. It must be forced by your machine's graphics card (GPU). Certain integrated graphics cards may not be able to perform this action. However, most Nvidia and AMD brand graphics cards can force anti-aliasing with some control center tweaks.

**Comment by Uranite** [comment]
Sorry but this just makes the game jittery and blurry

**Comment by Madis0** [comment]
Decided not to bundle it, instead [mentioned it in the wiki](https://wiki.download.fo/give-up-optifine#video-options) :)

**Comment by 0CCULTIST** [comment]
> Sorry but this also makes the game jittery and blurry

Not sure what you mean by jittery, I don't have any of that. Maybe it was bugged at some point?

**Comment by Uranite** [comment]
>Not sure what you mean by jittery, I don't have any of that. Maybe it was bugged at some point?

Like the whole world is shaking
