### ISSUE TITLE
mods showing as their mod name in the option menu.

### ISSUE THREAD

**Issue by ender2walker** [Fabulously-Optimized/fabulously-optimized#900]
### Describe the bug

several mods are showing up in several menus as "mod name" . "section of menu" 

### Modpack version

6.1.0-alpha 3

### Launcher

Minecraft Launcher (vanilla)

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

![Screenshot (2)](https://github.com/user-attachments/assets/ddad376e-92ed-4f53-85db-8d1a670e9fa6)
![Screenshot (4)](https://github.com/user-attachments/assets/48bafd68-b38d-4ba0-9c80-0b7da30e38b8)

**Comment by Madis0** [comment]
1. Please update to FO 6.2.0.
2. When selecting languages, please keep English (US) and add any other languages above it.
