### ISSUE TITLE
Game crashes when I press the key to open the chat

### ISSUE THREAD

**Issue by theaanimal** [Fabulously-Optimized/fabulously-optimized#903]
### Describe the bug

When I press "t" to open the chat my game crashes.

### Modpack version

6.40-alpha.1

### Launcher

CurseForge App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

### Additional context

https://mclo.gs/cYwIswE

**Comment by Madis0** [comment]
Did you update your instance from 1.21.1? It is not recommended to update from stable to alphas and betas.

Either way, the workaround is to disable "Show server safety" in No Chat Reports settings for now.
