### ISSUE TITLE
Sodium Dynamic Lights

### ISSUE THREAD

**Issue by Hebgbs** [Fabulously-Optimized/fabulously-optimized#907]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged

### CurseForge Mod Distribution

Allowed

### Modrinth link

https://modrinth.com/mod/sodium-dynamic-lights

### Mod file size

897.34 kB

### License

(any other license)

### What it does

Adds a new Dynamic Lighting option in the Sodium video menu.

### Why should it be in the modpack

This provides a means of accessing dynamic light settings, without the need to access it using Mod Menu / Catalogue.

### Why shouldn't it be in the modpack

Screencaps lie; requires interface dependency.

### Additional details

While nice to have the dynamic light settings in the video settings menu, recent adjustments to the mod had made it so Sodium Options API is a required dependency. So there's no real savings associated with this mod, but its dependency sure makes the video settings look pretty.

I'm not sure why the dependency was added, _especially_ considering the screencaps provided show it being compatible with Reese's Sodium Options but it's a good addition, and solid alternative mod candidate. Conflicts with LambDynamicLights, provides the same exact functionality.

**Comment by Madis0** [comment]
Forks of LambDynamicLights are currently not considered due to reasons described in #797. Besides, LambDynamicLights recently added some support for Sodium settings (not sure if visible with Reese's Sodium Options yet) and probably will add full settings once Sodium adds the respective API.
