### ISSUE TITLE
Creating Realm crashes on 6.4.0-alpha.3

### ISSUE THREAD

**Issue by shalots** [Fabulously-Optimized/fabulously-optimized#908]
### Describe the bug

currently on the newest version release of the modpack, and wanted to open a realm for my friend and I. Everytime I click on create my realm and finish typing in the name for it and hit continue, my game crashes. Any help or tips on this would be much appreciated.

### Modpack version

6.4.0-alpha.3

### Launcher

Modrinth App

### Confirm

- [X] This bug report is about an issue with the modpack itself, I have not modified the mods nor added any resource packs. If this is not the case, I know that I should post the issue to modpack's Discord support channel instead.

**Comment by Madis0** [comment]
Please send the crash log.

**Comment by Madis0** [comment]
No logs, assuming fixed.
