### ISSUE TITLE
Structure Essentials

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Fabulously-Optimized/fabulously-optimized#912]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric

### CurseForge Mod Distribution

Allowed

### Mod file size

28.6KB

### License

All Rights Reserved / ARR

### What it does

_From the mod description:_

- Fixes structure locating to be much faster, reduces server lagspikes when e.g. looting a chest with a treasure map
- Adds a timeout to structure locating, to prevent it taking too long and crashing the server
- Debug logging for structure placement
- Additional logging for structure placement errors
- Command to list nearby structures (/structureessentials getStructuresNearby)
- Command to list Tags for a Biome (/structureessentials getBiomeTags)
- Command to list Biomes for a Tag (/structureessentials getBiomesForTag)
- Command to list similar Biomes and Tags for a given biome (/structureessentials getSimilarForBiome)
- Prevent crashes for structure mod updates
- Prevent crashes of LegacyRandomSource errors

### Why should it be in the modpack

It improves performance whenever a player runs a `/locate` command.

### Why shouldn't it be in the modpack

This mod is not available on modrinth.

**Comment by Madis0** [comment]
By the description, the mod sounds very niche (very few people even use /locate) and therefore unsuitable for the modpack.
