### ISSUE TITLE
Recipe Essentials

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [Fabulously-Optimized/fabulously-optimized#913]
### CurseForge link

https://www.curseforge.com/minecraft/mc-mods/recipe-essentials-forge-fabric

### CurseForge Mod Distribution

Allowed

### Mod file size

51.9KB

### License

All Rights Reserved / ARR

### What it does

_From the mod description:_

- Caches recipe lookups to prevent lag from autocrafting machines, too many furnaces etc
- Reduce total size of the recipe packet to avoid size issues
- Improves item comparisons for better server performance

Recipe book:

- Option to disable or show all recipes, speeds up login time
- Better recipe sorting, by craftable and last used
- Option to show all recipes from the get-go

### Why should it be in the modpack

It could improve performance on worlds that have many autocrafters, and/or many furnaces, such as when an autosmelter is built.

### Why shouldn't it be in the modpack

This mod is not available on modrinth.

**Comment by Madis0** [comment]
I have a feeling these optimizations do not do much on singleplayer, or if they do, they might break things because a mod does the caching and not the vanilla server. See also: #41 #87 #656
