### ISSUE TITLE
Add darkmode GUI 

### ISSUE THREAD

**Issue by Hood1e10** [Fabulously-Optimized/fabulously-optimized#918]
### CurseForge link

 https://www.curseforge.com/minecraft/texture-packs/unique-dark

### CurseForge Mod Distribution

Unknown

### Mod file size

7.19kb

### License

All Rights Reserved / ARR

### What it does

Just makes the GUI dark, simple! 
![Screenshot 2024-12-29 095643](https://github.com/user-attachments/assets/8df42e97-e559-4e8a-a2a5-d18ebc0ba8cd)
![Screenshot 2024-12-29 095711](https://github.com/user-attachments/assets/f251f768-dff8-49c9-8ae9-5c85b2f6d23b)

### Why should it be in the modpack

No one likes their eyes being burned out by forced lightmode, darkmode just looks better and is easier on the eyes.

### Why shouldn't it be in the modpack

It changes the way the GUI is styled like, but it still fits in the vanilla style.

**Comment by Madis0** [comment]
> No one likes their eyes being burned out by forced lightmode, darkmode just looks better and is easier on the eyes.

Very subjective opinion. 

Generally this modpack avoids adding changes that visually change the game in a new and unique way, the goal is to rather make it easy for the users to customize their game with less effort. As such, I do not think things like dark mode or nostalgic textures belong to this pack, therefore the suggestion is rejected.
